### ISSUE TITLE
"Close window = close a tab" is kinda wierd

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#101]
**Is your feature request related to a problem? Please describe.**
I'm used to hitting X (or whatever) on the window decoration to close the whole window. Making it close tabs incrementally feels wierd. At most I'd expect it to confirm "you're closing N tabs, do you really wanna?".

I don't think I've seen this kind of interaction with any tabbed UI. Does it come from somewhere?

**Describe the solution you'd like**
I'd be happy with "close window = close everything" by default, but if the current idiom is actually common and desireable, maybe an option.

**Describe alternatives you've considered**
I've tried to get used to it, but it surprises me every time.

**Comment by wez** [comment]
The current behavior is janky and an accident of the UI-less tab interface, combined with winit not being able to reasonably spawn multiple windows.

We now have infrastructure for throwing up additional windows for use as dialogs (eg: ssh prompts) that could be applied to this.

It hasn't bothered me so far because I use `ctrl-d` to send EOF to kill a tab almost exclusively.

**Comment by jsgf** [comment]
There's also a CloseTab keybinding so you can close them individually even if they're unresponsive.

**Comment by wez** [comment]
This is fixed in master
