### ISSUE TITLE
FileDescriptor is used outside wezterm, maybe put it in a new repo?

### ISSUE THREAD

**Issue by mcr** [wez/wezterm#1065]
**Is your feature request related to a problem? Please describe.**
I have some suggestions on improving FileDescriptor 0.8, it might be easier if it was split off into it's own git.

**Describe the solution you'd like**
fork, rename, rip out rest of wezterm.  I could do this.

**Describe alternatives you've considered**
just live with the situation and send pull requests for FileDescriptor

**Comment by wez** [comment]
I'd like to keep the filedescriptor in this repo; it's not a situation to be lived with but an intentional strategy for reducing dependency management headaches while iterating.  Since most of the changes that I make to it are part of wezterm/termwiz/pty related development, it allows me to work faster and more easily with this structure.  Check out articles talking about "monorepo" for more on the pros and cons of this approach.

I'd love to hear more about what you have in mind for the filedescriptor crate!

**Comment by mcr** [comment]
I think that FileDescriptor is in error to set cloexec() on stdin/out/err. 
I will send a pull request to refactor this a bit so that it can be avoided.
This causes many surprises when calling tokio::process::Command, for instance. Subprocesses shouldn't have fd 0/1/2 closed, as that means that they might put other stuff on that fd, and then debugging goes wrong place.

**Comment by wez** [comment]
Closing this in favor of your PR in https://github.com/wez/wezterm/pull/1066
