### ISSUE TITLE
Skipped chunk of lines for 1 frame when scrolling in Kakoune (on a 4K sized window)

### ISSUE THREAD

**Issue by unrelentingtech** [wez/wezterm#1128]
### What Operating System(s) are you seeing this problem on?

FreeBSD X11, FreeBSD Wayland

### WezTerm version

wezterm 20210908-224845-2b7e2654

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When holding up or down in Kakoune, scrolling through a file, very very brief "blinking" style glitches are noticeable sometimes. I've captured the frames with apitrace, see below — quite a few lines in the middle of the screen are somehow skipped for just one frame, and the bottom lines have the background color of the last line.

This seems to be very dependent on buffer size. Does not really happen with small windows at all, and conversely, stretching the window to be larger than my 4K display makes it happen more often than just a maximized window.

Checked with both Wayland and X11 (XWayland), so doesn't seem backend dependent.

### Configuration

not relevant?

### Anything else?

Frame 99:
![63748 trace_frame_100-1_0](https://user-images.githubusercontent.com/208340/132588149-9ab809c0-b438-4709-ad59-392d8a58cb07.png)
Frame 100:
![63748 trace_frame_101-1_0](https://user-images.githubusercontent.com/208340/132588147-72cf0dad-37cb-46fc-aa53-629c5bc1f4a0.png)
Frame 101:
![63748 trace_frame_102-1_0](https://user-images.githubusercontent.com/208340/132588140-c87ea42a-5a20-4f3c-b73f-4774606526a0.png)

**Comment by wez** [comment]
I've only briefly skimmed this, but I wonder if this would be resolved by kak implementing https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036 to tell wezterm when a frame begins/ends?

**Comment by wez** [comment]
if you want to poke at that sync update aspect, this is the entry that tmux looks for in terminfo to determine if it is supported, and presumably kak could be made to do implement something similar without a huge effort:
https://github.com/wez/wezterm/blob/main/termwiz/data/wezterm.terminfo#L21

**Comment by unrelentingtech** [comment]
Turns out it does support it, but only with an explicit flag: https://github.com/mawww/kakoune/commit/428ddeb97bdc685d493723fe4383c5588f9ecfcc but that's probably not the "new" syntax you linked

**Comment by unrelentingtech** [comment]
Oh, and I think it's actually https://github.com/mawww/kakoune/issues/4317 so now I know wezterm specifically is not to blame :D

Alacritty has managed to completely avoid the issue… just by accident I guess (?)

**Comment by unrelentingtech** [comment]
Wait, so the creator of Kakoune says

> This would indicate the linux console renders every intermediate state instead of what most terminals do: render once there is no more terminal output pending. Its unfortunate because it means the current code that optimize for the amount of data on the wire leads to this flickering.

soooo does wezterm not wait for the end of pending output?

**Comment by wez** [comment]
There isn't a portable way to know when you've read the last pending data, without introducing an explicit settle period before sending the data to the terminal model.  That additional latency is noticeable, particularly when applications are doing more sophisticated things like scheduling image frames for 30-60fps animations.

wezterm uses a [1MB buffer](https://github.com/wez/wezterm/blob/main/mux/src/lib.rs#L69) which you could experiment with making larger if you wanted to.

The idea that terminals should be able to soak up an unbounded amount of data before rendering is a bit simplistic, especially if you consider the "cat giant file for benchmarking" case: what most do is read a "packet" into their local buffer, and apply that to their respective models as data is available, triggering a render update when they've consumed the available data.

More modern terminal emulators parse the input stream in a separate thread from rendering, which makes the UI more responsive but also makes them more sensitive to this kind of tearing artifact.

The synchronized update extension was added to terminals to provide the application a way to explicitly signal where their frames begin and end so that the terminal can provide glitch free rendering.

**Comment by wez** [comment]
FWIW, your frame 100 screenshot looks to me like we caught kak just after it executed a sequence like `SU` to "delete" a range of lines (by scrolling them up) prior to inserting the new lines back in their place, which does make me think that this would be fixed with a synchronized update bracketing things.

FWIW2: the `\033P=1s\033\\` sequence in the commit you referenced is the older iTerm2 sequence and isn't supported by wezterm.  I'm not opposed to seeing wezterm add support for that, but it's probably a bit of a faff because DCS is another layer of encapsulation.  The newer sequence has pretty good adoption across terminal emulators (including iTerm2), so it's probably better for kak to adopt the new sequence.

**Comment by unrelentingtech** [comment]
Making the buffer 2MB caused `setsockopt` to fail. I'll look into adding the new sequence to kak.
