### ISSUE TITLE
Open new tabs with same working dir

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#113]
**Is your feature request related to a problem? Please describe.**
Its useful to make new tabs open in the same dir as the current one. 

**Describe the solution you'd like**
When I hit `Ctrl-Shift-T` to open a new tab, I'd like it to have the same cwd as the current tab if possible.

**Describe alternatives you've considered**
The current behaviour is OK, but I end up almost always needing to type `cd` as the first command in a new tab.

**Additional context**
gnome-terminal does this, and I was surprised how useful it is (ie, how much I missed it). I have no idea how it implements this. I assume it can track cwd via OSC sequences, and it uses that as the initial dir for a command in a new tab.

**Comment by wez** [comment]
There are a few things needed to make this happen, if you felt like taking a crack at it:

* in the pty crate, teach the `CommandBuilder` how to spawn a process with a particular cwd for both posix and windows
* In terminalstate.rs, in `osc_dispatch`, process `OperatingSystemCommand::SetCurrentWorkingDirectory` and capture the new cwd (which is most likely a `file://` IIRC).
* Add a method named something like `get_current_working_directory` to the `Tab` trait in src/mux/tab.rs to retrieve the CWD.  It should probably return `Option<String>`; tabs can be attached to a serial port which doesn't have a cwd concept.  It should retrieve the extracted cwd.
* Adjust the tab spawning behavior for `spawn_tab`; when spawning in the `CurrentTabDomain`, retrieve the cwd from the current tab and pass it to the command builder.
* Augment `src/server/*` to propagate the cwd to the client so that it can report the cwd for a mux'd tab

**Comment by wez** [comment]
while writing up a few notes for the docs, I ran into this, which I haven't yet read through:

https://gitlab.freedesktop.org/terminal-wg/specifications/issues/20

**Comment by wez** [comment]
(That link doesn't have any productive additional outcome)

**Comment by benmontour** [comment]
Is there a way to disable this feature? Say I just want all of my tabs to open to ~ and not the current working directory?

**Comment by wez** [comment]
@benmontour you can redefine the key assignments that you use to spawn explicitly using https://wezfurlong.org/wezterm/config/lua/keyassignment/SpawnCommandInNewTab.html with `cwd = wezterm.home_dir`.
