### ISSUE TITLE
Idea: A better `wezterm.action` syntax

### ISSUE THREAD

**Issue by bew** [wez/wezterm#1150]
**Is your feature request related to a problem? Please describe.**
Feels weird that some actions need a `wezterm.action{...}` and some can simply be given as a string (=> they don't require arguments).

**Describe the solution you'd like**
A unified way to specify an action, using `wezterm.action` (which can be aliased to `act`).
And maybe a more flexible way to specify arguments (not always use a table!)

Example (~one binding per line, prelude: `act = wezterm.action`):
```lua
{..., action = act.ReloadConfiguration}
{..., action = act.ScrollByPage(-1)} -- or more generic? act.Scroll{ByPage = -1}
{..., action = act.ClearScrollback("ScrollbackAndViewport")}
{..., action = act.CloseCurrentTab{confirm = false}}
{..., action = act.Search{Prefill = "foo", CaseInsensitive = true}} -- split CaseInSensitiveString param in 2
{..., action = act.Search{Prefill = ""}}
{..., action = act.Search} -- same as previous (using default values)
{..., action = act.Multiple{
  act.SendKey{mods="CTRL", key="l"},
  act.SendString("ls"),
  act.SendKey"Enter", -- same as: act.SendKey{key="Enter"}, because `key` is a required arg
}}
```
NOTE: I noticed that `CloseCurrentTab` uses a fully lowercase param, but not the other actions, is that intentional?

**Describe alternatives you've considered**
keep existing syntax, but meh.. :eyes: 

**Additional context**
I think this change can be made backward compatible.

**Comment by wez** [comment]
I'm not opposed to making things better, but wanted to note that the current syntax is a result of the serde-based mapping from lua to the underlying rust types.  That mechanism gives a zero-manual maintenance way of representing the rust data type in lua.

It is highly desirable for me personally to avoid introducing a layer that needs manual effort each time a new variant is introduced in the rust code.

**Comment by bew** [comment]
noted

**Comment by wez** [comment]
What I think might be feasible to do here is to make `wezterm.action` be a userdata value with some metamethods:

* `__call` would call through and work exactly as it does today, preserving backwards compatibility.
* `__index` would be overridden with an implementation that:
   * Would check to ensure that the index was one of the valid variant names and raise an error if it isn't
   * If the variant is a unit variant, return the corresponding action value. That would allow `act.ReloadConfiguration` to work
   * Otherwise, return a function that will construct the action value based on the variant name and the parameters that will get passed to it. That would allow `act.ClearScrollback("ScrollbackAndViewport")` to work

Getting fancier with default values *might* be possible to swing through without breaking existing configs; because Rust doesn't allow deriving the `Default` trait for enum variants like `Foo { bar: bool }`, so the variant would need to be changed to define a separate struct `Foo` that `impl Default`, and then make the variant be `Foo(Foo)`.  Assuming that works, the `act.Search` case from your example above would need to be `act.Search()`.

Is that worth shooting for?

**Comment by bew** [comment]
That's the kind of implementation I was thinking about :+1:.

As for the `act.Search` case, that would still not be unified, as `act.ReloadConfiguration` would not require parenthesis, while `act.Search` would.

:point_right: What about making all `act.*` return a function, and allow the `action` field of a mapping to be a function that is auto-called, so that both `act.ReloadConfiguration` & `act.Search` magically work without having to know the detail of each ?
That function would check if it has required/optional params, or none (like `act.ReloadConfiguration`), and raise accordingly if needed. (but this would require to add a pre-processing step of the config, to resolve all un-called functions).
(the returned function could also be a table with a `__call`, could be useful to have a kind of marker that it's a special value that needs auto-call on config load)

**Comment by wez** [comment]
Here's what I'm thinking:

`wezterm.action` is a userdata with `__call` and `__index` metamethods.
* The `__call` method makes it behave as it does today.
* The `__index` method return value varies based on the type of the named variant:
   * If the variant is a unit variant, then return the variant name as a string; this will resolve to the correct value when converted back later.  (eg: `act.ReloadConfiguration` -> `"ReloadConfiguration"`)
   * If the variant payload implements `Default`, then return a table holding that default representation, but add a `__call` metamethod to it.  If that returned value is not called as a function then it will resolve to that default representation.  But if it is called as a function, that function will resolve the arguments and return the variant with those arguments applied.  That should make the `act.Search` and `act.Search(...)` cases be correctly mapped by the code that converts lua values to the new `wezterm_dynamic::Value` type.
   * Otherwise: (not a unit variant, or payload doesn't `impl Default`), return a function that needs to be called to resolve the full value. eg: `act.Multiple{...}`

**Comment by wez** [comment]
You can now do this in `main`; the snippets below were evaluated in the debug overlay (`ctrl-shift-L`):

For backwards compatibility:

```
> wezterm.action{QuickSelectArgs={}}
{
    "QuickSelectArgs": {},
}
```

and the new, more ergonomic, versions:

This one demonstrates default-construction; unlike the other cases below, this one shows the computed defaults in the return value. It was just more convenient in the code to do that. The other cases are equivalent and result in the same end behavior even though they omit those fields in what you see printed below:

```
> wezterm.action.QuickSelectArgs
{
    "QuickSelectArgs": {
        "alphabet": "",
        "label": "",
        "patterns": {},
    },
}
```

This one shows default-construction but overriding a single parameter.

```
> wezterm.action.QuickSelectArgs{alphabet="abc"}
{
    "QuickSelectArgs": {
        "alphabet": "abc",
    },
}
```

Default constructing when using 0 parameters:

```
> wezterm.action.QuickSelectArgs{}
{
    "QuickSelectArgs": {},
}
```

A unit variant (represented as string):

```
> wezterm.action.Copy
"Copy"
```

```
> wezterm.action("Copy")
"Copy"
```

```
> wezterm.action.ActivatePaneByIndex(1)
{
    "ActivatePaneByIndex": 1,
}
```

I haven't written any docs for this yet.  Can you give this a try and see how it feels?

**Comment by wez** [comment]
and the error cases:

```
> wezterm.action.Wrong
callback error
stack traceback:
        [C]: in metamethod 'index'
        [string "/Users/wez/.cargo/git/checkouts/mlua-4fd10c34..."]:1: in main chunk
caused by: `Wrong` is not a valid KeyAssignment variant.  There are too many alternatives to list here; consult the documentation!
```

```
> wezterm.action.Capy
callback error
stack traceback:
        [C]: in metamethod 'index'
        [string "/Users/wez/.cargo/git/checkouts/mlua-4fd10c34..."]:1: in main chunk
caused by: `Capy` is not a valid KeyAssignment variant. Did you mean `Copy`? There are too many alternatives to list here; consult the documentation!
```

and when used in the config file:

```
; ./target/debug/wezterm --config-file /tmp/wrong.lua
23:15:10.954  ERROR  mux::connui > Configuration Error: callback error
stack traceback:
        [C]: in metamethod 'index'
        [string "/tmp/wrong.lua"]:5: in main chunk
caused by: `Capy` is not a valid KeyAssignment variant. Did you mean `Copy`? There are too many alternatives to list here; consult the documentation!
```

**Comment by bew** [comment]
You're reading my mind, I was about to suggest adding some docs :P
