### ISSUE TITLE
Window resize is very janky with mux connections

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#116]
## Describe the bug

Resizing a window is very janky - the frame resizes but the contents lag behind significantly. The is especially true for remote windows. It looks like there's a round trip involved in what's essentially a local repaint.

## Environment (please complete the following information):

 - OS: Linux/Wayland
 - Frontend:  OpenGL
 - Version: wezterm 20191229-193639-e7aa2f3-162-g22884a2

## To Reproduce
- Create window
- Drag to resize

## Configuration

Config independent

## Expected behavior

Window should track resize and repaint at rate. I use gnome-terminal in the same environment as a point of comparison.

## Additional context

This is primarily a "feel" issue without much functional effect. However there are times it can take a long time to repaint at the end of resize, esp if the remote connection is poor.

**Comment by wez** [comment]
I think this is partly wayland/smithay-client-toolkit (with its weird disconnected window decorations) and partly an accidental blocking call in the mux transport.

**Comment by wez** [comment]
I don't believe that I've cured it, but it should now be less janky.
I think full resolution needs more of a separation between the client state and the server state; right now we have a very thin layer that results in fetches from the server.  I'd like to make the client more stateful so that we have an opportunity to do things like predictive local echo.  Smoother resizes should (at least partially) fall out of that effort.

**Comment by jsgf** [comment]
All this is much better now.
