### ISSUE TITLE
Support reloading config after error

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#1174]
**Is your feature request related to a problem? Please describe.**
When saving a config with an error, Wezterm reloads it and shows an error message.
But after you fix the error it will not be reloaded on save.

**Describe the solution you'd like**
Reload the config file even if it failed in the past.

**Describe alternatives you've considered**
You can press the reload-config combination, but that defeats the purpose of hot reload to begin with.

**Comment by follower** [comment]
I was confused by this request because I thought wezterm already *did* have this behavior. :D

Then I tested it again and it acted as you described.

But I was 95% certain that *yesterday* it had reloaded after an error, so what was different?

Ah, because yesterday, I had spawned the tab with my editor (`emacs`) in it like this:

```bash
/<path>/wezterm cli spawn env TERM=xterm emacs ~/.config/wezterm/wezterm.lua
```

But when I tested today I just pressed the `+` button to open the tab.

I further tested with:

```bash
/<path>/wezterm cli spawn
```

And then starting `emacs` & it reloaded as expected after error.

So it seems there's possibly an issue with change notifications being missed in some  situations?

**Comment by follower** [comment]
Some of the relevant code seems to be around here: https://github.com/wez/wezterm/blob/72cb110b65a909c242444725379f266a359b554c/config/src/lib.rs#L410-L521

But there's more further on in that file.

Seems like setting the Rust log level to `trace` or `debug` would give some useful insight into what's happening in terms of events generated.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by ModProg** [comment]
works as expected
