### ISSUE TITLE
Bind Caps to Ctrl in wezterm only and not OS

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#1177]
I would like to rebind `Ctrl` to `Caps` and vice-versa but only in wezterm and not in OS as sometimes I'm on a machine that is not main dev machine and would like others to use it as normal.

iTerm seems to have some sort of key binding changes but haven't tried if it works for Caps.
https://apple.stackexchange.com/questions/236119/how-do-i-swap-ctrl-and-alt-in-just-the-terminal

I'm not sure if this would even be possible and most likely also depends on OS capabilities but I'm primarily looking for OSX support.

**Comment by wez** [comment]
This is a problematic request because capslock isn't a modifier key at the hardware level, and thus isn't part of the normal modifier key mask.  If it was then it would be pretty straight forward to remap the bitmask based on configuration, but because it isn't, this kind of remapping would need a much more complex input processing state machine to consider arbitrary keys as modifiers.  It's made even more complicated because caps lock is a key that toggles a different kind of state in the keyboard, and that state is global.

I don't see this request as being feasible to implement in wezterm, sorry!
