### ISSUE TITLE
 Mouse selection mark still displaying after changing to a new tmux window

### ISSUE THREAD

**Issue by rbelem** [wez/wezterm#118]
## Describe the bug

Mouse selection mark still displaying after changing tmux window

## Environment (please complete the following information):

 - OS: KDE Neon Linux X11
 - Frontend:  OpenGL
 - Version: wezterm 20200113-222147-724ad3a-1-g18bbd2a

## Is it a build problem?

Nope

## To Reproduce

1. Open tmux
2. Select some text with the mouse
3. Create a new tmux window
4. The selection mark will follow the new window

## Configuration

None

## Expected behavior

Keep the selection mark in the original window

## Screenshots

None

## Session Recording

None

## Additional context

None

**Comment by wez** [comment]
Thanks for filing; the same effect could also be produced by running `top`, then double clicking on eg: a pid in one of the rows and then waiting three seconds.  I've been meaning to fix it since I introduced this regression in a recent refactor :)
The fix will show up in the "nightly" (it's really hourly) in about an hour.
