### ISSUE TITLE
non-blocking search

### ISSUE THREAD

**Issue by unrelentingtech** [wez/wezterm#1209]
**Is your feature request related to a problem? Please describe.**

Search sometimes can be slow and block the terminal UI, which is not very good for the user experience (e.g. cannot view other tabs while the search is being processed).

Worse, this can currently crash the application on Wayland because we're not reading the event queue and letting it overflow (though see [this discussion](https://gitlab.freedesktop.org/wayland/wayland/-/issues/159), this might be solved in other ways).

**Describe the solution you'd like**

Move search operations to a worker thread…

**Comment by wez** [comment]
Recent release(s) improved search performance to the point where this is less likely to be a problem.

The core implementation technically allows for a bounded/paged search over a region-at-a-time so that the gui won't be blocked, but the copy mode overlay runs over the entire scrollback range.

It wouldn't be especially difficult to adjust that code to work in chunks if someone is motivated.
Look for `pane.search(` in `wezterm-gui/src/overlay/copy.rs` if that someone is you.

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
