### ISSUE TITLE
Font character vertical alignment is off

### ISSUE THREAD

**Issue by rawhat** [wez/wezterm#1228]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20211010-192942-d461c1c0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I just pulled down the latest nightly, and the character alignment seems to be off.  I tried two fonts (JetBrains Mono and Cascadia Code).  It seems like Cascadia at size 14 font is maybe okay?  But at 13, they are both wonky.  JetBrains is not aligned at any size that I tried.

![image](https://user-images.githubusercontent.com/2095509/137355790-1a126a70-8958-4d93-97ce-9b30bf170d9f.png)

I didn't see anything in the most recent release, or in the issues related to this.  Not sure if I just missed something though!

### Configuration

```lua
local wezterm = require("wezterm")

local font = "JetBrains Mono"
-- local font = "Cascadia Code"
return {
	default_prog = { "S:\\Arch.exe" },

	font = wezterm.font_with_fallback({ font, "nonicons", "SauceCodePro NF" }),
	font_size = 13.0,
        -- ...
```

**Comment by wez** [comment]
> As far as I can tell this introduced it: [d54762b#diff-2d007a322e136f9ffbdd204ef9dc4b118e5a7ca49e6f7d9b61c42d7a4c7284c4](https://github.com/wez/wezterm/commit/d54762bf4bd6d1ef46d066f8183f1f8673977b2a#diff-2d007a322e136f9ffbdd204ef9dc4b118e5a7ca49e6f7d9b61c42d7a4c7284c4)

That commit seems unlikely because it only affects the width (eg: horizontal, rather than vertical) calculation for the tab bar, and not for all of the text in the rest of the display.

I would suspect more: https://github.com/wez/wezterm/commit/9b4f7e78d641b233908ddbfb401cb9482d869e67 and/or https://github.com/wez/wezterm/commit/e25deaaed10f038399461f28f900a8ec5e2095e8 which are playing with the baseline calculation

**Comment by krt-z** [comment]
Ok, well I'm not sure about the root cause, but it seems to actually be the half cell padding introduced here: https://github.com/wez/wezterm/commit/854ea8f2d189cfcbbba55f6f82f5b678132b6d2d

Adding window_padding = { top = "1cell" } fixes it for me on master.  Or 1, or 0, or any integer.  Anything fractional ruins the font rendering.

**Comment by wez** [comment]
@krt-z ah, that sounds plausible.  I'm in the middle of wrangling a big house move so I won't have time to directly repro and resolve this, but I just pushed 04768fd1e2881b6185ae8c6d5f6902d38257b4f5 to round down fractional pixels as a speculative fix.  Please let me know if this works for you all!
