### ISSUE TITLE
Incorrect character position in NeoVim for Emojis

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#1231]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20211002-212547-9a787549

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When having the following in a file opened by neovim and am using a noto-color-emojis for the emoji:
```
"✖️";
```
it gets displayed like so:
![grafik](https://user-images.githubusercontent.com/11978847/137535745-421ed83a-e555-4865-bc08-adc0d5204b06.png)
sometimes like this:
![grafik](https://user-images.githubusercontent.com/11978847/137535701-432ff718-6af5-45ec-a344-7e7d1859e9f1.png)
The problem is, this leads to the curser being offset by one:
![grafik](https://user-images.githubusercontent.com/11978847/137535991-dfa07170-5a2d-401f-b394-6c9add232305.png)
This cursor is at the last position in the line.

The correct but maybe wrong looking behavior in Alacritty:
![grafik](https://user-images.githubusercontent.com/11978847/137536171-4074a93a-1d2c-4658-9288-a7e86d7c78b2.png)
This leads to overflowing, but at least keeps the cursor position correct.

This might be at it's core an issue of vim not using the correct character width, but in the end I'd rather have overlapping characters, than an offset in the cursor.

**Comment by oblitum** [comment]
This also leads to character artifacts being left around when scrolling text (large chars are not being fully cleared).

**Comment by wez** [comment]
What you're seeing here is the effect of correctly supporting emoji vs text presentation.
Support for that was added in https://github.com/wez/wezterm/issues/997

Copying and pasting the text you supplied:

```
; echo ✖️ | iconv -f utf8 -t utf16be | xxd
00000000: 2716 fe0f 000a                           '.....
```

The emoji you're working with there is U+2716 followed by VS16 (U+FE0F).
VS16 is the explicit Emoji Presentation Variation Selector which causes that grapheme
to be treated as double-wide and use a fancy emoji glyph rather than a more simple
symbol glyph.

By default, U+2716 has Text Presentation, which causes it to occupy a single cell
and use a more simple symbol glyph.

Try this:

```
echo -e "\u2716  Multiply, text presentation by default"
echo -e "\u2716\ufe0e  Multiply, explicit text presentation"
echo -e "\u2716\ufe0f  Multiply, explicit emoji presentation"
```

In wezterm (and kitty, contour and other TEs with correct unicode/emoji support), the output looks like this:

![image](https://user-images.githubusercontent.com/117777/137632590-3bbaa514-28af-4fac-a5fb-305d8e81f506.png)

Alacritty doesn't currently support this properly and renders:

![image](https://user-images.githubusercontent.com/117777/137632643-8ab64d23-e3c5-401e-b234-be7b1bf846d3.png)

My recommendation is that you copy and paste the text presentation version of this sequence, either with no variation selector:

```
✖  Multiply, default presentation
```

or use it with explicit text presentation:

```
✖︎  Multiply, explicit text presentation
```

**Comment by oblitum** [comment]
It seems there's a conflict of intentions here, personally, I do wish to use emoji representations, but at the same time I don't wish a change in character width calculation that leads to unaligned text and character artifacts.

**Comment by wez** [comment]
https://github.com/wez/wezterm/issues/997#issuecomment-961274463 provides a helpful link to something that could help here

**Comment by wez** [comment]
I just pushed 225e7a124396362f2233394156d45cc156d438b5 which introduces a config setting for the unicode version; you can read more about it in the commit message.

The TL;DR is that wezterm now defaults to unicode 9 (which is really 9-13) and ignores the variation selector by default.
Since this is a config option, it is possible to set it at runtime; this screen shot shows the effects of that when running:

```
wezterm -n --config unicode_version=9 --config 'allow_square_glyphs_to_overflow_width="Never"'
wezterm -n --config unicode_version=14 --config 'allow_square_glyphs_to_overflow_width="Never"'
```

![image](https://user-images.githubusercontent.com/117777/143471452-1ba8f135-3d30-4dbf-add1-5f4b296d9add.png)

I'll introduce an escape sequence that allows setting/pushing/popping the unicode version in a follow up commit.

**Comment by wez** [comment]
OK, the escape sequence is now in `main`:

![image](https://user-images.githubusercontent.com/117777/143492488-d363b56c-3460-45f4-ab9a-fd7522ead1f4.png)

and docs on both the config value and the escape sequence are here:
https://wezfurlong.org/wezterm/config/lua/config/unicode_version.html
