### ISSUE TITLE
terrible image performance when using image protocols with multiplexer

### ISSUE THREAD

**Issue by xiangpeng2008** [wez/wezterm#1237]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

It looks like wezterm imgcat doesn't work with ssh domain
wezterm-mux-server just keeps using 100% CPU with rendering image

![image](https://user-images.githubusercontent.com/15676035/137633353-3a5aa767-4914-4ac7-a30a-d5183038e1e0.png)
If I start wezterm.exe ( without connect my.server ), and ssh to linux, then wezterm imgcat works
![image](https://user-images.githubusercontent.com/15676035/137633358-8c2bc81e-4396-403e-b0d0-2756e6f8d771.png)

### To Reproduce

```
wezterm connect my.server
wezterm imgcat paht/image.png
```

### Configuration

can't provide config right now as I'm not with that PC
but config is minimum

### Expected Behavior

expecting graphs to be printed

**Comment by wez** [comment]
The way images work in wezterm is that the image data is allocated as a shared "blob" (`ImageData`), then each of the cells hold a reference to that blob along with the texture coordinates (`ImageCell`).  

The way the mux protocol works is that each line within the changed region has its cells serialized and sent over the wire.

The serialization uses a simplistic approach with shared references: it just serializes the data into the data stream.

If you have a small image this is not too bad, but larger images are pathologically terrible: each cell will transmit a full copy of the image, and this will occupy both the client and the server with serializing and deserializing the data.

The way to fix this is to come up with an alternate representation of the data when serializing for this case; there needs to be a way for the client and the server to avoid transmitting the same image blobs.  The `ImageData` struct has a `hash` method that can be used to identify an image by its content hash and would be the way I would aim to tackle identifying images.

The challenge is: how to make that work with the serde crate?

Serializing is reasonably straightforward: for `ImageCell::data`, which has type `Arc<ImageData>`, we'd want to serialize as the content hash rather than the data itself.   Deserializing is the hard part: there isn't a way to pass context to the deserializer and the deserializer is synchronous.  So we can't do it that way.

An alternative is to come up with a parallel version of `ImageCell` (let's call it `SerializedImageCell`) that explicitly tracks the content hash instead of the `Arc<ImageData>`.  Then, when preparing the lines to serialize around here:

https://github.com/wez/wezterm/blob/f0ed6ce0c97174101e539b51b4673ef9b6fe8e4c/wezterm-mux-server-impl/src/sessionhandler.rs#L121-L122

a pass would be made to collect the `ImageCells` from each cell in the line and convert into `SerializedImageCell` and store those into `GetPaneRenderChangesResponse` along with their coordinates.

Then the codec would need be extended to add PDUs for requesting an image given its content hash.

https://github.com/wez/wezterm/blob/bb174811fab6f97646562d24ee84c8338b0cb5d2/wezterm-client/src/pane/renderable.rs#L299 will need to be updated to know how to translate `SerializedImageCell` back into `ImageCell` by way of making a request back to the server to get the `ImageData` for the hash, then those reconstructed `ImageCell`s need to be re-applied to the `Line`s that were just deserialized.

A cache needs to be added to the clientpane to avoid requesting the image data for each cell, otherwise all we've done is a lot of work to recreate a similar problem to the current implementation!

**Comment by Lenbok** [comment]
I just ran into this. Remote support for image display was one of the main reasons I wanted to try wezterm :-(.
