### ISSUE TITLE
ship appimage binary for linux

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#124]
Currently wezterm ships `.deb` and `.rpm` but I use archlinux which uses its own package manager `pacman`. Would it be possible to only ship [appimage](https://appimage.org/) so it works on multiple linux distros easily. Both `vim` and `neovim` ships appimage and makes it very easy to get started.

Another option would be to also create a create so all if I have a cargo setup all I can do is `cargo install wezterm`.

**Comment by wez** [comment]
FWIW, we also ship a binary tarball (eg: https://github.com/wez/wezterm/releases/download/20200113-222147-724ad3a/wezterm-20200113-222147-724ad3a.tar.xz) that you can probably extract and run on most linux systems.

I'm not sure about targeting appimage exclusively, but since it is pretty easy to make an appimage, I don't mind adding it to the set of downloads.  I have a PR open to test the CI/packaging adjustments to accomodate appimage building.

**Comment by wez** [comment]
An AppImage should show up in the next nightly release run; take a look in https://github.com/wez/wezterm/releases/tag/nightly in about an hour or so

**Comment by wez** [comment]
Please let me know whether the AppImage works for you!

**Comment by prabirshrestha** [comment]
Works. Thanks.
