### ISSUE TITLE
SSH port forwarding and sudo issues

### ISSUE THREAD

**Issue by memco** [wez/wezterm#1295]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I ran into a few issues testing out the wezterm ssh. Not sure if bugs or feature requests.

1. ssh with -L:
I tried to run wezterm ssh with -L and received the following error:

```
wezterm ssh foo -L 8080:localhost:80
error: Found argument '-L' which wasn't expected, or isn't valid in this context
```

2. I could not get `sudo su` to work in a wezterm ssh session. I saw messages saying:
```
2021-11-05T21:25:06.829Z WARN  wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
```

Not sure if this is expected.

### Configuration

no config

**Comment by wez** [comment]
wezterm doesn't currently support port forwarding in its integrated ssh client.  You can instead use `wezterm start -- ssh foo -L 8080:localhost:80` to use the openssh client, but it comes at the cost of tabs and panes being created locally instead of inside the remote session.

Regarding `sudo su`, it's extremely unlikely that wezterm has any bearing on that.  The warning is about an unsupported dec private mode 1034 which is an xterm extension that changes the behavior of meta key.

**Comment by memco** [comment]
>  The warning is about an unsupported dec private mode 1034 which is an xterm extension that changes the behavior of meta key.

Could you explain more about this? I use the option key (on mac) when inputting some characters and this could be what's preventing me from logging in if they're not being sent properly.

**Comment by wez** [comment]
xterm's docs say:

```
      Ps = 1 0 3 4  ⇒  Interpret "meta" key, xterm.  This sets the
          eighth bit of keyboard input (and enables the eightBitInput
          resource).
```

https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:eightBitInput
has more information about what that means in xterm.

wezterm doesn't support 8-bit mode, as it isn't compatible with UTF-8 encoded text.

**Comment by memco** [comment]
The issue went away when I enabled `use_ime` in my config.
