### ISSUE TITLE
Bad interaction between send_composed_key_when_left_alt_is_pressed, IME and dead keys

### ISSUE THREAD

**Issue by permelin** [wez/wezterm#1372]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20211205-192649-672c1cc1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

#### Scenario 1
```lua
send_composed_key_when_left_alt_is_pressed=true,
```
This behaved as expected in the 20210814 release but now some combinations with alt get eaten: I can't get @ (alt+2) for example, but  (alt+a) still works. (This is a Swedish keyboard layout.) Neither left nor right alt works.

#### Scenario 2
```lua
send_composed_key_when_left_alt_is_pressed=true,
use_ime=true,
```
I saw something in the changelog about IME that could be relevant, so I turned that on. Now my alt key works again, but dead keys are broken: I have to press them twice, e.g. `´´a` to get `á`.

#### Scenario 3
```lua
send_composed_key_when_left_alt_is_pressed=true,
use_ime=true,
use_dead_keys=false,
```
With dead keys disabled they work, but behave as if set to `true` instead of `false`.

### To Reproduce

See description above.

### Configuration

Everything was tested with a minimal config.

```lua
local wezterm = require 'wezterm';

return {
  send_composed_key_when_left_alt_is_pressed=true,
}
```

### Expected Behavior

See description above.

### Logs

On the second press of `´` in scenario 2 and the first press in scenario 3, this is logged:
```
set_marked_text_selected_range_replacement_range ´ NSRange { location: 1, length: 0 } NSRange { location: 9223372036854775807, length: 0 }
```

**Comment by permelin** [comment]
I figured out why out of all alt-combos only `@$[]{}|\` won't work. Those are all some combination of alt or shift+alt and 0-9 on a Swedish layout. In the latest release, the default keybinds of alt+\<num\> to switch tabs take precedence. They didn´t before. I didn't have multiple tabs open so I never noticed what was going on before I switched back to the old version.

If I comment out `[Modifiers::ALT, KeyCode::Char('2'), ActivateTab(1)]` in `keyassignment.rs` I can once again press alt+2 to get `@`.

Working around the problem without touching the code was a bit trickier, but I found a way. Assigning `action=wezterm.action{ActivateTab=1}` to something else in the config doesn't seem to override the defaults. But I can override them this (ugly) way:
```lua
    {key="2", mods="ALT", action={SendKey={key="@"}}},
    {key="4", mods="ALT", action={SendKey={key="$"}}},
    {key="7", mods="ALT", action={SendKey={key="|"}}},
    {key="8", mods="ALT", action={SendKey={key="["}}},
    {key="9", mods="ALT", action={SendKey={key="]"}}},
    {key="(", mods="ALT", action={SendKey={key="{"}}},
    {key=")", mods="ALT", action={SendKey={key="}"}}},
    {key="/", mods="ALT", action={SendKey={key="\\"}}},
```
With the above I don't even need `send_composed_key_when_left_alt_is_pressed` enabled.

**Comment by wez** [comment]
There's a set of open macos+IME bugs that are all related. I recognize that they are frustrating to users.  They are awkward to run down because macos doesn't really want apps to work in a different way from the provided text input widgets, so everything is by definition doing undocumented/unsupported stuff, and that makes it difficult to move with confidence, and that in turn makes it easier to avoid when there are other more fun tasks to tackle!

I'm glad you've found a way to configure around the issue for now, and I hope you can have patience until the right confluence of inspiration and free time strikes and this gets properly resolved!

**Comment by wez** [comment]
I'm making a pass over the IME/macOS related issues.  I just pushed a fix for https://github.com/wez/wezterm/issues/1409 which impacted key assignments when `use_ime=true` (especially for the leader key stuff) and I wonder if that might have contributed to your scenario 2?

For scenario 1, it sounded like that was caused by the default `ALT-<number>` key assignments?
If so, then I would suggested this alternative way to disable just those key assignments for those keys:

```
{key="2", mods="ALT",  action="DisableDefaultAssignment"},
```

which should be equivalent to commenting out the assignment in the code, but without needing to change the code.

For scenario 3, would you mind expanding on what does/doesn't work there?  I'd like to make sure I know exactly how to trigger the problem!

**Comment by wez** [comment]
I pushed a series of changes today that should improve keyboard processing on macos.  c0502012d5f38f7ceb1690abf704767721e7b462 should finish building out and be available as a nightly download within an hour.  Please give it a try!

**Comment by permelin** [comment]
Sorry for the late reply.

Running 20220106 nightly.

Scenario 1 is unchanged, but as you noted it was caused by the default `alt-<number>` keymap. Though that somehow wasn't a problem until the December release.

IME (scenario 2) seems to be working as expected now.

Scenario 3 is also fixed now. The problem there was that when IME was enabled, the setting for `use_dead_keys` did nothing. Either `true` of `false`, it always behaved as if `true`.
