### ISSUE TITLE
Cating a large text file is slow in wezterm

### ISSUE THREAD

**Issue by exi** [wez/wezterm#1453]
I wanted to check if wezterm really is faster due to GPU acceleration.

I checked this with a simple text file:
```
$ du -h strings.log
44M     strings.log
```

Timing it in various terminal emulators:
Gnome terminal:
```
$ time cat strings.log
<logs of output>
cat strings.log  0,00s user 2,32s system 32% cpu 7,135 total
```

Terminator:
```
cat strings.log  0,00s user 2,43s system 33% cpu 7,260 total
```

Wezterm:
```
cat strings.log  0,00s user 3,58s system 25% cpu 13,834 total
```

It seems like the traditional terminals are nearly 50% faster in printing lot's of output.
Although I have to admit that the rendering itself looks smoother in wezterm, the actual rendering of the terminal output is slower compared to non-accelerated terminals.

Contrasting this with another GPU-accelerated terminal that looks just as smooth:

Alacritty:
```
cat strings.log  0,00s user 2,23s system 99% cpu 2,238 total
```

Alacritty consistently beats all the other terminals in raw rendering performance.

**Comment by wez** [comment]
Architecturally speaking, you can think of terminal output processing as having three main phases:

* Parsing the byte stream and emulating the terminal to model the terminal display
* Shaping the display; evaluating runs of text with the same attributes, mapping to fonts, expanding ligatures, and rasterizing glyphs
* Rendering the shaped data to the GPU

Performance wise: the priority in wezterm is for interactive latency rather than minimizing the time for bulk data transfer to complete.  Wezterm performs parsing on a separate thread from the UI and uses a carefully selected buffer size to help ensure that CTRL-C can be recognized and interrupt the process more quickly.  We could make the buffer size larger so that `time cat` appears to complete faster, but it would really be cheating and interactive latency would suffer.

`time cat BIGFILE` exercises primarily the first phase: it is dominated by parsing and managing scrollback.

The second phase is sensitive to the randomness and length of the text runs: if every line is different then the cache
hit rate suffers, and it can cost 10's of ms to shape unique text runs and that can cause the frame rate to
suffer.  Note that Alacritty doesn't do proper shaping and uses a simpler char -> glyph mapping that leads
to a higher cache hit rate.

The third phase is really the "easy" bit compared to the other two: it essentially takes the results of shaping and composes/composites them on screen.

If you want to see what difference the GPU makes in wezterm, you can try running `wezterm --config 'front_end="Software"'` to force the use of the Mesa llvmpipe CPU renderer instead of GPU.

FWIW, I don't think that `time cat BIGFILE` is a great benchmark.  It's certainly easy to run, but it doesn't model
something that humans realistically need to do: a human can't read MB of text at the raw speed of modern
computers for example.

Rather than bias towards that, I'm more interested in interactive latency: when the user scrolls the screen
it should be fast. CTRL-C should be responsive. Input latency should be low, and so on.

**Comment by exi** [comment]
Thank you for clarifying the trade-offs that go into wezterm. That makes a lot of sense.

**Comment by bew** [comment]
@wez can you put that reply in a doc (about perf) somewhere? It's a wonderful explanation that should be better accessible for anyone I think

**Comment by mocksoul** [comment]
@wez, sadly, with small font@large display it becomes a problem.

```
linbro ~ % echo $COLUMNS $LINES
566 129
```

After moving to 3.5k display from 1080p I have noticable latency in vim now. After little investigation I did found:
1. Alacritty latency is not noticable. Even alacritty+tmux - feels very fast.
2. Wezterm latency **is** noticable once terminal is fullscreen-ed. And not noticable with lower cols/lines.

I know you hate "cat bigfile" benchmarks, but simple `find /home` shows the bottleneck:

```
    alacritty  find /home  3.94s user 4.47s system 98% cpu 8.567 total      (direct competitor)
    st         find /home  3.97s user 4.41s system 86% cpu 9.660 total      (added just as example)
    kitty      find /home  3.67s user 4.52s system 55% cpu 14.867 total     (added just as example)
    wezterm    find /home  3.76s user 4.49s system 33% cpu 24.660 total     (wezterm itself)
    konsole    find /home  3.60s user 4.33s system 33% cpu 23.971 total     (feels VERY slow, I stopped using it years ago)
```

Notice the difference in system cpu -- looks like alacritty do not become bottleneck here, while wezterm definitely does. Among these `alacritty` and `kitty` "feel" fast (watching find in 120Hz screen :-D). `st` and `konsole` "feel" worst.

This is quite sad, actually, because I love wezterm much more :(

I'm using custom-designed bitmap .pcf font for this in all terms except `kitty` ([infamous #97](https://github.com/kovidgoyal/kitty/issues/97))

everything above was done in not very ancient machine (i7-6800k @ Gentoo). And 3440x1440 screen with term fullscreen. 

but changing wezterm screen size drastically do not improve things a lot:

```
linbro ~ % echo $COLUMNS $LINES
221 33
find /home  3.70s user 4.24s system 52% cpu 15.168 total

linbro ~ % echo $COLUMNS $LINES
147 21
find /home  4.02s user 4.49s system 62% cpu 13.517 total
```

here is also a test timing full terminal cpu usage for same `find`:

```
time wezterm start --no-auto-connect --always-new-process -- zsh -c 'find /home; echo $COLUMNS $LINES >/tmp/cl'; cat /tmp/cl
220 72

time alacritty -e zsh -c 'find /home; echo $COLUMNS $LINES >/tmp/cl'; cat /tmp/cl
221 73

results:
wezterm   24.57s user 7.94s system 174% cpu 18.597 total
alacritty 12.99s user 9.58s system 267% cpu 8.422 total
```
