### ISSUE TITLE
document how to use OSC 7 on Windows

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#146]
As described in https://github.com/wez/wezterm/pull/114, I should be able to open wezterm, navigate up a directory `cd ..`, and then press the plus button to open a new tab, which should open a new cmd in `C:\Users`, but instead I get my default `C:\Users\{Username}` directory.

This might not be limited to Windows.

**Comment by wez** [comment]
That feature requires that the shell (or some other application) emit an escape sequence each time it changes the current directory.  That is in the default for bash and zsh on the Fedora system that **jsgf** used when building that feature, and I have a slightly different version of that in my personal shell setup.

While the escape sequence should logically be emitted when the working directory changes, the typical approach is to have the shell emit it just before it prints the prompt.

The same technique should work on windows, but you'll need to translate it to your shell; I don't think that is possible with CMD, but it should be possible with powershell.   For CMD, you might be wizard enough to cook up an alias or something that emits the escape sequence when you run `cd`.

I've attached the shell snippet from Fedora to this comment which includes more shell integration than just the current directory stuff, as well as some escaping.

The gist of the escape sequence is:

```
printf "\033]7;file://HOSTNAME/CURRENT/DIR\033\\"
```

If you come up with something that works for this for CMD and/or powershell, I've love to include it in the wezterm docs!

[vte.sh.txt](https://github.com/wez/wezterm/files/4174531/vte.sh.txt)

**Comment by ImportTaste** [comment]
Why not just pull the current directory from the cmd process's handles? The right one looks like this:
![image](https://user-images.githubusercontent.com/53661808/74088775-8ad84800-4a5f-11ea-84e0-20caf2193c1a.png)
It will always be a File handle with a Granted Access of 0x100020, and its File information is Directory in Mode 0x20

**Comment by wez** [comment]
re: why not look at handles?

cmd.exe may be running eg: msys bash.   How do you know which is the right process to snoop?  How do you know which is the right handle to look at?  What if you are actually sshing into a remote windows system where you don't have access to inspect the process?

The spec for this feature: https://gitlab.freedesktop.org/terminal-wg/specifications/merge_requests/7/diffs touches briefly on this.

**Comment by ImportTaste** [comment]
The right one would be a child process of wezterm.exe, yes?

**Comment by wez** [comment]
it's really not that simple: as I said above, the direct child may be running an arbitrary tree of nested children: a cmd may run a cmd which may run a cmd which may run a bash shell.   There is no "right" way to pick one, and even if there was, that isn't portable and doesn't fit how ptys and ttys work; there may not even be a child process: we may be running a serial connection to a linux machine for instance, or a TLS connection to a remote multiplexer.

The feature that is implemented works based on an escape sequence because that is the most reasonable way to implement this specification; that's why it is specified in the way that it is.

**Comment by ImportTaste** [comment]
That's a shame, I don't think there's any way of throwing the escape sequence in a way that wouldn't cause a new line, unless there's some magic way of doing it with doskey.

**Comment by wez** [comment]
I took a peek at some information for CMD and in theory using this feature should be as simple as:

```
prompt $E]7;file://localhost/$P$E\$P$G
```

but, because of the way that the windows PTY stuff works, the conhost layer in the background currently swallows and doesn't re-emit the sequence to the terminal emulator.

This issue is tracking support for this feature in the Windows PTY layer: https://github.com/microsoft/terminal/issues/3158

**Comment by wez** [comment]
Turns out that I overlooked something; the pty was actually passing through the sequence, but we weren't passing the cwd through to the newly spawned processes.

I've pushed a commit that enables this feature for windows; you just need to run:

```
setx prompt $E]7;file://localhost/$P$E\$P$G
```

to set it up in the default environment for you when you next login, so that it applies to all of your cmd windows by default.

**Comment by ImportTaste** [comment]
In the interest of portable compatibility, is there any way I can have wezterm auto-execute this for cmd windows?

**Comment by wez** [comment]
With the commit that I just pushed, put this in your `wezterm.toml`:

```toml
set_environment_variables = { "prompt"="$E]7;file://localhost/$P$E\\$P$G" }
```

**Comment by wez** [comment]
You can get a little more fancy; this shows an alternative way to express setting this environment, and also how to embed some SGR sequences to change the color and have the prompt span multiple lines:

```toml
[set_environment_variables]
prompt = "$E]7;file://localhost/$P$E\\$E[32m$T$E[0m $E[35m$P$E[36m$_$G$E[0m "
```

![wezterm-prompt-windows](https://user-images.githubusercontent.com/117777/74110365-b54e0200-4b40-11ea-9faa-6aaccbe5d941.png)

**Comment by ImportTaste** [comment]
damn that's fancy. The new `[set_environment_variables]` feature seems like it'll be pretty useful on its own too...

A thought occurs... and I'll open a new issue for this if you'd like, but it seems like something that would be pretty easy to add now that you've laid the groundwork here: Could you include a variable specific to the toml that expands to the wezterm.exe directories path? Perhaps using angle brackets since those are reserved characters on the windows filesystem (and very uncommonly used elsewhere)... like `<wtdir>`

I could potentially have some IDE stuff in a wezterm subdirectory that requires some environmental variables pointing at the right locations.
