### ISSUE TITLE
CTRL+Backspace Key Binding not working anymore

### ISSUE THREAD

**Issue by GladOSkar** [wez/wezterm#1495]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220103-002251-c0502012

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

A keybinding that has been working for months doesn't work anymore after updating.

### To Reproduce

Apply config below and use `CTRL+Backspace` in terminal

### Configuration

```lua
local wezterm = require 'wezterm';
return {
    keys = {
        {
            key="Backspace",
            mods="CTRL",
            action=wezterm.action{SendString="TEST"}
        },
    },
}
```

### Expected Behavior

The String `TEST` is printed on the edit line.

### Logs

```
12:43:07.278 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-41262
12:43:07.371 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2) 3.0 Mesa 21.3.2 is_context_loss_possible=false wezterm version: 20220103-002251-c0502012
````

### Anything else?

<3 Thanks for wezterm, it's awesome :)

**Comment by wez** [comment]
When debugging key input, I recommend setting [`debug_key_events = true`](https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html) so that you can see what's happening.

The nightly builds are in the middle of a pretty big shift in the input layer: https://github.com/wez/wezterm/issues/1483
so things are a little bit in flux right now.

Under X11, this is what CTRL-Backspace generates:

```
 2022-01-03T15:49:59.180Z INFO  wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }
 2022-01-03T15:49:59.180Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: CTRL, raw_key: None, raw_modifiers: CTRL, raw_code: Some(37), phys_code: Some(LeftControl), repeat_count: 1, key_is_down: true }
 2022-01-03T15:49:59.580Z INFO  wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Delete), modifiers: CTRL, phys_code: Some(Delete), raw_code: 22, repeat_count: 1, key_is_down:true, handled: Handled(false) }
 2022-01-03T15:49:59.580Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('h'), modifiers: CTRL, raw_key: None, raw_modifiers: CTRL, raw_code: Some(22), phys_code: Some(Delete), repeat_count: 1, key_is_down: true }
```

The last two lines are the import ones: there's a raw key event for the physical `Delete` key, and then a processed key event that shows it as CTRL-h, which is equivalent to backspace from the terminal's perspective, but because it is phrased differently, doesn't match your key assignment.

For now, I'd suggest using this config to match the physical key press:

```lua
  keys = {
    {
      key="phys:Delete",
      mods="CTRL",
      action=wezterm.action{SendString="TEST"}
    },
  },
```

There's an open question on #1483 about whether `key="Backspace"` should be equivalent to `key="phys:Backspace"`.
For that one key it seems like an easy thing to justify, but for alphabetical keys it would be a big shift for users that don't have US QWERTY layout.

**Comment by GladOSkar** [comment]
Thanks, the workaround with `key="phys:Delete"` works perfectly. Should this be left open as a regression since `key="Backspace"` worked before?

**Comment by wez** [comment]
Yes; see the last paragraph of my comment above

**Comment by wez** [comment]
You should be able to go back to your original config now in `main`.

**Comment by GladOSkar** [comment]
Works great, thanks!
