### ISSUE TITLE
Cant hide terminal on CMD+h

### ISSUE THREAD

**Issue by erf** [wez/wezterm#150]
## Describe the bug

In other macOS apps im able to hide the window with `CMD+h`, but not in `wezterm`, even if i assign the key binding in the `.wezterm.toml`.

## Environment (please complete the following information):

 - OS: macOS
 - Frontend:  OpenGL
 - Version: WezTerm-macos-github-20200202-200216-b07ed454-5-g9558fbe

## To Reproduce

Open wezterm and press CMD+h in a macOS. Nothing happens. Even after key binding.

## Configuration

```
[[keys]]
key = "h"
mods = "CMD"
action = "Hide"
```

## Expected behavior

I would expect to hide/close the wezterm app / window on CMD+h like in other apps.

**Comment by wez** [comment]
This one is a slightly weird one on macOS, because macOS has a slightly weird application-centric rather than window-centric approach to managing windows.

* The default assignment for the wezterm `Hide` operation is CMD-M because that is how I had this function set up in the original linux version
* The wezterm `Hide` operation is defined as hiding the window
* on macOS, the default assignment for CMD-H when using the macOS default menubar (which we don't use) it to hide the entire application, which we don't have as a concept in wezterm
* wezterm lost the ability to hide windows on macos when we moved away from the `winit` library.  I've just pushed a commit that re-enables `Hide` on macos, but it is equivalent to miniaturizing the window (the yellow button in the titlebar) rather than hiding the entire application because that is how the wezterm `Hide` operation is defined.

**Comment by erf** [comment]
Ok thanks. I would prefer the default way of hiding the window, because it happens instantly and works the same way as other apps, but if it cant be done i'll close this.

Also the `CMD+q` button does not work the same way as other apps, but rather i must close the app using `CMD+w`, but i guess there is a reason for this also?

**Comment by wez** [comment]
FWIW, there's no technical reason that we couldn't add `HideApplication` and `QuitApplication` actions.  It just hasn't come up yet.

**Comment by erf** [comment]
@wez is it possible to recreate the default macOS hide without the `winit` library?

I would prefer the default OS behaviour if possible, or configurable via settings - please feel free to reopen this issue if you'd like to support this, or should i create a new issue?
