### ISSUE TITLE
Bundle Nerd fonts as fallback

### ISSUE THREAD

**Issue by jankatins** [wez/wezterm#1521]
**Is your feature request related to a problem? Please describe.**

Nerdfonts seem to fall into the same category into which wezterm falls: if you need a differet terminal emulator, you likely also want nerdfonts at some point. https://github.com/starship/starship, https://github.com/Yash-Handa/logo-ls and probably a lot more suggest installing nerd fonts.  https://github.com/wez/wezterm/issues/1516#issuecomment-1007789099 made the great suggestion to add the nerdfonts only font and use it as a fallback instead of using a patched font.

**Describe the solution you'd like**

Bundle the suggested nerd font only font and add it as a default fallback

**Describe alternatives you've considered**

Installing it myself and configuring wezterm to use them.

**Comment by wez** [comment]
I'm not sure whether https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/NerdFontsSymbolsOnly/complete/Symbols-1000-em%20Nerd%20Font%20Complete%20Mono.ttf 
or
https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/NerdFontsSymbolsOnly/complete/Symbols-2048-em%20Nerd%20Font%20Complete%20Mono.ttf
is best to bundle.

https://github.com/ryanoasis/nerd-fonts/issues/753 worries me a bit, so perhaps the 1000-em version is best?
I don't have a great way to sanity check that things really look sane because I don't use starship or other fancy prompt/vim things.

I'd love for someone to play around with these fonts and come up with a verdict on what works best, then we can see about bundling the symbols.

As for licensing: https://github.com/ryanoasis/nerd-fonts/blob/master/license-audit.md#glyphicon-sources suggests that things are mostly fine, but the Pomicons symbols have a non-commercial restriction which is not as free as the licensing for the rest of wezterm.  I think if we were to bundle and distribute, we'd need a version with Pomicons removed in order to avoid making wezterm's license less free.

**Comment by jankatins** [comment]
I'm now using this

```
  font = wezterm.font_with_fallback({
         "JetBrains Mono",
         "Symbols Nerd Font"
   }),
```
which ends up as this:

```
[00:38:46] λ  wezterm ls-fonts
Primary font:
wezterm.font_with_fallback({
  -- /usr/share/fonts/truetype/jetbrains-mono/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /home/js/.local/share/fonts/Symbols-1000-em Nerd Font Complete.ttf, FontConfig
  "Symbols Nerd Font",

  -- /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})
```

If I use the mono variant, wezterm picks up the 2024 variant:

```
[00:42:44] λ  wezterm ls-fonts
Primary font:
wezterm.font_with_fallback({
  -- /usr/share/fonts/truetype/jetbrains-mono/JetBrainsMono-Regular.ttf, FontConfig
  "JetBrains Mono",

  -- /home/js/.local/share/fonts/Symbols-2048-em Nerd Font Complete Mono.ttf, FontConfig
  "Symbols Nerd Font Mono",

  -- /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf, FontConfig
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})
```

and logo-ls doesn't show any icon. Removing all 2024 variant from the font folder picks up the `1000-em-*Mono` variant, but does not show any icons either :-( So I guess at least the (RC) release fonts are broken :-(

I'm currently going by the non-moo variant, they work :-)

**Comment by SuperSandro2000** [comment]
> [ryanoasis/nerd-fonts#753](https://github.com/ryanoasis/nerd-fonts/issues/753) worries me a bit, so perhaps the 1000-em version is best?

That is only for the latest version. I suggest to grab an older one for now.

I use the following config:

```lua
  font = wezterm.font_with_fallback({"JetBrains Mono", "Symbols Nerd Font"}),
```

**Comment by jankatins** [comment]
Seems https://github.com/ryanoasis/nerd-fonts/commit/d2cd41e4c59f1f791cefea13e635d8a1c9857993 fixes some stuff for ryanoasis/nerd-fonts#753, haven't tested yet.

**Comment by wez** [comment]
I've bundled a version of the font without pomicons.
This is how `exa --icons` looks now with the default config:
![image](https://user-images.githubusercontent.com/117777/149682011-ea6705eb-4c30-4868-b067-3ec30d72cf4c.png)

**Comment by wez** [comment]
with 54e92b685851a9e28751f6a3a0c3498f379b642c you can now do:

```lua
local wezterm = require 'wezterm'

wezterm.log_info(wezterm.nerdfonts.dev_mozilla)
```

to resolve a nerd font glyph given its css name (minus the `nf-` prefix) from the https://www.nerdfonts.com/cheat-sheet

I anticipate this being helpful for folks using those symbols in their status lines for example.

**Comment by wez** [comment]
Docs at: https://wezfurlong.org/wezterm/config/lua/wezterm/nerdfonts.html

**Comment by jankatins** [comment]
Amazing, thank you!
