### ISSUE TITLE
Mux model improvements

### ISSUE THREAD

**Issue by wez** [wez/wezterm#1531]
[This is a brain dump / design in progress - incomplete]

Today, the mux model consists of:

A `Mux` instance, which tracks:
* A set of `Domain`s, identified canonically by a locally generated `DomainId` and via a (hopefully!) unique `domain_name`
* A set of `Pane`s, identified by a locally generated `PaneId` and associated with a `Domain` via its `DomainId`
* A set of `Window`s, identified by a locally generated `WindowId`.  Each window manages an ordered list of `Tab`
* A `Tab` maintains a binary tree shaped structure representing the `Pane`'s in the tab. Each split produces a new level in the tree.
* Splits are currently constrained to the same `Domain`.

When using the multiplexer protocol, wezterm creates proxy `Domain` and `Pane` objects to represent those objects from the remote mux and make them available in the local mux.  Multiple mux connections are possible.

Users coming from `tmux` have noted that wezterm doesn't have a concept equivalent to a tmux session.  Part of the reason for that is that a tmux client is essentially *single headed*: it is just a single window that can switch to look at different tmux sessions.  In that way of thinking, a tmux session is equivalent to a gui window and tmux windows are equivalent to a tab in the gui window.  Contrast with wezterm, where multiple gui windows can exist: it's not necessarily super clear how to map those sessions and there is no UX in wezterm to even work with the session concept.

Another request that is coming in a lot recently is the ability to perform window management functions via the CLI--for example, to set the focused pane.  That concept doesn't exist in the mux and it has some extra implications.  Consider the scenario where the mux server is running with no gui on a remote host.  A local instance of the wezterm gui is connected.  The user wants to use the CLI on the remote host to change the focus. That focus change needs to propagate to the gui.  On its own it's just a matter of propagating that info to the client.  It is more complicated if there is a second or third wezterm gui--perhaps one is running on a machine in the office, and the other running at home, or perhaps two different people are concurrently connected to the same mux.  If we were to simply send the focus change to both clients then one of them might be annoyed. 

### Workspaces

* A workspace is a collection of `Window`s, `Tab`s and `Pane`s
* A workspace has a name
* Multiple workspaces can exist
* Two or more workspaces *may* reference the same `Pane`, in potentially different `Window`/`Tab` arrangements
* This means that the same-domain-to-split constraint mentioned above needs to be removed in order to allow flexible arrangement

### Formalize the list of clients

* Explicitly track and expose the list of connected clients to the mux data model
* The client id should be structured to include *username*, *hostname*, *pid*, *start time*, so that clients can be distinguished/matched in different contexts
* A client has an optional *active workspace*.
* The active workspace dictates the set of `Window`/`Tab` that are shown locally, as well as which events are sent from the server to the client
* The CLI will not have an active workspace, so events/notifications will not be delivered to it.
* The client may inform the remote mux about a local pane. For example, if I connect to a remote mux and then split a pane so that I have a local pane mixed in with the remote panes, then I'd like the remote mux to know where my local pane is situated so that if I disconnect (eg: laptop goes to sleep) and then while disconnected manipulate the workspace from another client, it is easier to reconcile the changes in the workspace when the laptop resumes.

### What about that focus-via-the-cli example?

A well-qualified focus request will specify the client-id, workspace and pane_id of the window to focus: there is no ambiguity in that case.

We'll need a way to resolve ambiguity for client and workspace if those are unspecified.

Likely policies for this:

* there's only a single client with an active workspace containing the requested pane, then we can pick that
* Most recently active client/workspace
* Based on partial client match eg: user+host matches, indicating the client and the gui are from the same host
* Just send it to all clients

**Comment by rosshadden** [comment]
Would this new model allow for connecting to different workspaces on a single remote host? I'm hoping to recreate a common tmux workflow:
- ssh into remote computer
- connect to any tmux session
- either use a mapping to change to a different session, or detach->attach to another

I was trying to get something like this working with the existing wezterm multiplexing but for the life of me I can't figure out how to tell a wezterm-gui which remote mux server to connect to. It just connects to I believe the oldest one.

**Comment by wez** [comment]
The idea is that the tmux session concept corresponds to a wezterm workspace.  There will be UX for listing and selecting the active workspace.

There are some design considerations around that that need to be worked out; how to reconcile a single local wezterm gui process connecting to two different remote mux servers and manage the active workspaces?  The active workspace on the client connections is quite clear, but locally there is a union of the local panes and those from the remote to manage and model in the local multiplexer on the gui client.  If you split a remote tab and spawned a local pane into it, then change the workspace on that remote connection, what happens to that local tab? Does it pop into its own window?  What if you had a bunch of those? Do they all go into new windows, or do they get grouped together?  Reconnecting should probably stick those things back where before you disconnected.

**Comment by rosshadden** [comment]
> If you split a remote tab and spawned a local pane into it, ...

My gut reaction is that splitting off a new window/tab/pane would be in the workspace you are connected to. When making a new tab while connected to a remote workspace, that source workspace itself as well as any other frontends connected to it would have the same tab be created.

I understand the desire for a workflow that lets us attach directly to subsets of a workspace, and at one point even had a workflow built around that kind of functionality in tmux. That being said, I believe the mirroring behavior I outlined is likely the most the common workflow people want. Though obviously you would know best whether it would make more sense to start with that as a base onto which we add advanced features, or start with more powerful primitives like what you are talking about, which can be used to craft this common workflow.

Please excuse my potential ignorance and naivety here. I just found wezterm late last night and was excitedly reading up on it and experimenting instead of getting a good night's sleep. I'm sure you have noticed that a big part of your userbase and potential userbase are people that want to recreate tmux workflows without tmux. You will not be able to cater to all of them, and in many cases it will likely not even make sense to have 1:1 parallels. But if the building blocks you make are small and composable enough people can create the exact experiences they want, and then as a community it should be pretty straightforward to do another pass to make the most common workflows more convenient for people to jump into.

**Comment by klamonte** [comment]
I don't want to create extra mental load, but wanted to point out [XtermWM](https://xtermwm.sourceforge.io) as it overlaps some of these concepts.  There might be some nuggets for you, or more likely pitfalls you want to avoid. :-)  I believe xtermwm's analogous concepts to domain/window/tab/pane are: window = user connection or backend (= tmux session) ; tab = desktop ; pane = panel.  (I don't think you have xtermwm "window" -- that would be a cascading window / floating terminal.  Does wezterm have those?)

[On shared sessions](https://gitlab.com/klamonte/xtermwm/-/wikis/shared-sessions) - basically I use telnet since it reports cols/rows, and do my tiling/cascading within the text cells, so a lot like a tmux session.  (I even detect screen/tmux and provide [detach as a pull-down menu item](https://gitlab.com/klamonte/xtermwm/-/blob/master/java/src/xtwm/ui/XTWMApplication.java#L774) ).  To make shared/detachable sessions easier, I created a persistent HeadlessBackend which just houses a screen and produces no input events.  When a user connects, that's the screen that is replicated to all other connections.  Connections can be marked read-only or read-write.  Since the connections are literally just telnet clients, images work fine and will emit at whatever best protocol the terminal on that connection can handle.  I emit dtterm windowOps sequences to try to have all the heads maintain the same terminal size in a shared session.

Anyway, just wanted you to have it for reference.  Also for UI, you might find [vtm](https://github.com/netxs-group/vtm) of interest -- it has some unique mouse actions and can do "recursive" display.  (vtm, xtermwm, and twin are the only multiplexers I have found so far that do cascading windows rather than or in addition to tiling windows; if anyone has heard of more I'd love to hear it.

**Comment by CIAvash** [comment]
Would saving and restoring sessions/workspaces fall under this?

**Comment by CIAvash** [comment]
Just to be clear, I meant restoring sessions/workspaces after a computer restart.

**Comment by shuxiao9058** [comment]
> Would saving and restoring sessions/workspaces fall under this?

how about this feature going now ? thanks for the great job.

**Comment by wez** [comment]
This issue is unrelated to saving/restoring sessions. The closest one to that is:
* https://github.com/wez/wezterm/issues/256
