### ISSUE TITLE
add support for "open wezterm here" in windows explorer

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#155]
Might be something like `wezterm explorer --install"? 

Also would be good to have both "open wezterm here" and "open wezterm here as Administrator".

**Comment by prabirshrestha** [comment]
This is for just "open cmd here".

```reg
Windows Registry Editor Version 5.00

;Created by Vishal Gupta for AskVG.com

[HKEY_CLASSES_ROOT\Directory\Background\shell\askvgcmd]
@="@shell32.dll,-8506"
"Extended"=""
"NoWorkingDirectory"=""

[HKEY_CLASSES_ROOT\Directory\Background\shell\askvgcmd\command]
@="cmd.exe /s /k pushd \"%V\""

[HKEY_CLASSES_ROOT\Directory\shell\askvgcmd]
@="@shell32.dll,-8506"
"Extended"=""
"NoWorkingDirectory"=""

[HKEY_CLASSES_ROOT\Directory\shell\askvgcmd\command]
@="cmd.exe /s /k pushd \"%V\""

[HKEY_CLASSES_ROOT\Drive\shell\askvgcmd]
@="@shell32.dll,-8506"
"Extended"=""
"NoWorkingDirectory"=""

[HKEY_CLASSES_ROOT\Drive\shell\askvgcmd\command]
@="cmd.exe /s /k pushd \"%V\""

```

**Comment by wez** [comment]
If you don't mind playing around with the registry entries to come up with the right settings for this, I'll get wezterm to register them with the right paths.

I suspect that the command that should be run should be something like:

```
wezterm.exe start --no-auto-connect -- cmd.exe /s /k pushd \"%V\"
```

I can see folks potentially also wanting to start powershell here instead of cmd.

**Comment by ImportTaste** [comment]
Hmm, what would be truly difficult is to get it to start in administrator mode from explorer. It is technically possible using powershell's Start-Process -Verb RunAs, but syntax that wouldn't fail on folders with apostrophes, dollar signs, etc. would be very messy.

Would adding an --admin parameter option to start be doable? Even if it accomplished this internally using that same powershell command, it would be far easier for wezterm to handle invoking it since it's be able to save the path to a variable using the multi-line `@'` `'@' syntax for saving literal strings, and then that variable could be tied to `-LiteralPath`...

A script that's invoked through the registry could also work, but I really dislike relying on scripts for context menu actions.

**Comment by wez** [comment]
If you use the new installer to install the latest nightly, it will set up an "Open WezTerm here" context menu that runs the `default_prog` (so you can configure whether it is cmd, powershell or whatever through the wezterm configuration) in that directory.

https://github.com/wez/wezterm/releases/download/nightly/WezTerm-nightly-setup.exe

**Comment by prabirshrestha** [comment]
@wez Tried it and it works great. One option I would also want to have is when I `shift+right click` I would like to see another option called `Open WezTerm here (Admin)`. A bit more info about this at https://www.tenforums.com/tutorials/59686-open-command-window-here-administrator-add-windows-10-a.html

**Comment by ImportTaste** [comment]
Opening as admin is difficult. Here's an example of how to do it with command prompt (.reg file format):
```reg
[HKEY_CLASSES_ROOT\Drive\shell\OpenCmdHereAsAdmin]
@="Open command window here as administrator"
"Extended"=""
"Icon"="imageres.dll,-5324"

[HKEY_CLASSES_ROOT\Drive\shell\OpenCmdHereAsAdmin\command]
@="cmd /c echo|set/p=\"%L\"|powershell -NoP -W 1 -NonI -NoL \"SaPs 'cmd' -Args '/c \"\"\"cd /d',$([char]34+$Input+[char]34),'^&^& start /b cmd.exe\"\"\"' -Verb RunAs\""


[HKEY_CLASSES_ROOT\Directory\shell\OpenCmdHereAsAdmin]
@="Open command window here as administrator"
"Extended"=""
"Icon"="imageres.dll,-5324"

[HKEY_CLASSES_ROOT\Directory\shell\OpenCmdHereAsAdmin\command]
@="cmd /c echo|set/p=\"%L\"|powershell -NoP -W 1 -NonI -NoL \"SaPs 'cmd' -Args '/c \"\"\"cd /d',$([char]34+$Input+[char]34),'^&^& start /b cmd.exe\"\"\"' -Verb RunAs\""


[HKEY_CLASSES_ROOT\Directory\Background\shell\OpenCmdHereAsAdmin]
@="Open command window here as administrator"
"Extended"=""
"Icon"="imageres.dll,-5324"

[HKEY_CLASSES_ROOT\Directory\Background\shell\OpenCmdHereAsAdmin\command]
@="cmd /c echo|set/p=\"%V\"|powershell -NoP -W 1 -NonI -NoL \"SaPs 'cmd' -Args '/c \"\"\"cd /d',$([char]34+$Input+[char]34),'^&^& start /b cmd.exe\"\"\"' -Verb RunAs\""


[HKEY_CLASSES_ROOT\LibraryFolder\Background\shell\OpenCmdHereAsAdmin]
@="Open command window here as administrator"
"Extended"=""
"Icon"="imageres.dll,-5324"

[HKEY_CLASSES_ROOT\LibraryFolder\background\shell\OpenCmdHereAsAdmin\command]
@="cmd /c echo|set/p=\"%V\"|powershell -NoP -W 1 -NonI -NoL \"SaPs 'cmd' -Args '/c \"\"\"cd /d',$([char]34+$Input+[char]34),'^&^& start /b cmd.exe\"\"\"' -Verb RunAs\""
```
Basically it starts with the system default cmd and goes into powershell to use it's Start-Process command, -Verb RunAs is running as administrator. Everything else is just workarounds to get around the quoting issue.

Speaking of, I would really appreciate it if reg files were made available for adding wezterm to the context menu instead of having to run the install - even if the reg files were just exclusive to the git repo.

**Comment by wez** [comment]
Regarding the as-admin portion of this, I have perhaps unconventional views: I don't think wezterm itself should be run as admin and instead I think we should use [EleDo](https://github.com/wez/eledo#eledoexe) (which I plan to bundle with the wezterm download on windows) to spawn whatever your `default_prog` is as admin, so that only that part has admin privs.

For example, we could, by default, add an entry to the [launcher menu](https://wezfurlong.org/wezterm/config/launch.html#the-launcher-menu) that runs the `default_prog` with `eledo.exe` prepended to the command line.

Taking the principle of least privilege further, I'd personally lean towards never spawning an admin shell and just using eledo to elevate individual commands, which would obviate the need to launch either wezterm or the default prog as admin.

regarding `.reg` files / adding a `wezterm explorer --install`, I opted not to go that route because there isn't a great story around uninstalling or upgrading/evolving the registry entries.  I don't want to support making system level changes outside of the installer/uninstaller flow.  When I tag the next release the installer will be available on the stable "channel" and at that point I really want most people to be using the installer.  I view the portable-mode install via the .zip as being explicitly incompatible with setting up registry entries on the system; you either install it or don't!

Regarding development flows: I run with the installer-installed wezterm locally.  If I wanted to install that build before it's become available in the nightly, I can generate the installer locally and upgrade my local install that way.  I expect there to be very few people that would need to do this on any kind of regular basis, as the the CI generates the installer on each PR and continuously for the nightly builds--it is much quicker and easier to use those.

**Comment by ImportTaste** [comment]
>I view the portable-mode install via the .zip as being explicitly incompatible with setting up registry entries on the system; you either install it or don't!

There is precedent for terminals doing this, however. cmder, one of the most popular terminals, has this option. I personally have a script for adding things to the registry and then reverting them when I'm finished, so I don't believe it's conceptually against the idea of portables.

**Comment by prabirshrestha** [comment]
@wez Actually it is possible to add an uninstall item in control pannel via just inf and without creating a full blow installer. I was looking into cleaning up my dotfiles and noticed it. https://github.com/prabirshrestha/dotfiles/blob/3b3a1079e7a3505a1e34eeb0922ba09c1fd10d23/Console2Here.inf

It is using `inf` so you can right click the file and click install from explorer which will also add an uninstall section in control pannel and explain how to remove it. You could have `wezterm explorer --install` but then tell users to uninstall using control panel. Or you could also support `wezterm explorer --uninstall` that will automatically go and remove the registries.

**Comment by ImportTaste** [comment]
Using files meant for drivers to handle installation info... that's actually pretty clever, and incredibly backwards compatible.
