### ISSUE TITLE
Feature Request: Unify scroll mode, search mode and copy mode

### ISSUE THREAD

**Issue by leira** [wez/wezterm#1592]
**Is your feature request related to a problem? Please describe.**
There are 3 different modes which involve moving around in the history scroll buffer.
1. scroll mode: this mode is triggered through `<Alt+PgUp>` or mouse scroll. In this mode, one can select with mouse and copy using `<Ctrl+Shift+C>`. One can trigger search using `<Ctrl+Shift+F>`, but that will change to search mode, and the view will jump to the bottom of the history, despite where the view is in the scroll mode.
2. search mode: this mode is triggered using `<Ctrl+Shift+F>`. In this mode, one can search back through the scroll history. When search mode is triggered, no matter where the view is in the scrolling history, the view always jumps back to the bottom. If it was in copy mode, copy mode will exit. One can still use `<Alt+PgUp>` and mouse to scroll the view, but search again always jump back to where the current highlighted search is.
3. copy mode: this mode is triggered using `<Ctrl+Shift+X>`. This mode is similar to tmux copy mode. In this mode, one can scroll or move the cursor using key bindings. `<Space>` triggers selection. One can still use `<Alt+PgUp>` or mouse to scroll the view, but scrolling doesn't change the position of the cursor. Next time one use a copy-mode keybinding to move the cursor, the view jumps back. There is no built-in search in copy mode. `<Ctrl+Shift+C>` exits copy mode and enters search mode. The view is reset despite where the cursor is before the switch.

These 3 modes are very similar, has a lot of overlapping. But they don't provide a full feature set by themselves, and also don't play well with each other. Also, having these 3 different modes doing similar but slightly different things creates confusion and cognitive stress.

**Describe the solution you'd like**
I think these 3 modes essentially are one mode, a unified copy mode, just like the copy mode in tmux:
1. Unified copy mode is triggered through a. `<Alt+PgUp>` or other keybindings, b. mouse scroll.
2. When entering the unified copy mode, a cursor is drawn, the copy mode keybindings are enabled.
3. In unified copy mode, `<Alt+PgUp>` now behaves exactly like `<PgUp>` in copy mode, in that the cursor follows the view. Mouse scroll also works, it moves the cursor too if needed.
3. In unified copy mode, a forward search can be triggered with `/` or <Ctrl+F>, a backward search can be triggered with `<Shift+/>` or `<Ctrl+Shift+F>`. The search starts within the current view.
4. Triggering search move the cursor to the search input, when `<Enter>` is pressed, the cursor moves to the current highlighted match. One can move to the next match by pressing `n` or `<Ctrl+G>`, and move to the previous match by pressing `<Shift+N>` or `<Ctrl+Shift+G>`.

**Comment by NikosEfthias** [comment]
👍  this is much needed since theres no way to actually jump places quickly in copy mode.

**Comment by wez** [comment]
I just pushed a change to `main` that merges copy and search mode into a single overlay.  The two modes are still conceptually separated because the key bindings need to behave differently, but they now share state.

What that means is that you can activate search mode to find something, then activate copy mode to move the cursor around, or vice versa, and the search results and viewport position will remain as they were in the prior mode.

In addition, search mode key assignments are now configurable via a `search_mode` key table; I still need to write up docs for that, but you can get the gist of how it works by looking at:

* https://github.com/wez/wezterm/issues/993

and then looking at the available assignments for copy mode over here; these are the search mode specific assignments:

https://github.com/wez/wezterm/blob/main/wezterm-gui/src/overlay/copy.rs#L749-L756

An approximation of what you requested above might be set up something like this:

```lua
local wezterm = require 'wezterm';

return {
  key_tables = {
    copy_mode = {
      {key="Escape", mods="NONE", action=wezterm.action{CopyMode="Close"}},
      {key="h", mods="NONE", action=wezterm.action{CopyMode="MoveLeft"}},
      {key="j", mods="NONE", action=wezterm.action{CopyMode="MoveDown"}},
      {key="k", mods="NONE", action=wezterm.action{CopyMode="MoveUp"}},
      {key="l", mods="NONE", action=wezterm.action{CopyMode="MoveRight"}},
      {key=" ", mods="NONE", action=wezterm.action{CopyMode="ToggleSelectionByCell"}},
      -- Enter search mode to edit the pattern.
      -- When the search pattern is an empty string the existing pattern is preserved
      {key="/", mods="NONE", action=wezterm.action{Search={CaseSensitiveString=""}}},
      -- navigate any search mode results
      {key="n", mods="NONE", action=wezterm.action{CopyMode="NextMatch"}},
      {key="N", mods="SHIFT", action=wezterm.action{CopyMode="PriorMatch"}},
    },
    search_mode = {
      {key="Escape", mods="NONE", action=wezterm.action{CopyMode="Close"}},
      -- Go back to copy mode when pressing enter, so that we can use unmodified keys like "n"
      -- to navigate search results without conflicting with typing into the search area.
      {key="Enter", mods="NONE", action="ActivateCopyMode"},
    },
  },
}
```

**Comment by NikosEfthias** [comment]
I have just installed this version and trying but seems like the keybindings above have no effect whatsoever. <C-S-x> starts usual copy mode in which `/` has no effect (after copy pasting the bindings above)

**Comment by wez** [comment]
@NikosEfthias please file a new issue and be sure to include your full configuration

**Comment by bew** [comment]
It seems your resolution only merged copy mode & search mode, but not scroll mode with .

I tried it by:
- opening a wezterm without config (`wezterm -n`),
- print buch of text,
- scroll up with the mouse
- trigger copy mode => viewport is back to the bottom of the screen
- OR trigger search mode => (since previous search is prefilled, find that and move viewport to it), it's hard to search something you know is probably visible in the current viewport

**Comment by wez** [comment]
@bew can you open a separate issue for that?
