### ISSUE TITLE
Transparent gap between CSD and content when there are splits

### ISSUE THREAD

**Issue by unrelentingtech** [wez/wezterm#1620]
### What Operating System(s) are you seeing this problem on?

FreeBSD Wayland

### WezTerm version

wezterm 20220102-211953-732813e6

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Exactly what it says in the subject :) See screenshot below. I think this might be a consequence of fixing #1256.

### To Reproduce

Have no background except the color set by the shell, do a split.

### Configuration

no config

### Anything else?

![Screen_2022-02-06-14:26:41](https://user-images.githubusercontent.com/208340/152678870-a1d02147-6b22-4ffa-8ad1-58f91dbedb9d.png)

**Comment by kohnish** [comment]
Also on wayland. In my case, there is a gap only between tab bar and top.
You can also see weird black gaps in general, like when you open vim.

**Comment by wez** [comment]
Fixed in 5913783d1ef6a8b7a66e60a065c4568dc6db5f22

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
