### ISSUE TITLE
add support for wezterm sudo

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#167]
Given that there are already some features in wezterm such as `imgcat`, `ssh` would it be possible to have `wezterm sudo`. This would specially be very useful in windows where there is no good sudo commands.

Here is a useful link.
https://superuser.com/questions/42537/is-there-any-sudo-command-for-windows

**Comment by wez** [comment]
Can you expand on how you see that working?

`sudo` does a lot of stuff and most closely resembles the `runas` command that is builtin to `cmd.exe`, but I suspect that what you really want is something that runs elevated using the UAC consent UI.

One of the challenges with the Windows architecture here is that the only documented ways to trigger UAC are using `ShellExecute` (with the `runas` verb) and via a COM object (with an elevated moniker).  Neither of these allow for attaching the process to a PTY, which makes it a bit awkward to somehow integrate into a PTY-centric terminal emulator.

I'm not opposed to adding something like `wezterm win32-shell-execute -verb runas some command` as a more convenient way to configure a menu/hotkey action to eg: spawn a separate elevated wezterm instance, but it doesn't appear possible to integrate more deeply than that without doing something undocumented and unsupported.

**Comment by prabirshrestha** [comment]
I basically want to elevate a command temporary to show the UAC.

But I will never remember this command `wezterm win32-shell-execute -verb runas some command` unless wezterm has some sort of `alias` similar to git, so for windows I can use `wezterm sudo command`.

**Comment by wez** [comment]
I've been thinking about this and I'm still not sure that it makes sense for this to exist in wezterm, but also recognize that there aren't really any good existing solutions for this.

Recently at work we've been running into the opposite problem from this issue, which is people running too much from elevated sessions and causing problems with permissions.  I spent some time this past week looking into the guts of running commands in different contexts, mostly with an eye on reducing the privilege level.  Once I'd figured out how to do, adding support for elevating was pretty easy.

I have another rust crate that provides `eledo.exe` (*Elevated Do*, rather than *Super User Do*), and `normdo.exe` (*Normal User Do*) commands that behave in a similar way to the unix `sudo` utility; `eledo` elevates privs whereas `normdo` drops privs.

Crucially, these commands know how to spawn a PTY in the target context and tunnel it back into the current user context, allowing for each of `stdin`, `stdout`, `stderr`, `CONIN$` and `CONOUT$` to be bridged between the environments: so piping and terminal output should both work.

That crate lives over in this other repo, which needs a bit more cleanup before I consider a more formal release of that crate:

https://github.com/wez/deelevate#eledoexe

To use it you need to have `eledo.exe` and `eledo-pty-bridge.exe` in the same directory and to be somewhere in your `PATH`, then you can just `eledo PROGRAM [ARGUMENTS]` to run something with a UAC prompt.

I'm considering how I want to integrate this into wezterm; I think I might just bundle those executables as part of the wezterm download, but I need to think on this a bit more.

I'd welcome your feedback!

**Comment by prabirshrestha** [comment]
I currently use this for sudo on windows. http://blog.lukesampson.com/sudo-for-windows. 
I personally don't need to downgrade but do see some use cases for it. I wouldn't try to get sudo bundled in wezterm just for the sake of it. The only primary reason I brought it up was wezterm supports `imgcat` so thought it would be good to support `sudo` too.

Feel free to close the issue for now.

**Comment by prabirshrestha** [comment]
That makes sense. Also would love to have an option for installer that has a shim for "sudo" that internally call eledo. Heard to break the muscel memory.
