### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by truchi** [wez/wezterm#172]
Found out Wezterm last night, decided to give it a try! To no avail...

```
$ sudo apt install ./wezterm-nightly.deb 
Reading package lists... Error!
E: Problem parsing dependency 21 of wezterm:amd64=20200406-151651-5b700e4-29-gea401e1f
E: Error occurred while processing wezterm (NewVersion2)
E: Problem with MergeList /home/<censored>/wezterm-nightly.deb
E: The package lists or status file could not be parsed or opened.

$ sudo apt install ./wezterm-20200406-151651-5b700e4.deb 
Reading package lists... Error!
E: Problem parsing dependency 21 of wezterm:amd64=20200406-151651-5b700e4
E: Error occurred while processing wezterm (NewVersion2)
E: Problem with MergeList /home/<censored>/wezterm-20200406-151651-5b700e4.deb
E: The package lists or status file could not be parsed or opened.

$ sudo apt install ./wezterm-20200202-200216-b07ed454.deb 
Reading package lists... Error!
E: Problem parsing dependency 21 of wezterm:amd64=20200202-200216-b07ed454
E: Error occurred while processing wezterm (NewVersion2)
E: Problem with MergeList /home/<censored>/wezterm-20200202-200216-b07ed454.deb
E: The package lists or status file could not be parsed or opened.
```

Send help! Don't make me install Alacritty it doesn't even have ligatures...
I'll try to build from source and keep you posted.

EDIT:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

**Comment by truchi** [comment]
Building from source worked:

```
$ rustup update
$ curl -LO https://github.com/wez/wezterm/releases/download/20200406-151651-5b700e4/wezterm-20200406-151651-5b700e4-src.tar.gz
$ tar -xzf wezterm-20200406-151651-5b700e4-src.tar.gz
$ cd wezterm-20200406-151651-5b700e4
$ sudo ./get-deps
$ cargo build --release
$ cargo run --release -- start
    Finished release [optimized] target(s) in 0.20s
     Running `target/release/wezterm start`
 2020-04-27T11:52:44.529Z ERROR window::os::x_and_wayland > Failed to init wayland: Could not find a listening wayland compositor.
shm_available: true
picked visual 21, screen root visual is 21
 2020-04-27T11:52:44.627Z ERROR window::egl               > initialized EGL version 1.4

```

Gave me those two little errors but its working.
Can we fullscreen?

Thanks

**Comment by truchi** [comment]
Oh and:
![wez](https://user-images.githubusercontent.com/9745474/80369897-4fdff680-888f-11ea-9aca-70f34c336a43.png)

**Comment by wez** [comment]
Regarding the installation failure: I think that may be due to the ubuntu 19 not liking the ubuntu 16 package for whatever reason (likely some kind of binary package format change).  I can look at adding explicit builds for the different versions of ubuntu.  Another alternative to building from source is to try the AppImage or raw linux binary downloads.

Regarding the missing icon: I've pushed a commit that should populate the icon correctly both for X11 and Wayland now!

Regarding fullscreen: please file a separate issue for that.  Typically the window manager has a shortcut that works with wezterm, but we also claim to offer a built in hotkey action for this and it isn't hooked up right now!

**Comment by wez** [comment]
"Official" Ubuntu 19 packages are now linked from the install page:
https://wezfurlong.org/wezterm/installation.html
