### ISSUE TITLE
wezterm-gui.exe --help outputs nothing on Windows.

### ISSUE THREAD

**Issue by martinlindhe** [wez/wezterm#1801]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220330-204634-e23e972c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

On Windows, `wezterm.exe --help` outputs help text.

But `wezterm-gui.exe --help` does not. See screenshot.

The same version correctly outputs help text on macOS (well I only tried 20220319-142410-0fcdea07 on macOS. 20220319-142410-0fcdea07 on Windows exhibit the same issue as described here).

# 20220330-204634-e23e972c
![image](https://user-images.githubusercontent.com/181531/161065056-00759fbc-c592-49ea-9133-cca01ec64916.png)

# 20220319-142410-0fcdea07
![image](https://user-images.githubusercontent.com/181531/161060917-faed8fac-f890-4503-bd4f-fc1fff8e0e18.png)

### Configuration

```lua
local wezterm = require 'wezterm';

return {
	default_prog = { "nu.exe", "-l", "--config-file", "D:/Sync/config/nushell/config.toml" },
	color_scheme = "Monokai Remastered",
	font = wezterm.font("FiraCode NF"),
	font_size = 10, 
	initial_cols = 140,
	initial_rows = 40,
	use_fancy_tab_bar = false,
	tab_bar_at_bottom = true,
	window_close_confirmation = "NeverPrompt",
}
```

**Comment by wez** [comment]
`wezterm-gui.exe` is a win32 application and doesn't attach to a console by default.  This is deliberate, otherwise you'd always have a cmd.exe window open in addition to the wezterm window.   This Windows architectural quirk is one the main reasons that `wezterm` and `wezterm-gui` both exist.

You can run `wezterm-gui.exe --attach-parent-console` to have it explicitly connect to the console of its parent process, but if you are doing that then you perhaps should just be running `wezterm.exe` instead, which will pass that flag down when it forwards subcommands to the gui executable.

**Comment by martinlindhe** [comment]
Thanks @wez. I got a bit confused by this actually, trying to use wezterm-gui.exe for log output as in #1576.
