### ISSUE TITLE
Wezterm won't open in Parallels/Catalina

### ISSUE THREAD

**Issue by tcbtcb** [wez/wezterm#1819]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220405-071707-de615080

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When running in Parallels wezterm won't start after doing the 'this application was downloaded from the internet bit.' I guessed it was permissions, but it looks like it may be an issue w/ the graphics driver(s) in Parallells. Happened in both most recent stable and nightly. 

here's the basic output from the terminal. The longer trace logs I'll put below 

tcb@~ % /Applications/WezTerm.app/Contents/MacOS/wezterm-gui       
 2022-04-05T15:15:26.935Z INFO  wezterm_mux_server_impl::local > setting up /Users/tcb/.local/share/wezterm/gui-sock-760
 2022-04-05T15:15:27.010Z ERROR wezterm_gui::frontend          > Failed to create window: failed to create NSOpenGLPixelFormat

### To Reproduce

Open wezterm in parallels

### Configuration

no wezterm.lua was present in either case. 

### Expected Behavior

Application opens. 

### Logs

[wezterm-no-start.log](https://github.com/wez/wezterm/files/8419680/wezterm-no-start.log)

### Anything else?

Nope! I'll look at the rest some time soon, just be I'm interested, but I don't know much rust so I doubt I'll have any great ideas. 

Love the tool! Just was hoping to get it running in my virtual env that I have to fun in some situations for legacy software reasons.

**Comment by wez** [comment]
To get this to run, you need to set https://wezfurlong.org/wezterm/config/lua/config/prefer_egl.html to true and to install MetalANGLE.

We used to ship MetalANGLE in older versions of wezterm, but stopped since BigSur made CGL run in terms of Metal.
You can find that build of MetalANGLE in the wezterm repo:
https://github.com/wez/wezterm/tree/main/assets/macos/WezTerm.app

I have no plans to add this back to the distribution, so you may wish instead to use an older wezterm release.  `20201101-103216-403d002d` was the last version to ship with this.

Be aware that I can't effectively support these older/legacy systems, so you will likely be on your own if other issues arise.

**Comment by tcbtcb** [comment]
Ah, thanks for the info. I can manage that easily enough. This VM is kept around because we have legacy VPN clients that sometimes need to be used, so installing an older version and leaving it alone is just fine. Thanks a ton, I really appreciate it.
