### ISSUE TITLE
Weird keystorkes after saving file with VIM

### ISSUE THREAD

**Issue by DorZion** [wez/wezterm#1850]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220409-221922-b83c3272

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After the latest update (including nightly builds), after exiting and saving a file through VIM, keystorkes is being sent to the terminal after pressing on any key, forcing me to `CTRL+C` every time.

I'm using fish shell, so I thought it's a shell bug, but I also tried the same thing with bash and got the same result. It doesn't happen in different terminals though.

### To Reproduce

1. Open vim anywhere
2. Exit and save (`:x` / `:qw`)
3. Press any key
4. You should see the terminal is being filled with keystrokes, for example:
`:0+r4B31^[\^[P0+r4B33^[\^[P0+r4B34^[\^[P0+r4B35^[\^[P1+r6B42=1B5B5A^[\`

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  font_size = 12.0,
  audible_bell = "Disabled",
  automatically_reload_config = true,
  color_scheme = "Snazzy",
  force_reverse_video_cursor = true,
  use_fancy_tab_bar = false,
}
```

### Logs

```
15:37:30.418 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
15:37:30.419 WARN mux::localpane > unknown DeviceControlMode::Enter EnterDeviceControlMode(params: [], intermediates: [], byte: 'z' 0x7a, ignored_extra_intermediates=false)
15:37:30.419 WARN mux::localpane > unhandled DeviceControlMode::Data 7a z
15:37:30.419 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: "0%m"
15:37:30.944 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
15:37:30.944 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
```

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm
* Inside that terminal run `wezterm record`
* You'll then be inside a recording session; open and close vim as your repro steps say above
* After exiting vim, type exit.
* You should see a message like:

```
Child status: Some(ExitStatus { successful: true })
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

Attach the file that it produced to this issue.
The file is an asciicast (compatible with asciinema) and can also be replayed using `wezterm replay`.

**Comment by DorZion** [comment]
Here is the recording:
[wezterm-recording-QpMbPc.cast.txt](https://github.com/wez/wezterm/files/8459095/wezterm-recording-QpMbPc.cast.txt)

**Comment by wez** [comment]
> EDIT: I noticed I can only reproduce it if I open vim and just exit and save. Doing more stuff inside vim and then exiting, won't reproduce the bug.

Ah, I've been poking around at this since you shared the recording and I didn't see your edit.
OK, what you said gives me confidence that 4753df96f664dbc3415d3ff522ca3b72f50bd0e9 will fix things for you.

The gist of the issue is that `vim` sends `"\u001bP+q436f\u001b\\\u001bP+q6b75\u001b\\\u001bP+q6b64\u001b\\\u001bP+q6b72\u001b\\\u001bP+q6b6c\u001b\\\u001bP+q2332\u001b\\\u001bP+q2334\u001b\\\u001bP+q2569\u001b\\\u001bP+q2a37\u001b\\\u001bP+q6b31\u001b\\"` which translates to:

```
> SENT
        Action(XtGetTcap(["Co"]))
        Action(XtGetTcap(["ku"]))
        Action(XtGetTcap(["kd"]))
        Action(XtGetTcap(["kr"]))
        Action(XtGetTcap(["kl"]))
        Action(XtGetTcap(["#2"]))
        Action(XtGetTcap(["#4"]))
        Action(XtGetTcap(["%i"]))
        Action(XtGetTcap(["*7"]))
        Action(XtGetTcap(["k1"]))
```

the "junk" that you get when quitting vim quickly was stuff like `"\u{1b}P1+r6B75=1B4F41\u{1b}\\\u{1b}P1+r6B64=1B4F42\u{1b}\\\u{1b}P1+r6B72=1B4F43\u{1b}\\\u{1b}P1+r6B6C=1B4F44\u{1b}\\"` which is the encoded responses generated by wezterm.

Those responses are correctly formatted, but they just appear to be late.

The commit I mentioned explicitly flushes them in the hope that vim receives them more quickly.

So, please try a nightly build that has that fix; it should be available on linux within about 20 minutes of the commit being pushed.

**Comment by DorZion** [comment]
That seems to fix it.

Thanks for the fix and the explanation!
