### ISSUE TITLE
ShowLauncher Action not working from Keybinding

### ISSUE THREAD

**Issue by mborejdo** [wez/wezterm#188]
## Describe the bug
The documented _ShowLauncher_ action cannot be triggered by a keybinding.
Additionally the shown error-message cannot be selected and copied with the mouse

## Environment (please complete the following information):

 - OS: Microsoft Windows [Version 10.0.19041.264]
 - Frontend:  ?
 - Version: wezterm 20200517-122836-92c201c6-6-g7ddff705

## To Reproduce
Run Action via Keybinding

## Configuration
```
keys = {
    {key="m", mods="ALT", action="ShowTabNavigator"},
    {key="l", mods="ALT", action="ShowLauncher"},
}
```
## Expected behavior
The Launcher-UI should be shown. Instead wezterm errors

**Comment by wez** [comment]
ah, sorry about this; this is due to a legacy layer from the older TOML based config file days.
Coincidentally, I was looking at removing that already so was able to push f6743086ac8c9e48e71da5c2ec9a431e2fbc1835 just now, which seems to work for me; you can give that a try when this build completes:

https://github.com/wez/wezterm/actions/runs/111582964

Note that these changes also remove the legacy `arg` parameter from the key assignment, so if you see an error about an unexpected unit struct while parsing a `Key` then that is what it is referring to.  You're only likely to see that if you copied the sample config in for assigning F-keys to jump directly to tabs.

(I'll also look at the clipboard issue with the error window!)

**Comment by mborejdo** [comment]
@wez Thanks for providing the build. I can confirm, ShowLauncher-Action works.
I will open another bugticket for the unselectable Error-Message. This problem still persists.

**Comment by mborejdo** [comment]
## Describe the bug
A wezterm Configuration-Error Message cannot be selected with the mouse to be able to copy the message. A Selection is flashing for a short period of time, but is then reset

## Environment (please complete the following information):
OS: Microsoft Windows [Version 10.0.19041.264]
Frontend: ?
Version: wezterm 20200517-122836-92c201c6-6-g7ddff705

## To Reproduce
Add a misspelled Action for a Keybinding in wezterm-config-file

## Configuration
```
keys = {
		{
			key="m", mods="ALT", action="ShowTabNavigator"
		},		
		{
			key="l", mods="ALT", action="ShowLauncherx"
		},
	}
```
## Expected behavior
Being able to copy a provided error-message
