### ISSUE TITLE
cargo install --git not possible on Windows

### ISSUE THREAD

**Issue by mborejdo** [wez/wezterm#190]
Instead of checking out and compiling manually, I usually cargo install repos directly from git. 
Currently this is not possible with wezterm on Windows. The final buildstep in build.rs looks for assets to be copied on Windows, which unfortunately fails on my system. As I am new to rust / rustup, I might miss something.
It would be great, if there is a way to directly cargo install wezterm on windows and possibly skip the copy-step

**Comment by wez** [comment]
This isn't a flow that I've tried, and unfortunately doesn't seem like it's one that I can support; for the best experience on Windows we need put a few supporting files that are unknown (and unknowable!) to cargo into the right places.

I am interested in streamlining the install/upgrade scenario; today wezterm can check for explicitly tagged releases and show you a download screen if you're running an older version.  I haven't added support for testing for the nightly/continuous builds for this yet because I'd like the flow to be fairly automatic: it needs to be able to download and upgrade itself and it can be tricky to do that to an executable that is still running on Windows.

If you're looking for the convenience of a one-line upgrade command: you may wish to consider looking at Scoop. https://wezfurlong.org/wezterm/installation.html#for-scoop-users has some more links/details.  I'm not sure if scoop can be told to grab a nightly build though!

**Comment by mborejdo** [comment]
thanks for the reply @wez. Would it be possible hide the "asset-copy-step" behind some feature-flag? I have not much clue about rust and the ecosystem. Currently I am mostlikely misusing cargo install as the way to maintain my rust binaries.
I installed wezterm (stable) with scoop. They do have a versions-bucket where you can provide alternative versions/nightlies. Maybe I will go this path, as I currently install some tools with scoop. Thats also probably why I have the companion.files in the right places

**Comment by wez** [comment]
I'm not going to support using `cargo install` to install wezterm; the setup.exe installer and scoop are the recommended flows for this.
