### ISSUE TITLE
font-config matching issue when displaying ✔ (U+2714)

### ISSUE THREAD

**Issue by lyu** [wez/wezterm#1913]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Whether '✔' is displayed correctly depends on how it is shown in the terminal for the first time.
If it was shown by itself (or with no other visible characters close to it), then it will be displayed correctly thereafter.
If it was displayed with another visible character by its side, then it is displayed as an unknown dingbat character thereafter.

### To Reproduce

Let's say we have two text files with the following contents:

one.txt (SHA1: 661cafa4bbd04cd93b89317838ded28a8eefc767)
```
✔
```
two.txt (SHA1: 9f33a9cf813d7c0b0bd36eeea5726f0a75108f67)
```
✔a
```

The second file is just the first file with an additional 'a' (doesn't have to be 'a', but cannot be the whitespace).

Open a new instance of wezterm and cat the two files in different orders.

![one_two](https://user-images.githubusercontent.com/14036212/164999277-2c7c199e-33a8-4fff-bcf5-f01665502acb.png)

![two_one](https://user-images.githubusercontent.com/14036212/164999280-8e962335-5b66-41dd-abe0-5377789a0dc7.png)

I can play with two.txt to get different results, for example, inserting one or two whitespace between '✔' and 'a' isn't enough, but three works.

I can't test the nightly binary due to #1905

### Configuration

```
local wezterm = require 'wezterm';

return {
    enable_wayland = true,

    color_scheme = "Gruvbox Dark",

    font_size = 11.0,

    font = wezterm.font_with_fallback({
        {family="Cascadia Mono", weight="Regular"},
        "Noto Sans Symbols 2"
    }),

    scrollback_lines = 8192,

    use_fancy_tab_bar = false,

    enable_scroll_bar = true,

    window_padding = {
        left = 2,
        right = 0,
        top = 0,
        bottom = 0,
    },

    default_cursor_style = "SteadyBlock",

    tab_max_width = 128,
}
```

### Expected Behavior

I expect '✔' to always be displayed correctly.

### Anything else?

```
> printf "%x\n" \'✔
2714
> fc-list ':charset=2714'
/usr/share/fonts/TTF/fa-solid-900.ttf: Font Awesome 6 Free,Font Awesome 6 Free Solid:style=Solid
/usr/share/fonts/noto/NotoSansSymbols2-Regular.ttf: Noto Sans Symbols2:style=Regular
```

**Comment by wez** [comment]
Please run: `wezterm ls-fonts --text "$(cat one.txt)"` and `wezterm ls-fonts --text "$(cat two.txt)"` and share the output!

**Comment by lyu** [comment]
```
> wezterm ls-fonts --text "$(cat one.txt)"
LeftToRight
 0 ✔    \u{2714}     x_adv=14 cells=1  glyph=360  wezterm.font("Noto Sans Symbols2", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/noto/NotoSansSymbols2-Regular.ttf, FontConfig
> wezterm ls-fonts --text "$(cat two.txt)"
LeftToRight
 0 ✔    \u{2714}     x_adv=17 cells=1  glyph=90   wezterm.font("Last Resort High-Efficiency", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
 3 a    \u{61}       x_adv=9  cells=1  glyph=225  wezterm.font("Cascadia Mono", {weight="Regular", stretch="Normal", style="Normal"})
                                      /usr/share/fonts/TTF/CascadiaMono.ttf, FontConfig
```

**Comment by wez** [comment]
Weird!

Let's try: `WEZTERM_LOG=wezterm_font=trace,info wezterm ls-fonts --text "$(cat two.txt)" 2>&1 > /tmp/wat.txt` and attach `/tmp/wat.txt` here!

**Comment by lyu** [comment]
Here you go!
[wat.txt](https://github.com/wez/wezterm/files/8550703/wat.txt)

**Comment by wez** [comment]
Can you try changing your font setting to this?  Note that there is no space before the `2`:

```lua
 font = wezterm.font_with_fallback({
        {family="Cascadia Mono", weight="Regular"},
        "Noto Sans Symbols2"
    }),
```

**Comment by wez** [comment]
If that works, then the question is: why did it resolve with `one.txt` and not `two.txt`?  Could you put your config back to `"Noto Sans Symbols 2"` (with the space) and run:

`WEZTERM_LOG=wezterm_font=trace,info wezterm ls-fonts --text "$(cat one.txt)" 2>&1 > /tmp/one.txt`

and attach that file here so that we can compare what it's trying to do?

**Comment by lyu** [comment]
Removing the space before '2' fixed this issue lol. I used the fallback API when investigating this issue. Originally I used a single `font = wezterm.font("Cascadia Mono", {weight="Regular"})` when I first noticed this issue.

Anyway, here is the log: 
[wat2.txt](https://github.com/wez/wezterm/files/8550727/wat2.txt)

**Comment by wez** [comment]
In the `two.txt` case:

* The name listed in your config doesn't match the canonical name of the font
* font-config can return an approximate match (perhaps there is some system level config that provides an alias?) but since that name doesn't match the font, wezterm doesn't see it
* Because that font is a secondary font, wezterm doesn't warn about not being able to find it
* When shaping "U+2714 a", that whole string fails to shape because none of the known fonts have U+2714 so wezterm looks for fallbacks for both of those codepoints
* The fallback resolution finds a font that matches the `a` but not U+2714
* No additional fallback is attempted

In the `one.txt` case, the steps are broadly the same, except that fallback resolution only needs to find `U+2714` and it does find the symbols2 font.

The main question to answer here is:

* Why doesn't the fallback code consistently produce the symbols2 font for both cases?

**Comment by lyu** [comment]
One additional piece of info: wezterm 20220101-133340-7edc5b5a does not have this issue, while wezterm-20220319.142410.0fcdea07 and after do.

**Comment by l4zy0n3** [comment]
![image](https://user-images.githubusercontent.com/21274221/165113840-4ad2f49e-7434-4d58-bf4e-6aabd038b3e7.png)
![image](https://user-images.githubusercontent.com/21274221/165114075-b9d8fc9d-b2ce-4455-b405-3829d84d5a9b.png)

I am facing a similar issue in the prompt (git) section, which I believe is due to the ! character beside ✘ @wez these issues seem to have the same cause, do you want a separate bug for this?

**Comment by wez** [comment]
@l4zy0n3 yes please: a separate issue with the information from your system helps to understand whether it is actually the same, or if not, allows me to close out the different issue independently--it's easier to manage.

**Comment by wez** [comment]
> The main question to answer here is:
> 
> * Why doesn't the fallback code consistently produce the symbols2 font for both cases?

The answer is: because we already resolved the mapping for a different style of text and mistakenly skip doing it again for eg: bold text later on.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
