### ISSUE TITLE
using `exec "set <M-P>=\eP"` in vim cause partial XTGETTCAP answerback to appear in the editor

### ISSUE THREAD

**Issue by mikewy0527** [wez/wezterm#1917]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220425-071018-39d2726e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I want to Use Option+H/J/K/L to switch window between built-in terminal and other window in vim, so I mapped it in `vimrc`. I work, I can use it to switch window, but it cause other strange behavior: It generated a `Bell` event when enter vim first time; The first input `i` cannot enter `INSERT` mode, and so on.

In iTerm2 and Alacritty, the vimrc work correctly, So I consider it's a bug.

### To Reproduce

1. start wezterm:
```
wezterm --config-file wezterm.lua
```
2. in wezterm, start vim:
```
vim -u vimrc
```

### Configuration

1. wezterm.lua:

```
local wezterm = require 'wezterm';

return {
  window_close_confirmation = "NeverPrompt",
  debug_key_events = true,
}
```

2. vimrc:
```
set nocompatible

if !has('nvim') && !has('gui_running')
    function! Terminal_MetaMode(mode)
       function! s:metacode(mode, key)
            if a:mode == 0
                exec "set <M-".a:key.">=\e".a:key
            else
                exec "set <M-".a:key.">=\e]{0}".a:key."~"
            endif
        endfunc
        for i in range(10)
            call s:metacode(a:mode, nr2char(char2nr('0') + i))
        endfor
        for i in range(26)
            call s:metacode(a:mode, nr2char(char2nr('a') + i))
            call s:metacode(a:mode, nr2char(char2nr('A') + i))
        endfor
        if a:mode != 0
            for c in [',', '.', '/', ';', '[', ']', '{', '}']
                call s:metacode(a:mode, c)
            endfor
            for c in ['?', ':', '-', '_', '+', '=']
                call s:metacode(a:mode, c)
            endfor
        else
            for c in [',', '.', '/', ';', '{', '}']
                call s:metacode(a:mode, c)
            endfor
            for c in ['?', ':', '-', '_', '+', '=', "'"]
                call s:metacode(a:mode, c)
            endfor
        endif
    endfunc

    call Terminal_MetaMode(0)
endif

noremap <M-H> <C-w>h
noremap <M-L> <C-w>l
noremap <M-J> <C-w>j
noremap <M-K> <C-w>k

set termwinkey=<C-_>
tnoremap <M-H> <C-_>h
tnoremap <M-L> <C-_>l
tnoremap <M-J> <C-_>j
tnoremap <M-K> <C-_>k
```

### Expected Behavior

Map `Option+H/J/K/L` should work, and typing in vim should work as normal.

### Logs

keyevent log:
[wezterm-keyevent-20220426.log](https://github.com/wez/wezterm/files/8557332/wezterm-keyevent-20220426.log)

recording:
[wezterm-recording-H3sc7T.cast.txt](https://github.com/wez/wezterm/files/8557268/wezterm-recording-H3sc7T.cast.txt)

**Comment by mikewy0527** [comment]
Using the following vimrc,  generated a Bell event when enter vim first time.
```
set nocompatible

let s:c=nr2char(char2nr('A')+15)
exec "set <M-".s:c.">=\e".s:c
```

And it genetate some output like this:
![image](https://user-images.githubusercontent.com/15612693/165227784-d9f1e589-9f3e-4725-85f0-d8a418e0d79b.png)

recording:
[wezterm-recording-Aa6bNY.cast.txt](https://github.com/wez/wezterm/files/8560120/wezterm-recording-Aa6bNY.cast.txt)

**Comment by wez** [comment]
A clearer set of steps to repro this are:

1. Put this in `/tmp/1917-vimrc`:
 
```vimrc
set nocompatible
exec "set <M-P>=\eP"
```

2. Then run `vim -u /tmp/1917-vimrc` and observe the partial XTGETTCAP response inline in the editor.

See #1850 for a recent related issue.

What's interesting is that if you eliminate the `exec` and just directly `set`, then vim doesn't have this issue:
 
```vimrc
set nocompatible
set <M-P>=\eP
```

Trying the original vimrc in the kitty terminal emulator also results in the same behavior, with the XTGETTCAP response showing up in the editor.

I believe this to be a vim bug when using `set` to change its terminal related modes from withing an `exec`.
Please file an issue in the vim repo and link it back to this one so that we can figure out a way to resolve this!

**Comment by mikewy0527** [comment]
I test again in kitty with the vimrc I originally posted, It generated a Bell event when enter vim first time too, but the first input `i`  enter INSERT mode. (Here just use `i` as example)

And I found some difference in the line-end of XTGETTCAP response between wezterm and kitty:
test command:
```
vim -u min-vimrc -E
```

vimrc:
```
set nocompatible
exec "set <M-P>=\eP"
```

wezterm output:
```
... \Ð1+r2A37=1B5B313B3246\Ð1+r6B31=1B4F50\
```

kitty output:
```
... \Ð1+r2a37=1b5b313b3246\Ð1+r6b31=1b4f50\Ð1$r1 q\
```

wezterm lacking the `Ð1$r1 q\`

**Comment by wez** [comment]
> wezterm lacking the `Ð1$r1 q\`
> 
> Is this the reason?

No, that's a different response to a different request.

The heart of this issue is that vim doesn't appear to wait long enough to read the XTGETTCAP response when using `set` within an `exec`, and instead treats it as though input were typed in the editor.

That is behavior is visible in `xterm` (when it is configured to respond to `XTGETTCAP`), `kitty` and `wezterm` (which always respond to `XTGETTCAP`).
