### ISSUE TITLE
DECRQM (CSI ? Ps $ p) is delayed until next CSI

### ISSUE THREAD

**Issue by kumattau** [wez/wezterm#1950]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220501-214322-e0785311

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

DECRQM (CSI ? Ps $ p) is delayed until next CSI.

### To Reproduce

```
cat <<EOF > DECRQM.sh
read -s -t 1 -d y -p \$'\e[?5\$p'   A; echo "A=\$A" | cat -v
read -s -t 1 -d S -p \$'\e[?2;1;0S' B; echo "B=\$B" | cat -v
EOF

bash DECRQM.sh
A=
B=^[[?5;0$y^[[?2;0;952;992
```

### Configuration

```
local wezterm = require 'wezterm';
return {
  font = wezterm.font("Cica"),
  font_size = 11.0,
  freetype_load_flags = "DEFAULT",
  freetype_load_target = "Light",
  hide_tab_bar_if_only_one_tab = true,
  window_background_opacity = 0.8,
  keys = {
    {key="Enter", mods="CTRL|SHIFT", action="SpawnWindow"},
  },
  window_padding = {left = 0, right = 0, top = 0, bottom = 0},
}
```

### Expected Behavior

```
cat <<EOF > DECRQM.sh
read -s -t 1 -d y -p \$'\e[?5\$p'   A; echo "A=\$A" | cat -v
read -s -t 1 -d S -p \$'\e[?2;1;0S' B; echo "B=\$B" | cat -v
EOF

bash DECRQM.sh
A=^[[?5;0$y
B=^[[?2;0;952;992
```

### Anything else?

https://github.com/hackerb9/lsix expects the DECRQM (CSI ? 5 $ p) response but cannot get it and the following subsequent XTSMGRAPHICS (CSI ? 2 ; 1 ; 0 S) gets unexpected (the combination of DECQRM and XTSMGRAPHICS) response.

https://github.com/hackerb9/lsix/blob/f7cbe5d90249986be7b5c62b777363414231b331/lsix#L149-L162

**Comment by wez** [comment]
Thanks for the report; cee50fffb8cacfcdc55ea8932d2fadaaff22ceeb makes sure to flush after responding, so this should now be fixed in `main`!

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by kumattau** [comment]
@wez thank you for quick fix. I checked cee50fffb8cacfcdc55ea8932d2fadaaff22ceeb works fine.
