### ISSUE TITLE
Font offset option

### ISSUE THREAD

**Issue by aca** [wez/wezterm#1979]
**Is your feature request related to a problem? Please describe.**
This is related to https://github.com/wez/wezterm/discussions/1644
Alacritty has font offset option that I can use it to change font width without changing fonts and It is very useful.
I found that most of the fonts doesn't provides "stretch" option. So I have to patch font by myself (which I don't know how to do).

IBM PLEX MONO x offset 0
![image](https://user-images.githubusercontent.com/50316549/168032133-813af1ed-e9cc-4a30-b73d-432a8a77dac5.png)
IBM PLEX MONO x offset -2
![image](https://user-images.githubusercontent.com/50316549/168032154-f96666f5-6b07-4d2f-b829-00fb914f3d9a.png)

**Describe the solution you'd like**
I'm sorry but I have no idea.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by wez** [comment]
This is a potentially thorny problem because wezterm uses a proper font shaper (which is why ligatures are supported in wezterm and not in alacritty) and the proposed adjustment would conflict with what the font shaper is telling wezterm to do with glyph positioning.

What do you expect to happen when the font has ligatures for eg: `<=`?
I suspect that the result will look "smooshed" up and weird.  Is that desirable?
What about for ligatured scripts like farsi?  I think it will make things unreadable.

What about the computed cell size?  Is your proposal to make it 2 pixels narrower?

**Comment by wez** [comment]
`main` now has a [cell_width](https://wezfurlong.org/wezterm/config/lua/config/cell_width.html) option to scale the effective cell width.

This is explained in detail in the docs: https://wezfurlong.org/wezterm/config/lua/config/cell_width.html

This is implemented as a scaling factor rather than pixel offset so that it can work more consistently in situations where the system scaling factor is changed or when the font scaling is changed.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by kumattau** [comment]
I share cell_width experiments. It works fine.
cell_width option is very useful for me
because I like narrower spacing than hurfbuzz and freetype original.

cell_width = 1.0 (default)
![Screenshot from 2022-05-21 23-39-08](https://user-images.githubusercontent.com/171798/169656938-098081e4-3a8a-4378-b26b-635d1738a492.png)

cell_width = 0.85
![Screenshot from 2022-05-21 23-38-02](https://user-images.githubusercontent.com/171798/169656953-b71c217b-2b31-461d-8d99-e9a63e622b24.png)

cell_width = 0.75
![Screenshot from 2022-05-21 23-40-42](https://user-images.githubusercontent.com/171798/169656962-9f3cbf08-781a-4493-9529-a98c84c83144.png)

**Comment by aca** [comment]
Amazing. Awesome @wez !
