### ISSUE TITLE
Tab title does not update after exiting from ssh session

### ISSUE THREAD

**Issue by gwww** [wez/wezterm#1981]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220501-214322-e0785311

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

<img width="380" alt="Screen Shot 2022-05-12 at 22 52 12" src="https://user-images.githubusercontent.com/3060128/168202010-e6a8f365-c33a-4a4a-8173-48b070070167.png">

The title in the tabs remain as the text "exit" after exiting from a ssh session. They do not change again after "exit".

### To Reproduce

In `wezterm` do the following:
```
ssh somehost
# Title updates correctly for commands, cd, etc while ssh'ed somewhere

exit
# return to local shell, tab title says "exit" and will not change again while in local shell
# Tab title will change if I ssh again, but typing exit freezes tab title text again
```

### Configuration

I don't think I have anything relevant in my my config, but it is here: https://github.com/gwww/dotfiles/tree/main/.config/wezterm

### Logs

These don't seem relevant. Should they even be warnings?
```
12:52:54.768 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
12:52:58.987 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
12:53:02.452 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
12:53:28.340 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
12:53:35.473 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
12:59:44.736 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
13:00:16.724 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
13:00:18.777 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
13:00:51.754 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
13:02:06.049 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
13:02:09.939 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
22:54:45.548 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
22:54:47.308 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
```

**Comment by wez** [comment]
This isn't a bug. What's happening is:

* Your local shell doesn't do anything to set the title, so the default behavior is wezterm's dynamic "guess the program" title value
* When you login to the remote host, the remote shell changes the title some number of times
* When you exit the remote host, you are returned to your local shell session which no longer changes the title
* Since the title was explicitly set, the dynamic "guess the program" title isn't used.
* In the absence of the shell/programs running in the terminal telling wezterm that something like this has happened, wezterm has no way to know that this has happened and thus cannot react to it.

The solution is to configure your local shell to explicitly set the title to something useful.

**Comment by gwww** [comment]
That makes sense. Is there a "magic" sequence that will turn the "guess the program" back on? I'm not asking for anything, this really is nothing I care that much about.

**Comment by wez** [comment]
Setting the title to `wezterm` will trigger the guessing logic:

```bash
echo "\x1b]0;wezterm\x1b\\"
```
