### ISSUE TITLE
nushell duplicates lines for every key

### ISSUE THREAD

**Issue by CGMossa** [wez/wezterm#1999]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm on Windows, nushell version 0.62.0:

For every keystroke, wezterm just repeats the line:
![image](https://user-images.githubusercontent.com/1063624/168675966-daac7f4c-b35c-4b2b-a855-932b30853967.png)

I've tried

- Using default wezterm configuration
- Already using default nushell
- Nightly version of nushell
This behavior doesn't happen on `windows-terminal`. 

### Configuration

no config

**Comment by wez** [comment]
This sort of thing sounds like you might have a stray newline in your prompt stuff.

wezterm doesn't care that you're running nushell, so if you only see this with nushell and wezterm, it's more likely that nushell is doing something that manifests this way in wezterm.

I don't run nushell and I have no idea how to configure it, so I can give only very high level advice here.

What I would do in your place is work through the various options available to nushell, particularly around the prompt customization, to see if you can find something that influences this.

If possible, try starting nushell in a mode that bypasses all local configuration options, so that it runs in its most basic mode to see if that changes this behavior.

It's probably also worth opening an issue with the nushell folks to see if they can give some advice on how to isolate what is happening and then we can figure out what to do about it.

**Comment by CGMossa** [comment]
I've tried a few things, and @fdncred over at nushell's Discord has spent a lot of time trying to replicate this, but without success. I don't know what to do honestly @adrianstaniec.

**Comment by CGMossa** [comment]
I *think* the issue lies with the prompt code. I changed configuration to use `starship`, and that helped, but there is flickering, and the flickering (atleast on my end) looks like there is an `/r/n` being dealt with somehow. 
If you can explore the prompt used in your configuration, and show me how to show that, then maybe we can troubleshoot further.

**Comment by CGMossa** [comment]
@adrianstaniec Please try to install nushell 0.62.1 (currently on main). I've put the command line to do in nushell/nushell#5585. I just tried that, and the issue disappeared.

**Comment by adrianstaniec** [comment]
@CGMossa , yes! thank you, that solved my problem :)

**Comment by CGMossa** [comment]
Closing this then. I did find other stuff while troubleshooting this.
But that's for other issues
