### ISSUE TITLE
Strange escape sequences in vim and neovim for Ctrl-Up|Down|Right|Left

### ISSUE THREAD

**Issue by diefans** [wez/wezterm#203]
## Describe the bug

In `vim` and `neovim` I get not the usual escape sequences. 

I would expect the same sequences as in e.g. `alacritty` or `xterm`, e.g.:

### vim
```
                wezterm   alacritty/xterm

Ctrl-Up         ^[O1;5A   ^[[1;5A
Ctrl-Down       ^[O1;5B   ^[[1;5B
Ctrl-Right      ^[O1;5C   ^[[1;5C
Ctrl-Left       ^[O1;5D   ^[[1;5D
```
### neovim
```
                wezterm   alacritty/xterm

Ctrl-Up         ^A;5A     <C-Up>
Ctrl-Down       ^A;5B     <C-Down>
Ctrl-Right      ^A;5C     <C-Right>
Ctrl-Left       ^A;5D     <C-Left>
```
## Environment (please complete the following information):

 - OS: archlinux
 - Frontend:  OpenGL
 - Version: wezterm 20200517-122836-92c201c6-67-g7c2dce47

## To Reproduce

Start vim or neovim, start insert mode press `<C-V><C-Up|Down|Right|Left>`

## Configuration

no custom keys

## Expected behavior
Same as alacritty or xterm

**Comment by wez** [comment]
Those are SS3 representations of the cursor keys.  It looks like this is a slightly weird behavior of neovim tickling a weird behavior in wezterm.

neovim enables [DECKPAM](https://vt100.net/docs/vt510-rm/DECKPAM.html) and [DECCKM](https://vt100.net/docs/vt510-rm/DECCKM.html) modes to switch the reporting sequences for keypad and cursor keys.

However, the vt510 docs for DECCKM are incomplete; here's an excerpt from the https://vt100.net/docs/vt100-ug/chapter3.html docs:

> DECCKM – Cursor Keys Mode (DEC Private)
> This is a private parameter applicable to set mode (SM) and reset mode (RM) control sequences. This mode is only effective when the terminal is in keypad application mode (see DECKPAM) and the ANSI/VT52 mode (DECANM) is set (see DECANM). Under these conditions, if the cursor key mode is reset, the four cursor function keys will send ANSI cursor control commands. If cursor key mode is set, the four cursor function keys will send application functions.

So it seems that DECCKM doesn't make sense unless [DECANM](https://vt100.net/docs/vt510-rm/DECANM.html) is also enabled--hence my comment about the slightly weird neovim behavior (why enable one without the other?).  Note that regular vim doesn't enable those modes.

Regardless, since wezterm is the one with the differing behavior I've fixed it up to conform to the vt100 docs.

**Comment by diefans** [comment]
thanks!
