### ISSUE TITLE
Redesign of the logo

### ISSUE THREAD

**Issue by saccarosium** [wez/wezterm#2045]
Hi,
I'm loving the terminal, and I would like to contribute to the project. Unfortunately I don't know rust, but as a graphic designer I could help with the logo.

Is it something that you're interested in?

**Comment by wez** [comment]
Thanks for offering to contribute!

I'd suggest look at https://github.com/wez/wezterm/discussions/1142 which was an earlier pass over the logo to arrive at the current one.

I'm open to seeing new designs, but want to be transparent about how I think about this: based on the earlier discussion, it's clear that what people think of as good for logos/icons is subjective, and there's no guarantee that what you design will become the primary logo/icon.  That said, I think it would be nice to offer a few alternative icons for folks to pick from to have a better chance of matching their desktop aesthetic.

If you're looking to apply your design/artistic skills, there are some other areas around wezterm that I think would be cool to develop; I recognize that graphic design skills don't automatically equate to some of these, but I'm just putting these ideas out there:

* wezterm supports animated background images. https://www.reddit.com/r/unixporn/comments/m5bwp8/wezterm_a_highly_configurable_cross_platform/ shows some of the customization features. I think it would be great to offer some nice animated backgrounds that have subtle/low-movement that wouldn't be too distracting to use as the backdrop to a window that people use for hours a day.
* Another thing I've been thinking of around this is making the the background image be able to scroll with a kind of parallax effect (eg: scrolling the text up by 3 rows might scroll the background up by, say, 3 pixels, rather than 30 if a cell is 10 pixels tall). If there were some good background images designed to tile vertically, I that effect could look pretty cool. eg: a very tall tree slows scrolls as you work in your shell. Or a retro/pixel art elevator scene. Maybe a space elevator or something.  Those images could also be animated as well.
* https://github.com/wez/wezterm/issues/1432 talks about supporting animated cursors, but I haven't put any significant effort into this yet because I haven't found any animated gifs that might look good as a cursor. What I have in mind is something like a "light chasing" effect where instead of blinking/fading the cursor bar/box runs back and forth around the edges. I think there are probably quite a few different "spinner" animations out there that might give some inspiration on this. Similar to the first point, I think the best ones are likely to be relatively slow/subtle effects, and work with the text cell rather than getting in the way of it. If we had a handful of good options for this sort of thing, I think that would be great!

**Comment by saccarosium** [comment]
> based on the earlier discussion, it's clear that what people think of as good for logos/icons is subjective, and there's no guarantee that what you design will become the primary logo/icon.

I'm aware of this and I would never impose anything, you have the last word after all. Having said so, my goal is to design some icons that feels at home on the different environment where the application runs, mainly OSX and Linux (Gnome and KDE).

> That said, I think it would be nice to offer a few alternative icons for folks to pick from to have a better chance of matching their desktop aesthetic.

Yeah would be a great idea! It can be implemented, at least in homebrew, like [emacs plus](https://github.com/d12frosted/homebrew-emacs-plus) does.

![image](https://user-images.githubusercontent.com/96259932/170835377-1fbe74fd-313e-4f90-a616-70a02c6bc3a5.jpeg)

For the other stuff I see what I can do... I'm at my first year of CS, I will try to learn and help where I can.

**Comment by wez** [comment]
I'm going to close this out for now, as there isn't any action for me to take right now
