### ISSUE TITLE
Sync the current working directory from the running program

### ISSUE THREAD

**Issue by sayanarijit** [wez/wezterm#2054]
**Is your feature request related to a problem? Please describe.**

When I use a TUI program like [xplr](https://github.com/sayanarijit/xplr) to navigate the file system in wezterm, spawning a new tab or window opens the session in my home directory.

To reproduce, 

- Use any terminal file manager (e.g. nnn, lf, ranger, vifm, xplr)
- Navigate to any directory other than your home directory.
- Spawn a new window or tab by pressing `cmd-n` or `ctrl-shift-t`.

**Describe the solution you'd like**

I would like the new session to open in the current working directory of the application, similar to when I spawn the session from a shell prompt.

**Describe alternatives you've considered**

None.

**Additional context**

The functionality is implemented in Alacritty and Kitty.

**Comment by wez** [comment]
wezterm already does this.  Take a look at the flow chart over here to see how the working directory is determined: https://wezfurlong.org/wezterm/config/lua/config/default_cwd.html

From what you described, I'm assuming that your shell uses OSC 7 to set the current working directory and that xplr does not.
Since OSC 7 takes precedence, the "resolve the cwd of the process" logic is skipped.

There are two ways you can reconcile this:
* Configure your shell to not emit OSC 7, so that it doesn't override the cwd
* Raise an issue with the xplr folks to have them emit OSC 7 when xplr changes the current working directory.

[More information on OSC 7 can be found here](https://wezfurlong.org/wezterm/shell-integration.html#osc-7-escape-sequence-to-set-the-working-directory)

**Comment by sayanarijit** [comment]
Thanks for your response. I'll definitely give it a reading, But before that, I wonder about the following points:

- This happens not only with xplr, but also with nnn, vifm, ranger etc.
- From terminal side, this happens only with Wezterm, but not with Alacritty and Kitty.

So, shall still I assume that it's the intended behavior and other terminals haven't implemented the specification yet?

**Comment by wez** [comment]
What I suspect is that your shell doesn't enable OSC 7 for those other terminals. If it did, I'd expect them to exhibit the same issue.

**Comment by wez** [comment]
I made a suggestion on that PR that will make it work!

**Comment by sayanarijit** [comment]
Awesome. It works. So, since I don't have much background on this, is there any compatibility related concern I need to be aware of while implementing this?

**Comment by sayanarijit** [comment]
Actually, I managed to break things even in modern terminals. One of xplr's use case is selected and printing files on stdout `xplr > selected_files.txt`, which doesn't play well with OSC 7. So, for terminal tools with similar functionality, I think OCS 7 will be a problem. Is there a way to disable it in Wezterm?

**Comment by wez** [comment]
No, OSC 7 cannot be disabled.

I'd suggest one of two options:

* See if you can piggy back on the stream that the tui library is using to write to the terminal, instead of writing to stdout directly. https://docs.rs/tui/latest/tui/backend/struct.CrosstermBackend.html implements Write so if you can get at the backend, you can write OSC 7 to that.
* Alternatively, open `/dev/tty` for yourself and write OSC 7 there

**Comment by sayanarijit** [comment]
Ah right... That makes sense. I can treat it as a UI thing. Thanks for the tips.
