### ISSUE TITLE
Certain powerline glyphs don't look right

### ISSUE THREAD

**Issue by ProspectPyxis** [wez/wezterm#2079]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220605-223126-4776c8d9

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I wanted to use some of the fancier powerline glyphs for customization of my tab bar, but they don't seem to display correctly. Everything from `0xe0c0` to `0xe0d4` as described [here](https://github.com/ryanoasis/powerline-extra-symbols#glyphs) don't cover the entire column even when `allow_square_glyphs_to_overflow_width` is set to `"Always"`, and setting the config option to `"Never"` only worsens the issue as the glyphs are rendered as normal text.

### To Reproduce

In any terminal, type the command:
```bash
printf '\e[0;47m   \e[0;37m\u[CODE]\n'
```
Replace [CODE] with any unicode ID between `e0c0` to `e0d4`. This will print out three colored spaces for comparison, then the chosen powerline glyph.

This should make it clear that the glyph is noticeably smaller than the full height of the line.

### Configuration

```lua
-- Optional, to test behavior with allow_square_glyphs_to_overflow_width
return {
  allow_square_glyphs_to_overflow_width = "Always" -- or "Never"
}
```

### Expected Behavior

The glyphs should:
1. Take up the full height of the line.
2. Ideally, not overflow the width even if `allow_square_glyphs_to_ovewflow_width` is `Always`, though that may be out of scope for this issue.

### Logs

N/A as far as I know.

### Anything else?

Some examples I tried:
![image](https://user-images.githubusercontent.com/25642180/172146849-b96be7e1-0e7c-4005-a9eb-0b00f121a37b.png)

**Comment by digitallyserviced** [comment]
Is that the only font related config option you have set? This is rather difficult to help if we do not know what your full configuration is.

Can you provide parts pertaining to font options or just all of your config?

Font size, line height, and font family specifically. 

I had similar issues, and it ended up being that certain fonts do not like being set with fractional (10.5), or the specified font size and line height do not jive when being anti aliased or hinted by the font renderere. It takes some trial and error to find what causes those issues for you, defaults try their best to work for everyone but when you star to customize one part of the default config it does not always like the rest of the defaults to work with.

**Also you will sometimes have to _completely_ restart the Wezterm GUI instead of just letting the config reload to see if the changes worked as this was a cause of frustration for me because it was never looking like it was making anything better when working with the config.**

**Comment by ProspectPyxis** [comment]
That actually is the entire config - this bug happens even without a config file for me. I just inserted the snippet to show what happens when you set that particular option. I can try manually setting line height and font size, though, and see if the issue disappears.

**Comment by wez** [comment]
Those glyphs come from the default `Symbols Nerd Font Mono` fallback font, which has slightly different metrics from the baseline font.  Automatically adjusting metrics across different font families is difficult.  wezterm actually draws its own versions of most of the powerline glyphs to guarantee that they are pixel-perfect, but the symbols you've chosen are not in that range because they are much more complex than most of the simple powerline block glyphs.

What you can do to configure around this is override the scaling for that fallback font; https://wezfurlong.org/wezterm/config/lua/wezterm/font_with_fallback.html#manual-fallback-scaling explains this, but the config might look something like this; you may need to tweak the scale for it to look right:

```lua
local wezterm = require 'wezterm'

return {
  font = wezterm.font_with_fallback({
    "JetBrains Mono",
    {family="Symbols Nerd Font Mono", scale=1.2},
  }),
}
```

I'm open to making that default fallback font also use an adjusted scale factor like that if we can be confident that the same factor will work across linux, mac, windows with both hi and standard dpi, and if that scale factor also works with other fonts than JetBrains Mono.

**Comment by ProspectPyxis** [comment]
Hmm, this is more complicated than I thought. Something I noticed while I was trying to get the scaling right is that the glyphs tend to get pushed down somewhat:
![image](https://user-images.githubusercontent.com/25642180/172808581-ebe14d88-941a-4dfc-894a-335493aba612.png)
_This is with scale 1.2._

I tried setting the scaling higher, but that created the opposite issue where the glyphs are now overflowing the bottom:
![image](https://user-images.githubusercontent.com/25642180/172808881-0bba3c0d-a49a-4103-b082-4ce1c6849ac9.png)
_This is with scale 1.4. Also note the little gap before the lego block glyph._

Scale 1.3 just ends up making it look blurry, and it doesn't quite align with either the bottom or the top:
![image](https://user-images.githubusercontent.com/25642180/172810508-8026de9a-6627-4aac-a734-c182464a594f.png)

Regardless of the scaling used, though, the problem with scaling the backup font here is that it ends up making all the other icon fonts too big for me too. The only way I can think of to fix that, though, would be to have some way to separately scale a glyph range, but that might not be practical to implement...

The new config I'm using for all these screenshots is just your config snippet with the scale value changed.

(Side note, I've decided to not use these glyphs for my configuration in the end, so feel free to close this issue if you don't think there's anything to be done here.)

**Comment by wez** [comment]
I don't think this is really fixable in wezterm itself (unless someone recreates those powerline glyphs in wezterm's custom block glyph set, but that seems difficult given the nature of those particular glyphs), so I'm going to close this out.
