### ISSUE TITLE
Use Github light theme, but got visual impairment

### ISSUE THREAD

**Issue by richie-king** [wez/wezterm#2097]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220508-223436-7858f652

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I use wezterm with GitHub light/dark theme, but on light theme, have a little bit visual problem, details as bellow

This yellow chars (eg. "USAGE" in selected, "OPTIONS" "SUBCOMMANDS" not selected) can not seen in GitHub light theme

<img width="700" alt="image" src="https://user-images.githubusercontent.com/45933315/172774904-ddde045f-4768-4542-83dc-70f5bbaf2945.png">

I want to know the GitHub theme file location, so I can change the font color to make it visiable rather than each time to select to make it seen

Thanks for your kindly help, wezterm make my terminal experience really good

### Configuration

no config 
only have problem with GitHub light theme

**Comment by wez** [comment]
See https://wezfurlong.org/wezterm/config/lua/wezterm/get_builtin_color_schemes.html for an example of how to override colors from a color scheme.

Note that the color schemes have their source of truth in https://github.com/mbadolato/iTerm2-Color-Schemes, so if you wish to propose a permanent change to them, you will need to do so over there so that we can then sync the changes back over here.

**Comment by richie-king** [comment]
Thanks for your nicely  explanation. Have a nice day !!! 😄
