### ISSUE TITLE
Change enable_wayland default to true

### ISSUE THREAD

**Issue by Quackdoc** [wez/wezterm#2104]
**Is your feature request related to a problem? Please describe.**
Wayland should be automatically detected. When using xWayland it can often cause the text to be blurry, this can cause eyestrain and cause people headaches when looking at it for prolonged periods of time. 

**Describe the solution you'd like**
By default wayland should be enabled when on wayland platforms.  

**Additional context**
There are two potential environment variables that wezterm can check to determine if running on wayland. you have 

`WAYLAND_DISPLAY` or `XDG_SESSION_TYPE`. xdg_session_type can be hit or miss, wayland_display should be preferred here. this also opens up the ability to be potentially aware of potentially running in nested compositors.

**Comment by wez** [comment]
There isn't really any detection that needs to be done for this; by default, wezterm explicitly doesn't try wayland because wayland support isn't as good as its x11 support and XWayland is usually a better experience.

I think we can consider changing this default now, as a number of improvements have been made to wayland support over the past couple of releases.
