### ISSUE TITLE
macos: integrated GPU is used when launched via Finder, discrete is used when launched via CLI

### ISSUE THREAD

**Issue by pmizio** [wez/wezterm#2138]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Bug is clearly visible on video:

https://user-images.githubusercontent.com/4346598/174482203-cb0c2dab-e173-472b-bb24-8a512f8110a8.mov

Logs aren't helpful I think because like you see in video bug isn't there when I run wezterm from another terminal. 
I tried nightly also and suffers same problem.

### Configuration

```lua
local wezterm = require("wezterm")

return {
	default_prog = { "/usr/local/bin/fish", "-l" },
	color_scheme = "Gruvbox Dark",
	font = wezterm.font("FiraCode Nerd Font Mono"),
}
```

### Logs
Run from GUI:
```
15:04:03.332 WARN env_bootstrap > setlocale(en_PL.UTF-8) failed, fall back to en_US.UTF-8
15:04:03.405 INFO wezterm_mux_server_impl::local > setting up /Users/user/.local/share/wezterm/gui-sock-9214
15:04:03.545 INFO wezterm_gui::termwindow > OpenGL initialized! Intel(R) UHD Graphics 630 4.1 INTEL-18.7.4 is_context_loss_possible=false wezterm version: 20220408-101518-b908e2dd
```

Run from other terminal:
```
15:10:39.189 WARN wezterm_gui > while attempting to ask existing instance to spawn: Running GUI is a different executable from us, will start a new one
15:10:39.242 INFO wezterm_mux_server_impl::local > setting up /Users/user/.local/share/wezterm/gui-sock-9290
15:10:40.978 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon Pro 5300M OpenGL Engine 4.1 ATI-4.8.54 is_context_loss_possible=false wezterm version: 20220408-101518-b908e2dd
```

**Comment by wez** [comment]
I'm not sure what I'm looking at in the video as there is a lot of zooming around. Could you explain in words what the issue is?
Thanks!

**Comment by pmizio** [comment]
It's all about this zooming, when I run term from GUI of macos no matter it is spotlight, bottom bar or finder wezterm use incorrect gpu:
```
15:04:03.545 INFO wezterm_gui::termwindow > OpenGL initialized! Intel(R) UHD Graphics 630 4.1 INTEL-18.7.4 
```
And I suppose cause this stuttering while zooming.

When I launch wezterm from other terminal, wez pickup dedicated gpu of my mac:
```
15:10:40.978 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon Pro 5300M OpenGL Engine 4.1 ATI-4.8.54 ```
And in this case everything is buttery smooth.

**Comment by wez** [comment]
Oh, very interesting. I don't have a intel mac to try this on, but do you see preferences in the Finder info for the wezterm app?
https://www.imore.com/how-set-your-egpu-preferred-rendering-device-macos-mojave suggests that there is some control for egpu, I think there might be something similar for the integrated one?

It seems like https://gfx.io/ might give you some control over this.

There is probably something that can be done in the code, but since I don't have a system like this, it will be difficult for me to make any changes for it with confidence!

**Comment by pmizio** [comment]
So, I done some googling related to force discrete GPU for specific app and I believe there is no such switch for integrated/discrete gpu.
In preferences of app there is no such option like for eGPU.

Last thing https://gfx.io/ can switch GPU for entire os, it create workaround - switch to discrete GPU launch wezterm, then switch back to auto choosing GPU.

So, I think the best option will be fix that in code somehow but, I understand you don't have hardware to test this.
But if you want to blindly prepare some "fix" I can test that for you.

**Comment by pmizio** [comment]
Ok, so I done some deeper research and I found [this article](https://zacwe.st/2012/06/23/preventing-rdio-from-using-discrete-graphics/). wezterm declate `NSSupportsAutomaticGraphicsSwitching` in `Info.plist` of app it mean mac run it on integrated gpu and when app request discrete gpu it will switch to it.
So, I run command `defaults delete /Applications/WezTerm.app/Contents/Info.plist NSSupportsAutomaticGraphicsSwitching` to delete this key from file and from this time wezterm always use discrete gpu.

I don't know you want to always force discrete gpu, but if yes you can remove https://github.com/wez/wezterm/blob/f58f47522d1e8bb581f6bae214ae28540c403c58/assets/macos/WezTerm.app/Contents/Info.plist#L33 this key.

I hope some of my research help you to resolve this problem!

**Comment by wez** [comment]
From what I can tell, there are widespread reports of OS level stuttering when using the integrated GPU:
* https://developer.apple.com/forums/thread/666661
* https://piunikaweb.com/2020/12/04/macos-big-sur-update-choppy-animations-and-system-lag/

I'm open to the idea of removing `NSSupportsAutomaticGraphicsSwitching` from the `Info.plist`, but I don't want to bump the power utilization for folks that aren't having issues.  But if that applies to everyone, then I'm not sure that we have a choice.

I couldn't find a way in code for an OpenGL app to specify that it wants the discrete GPU, only this note about the Info.plist:
https://developer.apple.com/library/archive/qa/qa1734/_index.html

re: 'EGL init failed' debug message: that's actually fine. Using CGL *should* run just fine on an Intel mac and runs very well on an M1 mac.  If you want to experiment with running EGL to see if it is better on your system, you can download the MetalANGLE EGL libraries from here:

https://github.com/wez/wezterm/tree/main/assets/macos/WezTerm.app

and put them in the `WezTerm.app` directory on your system, then start wezterm.

That EGL implementation uses Metal rather than CGL.  You might find that it performs better on your Intel mac.

One possible outcome from this, if you find that it resolves these issues, is that we break up the universal binary into one for Intel and one for M1 and package things up slightly differently.

**Comment by toddradin** [comment]
I ran into this issue today on my MacBook Pro (2019, Intel) with "Automatic Graphics Switching" enabled. It's somewhat strange in that if I launch `wezterm` from the dock or spotlight, it uses the integrated graphics:
```
Debug Overlay
wezterm version: 20220905-102802-7d4b8249
OpenGL version: Intel(R) UHD Graphics 630 4.1 INTEL-18.8.5
```
Whereas if I launch `wezterm` from another terminal, it uses the dedicated GPU:
```
Debug Overlay
wezterm version: 20220905-102802-7d4b8249
OpenGL version: AMD Radeon Pro 5300M OpenGL Engine 4.1 ATI-4.8.101
```
This occurs regardless of whether the laptop is plugged in or not.

If I disable "Automatic Graphics Switching", `wezterm` will use the dedicated GPU for both cases.
