### ISSUE TITLE
enable_csi_u_key_encoding doesn't work as expected

### ISSUE THREAD

**Issue by abdalrahman-ali** [wez/wezterm#2152]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220619-214005-be8a6e18

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using the setting:   `enable_csi_u_key_encoding = true`, I expected keys to send the corresponding csi u code automatically.

This is not the case, I have to explicitly bind the keys to send the code with something like this:
`{key = "phys:i", mods = "CTRL", action = wezterm.action({ SendString = "\u{1b}[105;5u" }) }`

I am not sure, Is this the intended behavior and I indeed need to bind the keys to send csi u codes manually or am I missing something?

### To Reproduce

with a config file that has `enable_csi_u_key_encoding = true` open the terminal, press ctrl-v then press ctrl-i:
expected output:  ^[[105;5u
actual output: empty string as we pressed the tab key

### Configuration

`enable_csi_u_key_encoding = true`

### Logs

```
17:43:41.391  INFO   wezterm_gui::termwindow > OpenGL initialized! Intel(R) UHD Graphics 620 4.5.0 - Build 30.0.101.1338 is_context_loss_possible=true wezterm
 version: 20220619-214005-be8a6e18
```

**Comment by wez** [comment]
On Windows, the nightly build defaults `allow_win32_input_mode=true` which takes precedence.
I would suggest setting `allow_win32_input_mode=false` if you also want CSI-u encoding.

Also: the nightly build now also has support for the kitty keyboard protocol, which addresses some deficiencies in the original CSI-u encoding: you may want to consider trying that out: `enable_kitty_keyboard=true` enables that.
https://sw.kovidgoyal.net/kitty/keyboard-protocol/ has more details on the protocol.
Note that because the protocol is enabled via an escape sequence, you don't need to disable win32 input mode for it to work.

This stuff needs some updates to the docs to help make this clearer!

**Comment by wez** [comment]
See https://wezfurlong.org/wezterm/config/key-encoding.html for an explanation of this area.
