### ISSUE TITLE
Random/garbage characters are rendered when using tmux splitting

### ISSUE THREAD

**Issue by krishnakumarg1984** [wez/wezterm#218]
## Bug description

Sometimes when using `tmux` and working with splits, random garbage characters are rendered near the line splitting the window. See screenshot
<img width="1416" alt="Screenshot 2020-06-12 at 16 10 18" src="https://user-images.githubusercontent.com/15239509/84517762-a1213980-acc7-11ea-992e-04e2f5a33f92.png">

## Environment
 - OS: macOS
 - Version: wezterm 20200608-110940-3fb3a61
 - tmux: v3.1b

## To Reproduce

While inside tmux, open up two splits (eg. vertical) and have a large amount of independent text in both.   For example a text-heavy prose file in `vim` on the left pane, and a lengthy `man` page on the right pane. After some scrolling, editing etc. of both panes, close these applications. In the end, we are left with garbage text near the vertical split line, which persists for a fairly long time, and even persists well into other terminal session (eg. opening another `man` page), and after some scrolling these garbled characters start changing positions, and it takes some time and effort to fully get rid of them.

This is a pretty big distraction when editing research papers in LaTeX etc.

**Comment by wez** [comment]
Please capture this in a session recording:

https://github.com/wez/wezterm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#session-recording

**Comment by krishnakumarg1984** [comment]
@wez See the session recording [here](https://asciinema.org/a/4zlncQNl3dFJrLyZIyAdiKSXl)

**Comment by krishnakumarg1984** [comment]
@wez Whew! Took me a while to get there, but here is the recording which shows the issue.

![wezterm_garbage](https://user-images.githubusercontent.com/15239509/84527622-227fc880-acd6-11ea-9ee4-a09ebda3ad2e.gif)

**Comment by wez** [comment]
Thanks, but I was looking for a `script` session recording so that I could replay the same sequence of characters locally to reproduce and debug the issue.

Using the `wt-record` script as mentioned in the session recording section of https://github.com/wez/wezterm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#session-recording will capture that!

Could you also share the output from `tmux info`?

**Comment by krishnakumarg1984** [comment]
@wez it's really easy to reproduce

1. run `man ls` in the terminal. Scroll the manpage a bit
2. Open a vertical tmux script. You should already see spurious single characters at the right-side of the original split
3. Run `man ls` in the newly opened tmux split. Scroll forward just a bit 
4. Close the man page in the new split
5. Move to the original split and close the man page
6. Garbage characters persist near the split

**Comment by wez** [comment]
The purpose of the screen recording is to capture exactly what is happening for you so that I don't have to try to recreate your environment; I cannot scale myself to support a free time project if I have to install software that I don't use and match its configuration and workflow to that of everyone that might use this project.

I do trust and believe that this is happening for you, but I need your help to run down an issue that is so far as I'm aware only affecting you!

**Comment by krishnakumarg1984** [comment]
@wez Yes. Apologies for the delay in replying. I truly appreciate your efforts in developing this awesome terminal emulator and acknowledge the time pressures of a free time project. The recording aspect was just new to me, and it took a bit of time to figure it out.

Here are the outputs produced by the recording script: [typescript file][https://www.dropbox.com/s/xhu4ff6lg5ihm4n/20200612204904.typescript?dl=0] and [tar.gz file](https://www.dropbox.com/s/7ig5rve4tidr5xz/20200612204904.tgz?dl=0).

**Comment by wez** [comment]
This is resolved in the nightly builds

**Comment by krishnakumarg1984** [comment]
Yes. This now works fine.
