### ISSUE TITLE
Add option for not render ligatures under cursor

### ISSUE THREAD

**Issue by huibosa** [wez/wezterm#2181]
I've thought It would be nice to add two options:

* Not render ligatures under cursor
* Not render ligatures under cursor line

## Not render ligatures under cursor

![image](https://user-images.githubusercontent.com/78707242/175793851-3412bf12-bf2c-4278-848e-96540882963f.png)

## Not render ligatures under cursor line

![image](https://user-images.githubusercontent.com/78707242/175793961-1f8d7085-4899-4771-b53d-b7c052bb9f68.png)

**Comment by wez** [comment]
I'm hesitant to add this because:

* [BIDI](https://github.com/wez/wezterm/issues/784):
  * requires that an entire "paragraph" be considered together when it comes to shaping
  * Forcing ligatures off at the cursor position introduces an artificial break for shaping purposes
  * The break could result in incorrect BIDI and incorrect shaping especially for arabic text
  * A secondary consequence is that mapping post-BIDI text for selection purposes (while not currently implemented) would also be broken
* Ignoring BIDI:
  * Shaping is one of the most expensive things we do when it comes to computing display presentation
  * Changing shaping properties based on the cursor position requires recomputing the shaping info for both the prior and the new cursor position on each cursor movement, resulting in a performance penalty
  * Performance of cursor movement, especially in nvim, is a frequently reported issue against wezterm

Implementing options for this sort of thing increases the complexity of the code and support burden and I'm not convinced that it is worth the effort; in my opinion, I think people either like ligatures and leave them on, or don't like them and turn them off. Aside from perhaps a few cases where you might need to learn the ligatures in a new font, I don't think there are many situations where you need to quickly switch between both.

https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html has an example that shows how to make a key assignment that toggles ligatures for the window that I think is a reasonable option for those that do need to do that.
