### ISSUE TITLE
Global variable for missing glyphs (counter/flag) and/or notification debouncing

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#2188]
**Is your feature request related to a problem? Please describe.**

I like notifications about missing glyphs. But, a few weeks ago, I `cat`'d some file[1] and WezTerm spuriously sent a lot of notification about missing glyphs, almost filling about 3/4th of my screen.

[1] I don't remember what it contained.

**Describe the solution you'd like**

1. After a notification about missing glyphs is sent, wait for X seconds before sending anothing one.

2. It would also be nice if there was a global variable containing the count of missing glyphs, or if it's too much, then a boolean flag. This would enable the user, for example, to set an icon in the WezTerm status bar if there is any missing glyph, or even create a custom notifier.
    - There should be a function to reset this variable. This should also be done after each notification.

**Describe alternatives you've considered**

Disable missing glyph notification. If possible, I would rather not do that though.

**Additional context**

NIL.

**Comment by wez** [comment]
49e3fd4c9e668e77adacec819aa96eec3e24cc51 limits the notifications to once per hour.
I don't think we need more complexity around this than being able to turn the notifications off (for which there is already an option) and having a reasonable, occasional notice about what is happening.
The purpose of the notification is to explain why a fallback glyph is being used to new/unfamiliar users, which is why these notifications are shown by default.  But I agree that it is not necessary to keep spamming the user about them all the time.

**Comment by MuhammedZakir** [comment]
Sounds reasonable. You're right, a counter is too much.

Does the 1-hour-debouncing reset when config is reloaded?

**Comment by wez** [comment]
It does now! :)
