### ISSUE TITLE
"Copy as HTML" and/or "Copy with ANSI"?

### ISSUE THREAD

**Issue by jaysonlarose** [wez/wezterm#2223]
Hello!

I just learned about this terminal emulator, and it seems pretty cool so far!

One feature I've gotten rather fond of in Gnome-Terminal is the "Copy as HTML" feature. When you use it, it copies the currently selected text to the clipboard, but also:

- HTML-encodes the selected text
- wraps it in `<pre></pre>` tags
- adds in `<font color="#xxxxxx"></font>` tags for foreground colors
- adds in `<span style="background-color:#xxxxxx></span>` tags for background colors
- adds in '<strike></strike>`, `<u style="text-decoration-style:single></u>`, `<u style="text-decoration-style:double></u>`, `<b></b>`, `<blink></blink>`, and `<i></i>` tags to represent strikethrough, single underline, double underline, bold, blinking, and italic text, respectively.

I love this feature for creating accurate-looking copy/pastable documentation. I was wondering if you would entertain the idea of adding such a feature?

(kitty implemented this feature by using ANSI escape sequences. I'm not picky. If there's any way of programatically getting the currently selected text with its formatting, I'm happy!)

**Comment by wez** [comment]
I just pushed a couple of commits that allow you to do something like this:

```lua
local wezterm = require 'wezterm'

return {
  keys = {
    {key="E", mods="CTRL", action=wezterm.action_callback(function(window, pane)
      local ansi = window:get_selection_escapes_for_pane(pane);
      window:copy_to_clipboard(ansi)
    end)}
  }
}
```

In that example, pressing `CTRL-SHIFT-E` will copy the selected region to the clipboard with embedded escape sequences to reproduce the original styling.

I'm open to also adding HTML for this, but there isn't any existing infrastructure in the wezterm repo to produce that form of output, so it wasn't as quick to hook up as the escape sequence form.  What I think I'd prefer to see for that is actually to expose the underlying `Line`, `Cell` and `CellAttributes` types to lua so that you can precisely control how to generate HTML or any other form of output.

Those commits are currently building out and should be available in the nightly downloads within about an hour from now.
Please try it out and let me know what you think!

**Comment by wez** [comment]
Docs at:
* https://wezfurlong.org/wezterm/config/lua/window/get_selection_escapes_for_pane.html
* https://wezfurlong.org/wezterm/config/lua/window/copy_to_clipboard.html

**Comment by jaysonlarose** [comment]
Oh my gosh. I'm honestly super excited about this!  I've been using Wezterm for the past few days, and it's been ticking just about every box on my list of requirements in a terminal emulator.
