### ISSUE TITLE
Allow setting the "browser" (on-click handler) by implicit hyperlink type

### ISSUE THREAD

**Issue by sanga** [wez/wezterm#223]
Allow executing an external program, configurable by implicit hyperlink type, instead of the default browser.

As that is possibly not very clear, to use the example from the docs (see: https://wezfurlong.org/wezterm/hyperlinks.html#implicit-hyperlinks):

Rather than opening Firefox or Chrome when clicking `T123`, instead spawn another wezterm and execute a cli command e.g. `wezterm -- jira view T123`.

**Comment by wez** [comment]
What I have in mind here isn't exactly what you describe, but I think it will help you achieve your goal.

Building on top of the plumbing in https://github.com/wez/wezterm/issues/225 it should be possible to define a lua callback that we call instead of the default "open a URL" action.

In that lua function you will have access to the clicked URL and can decide what to do with it.
Adding a lua function that performs the default URL opening action will also help handle the default case, so you'd end up with something that probably looked like this:

```lua
wezterm.register_callback("open-url", function(url)
  if url:contains("jira") then
      local task = extract_task_from_url(url);
      wezterm.perform_action(wezterm.action{SpawnCommandInNewWindow={
         args={"jira", "view", task}
      }}})
  else
      wezterm.open_url(url)
  end
end)
```

**Comment by sanga** [comment]
This sounds fine to me. Thanks!

**Comment by wez** [comment]
Current master should allow for something like this:

```lua
wezterm.on("open-uri", function(window, pane, uri)
  -- The assumption is that `extract_task_from_uri` will return
  -- a task id string for URLs that match your criteria, or `nil` otherwise
  local jira_task = extract_task_from_uri(uri);
  if jira_task then
    window.perform_action(wezterm.action{SpawnCommandInNewWindow={
         args={"jira", "view", jira_task}
      }});
    -- prevent the default action from opening in a browser
    return false
  else
    -- log but allow the uri to be opened in the browser
    wezterm.log_error("clicken " .. uri)
  end
end)
```
