### ISSUE TITLE
Switching workspace using `mux.set_active_workspace` or via `wezterm cli spawn --workspace <name>` is buggy

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#2248]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

~20220709-231243-60728793~
20220711-212031-98fb67c0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

~No, I'll explain why below.~

Edit: Also tried with latest nightly (`20220711-212031-98fb67c0`).

### Describe the bug

Executing `set_active_workspace` function changes the value returned by `get_active_workspace`, however, the workspace currently shown doesn't change. I also expect the workspace to change when using spawning a pane/tab/window via cli into a different workspace than the current one.

Edit: After using `set_active_workflow`, if I spawn a new window (e.g. `wezterm cli spawn --new-window`), then the workspace is switched.

### To Reproduce

1. Start WezTerm.
    - workspaces: `default`.
2. `wezterm cli spawn --new-window --workspace test`
    - workspaces: `default`, `test`
3. Try switching workspace using `set_active_workspace` using the debug overlay, and/or using a key assignment bound to
```lua
wezterm.action_callback(function()
   wezterm.mux.set_active_workspace("test")
end
```

### Configuration

no config

### Expected Behavior

Workspace should switch when using `mux.set_active_workspace` function, or when spawning into a specific workspace via the cli.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by MuhammedZakir** [comment]
Switching using `set_active_workspace` works correctly. Thanks! :-)

---

When spawning a window to an inactive workspace via `spawn` cli command, WezTerm hides that window. However, it spawns the tabs and panes to the current workspace. Panes are okay, but I think tabs should be opened in the given workspace. I also think workspace should be switched when `--workspace` option is used; it maybe just me who thinks like that though.

**Comment by wez** [comment]
> it spawns the tabs and panes to the current workspace. Panes are okay, but I think tabs should be opened in the given workspace

New tabs are spawned into the pre-existing window associated with the current pane; that window already belongs to its own existing workspace, so there isn't really space for specifying a different workspace.

If you were to specify a workspace it raises a number of questions that don't have clear answers: if the workspace for the window that ultimately contains the current pane is different than the name you specified, where would the new tab go? Would it imply `--new-window`?  But what if there is already a window in that workspace and you'd want it to go there? Perhaps it should somehow find that existing window in the requested workspace? If so, what should it do if there is more than one of those?   What if you don't want it to do that? I don't think there is a definitive answer to this line of questioning, and the behavior is clearly described in the docs and help output:

```
       --workspace <WORKSPACE>        When creating a new window, override the default workspace
                                      name with the provided name.  The default name is "default"
```

If you want it to go in a new window then that's what `--new-window` is for. If you want it to go into a specific window then that is what `--window-id` (likely in conjunction with `wezterm cli list`) is for. 

> I also think workspace should be switched when `--workspace` option is used;

The active workspace is an attribute of the client (as you can see in `wezterm cli list-clients`); the CLI is a separate client session from the GUI and doesn't currently have a way to change the workspace associated with another client.

If/when it does grow that ability: I think having a separate flag named something like `--switch-to-workspace` for the spawn commands would be the most flexible and clear way to deal with this, rather than implicitly doing something that someone may not want, especially because the current behavior is not switching.  When that capability is added, in order to preserve compatibility with scripts/automation that users have created, we can't make it suddenly start switching.

**Comment by MuhammedZakir** [comment]
Makes sense!

> If you want it to go in a new window then that's what `--new-window` is for. If you want it to go into a specific window then that is what `--window-id` (likely in conjunction with `wezterm cli list`) is for.

Then I think a warning/error should be reported when using `--workspace` with `spawn` without `--new-window` or `--window-id`. Current one is *slightly* confusing. A note about this in the help msg would also be enough.

**Comment by wez** [comment]
I made the arg parser error out if --workspace is used without --new-window

**Comment by MuhammedZakir** [comment]
> I made the arg parser error out if --workspace is used without --new-window

What about `--window-id`?

**Comment by wez** [comment]
It's already set to conflict with `--new-window`:

```
; wezterm cli spawn --window-id 1 --new-window
error: The argument '--window-id <WINDOW_ID>' cannot be used with '--new-window'
```

**Comment by MuhammedZakir** [comment]
I thought this wouldn't work as `--new-window` is "required":
```
wezterm cli spawn --workspace test --window-id 1
```

I just tested using latest nightly and it works. However, the error msg [1] is confusing as it implies `--window-id` with `--workspace` won't work.

[1] `$ wezterm cli spawn --workspace test`:
```
error: The following required arguments were not provided:
    --new-window

USAGE:
    wezterm cli spawn --new-window --workspace <WORKSPACE>

For more information try --help
```

**Comment by wez** [comment]
There's only so much that can be done with the clap arg validation; higher quality error messages require removing the validation from the arg parser and coding it by hand, and I don't think it is worth the time investment. I've spent way more time on this than I think is needed as the information is present in the --help output.

**Comment by MuhammedZakir** [comment]
Can we only pass a single flag as required?

Regardless, this issue is fixed. Feel free to close this.

**Comment by wez** [comment]
ok, I made one more pass over this, and I'm now calling it done. Thanks!
