### ISSUE TITLE
QuickSelect actions select first matching element (not selected element)

### ISSUE THREAD

**Issue by aca** [wez/wezterm#2250]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220711-174636-c8ca2054

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

<img width="526" alt="image" src="https://user-images.githubusercontent.com/50316549/178479996-afd98dbd-3584-4434-9e24-fb8cdf0e50c1.png">

It's quite easy to reproduce the bug. When I start quickselect and choose the last "asdasdasdasd", it selects first matching "asdasdasdasd" not the one I selected.
It might not matter as the result is same when copying, but it's quite wierd.

### Configuration

```
    quick_select_patterns = {
        "[A-Za-z0-9-_.]{6,100}",
    },
```

### Expected Behavior

Select what I choosed.

### Anything else?

Thank you!

**Comment by wez** [comment]
quick select selects by content rather than position: each item with the same content has the same label. So when you select a label there isn't a way to know which one you picked because there isn't eg: eye tracking to know which one you were looking at.

I've pushed a commit that changes from using the top-most match to the bottom-most match, as I think it is more likely that you are looking nearer the bottom than the top and there isn't another way to resolve the ambiguity for obvious pathological cases like when you have multiple matches present in the current viewport.

**Comment by wez** [comment]
I'll accept a PR for that, but I'm not going to hack on it myself
