### ISSUE TITLE
Last tab index

### ISSUE THREAD

**Issue by luben** [wez/wezterm#228]
**Is your feature request related to a problem? Please describe.**

I would like to be able to configure shortcut to jump to the rightmost tab. Either this functionality is missing or not documented.

**Describe the solution you'd like**
May be have `ActivateLastTab` action.

**Comment by wez** [comment]
Ah, I thought we had something for this already, but it's clear that we don't.
What do you think about having negative numbers wrap around backwards?

eg: `wezterm.action{ActivateTab=-1}` would reference the rightmost tab, with `-2` the tab preceding that and so on?

**Comment by luben** [comment]
Yes, negative numbers would be perfect.

**Comment by luben** [comment]
Building it now, may be the default for the last tab is better to be `CTRL+SHIFT+0` as it is unused currently

**Comment by luben** [comment]
Works as expected. Thanks

**Comment by wez** [comment]
re: `0` for last tab, I didn't make `CTRL+SHIFT+0` do that because we use `CMD` and `CTRL+SHIFT` as equivalent modifiers (basically CMD is the "ideal" on macOS, with `CTRL+SHIFT` being "what we have to use" on other systems).

`CMD-0` is assigned to reset font size, so the logical assumption is that `CTRL+SHIFT+0` should behave the same way... but in a case of unexpected asymmetry, I made `CTRL-0` the equivalent function.  So that's a bit messy and I should give that some thought.

Meanwhile, `9` was assigned to the last reachable tab from the left and re-purposing that to be the literal last tab seems OK for the moment.

**Comment by luben** [comment]
Aaa, I see. It's easy to change though. Thanks
