### ISSUE TITLE
Incorrect screen wrapping/reflow upon resizing terminal window

### ISSUE THREAD

**Issue by krishnakumarg1984** [wez/wezterm#234]
## Description

Upon resizing the terminal window, the screen does not dynamically reflow.

## Environment

 - OS: macOs
 - Version: wezterm 20200620-160318-e00b076c

## To Reproduce

1. Start `wezterm` with default configuration using `wezterm -n` and with the default window-size (unmaximised)
2. Execute a command that presents some long running text on screen eg. `man ls`
3. Now maximise the terminal window.  Desired behaviour is that the man page should reflow such that the text shall now wrap suitably to occupy the additional screen width now available.
4. Notice that the manual page remains wrapped as per original (i.e. narrow columns) and does not reflow to take advantage of the increased real estate. 

## Configuration

Is not relevant as we use `wezterm` with default config skipping `wezterm -n`.

## Expected behavior
The screen reflows suitably. 

## Screenshots

With wezterm (after maximisation):
<img width="1440" alt="incorrect_screen_wrap" src="https://user-images.githubusercontent.com/15239509/85345521-96964980-b4ea-11ea-9623-6383c40a1104.png">

With iterm, the dynamic screen reflowing works fine to take advantage of all the available real estate.

**Comment by wez** [comment]
FWIW, `iTerm` doesn't have the resize behavior that you describe for me, and I don't think I've ever seen a system where that is true; `man` spawns `groff` which captures the probed terminal size at startup, formatting the text to that width, and the result is piped to less, which faithfully uses that size even if the terminal is resized, because it doesn't know how to "upscale" the plain text to re-wrap it.

If you start with a wider display and resize downwards then less will reflow the long lines.  Perhaps that is what you saw in iTerm?

If you run `less` directly on a wide file (rather than piped input), then it will resize/reflow in both iTerm and wezterm, but again the behavior will only be to reflow lines that are physically wider than the display.  It won't auto-reflow the input text because it doesn't know how to do that.

**Comment by krishnakumarg1984** [comment]
Hmm. Ah, indeed you are right? There was some subtle difference between iterm and wezterm that I noticed in my operational workflow that stood out at the time. Just something seemed off. My mind interpreted it as a "reflow" issue since I noticed this upon some sort of resize operation, and I quickly created this now.

Now, after reading your explanation, I tend to agree that you are right. Still something seems ever-so slightly different in the windowing/text-flowing/reading behaviour that I cannot quite put a finger to.  Maybe feel free to close this for now?
