### ISSUE TITLE
Whenever I'm fullscreen and reload the configuration, it goes out of fullscreen

### ISSUE THREAD

**Issue by luisiacc** [wez/wezterm#2395]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220810-061048-13064541

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I use fullscreen mode all the time, and every time I save the configuration file and it reloads the file it goes out of the fullscreen mode into the state it has when it's not fullscreen, like a maximized one, where the title bar of the program is shown.

### To Reproduce

It happens all the time.

### Configuration

This is my wezterm directory.

[wezterm.zip](https://github.com/wez/wezterm/files/9328529/wezterm.zip)

### Expected Behavior

I'd expect the fullscreen mode to be maintained.

**Comment by wez** [comment]
Try removing `cfg.dir = 144.0` from your config. You shouldn't need to specify dpi on windows and I think that might cause excess resizing while trying to reconcile the actual dpi

**Comment by luisiacc** [comment]
Just did, but it's the same behaviour.

**Comment by wez** [comment]
Likely fixed by https://github.com/wez/wezterm/commit/69ae847273aa2b0a64bdb07cf19d3f6fbaaa6b71

This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
