### ISSUE TITLE
Key repeat gets stuck after pressing two keys in fast succession

### ISSUE THREAD

**Issue by chmanie** [wez/wezterm#2452]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Sway

### WezTerm version

20220823-103207-53bc8711

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The key repeat is stuck when pressing two keys in quick succession resulting in the second key printing only one character instead of continuously printing.

### To Reproduce

Go into a terminal. Press the key `A` on your keyboard and hold it. Release it and quickly press the letter `B` on the keyboard and hold it. `b` is only printed once, even though it should be continuously be printed.

### Configuration

no config

### Expected Behavior

Every key that is pressed and held should be repeated, even when keys are typed in quick succession.

### Logs

There seem to be no logs created from this action

**Comment by lexi-nadia** [comment]
I'm seeing this too, FWIW.

**Comment by unrelentingtech** [comment]
Can reproduce, though cannot imagine what you were doing to discover that during normal usage :)

I think this might be happening because the press of the second key comes before the release of the first one:

```
[2471895.630] wl_keyboard@14.key(18833, 7498288, 48, 1)
[2471902.686] wl_keyboard@14.key(18834, 7498296, 30, 0)
```

Looking at GTK (gedit), any new key press (without releasing the previously held key at all) does interrupt the key repeat :heavy_check_mark:
