### ISSUE TITLE
On X11, please set the EWMH property _NET_WM_WINDOW_TYPE

### ISSUE THREAD

**Issue by MHellmund** [wez/wezterm#2458]
**Is your feature request related to a problem? Please describe.**
I am using the i3 window manager, together with a small utility to list and jump to all windows.
The utility ignores wezterm. It ignores all windows  where the window type is not set.

**Describe the solution you'd like**
wezterm running under X11 should set _NET_WM_WINDOW_TYPE=normal,
see https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html

Many thanks for your  great software!

**Comment by wez** [comment]
I'm not opposed to adding it, but I don't see it set in eg: xterm. Does that utility also ignore xterm?

From the docs:

> _NET_WM_WINDOW_TYPE_NORMAL indicates that this is a normal, top-level window. Windows with neither _NET_WM_WINDOW_TYPE nor WM_TRANSIENT_FOR set MUST be taken as this type.

That last sentence suggests that the utility is in error for not assuming that the type is normal; I think it's more scalable to fix that issue in the utility, rather than asking every other app to workaround that issue.

**Comment by MHellmund** [comment]
Hmm, `xterm` has the same problem on my desktop and your reading of the docs seems right. 
So I just opened https://github.com/regolith-linux/ilia/issues/43

BTW, I looked for  apps w/o type hint on my laptop and found only  good old xterm, xclock, xeyes.... So I  guess that at least every Qt- or GTK-app sets the type, perhaps by default. (I have a small self-written Python-Qt5 app and it has the type=normal hint  and I don't set it explicitly in my code.)
