### ISSUE TITLE
support alternative styling/config based on TTY flags (e.g. disable-input-echo => red background)

### ISSUE THREAD

**Issue by jokeyrhyme** [wez/wezterm#2460]
**Is your feature request related to a problem? Please describe.**
- When a terminal application prompts me to input a password or other secret, it's not always clear (in-advance) whether my keystrokes will be visible or not

**Describe the solution you'd like**
- I was wondering about making it so that my terminal window changes colour or something whenever the input will not be echoed
- I noticed that the default Terminal application on macOS displays a padlock symbol in the cursor for this purpose, but I think any sort of visual indication would be helpful
- Looking around, it looks like one standard-ish way of performing password inputs is to change a TTY flag: https://github.com/finfet/passterm/blob/main/src/lib.rs#L164-L182
    - so one general solution could be to detect when TTY flags change (if possible) and provide a Lua event: https://wezfurlong.org/wezterm/config/lua/wezterm/on.html
    - or if this is considered really bad for performance, a non-programmable solution could be to have a section in the config that is applied based on TTY flags

**Describe alternatives you've considered**
- could be solved by typing a few random keys in first to see if they are visible, then deleting them and typing my real secret
- could be solved by modifying the terminal apps that I use so that they clearly indicate when input-echo is disabled

**Additional context**
- From Matrix: 
    > I think for this to work, it would be constrained to locally spawned processes, and wouldn't work for eg: ssh or mux sessions. There's also the question of what should be displayed when local echo is disabled
    - does "mux sessions" here mean e.g. `screen`/`tmux` or the multiplexing features built-in to wezterm?

**Comment by wez** [comment]
> From Matrix:
> > I think for this to work, it would be constrained to locally spawned processes, and wouldn't work for eg: ssh or mux sessions. There's also the question of what should be displayed when local echo is disabled
> 
> * does "mux sessions" here mean e.g. `screen`/`tmux` or the multiplexing features built-in to wezterm?

It may be surprising to learn that the terminal emulator doesn't normally care about local echo: that is something that is handled by the kernel at the PTY layer (the kernel is responsible for local echo) and it isn't explicitly part of the interface with the terminal emulator side of the PTY.

The suggestion to look at local echo settings is only possible on POSIX systems where we have a handle to a PTY that is directly connected to the client application and can read its termios to get at the local echo setting.

That means that this feature won't work on Windows systems (there is no way to read those sort of flags from the terminal emulator side of the pty), and won't work for SSH sessions (the PTY where local echo is manipulated is on the remote host and the SSH protocol doesn't have a termios equivalent).

Applications like tmux add another layer of PTY, so while wezterm could read the termios of the tmux client application, that would not be the PTY of the application which is manipulating local echo: only tmux can see that.

wezterm's own mux protocol, like ssh, has no termios concept because that isn't really part of the terminal emulator interface of a PTY.

So! There are a bunch of caveats around this!

**Comment by jokeyrhyme** [comment]
> So! There are a bunch of caveats around this!

Wow, indeed!

I've asked some macOS friends to check, and I think the little lock symbol only appears in Terminal.app, and potentially with all the same limits that you've laid out (not in `tmux`, not in SSH)

This might be one of those feature requests that started of sounding simple but ended up being extremely tricky :)

**Comment by wez** [comment]
This is implemented now in `main`.

The cursor will change to a lock if we think that we're in a password input scenario.
In addition, this information is exposed via a new metadata method so that you can use it from lua; this example changes the color scheme based on the state:

```lua
local wezterm = require 'wezterm'

wezterm.on('update-status', function(window, pane)
  local meta = pane:get_metadata() or {}
  local overrides = window:get_config_overrides() or {}
  if meta.password_input then
    overrides.color_scheme = "Red Alert"
  else
    overrides.color_scheme = nil
  end
  window:set_config_overrides(overrides)
end)

return {}
```

You can verify this by using this one-liner to prompt for a line of input with local echo disabled:

```bash
bash -c "read -s -p woot: pw"
```

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by jokeyrhyme** [comment]
Wow, this is delightful :)

I built from source and it does indeed work exactly the way you say it does <3

**Comment by jokeyrhyme** [comment]
Using the ["update-status"](https://wezfurlong.org/wezterm/config/lua/window-events/update-status.html) event that is triggered every ["status-update-interval"](https://wezfurlong.org/wezterm/config/lua/config/status_update_interval.html) does result in a little latency here, but for me this is a sensible trade-off (resource-usage versus latency)
