### ISSUE TITLE
tab title is not used (e.g. when set by oh-my-zsh)

### ISSUE THREAD

**Issue by jankatins** [wez/wezterm#247]
## Describe the bug

In wezterm, the window title is displayed both as a window title and as the tab title. The tab title seems to be ignored.

background: oh-my-zsh brings with it an auto title which will display (in iterm2 and on my linux gnome console) `<user>@<host> <directory>` as the window title and the last 15 chars of the path as a tab title (https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/termsupport.zsh#L19-L23 for how this is set and what values are set https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/termsupport.zsh#L44-L55). 

This brings with it that when I have multiple tabs open, only the start of the title is displayed, making the tab title more or less useless as `<user>@<host>` is always the same and the interesting thing is at the end but the end is not displayed due to size.

## Environment (please complete the following information):

 - OS: macOS
 - Version: `wezterm 20200718-095447-d2315640`

## To Reproduce

Use zsh and run the following commands (same as would be run by https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/termsupport.zsh):

```zsh
DISABLE_AUTO_TITLE="true" # just in case you have oh-my-zsh and the autotitle on
print -Pn "\e]2;window_title\a" # set window name
print -Pn "\e]1;tab_title\a" # set tab name
```
-> only the window title is displayed. In iterm2 it displays them separately as tab and window titles

## Expected behavior

If a tab title is set, the tab uses that as a title in the tab

## Screenshots

Iterm2:
![image](https://user-images.githubusercontent.com/890156/89082304-dc69eb80-d38d-11ea-9f49-1ce2087a5dd6.png)

Wezterm:
![image](https://user-images.githubusercontent.com/890156/89082496-77fb5c00-d38e-11ea-9035-9266e4878815.png)

**Comment by wez** [comment]
This is intentional behavior; the underlying terminal instance (that processes escape sequences) is unaware of other tabs and thus only supports setting its own "window" title.

With that in mind, I'm classifying this as a feature request.  I'll give this a bit of thought when I'm next in the right frame of mind, but what I'm leaning towards at the moment is treating the two sequences (tab and window) as the same thing.

**Comment by wez** [comment]
I've pushed a commit that treats those as the same thing.  I don't know if that will satisfy your needs, because whatever is set by the most recent `OSC 0`, `OSC 1`, `OSC 2` sequence will be treated as the title.

It wouldn't be the most difficult thing to add support for tracking Icon Name (which is really what that `OSC 1` is setting) separately, I'm just being lazy at the moment :-p

**Comment by jankatins** [comment]
I would prefer to show the tab title, because that has better information when informations gets shortend due to space limitations when too many tabs are open. I think I can adjust omzsh to do this for now but still it would be nice feature to have both.

**Comment by wez** [comment]
That makes sense; I've adjusted the code to prefer returning the icon title now.  Let me know how that works out for you!
