### ISSUE TITLE
side by side comparison with Windows Terminal shows text rendering differences

### ISSUE THREAD

**Issue by kunchenguid** [wez/wezterm#2477]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220807-113146-c2fee766

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using the exact same font family , font size, getting significantly different results between windows terminal vs wezterm. 
* both are using normal/regular font weight, but text looks thinner in wezterm
* both using default 100% line height but the same text ends up taking less vertical space in wezterm
* using same color scheme but color looks less saturated in wezterm
* horizontal spacing between characters is significantly larger in wezterm (i don't mind this too much)

Left: windows terminal
Right: wezterm

![image](https://user-images.githubusercontent.com/3233006/188261046-d00b1a71-861b-48ab-85bf-24d51332176c.png)

### Configuration

```lua
local wezterm = require 'wezterm'

return {
  font = wezterm.font 'DroidSansMono NF',
  font_size = 12.0,
  color_scheme = 'Rosé Pine Moon (base16)',
  window_decorations = "RESIZE",
  window_frame = {
    font_size = 12.0,
  },
  leader = { key = '`', mods = '' },
  keys = {
    {
      key = '`',
      mods = 'LEADER',
      action = wezterm.action.SendString '`'
    },
    {
      key = 'c',
      mods = 'LEADER',
      action = wezterm.action.SpawnTab 'CurrentPaneDomain'
    },
    {
      key = 'x',
      mods = 'LEADER',
      action = wezterm.action.CloseCurrentTab { confirm = true }
    },
    {
      key = '1',
      mods = 'LEADER',
      action = wezterm.action.ActivateTab(0)
    },
    {
      key = '2',
      mods = 'LEADER',
      action = wezterm.action.ActivateTab(1)
    },
    {
      key = '3',
      mods = 'LEADER',
      action = wezterm.action.ActivateTab(2)
    },
    {
      key = '4',
      mods = 'LEADER',
      action = wezterm.action.ActivateTab(3)
    },
    {
      key = '5',
      mods = 'LEADER',
      action = wezterm.action.ActivateTab(4)
    },
    {
      key = '6',
      mods = 'LEADER',
      action = wezterm.action.ActivateTab(5)
    },
  },
  default_prog = {
    'C:\\Windows\\System32\\wsl.exe',
    '-d',
    'Ubuntu-22.04',
    '--cd',
    '~'
  },
  launch_menu = {
    {
      label = 'Ubuntu',
      args = {
        'C:\\Windows\\System32\\wsl.exe',
        '-d',
        'Ubuntu-22.04'
      }
    },
    {
      label = 'Powershell',
      args = {
        'C:\\Program Files\\PowerShell\\7\\pwsh.exe'
      }
    }
  }
}
```

### Expected Behavior

text rendering looks closer to what windows terminal shows.

**Comment by wez** [comment]
> the latter looks a bit odd to me. something doesn't feel right)

Please be very specific: what looks odd? What specifically doesn't feel right?

This type of report, where there is a massive screen shot with the areas of comparison 100's of pixels apart and a comment about a feeling is not actionable.

Please focus in on the area(s) that you have questions about: please post small, focused screen shots that highlight the differences easily and in a small area.

**Comment by kunchenguid** [comment]
@wez thanks for looking. My bad for not pointing out the specific differences. Updated the description to include more details.

**Comment by wez** [comment]
This isn't a bug. wezterm uses freetype for rasterizing fonts on all platforms, whereas windows terminal uses a different font rasterizer, provided by the system. It is not a goal of wezterm to reproduce how other programs render their text or to use platform rasterizers.

wezterm gives you a number of options that control freetype so that you can dial in how text is rendered:

* https://wezfurlong.org/wezterm/config/lua/config/freetype_load_target.html
* https://wezfurlong.org/wezterm/config/lua/config/freetype_load_flags.html (you may wish to try `NO_HINTING`)
* and if you use subpixel modes, https://wezfurlong.org/wezterm/config/lua/config/freetype_interpreter_version.html and https://wezfurlong.org/wezterm/config/lua/config/freetype_render_target.html

Color saturation differences *may* be a graphics driver issue, and you may want to try adjusting https://wezfurlong.org/wezterm/config/lua/config/prefer_egl.html to see if it changes behavior.

Another option if you want to punch up the saturation is: https://wezfurlong.org/wezterm/config/lua/config/foreground_text_hsb.html

**Comment by kunchenguid** [comment]
Thanks a lot @wez. I tried a bunch of the ideas above. What made a significant difference for me was simply setting font weight to 'DemiBold'. This surprisingly also helped with color saturation as well. Now the looks match very closely to what I got used to from other terminals!
