### ISSUE TITLE
Allow `tab_max_width` to be disabled

### ISSUE THREAD

**Issue by heygarrett** [wez/wezterm#2535]
**Is your feature request related to a problem? Please describe.**
I need to set `tab_max_width` to an arbitrarily large number to effectively have no max width.

**Describe the solution you'd like**
Allow `tab_max_width` to be disabled by setting it to 0 or -1.

**Describe alternatives you've considered**
Currently I've set `tab_max_width` to 100.

**Comment by wez** [comment]
Thanks for the suggestion, but I don't plan to change this; since the max width is passed through to user's lua code in the event callbacks, there would be more complexity for more people to deal with the concept of either nullability or some sentinel value having different semantics, as well as the additional complexity in the code of wezterm itself.

In terms of configuration, whether you set `-1`, `0`, `100`, `100000` or some other number, you still need to have a line in your config.

I think it is simplest overall if you just stick a big number in there; I know it may not feel like the most elegant solution, but it is the most pragmatic.

**Comment by heygarrett** [comment]
That's understandable; thanks for the explanation. Should I close this issue, or should I leave it open to allow for the possibility of a more elegant solution in the future?

**Comment by wez** [comment]
I'll close it!
