### ISSUE TITLE
Ctrl+Shift+<Num> does not trigger action of ActivateTab=<Num>

### ISSUE THREAD

**Issue by madjxatw** [wez/wezterm#2623]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Ctrl+Shift+<Num> does not trigger action of `ActivateTab=<Num>`, though they are listed as [Default Key Assignment](https://wezfurlong.org/wezterm/config/default-keys.html). What actually happens is that `Ctrl+Shift+1` produces `!` in the terminal, `Ctrl+Shift+3` produces `#`, etc.
BTW, Super+Num does work after I remapped the mod key of i3 to some other. Not sure this is the issue of wezterm itself or something else in my system. 

### Configuration

```lua
local wz = require 'wezterm'

return {
  font = wz.font_with_fallback {
    { family = 'JetBrainsMono Nerd Font Mono', weight = 'Medium' },
    'Noto Color Emoji',
  },
  font_size = 10.0,
  color_scheme = 'nord',
}
```

**Comment by wez** [comment]
Try turning on key event debugging, pressing that key combination and sharing the logs:
https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html

**Comment by madjxatw** [comment]
> Try turning on key event debugging, pressing that key combination and sharing the logs: https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html

Sorry, the key event debug procedure seems not very clear. I've tried it before but not sure whether I did it correctly. Shall I press `Ctrl+Shift+L` to activate debug overlay first, and then press the key to be debugged + `Enter` to have the log printed to console?

**Comment by wez** [comment]
You can either:
* Add `debug_key_events=true` to your config file, press `CTRL-SHIFT-1`, then `CTRL-SHIFT-L` to open the overlay and copy and paste the logs
* Run `wezterm --config debug_key_events=true` from another terminal, press `CTRL-SHIFT-1` in the wezterm window, and copy and paste the logs that were output in the original window

**Comment by madjxatw** [comment]
```
❯ wezterm --config debug_key_events=true
11:08:17.849  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\r'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Return), modifiers: NONE, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
11:08:17.849  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Enter mods=NONE
11:08:20.572  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(RightShift), modifiers: SHIFT, phys_code: Some(RightShift), raw_code: 62, repeat_count: 1, key_is_down: true, handled: Handled(false) }
11:08:20.572  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Shift, modifiers: SHIFT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(RightShift), modifiers: SHIFT, phys_code: Some(RightShift), raw_code: 62, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
11:08:20.573  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Shift mods=SHIFT
11:08:20.586  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(RightControl), modifiers: SHIFT | CTRL, phys_code: Some(RightControl), raw_code: 105, repeat_count: 1, key_is_down: true, handled: Handled(false) }
11:08:20.586  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: SHIFT | CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(RightControl), modifiers: SHIFT | CTRL, phys_code: Some(RightControl), raw_code: 105, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
11:08:20.586  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Control mods=SHIFT | CTRL
11:08:20.651  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(K1), modifiers: SHIFT | CTRL, phys_code: Some(K1), raw_code: 10, repeat_count: 1, key_is_down: true, handled: Handled(false) }
11:08:20.651  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('!'), modifiers: SHIFT | CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(K1), modifiers: SHIFT | CTRL, phys_code: Some(K1), raw_code: 10, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
11:08:20.651  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char('!') mods=SHIFT | CTRL
11:08:20.651  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "!", Char('!') SHIFT | CTRL
11:08:20.772  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Shift, modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(RightShift), modifiers: CTRL, phys_code: Some(RightShift), raw_code: 62, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
11:08:20.772  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Shift mods=CTRL
11:08:20.787  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(RightControl), modifiers: NONE, phys_code: Some(RightControl), raw_code: 105, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
11:08:20.787  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Control mods=NONE
11:08:20.802  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('1'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(K1), modifiers: NONE, phys_code: Some(K1), raw_code: 10, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
11:08:20.802  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('1') mods=NONE
```

**Comment by madjxatw** [comment]
I tried wezterm on Windows and found these key bindings do not work either.

**Comment by wez** [comment]
I've fixed this in `main`, but want to note that:
* With the default [key_map_preference](https://wezfurlong.org/wezterm/config/lua/config/key_map_preference.html) = `"Mapped"`, shifted number keys generate punctuation characters instead of numbers
* wezterm will treat the US-keymap version of those shifted numbers as valid matches for these default key assignments
* If your keymap has different number -> punctuation mappings, then these key assignments won't behave
* You can either explicitly define your own mappings in that case, or consider switching `key_map_preference = "Physical"`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by madjxatw** [comment]
wez, thanks a lot for the quick fix and detailed instructions! I've tested the nightly build and confirmed that it works!
