### ISSUE TITLE
Weird behaviour on missing font

### ISSUE THREAD

**Issue by erf** [wez/wezterm#263]
## Describe the bug

I had configured `.wezterm.lua` to load the `Fira Code` font with: `font = wezterm.font("Fira Code")`

However i had uninstalled the font which caused some very weird visual bugs and long startup time.

## Environment (please complete the following information):

 - OS: macOS
 - Version: 20200909-002054-4c9af461

## To Reproduce

Open wezterm with the following configuration and with the font missing.

## Configuration

```
font = wezterm.font("Fira Code")
```

## Expected behavior

I would expect it to behave more gracefully and use the default font, with perhaps a message that the font is missing.

## Screenshots

<img width="1022" alt="Screenshot 2020-09-09 at 18 52 43" src="https://user-images.githubusercontent.com/1562523/92628796-a80f1680-f2cd-11ea-9413-d004ee990a34.png">

**Comment by wez** [comment]
What's happening here is that one of the implicit emoji fallback fonts is being used as the source of the cell metrics.  Emoji fonts tend to have large dimensions because they're typically embedding bitmaps.  Because the emoji fallback precedes a textual fallback the cells are oversized and yet still able to include text glyphs from a later fallback.

**Comment by erf** [comment]
I see. But is this the best fallback font? The cells seem VERY large. Could a more regular sized font be used?

**Comment by wez** [comment]
I'm still thinking about how best to resolve this; there are a couple of things to ponder:

* If we can reliably tell that a font is an emoji font then we should probably filter it out for this metric calculation
* If none of the explicitly specified fonts were found, could we use the system default?
* Some config options prevent using system default fonts and only look in user specified dirs, so the system default font may not actually work
* I'm wondering if wezterm should bundle eg: `JetBrains Mono` to use as an embedded default font so that there is a consistent default experience on all platforms.

**Comment by erf** [comment]
Do you really have to check for / use an emoji font? If it's just a fallback font (in case you configured something wrong), maybe a textual font is good enough? Although you'd have to deal with / display emojis as text. Bundle a default font sounds like a good idea, especially if the system default font doesn't work, or just always default to a bundled font if the one in config is missing. The `Jetbrains Mono` sounds like a decent choice. Or perhaps `Fira Mono`, as it's in a few top-programmer-font lists that i've seen. Btw is there a way to show a notification / alert to tell the user that the configuration is wrong?

**Comment by wez** [comment]
Re: `JetBrains Mono` vs `Fira Code`, I did take a closer look at them both and personally I find `JetBrains Mono` to have a slight edge over `Fira Code`.  They're both pretty similar, but a few of the characters in JetBrains look better to me, so I'd prefer that to be the default/fallback experience.
