### ISSUE TITLE
Support fullscreen

### ISSUE THREAD

**Issue by Freed-Wu** [wez/wezterm#2697]
**Is your feature request related to a problem? Please describe.**
fullscreen mode will hide title bar, press F11 or add some config can enter this mode.

**Comment by BetaRavener** [comment]
Doesn't ToggleFullScreen support what you want? https://wezfurlong.org/wezterm/config/lua/keyassignment/ToggleFullScreen.html
Default key mapping is Alt+Enter

**Comment by Freed-Wu** [comment]
> add some config can enter this mode.

It there any method to enter fullscreen mode at the beginning? such as
`wezterm --start-as=fullscreen` or

```lua
return {mode='fullscreen'}
```

**Comment by Freed-Wu** [comment]
I try

```lua
local wezterm = require 'wezterm'
local mux = wezterm.mux
wezterm.on('gui-startup', function(cmd)
    local tab, pane, window = mux.spawn_window(cmd or {})
    window:gui_window():maximize()
end)
return {
}
```

but it cannot be fullscreen when I enter it.

```sh
❯ has wezterm
✓ wezterm 20220905
❯ uname -r
6.0.2-arch1-1
❯ echo $XDG_SESSION_TYPE
x11
```

**Comment by wez** [comment]
You want to use https://wezfurlong.org/wezterm/config/lua/window/toggle_fullscreen.html instead of `maximize`

**Comment by carneeki** [comment]
For future reference, here is what I added to my config to give me the desired result (F11 for toggling fullscreen):

```lua
    keys = {
        {
            key = 'F11',
            action = wezterm.action.ToggleFullScreen,
        },
    },
```

(this is in a much larger return block)

**Comment by BuggusMageevers** [comment]
I just started using Wezterm and I'm enjoying my experience so far.  I, also, have been trying to get Western to start in fullscreen mode upon launch.  However, using `toggle_fullscreen()` makes the Wezterm window fill the screen *and* takes over the desktop on macOS.
The app should instead create a separate fullscreen screen space from the desktop.
Additionally, switching from one screen space (such as Western), to another (such as Safari in full screen mode), causes the dock to pop up when switching back to Western.  Going into and out of command view makes the dock hide itself again.  I think this is happening because Western is using the desktop screen space instead of its own space for full screen mode.

PC:  13-inch M1, 2020
OS:  macOS 13.0.1
Western: 20221119-145034-49b9839f

**Comment by wez** [comment]
@BuggusMageevers take a look at https://wezfurlong.org/wezterm/config/lua/config/native_macos_fullscreen_mode.html

**Comment by BuggusMageevers** [comment]
@wez Thank you.  I saw that option, but by the description, thought it was just about how quickly a transition occurred going fullscreen.  Use this option with the above code example does work for those that find this thread.  The app opens in window mode, but immediately transitions to fullscreen mode.  The Westerm now has its own screen space, the dock doesn't pop-up unexpectedly, and the desktop screen space is again available.

If there is a way to add a note to `native_macos_fullscreen_mode` with the above code segment, that may be helpful to future users who would like fullscreen mode on macOS.

Thank you, again.

**Comment by wez** [comment]
@BuggusMageevers I've clarified the docs for that option

**Comment by BuggusMageevers** [comment]
That's awesome.  Looks great!
