### ISSUE TITLE
Come with sane default configuration

### ISSUE THREAD

**Issue by markfaine** [wez/wezterm#2726]
I shouldn't have to google how to paste in wezterm.  This should be intuitive.  A context menu and preferences dialog would be the best option for configuring this but if that is simply unacceptable at least ship the package with some reasonable default settings.

**Comment by bew** [comment]
What is your issue with it?
What change of default settings are you suggesting?

**Comment by markfaine** [comment]
I'll have to come up with a list, I'm not on that computer right now, off the top of my head I'd say copy and paste should work out-of-the-box.

**Comment by markfaine** [comment]
I think the general philosophy seems to be backwards.  Perhaps, I'm misunderstanding something but  it seems to me that the terminal in it's default  freshly installed state comes with nothing enabled by default and the user is left to customize it how they like it, when it should come with defaults for everything (or at least the most used functions) and the user can then optionally customize it to their heart's content,  but...  isn't required to in order to have a functioning terminal.

**Comment by wez** [comment]
FWIW, thousands of users are able to use copy and paste with the default configuration: it has been designed to work out of the box and not require any particular configuration to get the most common unix terminal behaviors.

What we're missing from this report is a more detailed description of the concrete problem that you are facing so that we can productively help you figure out how to be successful.

As written, your comments on this issue are somewhat adversarial and pretty vague, so it's difficult to see how to help.  The low level of detail and the lag in your response also make it seem like it isn't a priority for you to resolve this, and it therefore it may not be worth expending too much effort to try to tease the details out of you.

If you don't want to spend the time writing things up a bit more, that's totally fine.

If you do want to get to the bottom of the issues that you encountered, I'd encourage you to file a new [bug report issue](https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&template=bug.yml) for each distinct issue by filling out the sections in the template, and we can follow up there.

With that in mind, I'm going to close this particular issue.

**Comment by markfaine** [comment]
You didn't give me a chance.  I just  commented that I was going to come up with a list  [here](https://github.com/wez/wezterm/issues/2726#issuecomment-1322796571).  Maybe you don't want me to?
