### ISSUE TITLE
Publish `wezterm-term` crate

### ISSUE THREAD

**Issue by chipsenkbeil** [wez/wezterm#2799]
Is there any chance of having `wezterm-term` published? The state machine and ability to advance via a byte stream is really appealing to me, and I'd rather not have to do it myself or fork the entire crate into distant.

Since the `Performer` and other related components aren't exposed, I'm using `termwiz` to poll input to send to a remote process, but I'm just printing the returned stdout, which results in a variety of situations that aren't as nicely handled.

**Comment by chipsenkbeil** [comment]
@wez bumping this again to see if there's any intent to publish this crate.

**Comment by wez** [comment]
I'm not sure that I want to be on the hook to guarantee that the API will be stable, which is an implicit part of the contract of publishing to crates.io.

This crate is really the heart of wezterm's emulation and I will make breaking changes there. If you're OK to follow those, I think that you should be ok to import it from git rather than via crates.io.

**Comment by chipsenkbeil** [comment]
Yeah, I could import from git for the CLI, since I don't need to publish that to crates.io, and it's only the CLI itself that uses the termwiz library and therefore would benefit from the switch to wezterm-term. I'll close this out now that I've got a read from you on the crate 😄
