### ISSUE TITLE
$SHELL no longer respected

### ISSUE THREAD

**Issue by dstromberg** [wez/wezterm#2812]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20221127-215232-c6e29b78

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

$SHELL no longer appears to be respected.  Instead, I just get /usr/local/bin/bash.

Wezterm's respect for $SHELL on MacOS is why I'm using it.  $SHELL is needed for https://stromberg.dnsalias.org/~strombrg/hcm/

### Configuration

SHELL=/tmp/hcm-82917-16697364051318 wezterm

...for example.  Just set $SHELL to a shell script to run in wezterm.

### Expected Behavior

The $SHELL should be run on all tabs.

### Logs

Debug Overlay
wezterm version: 20221127-215232-c6e29b78
OpenGL version: AMD Radeon Pro 5500M OpenGL Engine 4.1 ATI-4.8.101
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

**Comment by wez** [comment]
Moving away from `$SHELL`  was an intentional choice so that wezterm can pick up the current shell if the user has changed it since starting wezterm, so that multiple panes/tabs/windows don't need to be closed and restarted.
https://github.com/wez/wezterm/commit/7158c435d5a56bfa1502dd0af7470a9cca868c81 is part of that thread of changes.

I don't understand quite what hcm is doing with SHELL, but the supported way to spawn a specific command into a wezterm window is via the `start` subcommand; assuming that the temporary script is executable, something like this should work:

```
wezterm start /tmp/hcm-82917-16697364051318
```

you might consider writing a little wrapper script for your integration, something like:

```
#/bin/sh
# save me as wezterm-with-shell
exec wezterm start $SHELL
```

then tell hcm to use that script

**Comment by dstromberg** [comment]
Thanks, that's working for me.

hcm, among other things, makes it so you can open a new tab and automatically get an ssh session to a preselected host (including the possibility of ssh'ing to a, and from there to b, with a syntax like a!b).

**Comment by dstromberg** [comment]
I didn't test far enough.  It's not working.

I have:
$ cat $(which wezterm-wrapper)
cmd output started 2022 Tue Dec 06 12:38:07 PM PST
#!/bin/bash

wezterm start "$SHELL"

...and it makes the first tab start my $SHELL, but subsequent tabs just run bash.

Is there a way to make wezterm start that same $SHELL for all tabs?

**Comment by dstromberg** [comment]
Please note that when I say "for all tabs", mean for all tabs in a given wezterm window.  I do not mean starting the same shell on all wezterms on the same desktop login.

**Comment by dstromberg** [comment]
Why hcm wants this:
It's really nice to be able to start up a fresh ssh session, with pty logging, and an assortment of environment variable changes, with the click of a single button.  If one of your sessions times out, you just click the button again and get a fresh login to the same host with the same customizations.

**Comment by wez** [comment]
Consider using: `wezterm --config "default_prog={'$SHELL'}" start --always-new-process` to create a new wezterm window that will use only `$SHELL` by default for all newly spawned windows, tabs and panes launched from that instance.
