### ISSUE TITLE
Mouse action ExtendSelectionToMouseCursor=nil gives a Lua error

### ISSUE THREAD

**Issue by bew** [wez/wezterm#282]
## Environment (please complete the following information):

 - OS: Linxu X11
 - Version: 20200909-002054-4c9af461

## To Reproduce

Following the mouse assignments described at: https://wezfurlong.org/wezterm/config/keys.html#default-mouse-assignments
![mouse](https://user-images.githubusercontent.com/9730330/94370294-72509700-00ef-11eb-88ec-d12aa56e4d88.png)

I assigned a mouse event to `wezterm.action{ExtendSelectionToMouseCursor=nil}`

but got a Lua error:
```
callback error: external error: invalid value: map, expected map with a single key
```
With an unhelpful stack traceback.

Also, I'm wondering what nil means in this case, is it that it'll use the same selection mode as the last selection?

**Comment by wez** [comment]
It looks like `nil` is intended to map to the underlying Rust `Option::None` which should select the default mode of `Cell`.

I think my intent was to allow it to be left unspecified when using SHIFT to support picking up whatever selection mode was active for when https://github.com/wez/wezterm/issues/182 is implemented.

Due to weirdness in how lua treats `nil` and how serde wants to process Options, and how `wezterm.action` works, that configuration is not expressible via `wezterm.action`.

I'll push a commit which makes it possible to express this concept and update the docs.

**Comment by bew** [comment]
I personally don't this it's worth adding this concept to the configs, when #182 lands I think there will be a new selection mode like `LastMode`.
But this `FooBar={}` to represent a kind of default action looks really weird in my opinion, and does not add much.
