### ISSUE TITLE
default_cwd not working on WSL when split the pane

### ISSUE THREAD

**Issue by joexue** [wez/wezterm#2826]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220807-113146-c2fee766

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The default_cwd works when we start the wezterm, then if we use split to create a new pane, the work directory goes to windows default home instead of wsl home we set.

### Configuration

     default_prog = {"wsl"},
     default_cwd = "\\\\wsl$\\Ubuntu-22.04\\home\\myid",

### Expected Behavior

should goes to my set default_cwd

### Logs

16:44:56.201  WARN   mux::domain > Directory "/wsl$/Ubuntu-22.04/home/myid/" is not readable and will not be used for the command we are spawning: The system cannot find the path specified. (os error 3)
16:45:20.297  WARN   mux::domain > Directory "/wsl$/Ubuntu-22.04/home/myid/" is not readable and will not be used for the command we are spawning: The system cannot find the path specified. (os error 3)

**Comment by joexue** [comment]
I use the follow configuration to solve it.
default_prog = {"wsl", "--cd", "~"},

**Comment by wez** [comment]
I'd recommend that you use [WslDomains](https://wezfurlong.org/wezterm/config/lua/WslDomain.html) and set [default_domain](https://wezfurlong.org/wezterm/config/lua/config/default_domain.html) to the name of the WSL distro you want to use by default; that page has an example.

**Comment by joexue** [comment]
> I'd recommend that you use [WslDomains](https://wezfurlong.org/wezterm/config/lua/WslDomain.html) and set [default_domain](https://wezfurlong.org/wezterm/config/lua/config/default_domain.html) to the name of the WSL distro you want to use by default; that page has an example.

Hi Wez, looks not working either, the below is my configuration. it still goes to my windows home directory whatever I set the default_cmd or not.

default_domain = 'WSL:Ubuntu-22.04',
    wls_domains = {
    {
      name = 'WSL:Ubuntu-22.04',
      distribution = 'Ubuntu-22.04',
      username = "joe",
      default_cwd = "/home/joe/"
      -- default_prog = {"fish"}
    },

**Comment by wez** [comment]
I think the issue is that, if you haven't installed the shell integration inside WSL, the current working directory reported for `wsl.exe` is what is used for the current working directory, and that is used when spawning additional tabs.

https://wezfurlong.org/wezterm/shell-integration.html#shell-integration has information about shell integration.

I think the thing to fix here in wezterm is to teach it not to look at the `wsl.exe` process when determining the current working directory for a WSL domain.  Or perhaps ever if the process is named `wsl.exe`.

**Comment by joexue** [comment]
> I think the issue is that, if you haven't installed the shell integration inside WSL, the current working directory reported for `wsl.exe` (rather than the linux processes inside it) is what is used for the current working directory, and that is used when spawning additional tabs.
> 
> https://wezfurlong.org/wezterm/shell-integration.html#shell-integration has information about shell integration.
> 
> I think the thing to fix here in wezterm is to teach it not to look at the `wsl.exe` process when determining the current working directory for a WSL domain. Or perhaps ever if the process is named `wsl.exe`.

Actually, from the log, it does know the default_cwd (without using domain), the thing is, somehow it covert the windows path to linux path and cannot use it I think.

>16:44:56.201 WARN mux::domain > Directory "/wsl$/Ubuntu-22.04/home/myid/" is not readable and will not be used for the command we are spawning: The system cannot find the path specified. (os error 3)
16:45:20.297 WARN mux::domain > Directory "/wsl$/Ubuntu-22.04/home/myid/" is not readable and will not be used for the command we are spawning: The system cannot find the path specified. (os error 3)

**Comment by benelan** [comment]
I'm running into this issue while using `WslDomains` and setting the `default_domain` as recommended. I tried sourcing [`wezterm.sh`](https://github.com/wez/wezterm/blob/main/assets/shell-integration/wezterm.sh) at the end of my WSL2 Ubuntu 22.04 instance's bashrc but unfortunately it didn't help. I also unsuccessfully tried installing the deb since it said bash would work automatically. 

@wez are you aware of any additional shell integration steps that need to be taken for WSL2 with Ubuntu 22.04?


<details>
<summary>deb install error logs</summary>

```
$ sudo apt update && sudo apt upgrade -y && sudo apt install libc6 libx11-xcb1
...
libc6 is already the newest version (2.31-0ubuntu9.9).
libx11-xcb1 is already the newest version (2:1.6.9-2ubuntu1.2).

$ sudo apt install libssl3
...
E: Unable to locate package libssl3

$ sudo apt install -y ./wezterm-20221119-145034-49b9839f.Ubuntu22.04.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'wezterm' instead of './wezterm-20221119-145034-49b9839f.Ubuntu22.04.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wezterm : Depends: libc6 (>= 2.34) but 2.31-0ubuntu9.9 is to be installed
           Depends: libssl3 (>= 3.0.0~~alpha1) but it is not installable
           Depends: libx11-xcb1 (>= 2:1.7.5) but 2:1.6.9-2ubuntu1.2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

</details>

Here is a minimal config that repros the issue:

```lua
local wezterm = require("wezterm")

wezterm.on('gui-startup', function(cmd)
  -- attempting to set the cwd or manually cd in args
  -- doesn't work when spawning a new mux window either
  local _, pane, window = wezterm.mux.spawn_window {
    cwd = wezterm.home_dir,
    args = { 'cd', '/home/ben' }
  }

  -- finally, using send_text works for me, but oddly
  -- only after removing the args option above
  -- pane:send_text('cd /home/ben\n')
end)

return {
  default_domain = 'WSL:Ubuntu', -- found in default_wsl_domains()
  default_cwd = wezterm.home_dir, -- "/home/ben" doesn't work either
  default_prog = { 'cd', '/home/ben' } -- default_prog doesn't fix it for me 
}
```

Let me know if you need any additional info from my end.

> I think the thing to fix here in wezterm is to teach it not to look at the `wsl.exe` process when determining the current working directory for a WSL domain. Or perhaps ever if the process is named `wsl.exe`.

This sounds promising. The solution may also help fix a small WSL annoyance where the tab always shows the process as `wslhost.exe` instead of whatever you're doing inside WSL (nvim, bash, top, etc.)

Thanks for all your hard work on wezterm by the way, its an amazing terminal emulator!

**Comment by wez** [comment]
@benelan those deb error messages make it seem like you have a strange mixture of ubuntu versions installed. You should be able to create a WSL distro from one of the more recent versions of Ubuntu for which wezterm offers downloads.

Regarding teaching wezterm to understand the wsl process tree: I did sit down to look at that a couple of weeks ago, but on my Windows 11 system I couldn't reproduce the behavior and the process tree didn't conveniently point to `wsl.exe`, and neither did I see a UNC path for `wsl$` show up for the processes that were in the process tree.

**Comment by xanderificnl** [comment]
In addition to sourcing `wezterm.sh` in `.bashrc`, I'm using the configuration below with success. 

In short:

- Fresh sessions start in `$HOME` (on the Linux side).
- Panes and tabs respect the current working directory.
- Window title does change (i.e. `xander@pc:/usr/share`)

```lua
return {
    default_domain = 'WSL:Ubuntu-22.04',

    wsl_domains = {
        {
            name = 'WSL:Ubuntu-22.04',
            distribution = 'Ubuntu-22.04',
            default_cwd = '~'
        }
    },
}
```

Perhaps the `default_cwd` for WSL can be set to `~` so that we may avoid the extra configuration? I suppose a very obscure shell might not expand the tilde but that seems like an edge case.

_This configuration works with and without having Wezterm installed in WSL._

**Comment by wez** [comment]
I've made the default returned by https://wezfurlong.org/wezterm/config/lua/wezterm/default_wsl_domains.html be `~` in `main`.
