### ISSUE TITLE
faster way to navigate lines

### ISSUE THREAD

**Issue by KiaraGrouwstra** [wez/wezterm#2904]
**Is your feature request related to a problem? Please describe.**
After opening a file, I tend to move the cursor to the part of the file I'm interested in, which may well be down a bit.
I'd expect for e.g. PageDown to move the cursor down by a screen, but instead find it to not move the cursor at all.

**Describe the solution you'd like**
Have PageDown move the cursor, or have some other alternative to move the cursor by more than a line.

**Describe alternatives you've considered**
jjjjjjjjjjjjjjjjjjjjjjjjjjjjj

**Additional context**
n/a

**Comment by wez** [comment]
It sounds like you may be having problems using some other program (vim?) but you haven't really explained in detail what you're trying or what went wrong. I'd encourage you to open a new issue using [this page](https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&template=bug.yml) and fill out all of the information prompted by the template/form so that we can understand what is happening.
I'm going to close this one.

**Comment by KiaraGrouwstra** [comment]
I don't know if this is a bug, not knowing how wezterm is intended to work.
What I'm trying to say here is I'm not sure how to scroll down fast, to edit relevant parts of a file. I'm aware of:

- just using `j`, which is quite slow
- use `shift+j` to reach the end, but usually I don't want to move that far
- use `PgDown`, but this appears to move the screen without moving the cursor, meaning if you want to edit half-way across a file, this won't help

**Comment by wez** [comment]
it sounds like you might need help with your editor program, rather than with wezterm, but there's not enough information here to know for sure whether it is something that works in other terminals (and is thus a wezterm bug), or is just something you are curious about.  Framing this using the bug report form helps to capture more surrounding information and makes it easier to point you in the right direction, whether it is a bug in wezterm or not.

**Comment by KiaraGrouwstra** [comment]
my mind failed me -- i indeed filed this at the wrong repo. apologies.
