### ISSUE TITLE
missing $WINDOWID in linux

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#294]
`xterm` seems to set `$WINDOWID`. [ttygif](https://github.com/icholy/ttygif) seems to use it which is by default set in xterm. In weztem I get an error saying `$WINDOWID` is not defined.

Based on the instruction here. https://github.com/icholy/ttygif#additional-notes. I needed to add the following.

```bash
$ yay -S xdotool
$ export WINDOWID=$(xdotool getwindowfocus)
```

Would it make sense if `$WINDOWID` was set by default in `wezterm`?

**Comment by wez** [comment]
I'm leaning towards no, for a variety of reasons:

* X11 may not be in use
* The underlying X window ID isn't exposed through the window crate
* The first pty/process at wezterm startup is spawned before a window is created and thus can't set the var for that initial process.
* Even though the UI doesn't enable it today, the underlying data model allows for a pane to be moved between tabs and windows.  In that situation, the `WINDOWID` is not able to be updated and would thus be incorrect.

**Comment by prabirshrestha** [comment]
Sounds good. Closing it for now.

Do you have plans to add recording gif support in wezterm or as separate binary? I found this such as complex thing to do in a cross platform way. There doesn't seem to be on tool to do this.

wezterm already has `wt-record` would be good to have a way to convert it to gif. Let me know if you are interested and I can open a new issue else will close it out.

There is [t-rec](https://github.com/sassman/t-rec-rs) but gpl and only supports mac currently.

**Comment by wez** [comment]
I hadn't planned on adding screen recording.  I had a quick look into what it might take:

This glium example shows how to asynchronously capture the rendered buffer from the opengl state:
https://github.com/glium/glium/blob/master/examples/screenshot-asynchronous.rs

The `if take_screenshot {..}` part of that would logically need to be inserted at the bottom of `TermWindow::call_draw`; I think you can pass the `frame` in place of the `Facade` type in the example.

Instead of writing out a png, you'd want to use <https://docs.rs/gif/> to write out a frame to the gif file.
It appears as though `gif::Frame::delay` allows setting the delay since the prior frame; it should be relatively straight forward to compare a new frame with the prior frame and only write the new frame to the gif if it is different.  Keeping track of the time at which the prior frame was written would allow setting the frame delay in the gif file.

I think the main tricky part of this is down-sampling to a 256 color palette.  The `image` crate may have something to help with this.  `gif::Frame::palette` appears to allow setting this per frame which is good, because with true color terminals we can't pre-compute a palette at gif creation time.

If you wanted to take a crack at submitting a PR for this, I'd suggest adding a KeyAssignment to toggle screen recording state in a window and then using that in place of the `if take_screenshot` condition from the example.
