### ISSUE TITLE
Text in tab isn't restored to what it was under certain circumstances

### ISSUE THREAD

**Issue by Porkepix** [wez/wezterm#2950]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Gnome

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When opening a file with the kakoune editor (https://kakoune.org/), it modifies the tab's text to show which file is opened and so on.
Once exiting the editor, it's supposed to go back to the previous text (usually the prompt). Bug when this is done from a zsh shell, it never goes back to the previous text.

Bug can't be reproduced from bash. Bug can't be reproduced in another terminal with tabs.

### To Reproduce

- Open a file with kakoune from a `zsh` shell.
- Exit kakoune
- Look at the tab; it's still showing that it's kakoune with a file opened.

### Configuration

No config

### Expected Behavior

The tab's text should get back to its prompt

### Logs

wezterm record logs here: 
[wezterm-recording-FprbUB.cast.txt](https://github.com/wez/wezterm/files/10406187/wezterm-recording-FprbUB.cast.txt)

**Comment by wez** [comment]
Analyzing the recording with the `--explain` flag shows more human readable interpretations of the escape sequences from the recording:

```
; wezterm replay wezterm-recording-FprbUB.cast.txt --explain | grep -i window
...
        Action(OperatingSystemCommand(SetWindowTitle("/tmp/wezterm-bug.txt 1:1  1 sel - client0@[18291] - Kakoune")))
        Action(OperatingSystemCommand(SetWindowTitle("/tmp/wezterm-bug.txt 1:1  1 sel - client0@[18291] - Kakoune")))
        Action(OperatingSystemCommand(SetWindowTitle("/tmp/wezterm-bug.txt 1:1  prompt - client0@[18291] - Kakoune")))
        Action(OperatingSystemCommand(SetWindowTitle("/tmp/wezterm-bug.txt 1:1  prompt - client0@[18291] - Kakoune")))
        Action(OperatingSystemCommand(SetWindowTitle("/tmp/wezterm-bug.txt 1:1  prompt - client0@[18291] - Kakoune")))
        Action(OperatingSystemCommand(SetWindowTitle("/tmp/wezterm-bug.txt 1:1  prompt - client0@[18291] - Kakoune")))
```

the only window title related sequences captured in the recording are those shown above, and they appear to come from kakoune.

Usually, folks configure some shell configuration to update the window title when the prompt is displayed. It seems like you may not have that configured.  Some systems ship with something that does it by default, some do it when certain packages are installed.  I've had something in my dotfiles to do this since the 90's so I've never needed to rely on the system for it.
If this works in bash but not zsh, then I'd suggest comparing your dotfiles and those in places like `/etc/profile.d` to see if you can figure out what is setting it up for one and not the other.

The reason I asked you to submit a recording for this is because there are a couple of escape sequences that push/pop titles that wezterm doesn't currently support and I wanted to be sure that those were not being used in this case before I boldly stated that the bug was elsewhere.

**Comment by Porkepix** [comment]
> Usually, folks configure some shell configuration to update the window title when the prompt is displayed. It seems like you may not have that configured. Some systems ship with something that does it by default, some do it when certain packages are installed. I've had something in my dotfiles to do this since the 90's so I've never needed to rely on the system for it. If this works in bash but not zsh, then I'd suggest comparing your dotfiles and those in places like `/etc/profile.d` to see if you can figure out what is setting it up for one and not the other.

I could reproduce it in an environment where zsh have no dotfiles for itself (at least, no `.zshrc`, no `.zprofile` and so on). 
`/etc/profile.d`  seems unrelated to me, but just for the record if it may help, from a different computer than the one used for the record but I reproduce the issue on both:

```
/etc/profile.d/
debuginfod.csh         gpm.sh                 perlbin.csh
debuginfod.sh          jre.csh                perlbin.sh
flatpak-bindir.sh      jre.sh                 vte.csh
flatpak.sh             libreoffice-fresh.csh  vte.sh
freetype2.sh           libreoffice-fresh.sh   wezterm.sh
gawk.csh               locale.sh
gawk.sh                PackageKit.sh
```
(I doubt any of them would come mess here.

> The reason I asked you to submit a recording for this is because there are a couple of escape sequences that push/pop titles that wezterm doesn't currently support and I wanted to be sure that those were not being used in this case before I boldly stated that the bug was elsewhere.

While absolutely no expert on the matter, that's the kind of things I had in mind.

One other very strange thing I could notice though: tests I've done include cases where `zsh` isn't the main shell (not the one picked when I open my terminal) as it's still bash, so `zsh` was run from `bash`. And after reproducing the issue (so, I have tab's text that's messed), exiting `zsh` (so going back to bash) "fixes" the tab's text.

So I don't know if that could point an issue to `zsh` itself…

Which program is responsable to give the instructions for these tab's text? Is kakoune sending it directly to the terminal? Is it sending it to the shell that's then forwarding it to the terminal, modified or not?

**Comment by wez** [comment]
The shell, once it spawns a program, essentially goes to sleep until the program quits.  The program being run doesn't communicate with the shell; it just outputs to the stdio and terminal streams.

kak is setting the title in the your recording.

When the shell resumes, the shell doesn't change the title because that isn't what shells do by default: they need some additional configuration to tell them to do it.

There's something about your shell configuration that isn't doing that: you need to do something to make that happen for your system.

I'd suggest searching and reading up on this; google for something like "zsh window title" and see what you can find that is applicable to your system and setup.

**Comment by Porkepix** [comment]
> The shell, once it spawns a program, essentially goes to sleep until the program quits. The program being run doesn't communicate with the shell; it just outputs to the stdio and terminal streams.
> 
> kak is setting the title in the your recording.
> 
> When the shell resumes, the shell doesn't change the title because that isn't what shells do by default: they need some additional configuration to tell them to do it.
> 
> There's something about your shell configuration that isn't doing that: you need to do something to make that happen for your system.
> 
> I'd suggest searching and reading up on this; google for something like "zsh window title" and see what you can find that is applicable to your system and setup.

But shouldn't this be the default behavior of the shell, or from the editor?
Also, what's still strange about this is that if you take Gnome's console (their latest basic GTK4 terminal) and reproduce the same steps: use `zsh`, open kakoune, exit it, then their tabs are correctly going back to prompt text. Why would this terminal act correctly while it's not the case on wezterm, with the exact same shell configuration? (Very basic when even existing configuration, that said).

**Comment by wez** [comment]
`/etc/profile.d/vte.sh` is an integration installed by Gnome Terminal that includes logic to set the window title but only when running in gnome terminal.

I consider changing the title to be a bit invasive (there doesn't appear to be a way to customize it or disable it), so wezterm's shell integration doesn't do that.

**Comment by Porkepix** [comment]
I don't see what would be responsible for this into https://gitlab.gnome.org/GNOME/vte/-/blob/master/src/vte.sh.in

I admit I'm not really sure what are those lines doing: https://gitlab.gnome.org/GNOME/vte/-/blob/master/src/vte.sh.in#L31-41
But at first glance it doesn't looks like it's doing things related to tabs?

**Comment by wez** [comment]
this line is using the `OSC 0` sequence to set the title:
https://gitlab.gnome.org/GNOME/vte/-/blob/master/src/vte.sh.in#L39

**Comment by wez** [comment]
I'm closing this out, as it isn't an issue in wezterm

**Comment by Porkepix** [comment]
Yeah, I didn't found out how to change this in non-vte terminals, and to be honest I feel like as it's kakoune changing it when starting, it should restore it when closing, but anyway yes this isn't Wezterm's problem.
