### ISSUE TITLE
Using WebGPU front end disables opacity on MacOS

### ISSUE THREAD

**Issue by farzadmf** [wez/wezterm#2952]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

To have a better font rendering discussed in #2927 , I switched the frontend to WebGPU, and the text seems to look much nicer.

Before switching the frontend, I had opacity enabled on my window. but after switching the frontend, the window is always opaque and has no transparency.

### To Reproduce

Configure WezTerm to have an opacity value and use WebGPU by having this in the config
```lua
  front_end = "WebGpu",
  window_background_opacity = 0.9,
```

Open WezTerm, and see the opacity value has no effect.

### Configuration

```lua
return {
  -- other things
  front_end = "WebGpu",
  window_background_opacity = 0.9,
}
```

### Expected Behavior

The WezTerm window should reflect the opacity value I set in the config.

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by farzadmf** [comment]
Hey @wez , that's great to hear. It's a bit late for me now, and I need to rest, but will definitely try this out in a few hours

**Comment by farzadmf** [comment]
Hello again @wez , so I downloaded the nightly, and the opacity seems to be working, good news 🙂

However, I have `color_theme = 'Gruvbox Dark'`, but the colors shown in the nightly don't seem to be the one from the theme 🤔 (My default non-nightly version, when opened, shows different colors)

**Comment by wez** [comment]
The upstream iTerm2-Color-Schemes repo renamed that color scheme; see:
https://wezfurlong.org/wezterm/changelog.html#changed

**Comment by farzadmf** [comment]
Thank you. Things look much better.

Although I must say, the new `GruvboxDark` one doesn't seem to be the "dark" version and is wayyy brighter than what I have for the non-nightly version. Do you think it's something happening in upstream?

**Comment by wez** [comment]
https://github.com/mbadolato/iTerm2-Color-Schemes/commit/2a47ecb74b17870540f69b26890290d78b758c84 was the commit that renamed it; it also says that it fixed some colors.

There are a couple of other gruvbox variants available starting here and scrolling down:
https://wezfurlong.org/wezterm/colorschemes/g/index.html#gruvbox-gogh

**Comment by farzadmf** [comment]
Right, thanks for the link. I think they _broke_ the colors rathar than _fix_ them 😆

But `color_scheme = 'GruvboxDarkHard'` seems to be darker and maybe similar to what `Gruvbox Dark` was before.

When do you think this change will be in the package managers? Mac's `brew` specifically since I'm on Mac

**Comment by wez** [comment]
I don't have a date in mind for the next release yet; I need to sit down and triage the open issues and see what else I think needs to be tidied up.

**Comment by farzadmf** [comment]
Yeah, totally makes sense. Hopefully it's sooner rather than later 🙂

**Comment by farzadmf** [comment]
Hey @wez , sorry to bother you again, I was wondering abou the italic font in WezTerm

This is what I see in WezTerm:
![image](https://user-images.githubusercontent.com/5768792/212406591-edea16fd-0bd0-4aeb-b943-e4857a592b15.png)

And this is what I see in Kitty:
![image](https://user-images.githubusercontent.com/5768792/212406726-d2b44f1f-408a-48c3-b3f6-985790964feb.png)

As you can see:
- In Kitty, the text is italics (although WezTerm seems to be a bit "too italic" 😝 )
- In Kitty, the icons/glyphs (sorry I don't know the exact technical term) don't appear slanted, and I think it's nicer like that

Is there any settings or something to play around with these?

**Comment by wez** [comment]
Italics are usually part of the font itself, but if your selected font doesn't have an italic variant, wezterm will apply a simple skew operation to make them appear italic.  You can use `wezterm ls-fonts` to see whether that is the case: if it says something like "will synthesize italic" then it is a skew operation.

wezterm doesn't know whether a given glyph should be italicized or not (full text shaping can reorder and introduce more glyphs than were input as code points, and reverse mapping is a hard problem).  In addition, italics are a subjective design choice made by the font designer, and it is difficult for a program to make the correct choice for every font.  The sanest thing is to either skew everything in the font or nothing otherwise things will look weird and inconsistent.

Some block glyphs have built-in versions in both kitty and wezterm; see https://wezfurlong.org/wezterm/config/lua/config/custom_block_glyphs.html for which ones wezterm supports.  I don't know if kitty supports a wider range than wezterm, but it's possible that it does and that that is why it looks square in kitty.

My advice would be for you to pick a font that has a proper italic variant and use that, rather than relying on the simple skew synthesis.

https://wezfurlong.org/wezterm/config/lua/config/font_rules.html explains how you can pick a different font for just italic text if you wish.
