### ISSUE TITLE
Add pane-related styling options

### ISSUE THREAD

**Issue by mborejdo** [wez/wezterm#297]
It would be great, if we could style the panes (active/inactive pane, pane separator etc) just as we can with tabs (https://wezfurlong.org/wezterm/config/appearance.html#tab-bar-appearance--colors)

PS. The fact I am currently styling wezterm to be visually inline with my Desktop, shows that its almost feature-complete for me and used daily. Thanks a lot for this great terminal emulator @wez. The best terminal I have worked with.

**Comment by wez** [comment]
I've thought a little bit about this, and have been deliberately holding off until I hear more from users about what form this should take.

https://github.com/wez/wezterm/issues/117 has some open questions around "profiles".  I've been thinking that it would be interesting to add a profile override as a parameter to the [SpawnCommand](https://wezfurlong.org/wezterm/config/lua/SpawnCommand.html) struct so that new panes/tabs/windows could spawn with an alternate scheme.  I think that this might be visually quite striking to see in panes.

I'm not super clear on what has the most utility for styling active vs. inactive panes.  iTerm2 on macOS has an option to "dim" inactive panes to de-emphasize them, which makes sense to me.  I'm not sure if it makes as much sense to switch color scheme based on the active/inactive pane, but may not be that difficult to do, as there's some similar processing that happens for TLS multiplexer tabs that are experiencing long delays.

tmux and Windows Terminal Preview have options to change the color of the pane split.  I'm not 100% sure of the utility of that because it seems very ambiguous to me for example in the simple case of a single split.  Maybe it makes sense to change the glyph used in the pane border to have eg: `<` on a vertical split to point to the left pane when it is active, or `>` when the right is active.

I'd like to find the right balance between utility and effort to build for this sort of thing :-)

**Comment by mborejdo** [comment]
Thanks for clarifying your view on this.
To me profiles are not very important in my daily workflow, so my need is basically for split-line color (maybe transparency) and active/inactive panes. 
Id love to be able to have a more subtle color for the line. Considering the active-pane-indicator, it would be great to be able to set something like "inactive_pane_background_opacity" or the like. Probably dimming/tinting via 'inactive_pane_background_tint' could be an alternative.

**Comment by wez** [comment]
eb9f7aefc696393899ab583a327c3d1e944d2dfe adds three new config settings:

`inactive_pane_hue`, `inactive_pane_saturation` and `inactive_pane_brightness`
allow for transforming the color of inactive panes.

The pane colors are converted to HSV values and multiplied
by these values before being converted back to RGB to
use in the display.

Modifying the hue changes the hue of the color by rotating
it through the color wheel.  It is not as useful as the
other components, but is available "for free" as part of
the colorspace conversion.

Modifying the saturation can add or reduce the amount of
"colorfulness".  Making the value smaller can make it appear
more washed out.

Modifying the brightness can be used to dim or increase
the perceived amount of light.

The range of these values is 0.0 and up; they are used to
multiply the existing values, so the default of 1.0
preserves the existing component, whilst 0.5 will reduce
it by half, and 2.0 will double the value.

A subtle dimming effect can be achieved by setting:

```lua
return {
  inactive_pane_saturation = 0.9,
  inactive_pane_brightness = 0.8,
}
```

**Comment by wez** [comment]
1978eba0a13e4c78797684754ccf14ef5e880f83 allows specifying the color of the split divider, and makes it a bit darker by default:

```lua
return {
  colors = {
    split = "#444444",
  }
}
```

**Comment by mborejdo** [comment]
Thanks a lot! That is exactly what I needed.

**Comment by mborejdo** [comment]
one thing I forgot to mention and would love to see: Currently it is hard to distinguish between a "single pane" and "maximized pane". I'd love to be able to indicate the "maximized/fullscreen" pane. I am not sure if saturation and brightness would help here or if there should be another way to visualize maximized panes. Maybe some horizontal line (top/bottom) (with custom color and width), colorized padding/border or the like would work here

**Comment by wez** [comment]
What do you think about having something show up in the titlebar to indicate zoomed state?

**Comment by mborejdo** [comment]
I also thought about this. What about titles being set with OSC1? wouldnt this be overrridden in this case?

**Comment by wez** [comment]
The window title is already augmented with `[1/2]` to show the active vs. number of tabs (that pre-dates the tab bar).
Adding a status character in there (perhaps `Z` for zoomed, similar to tmux) would help?

**Comment by mborejdo** [comment]
Ah, yes. I forgot about that. In that case some character or symbol would work.
