### ISSUE TITLE
`ActivateTab` and `:set_title` via `wezterm cli`

### ISSUE THREAD

**Issue by matthewgrossman** [wez/wezterm#2979]
**Is your feature request related to a problem? Please describe.**
I'm in the process of migrating from a different terminal emulator and I'm trying to reach feature parity. One of these integrations is a shell func ([current version](https://github.com/matthewgrossman/dotfiles/blob/8cd438390cf0433d13e35c84bda4bf00275f2fc0/config/zsh/functions.sh#L58-L66)) that does a few things:
1. print out all of current tabs that are open (and their `cwd`s), letting the user choose which one they want to navigate to
2. once chosen, set the chosen tab as the current focused tab in the terminal
3. set the tab's title to the `cwd`

wezterm enables me to do (1) via `wezterm cli list --format json | jq ...`. However, how do I use my shell (bash/zsh) to focus on a tab (2) and change the tab's title (3)?

I know this functionality exists programmatically in lua:
* [`ActivateTab`](https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivateTab.html?highlight=activatetab#activatetab)
* [`set_title`](https://wezfurlong.org/wezterm/config/lua/MuxTab/set_title.html)

**Describe the solution you'd like**
While we could expose those two functionalities in the CLI (like suggestion here: https://github.com/wez/wezterm/issues/1598#issuecomment-1324381537), I wonder if there's a better way to have the CLI hook into lua?

The reason I kept these two semi-related feature-requests together is because it feels like I'm missing some way to just hook into the lua API already defined. This seems more scaleable than adding a new `wezterm cli` command each time we want to expose more of the editor's functionality

**Describe alternatives you've considered**
* We _could_ just expose both of these via `wezterm cli`
* Leverage some existing way to trigger an event, such that `wezterm` can use the lua api in response to the event. This might be easy enough? Feels a little messy to have to bounce control back and forth between the the shell func and a wezterm event handler though
* I could just rely on standards to set the tab title (e.g in nvim `set title`/`set titlestring`). This way I don't need to do anything with the terminal emulator (I might do this regardless, but this only solves (3))

**Additional context**
Similar tickets:
* ~https://github.com/wez/wezterm/issues/2973~ hmmm this isnt' the one I was thinking of, can't find a similar one I was thinking of

**Comment by wez** [comment]
The `wezterm cli` subcommands wrap up the *mux protocol* for use in the CLI.

The mux-layer lua scripting API operates on an internal `Mux` object (which may itself manage multiple mux protocol clients).

The GUI-layer lua scripting API operates on the GUI process state, which sits atop a Mux object but that has other GUI related stuff to contend with.

Anything you want to do via `wezterm cli` needs to have a corresponding request/response PDU defined in the mux protocol, which is how mux servers and clients communicate.  The cli doesn't have a Mux object as it is itself not a multiplexer.

The mux protocol can have multiple clients; not all clients may be attached to a GUI.  Some clients may actually want to focus different tabs at the same time, so activating/focusing a specific window/tab/pane needs to take that into account (see https://github.com/wez/wezterm/issues/1531 for more discussion on this).

Yes, I agree that it would be nice to simply expose those lua functions to the CLI, but it isn't as simple as it seems.  There's more discussion around the difficult aspects of that sort of thing in https://github.com/wez/wezterm/issues/2251.

In the meantime, for your 2) use-case, there is a thing you can piggy back on top of:

## User Vars

You can use an OSC escape sequence to set a *user var* for a given pane.  Those can be retrieved by 
[pane:get_user_vars()](https://wezfurlong.org/wezterm/config/lua/pane/get_user_vars.html), but what makes them interesting for your use case is that assigning a user-var will generate a notification that will get dispatched to all connected mux clients and get dispatched to the [user-var-changed](https://wezfurlong.org/wezterm/config/lua/window-events/user-var-changed.html) event and allow you to react to the event in your lua code.

This is definitely somewhat indirect, but it's something that exists now and can be bent to your will.

For example, you could set `FOCUS_TAB=2` as a user-var and then in your handler transform that into the actions you want to take.  Most likely it would be something like `window:perform_action(wezterm.action.ActivateTab(tonumber(value))`.

It's possible that you'll want more functionality to be exposed to the lua API and to the CLI: I've been somewhat deliberately holding tight on exposing every possible function to see what user requests come through in order to avoid having to manage backwards compatibility with a poorly thought out API.

**Comment by matthewgrossman** [comment]
Thanks for explaining the complexity @wez. I'll look into the OSC escape sequences to make part of my solution work for me.

Feel free to close out if you think it dupes other requests!

**Comment by SimplyKnownAsG** [comment]
well, for anyone else who stumbles on this. I did what @wez mentioned, I think. It is not too difficult. However; I'm new to lua, and debugging this was not easy.

```bash
# shell functions
wopen-tab() {
  printf "\033]1337;SetUserVar=%s=%s\007" hacky-user-command $(printf '{"cmd":"open-tab","title":"%s"}' $1 | base64)
}
wset-tab-title() {
  printf "\033]1337;SetUserVar=%s=%s\007" hacky-user-command $(printf '{"cmd":"set-tab-title","title":"%s"}' $1 | base64)
}
```

```lua
-- wezterm.lua
local wezterm = require 'wezterm'
local act = wezterm.action

local hacky_user_commands = {

  ['set-tab-title'] = function(window, pane, cmd_context)
    pane:mux_pane():tab():set_title(cmd_context.title)
  end,

  ['open-tab'] = function(window, pane, cmd_context)
    for tab_index, tab in ipairs(window:mux_window():tabs()) do
      if tab:get_title() == cmd_context.title then
        window:perform_action(
          act.ActivateTab(tab_index-1),
          pane
        )
        return
      end
    end

    local new_tab, _, _ = window:mux_window():spawn_tab {
      cwd = wezterm.home_dir
    }

    new_tab:set_title(cmd_context.title)

    return
  end,
}

wezterm.on('user-var-changed', function(window, pane, name, value)
  if name == 'hacky-user-command' then
    local cmd_context = wezterm.json_parse(value)
    hacky_user_commands[cmd_context.cmd](window, pane, cmd_context)
    return
  end
end)
```

**Comment by wez** [comment]
@SimplyKnownAsG that looks nice and clean!
FWIW, for JSON in the shell, you can use [jq](https://stedolan.github.io/jq/) to quote and encode the json objects:

```
jq -n --arg title "$1" '{"cmd":"open-tab","title":"$title"}'
```

**Comment by wez** [comment]
Note that the latest release has:
* [wezterm cli activate-tab](https://wezfurlong.org/wezterm/cli/cli/activate-tab.html)
* [wezterm cli activate-pane](https://wezfurlong.org/wezterm/cli/cli/activate-pane.html)
