### ISSUE TITLE
Bind `_` to MoveToStartOfLineContent in CopyMode

### ISSUE THREAD

**Issue by craigmac** [wez/wezterm#2988]
In Vim `_` key in Normal mode goes to first non-whitespace character on the line, which is a bit different than `0` which just goes to the first column.  Right now `^` is bound to that in my version of wezterm (latest official release on macOS), which I'm assuming you just repurposed since there's no 'last buffer' to switch to while in wezterm copymode. I have no issue with that, just was thinking we should add this one as well. I'd send a PR but looked at a couple of others for adding keybinds and it was beyond my Rust knowledge, which is 0.

I'm using right now:

```lua
return {
  key_tables = {
    copy_mode = {
      { key = '_', mods = 'SHIFT', action = act.CopyMode 'MoveToStartOfLineContent' },
      { key = '_', mods = 'NONE', action = act.CopyMode 'MoveToStartOfLineContent' },
    },
  },
}
```

**Comment by wez** [comment]
FWIW, `^` is a left-right motion documented in `:help motions.txt` in vim:

```
                                                        ^
^                       To the first non-blank character of the line.
                        exclusive motion.  Any count is ignored.
```

that behavior is exactly `MoveToStartOfLineContent`.

`_` is:

```
                                                        _
_  <underscore>         [count] - 1 lines downward, on the first non-blank
                        character linewise.
```

which is only similar to `MoveToStartOfLineContent` when no count is specified; it's actually an up-down motion that happens to also move to the start of the content.

I'm not sure that I want to alias `_` to `MoveToStartOfLineContent` by default because of this difference: it feels like it would immediately become tech debt that would need to be discovered and resolved if/when we later add *count* support to copy mode.
