### ISSUE TITLE
piping image to wezterm's imgcat on Windows not working

### ISSUE THREAD

**Issue by mborejdo** [wez/wezterm#301]
## Describe the bug
 8e6c2cfa2acfc3c7b6847b15b62012c1b85c0a4f introduced piping an image to wezterm's imgcat.
This does not seem to work on windows. The command just does not exit.

I tried powershells get-content, cmd type, bat (in plain mode etc)

## Environment (please complete the following information):

 - OS: Windows 10
 - Version: wezterm 20200909-002054-4c9af461-187-g2364b0a

## To Reproduce

start cmd in wezterm and run "type image.png | wezterm imgcat"

using cat in wsl (and wezterm.exe on the windows host) does work.

**Comment by wez** [comment]
Confirmed; this is due to `wezterm.exe` being marked as a `win32` subsystem executable rather than a `console` subsystem executable.

What that means is that cmd launches the program async and then there's some weirdness with pipes.

Commenting out the `windows_system` line from `wezterm/src/main.rs` "fixes" this, but means that wezterm will spawn a console host when launched from the gui.

To properly resolve this means splitting the CLI functionality from the GUI functionality and having separate executables for these on windows.

**Comment by mborejdo** [comment]
thanks for clarifying this.
what exactly do you mean by splitting gui from cli functionality. Like making wezterm's imgcat a dedicated binary?

**Comment by wez** [comment]
One way might be to move the GUI functionality into `wezterm-gui.exe` and teach `wezterm.exe start` how to launch it.
Then `wezterm.exe` could be a console subsystem binary with the same interface.

**Comment by mborejdo** [comment]
Great! Works for me now. thank you very much @wez
