### ISSUE TITLE
calling pane.get_current_working_dir() inside of an event listener throws an error

### ISSUE THREAD

**Issue by odama626** [wez/wezterm#3012]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

mutter

### WezTerm version

20230125-180646-f15bb186

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

calling pane.get_current_working_dir() inside of  the open-uri event is throwing an error

### Configuration

```lua
wezterm.on("open-uri", function(window, pane, uri)
  local start, match_end = uri:find("vscode://");
  if start == 1 then
    local cwd = pane.get_current_working_dir()
    local url = "vscode://file" .. cwd .. uri:sub(match_end+1);
    window.open_with(url)

    return false;
  end
end)
```

```lua
{
  hyperlink_rules = {
    {
      regex = '\\b[/\\w.-]+\\.[a-z]{2,15}:?\\d*:?\\d*\\S*\\b',
      format = 'vscode://$0'
    },
  }
}
```

### Logs

```
ERROR wezterm_gui::termwindow > while processing open-uri event: callback error
stack traceback:
        [C]: in field 'get_current_working_dir'
        [string "/home/asparks/.config/wezterm/wezterm.lua"]:7: in function <[string "/home/asparks/.config/wezterm/wezterm.lua"]:4>
caused by: error converting Lua missing argument to userdata
```

**Comment by wez** [comment]
You need to use `:` rather than `.` to call a method in lua: `pane:get_current_working_dir()`.

The pane object methods all expect to receive the `pane` object as their first "self" parameter. In other words, that method is declared equivalently to:

```lua
pane.get_current_working_dir = function(pane)
   -- do something
end
```

When you try to invoke `pane.get_current_working_dir()` you're missing out the required first parameter to the method, which results in the not-very-clear error message you saw.

When you use `pane:get_current_working_dir()` it is syntactic sugar for `pane.get_current_working_dir(pane)`, which will have the desired result.

**Comment by odama626** [comment]
oh ok thank you!
