### ISSUE TITLE
Nightly: MacOS menu bar shortcuts strip LEADER

### ISSUE THREAD

**Issue by brandonchinn178** [wez/wezterm#3021]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230125-180646-f15bb186

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I have `CloseCurrentTab` bound to `LEADER|CMD + w`, but the MacOS menu bar just shows "CMD + w". The configuration is being applied correctly; changing it to `LEADER|CMD|SHIFT + x` shows "CMD|SHIFT + x" in the menu.

This becomes an issue because MacOS menu shortcuts take precedence over application shortcuts, so "CMD+W" will keep closing windows, even though I've remapped it to `LEADER+CMD+W`.

I can confirm that the non-nightly release of Wezterm does not have this behavior.

### Configuration

```lua
return {
  leader = { key = ';', mods = 'CMD' },
  keys = { { mods = 'LEADER|CMD', key = 'x', action = act.CloseCurrentTab{confirm = true} },
}
```

**Comment by brandonchinn178** [comment]
To workaround this, I'm doing:
```lua
keys = {
  { mods = 'LEADER|CMD', key = 'w', action = CloseCurrentTab{confirm = true} },
  { mods = 'LEADER|CMD|CTRL|ALT|SHIFT', key = 'x', action = CloseCurrentTab{confirm = true} },
}
```
I'm not exactly sure how Wezterm chooses which keyboard shortcut to use, but it seems to only work when the overriding `mods` starts the same as the overridden `mods`

**Comment by wez** [comment]
Note that you probably want to use [DisableDefaultAssignment](https://wezfurlong.org/wezterm/config/lua/keyassignment/DisableDefaultAssignment.html) to turn off the key assignments that you don't want to be used and shown in the menubar, such as the default `CMD-w` assignment.  You can use `wezterm show-keys --lua` to identify the complete, effective set of key assignments.

That's separate from the bug that you reported though: I've made it so that key assignments using LEADER are not included in the set of candidates that are used for the menubar in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by brandonchinn178** [comment]
Seems like CI for MacOS failed. But I built from source and can confirm it works. Thanks for the quick turnaround!

Random comment (I've opened a ton of issues, I don't want to create another one for this minor thing): I set the tab title to the name of the directory I'm in, e.g. in my `~/.zshrc`:
```bash
function precmd {
  print -f '\e]1;%s\a' "$(basename $PWD)"
}
```
This is working pretty much everywhere, but it seems like in the special case where I'm in a directory named `wezterm` (e.g. when I cloned the repo), wezterm seems to ignore this. Is that a known behavior?

Repro:
- `wezterm start -- zsh --no-rcs`: title is `zsh`
- In new shell: `print -f '\e]1;asdf\a'`: sets title to `asdf` correctly
- `print -f '\e]1;wezterm\a'`: goes back to `zsh` title

**Comment by wez** [comment]
if the title is exactly `wezterm` (which happens to be the default title), wezterm will fall back to returning the local process name.

You could finagle around that by doing something like: `print -f '\e]1;%s \a' "$(basename $PWD)"` (note the extra space!)

**Comment by brandonchinn178** [comment]
Thanks!
