### ISSUE TITLE
Set window_padding color to current background color 

### ISSUE THREAD

**Issue by erf** [wez/wezterm#303]
**Is your feature request related to a problem? Please describe.**

If i open a editor with a theme of e.g. blue background color, i wish that the `window_padding` color could also be blue, instead of black.

**Describe the solution you'd like**

When the terminal background color changes, i would like the `window_padding` color to be set to the same color.

**Describe alternatives you've considered**

I'm not aware of a way to set `window_padding` color per now - maybe there should be an api to set this?

**Additional context**

Ref #195

**Comment by wez** [comment]
You can do this today, if you use the right escape sequences!

First a little bit of info:
In the wezterm color settings one of the attributes is the background color.
That is the color that is used when the SGR attributes for the cell use the "default background color".

The `vis` editor emits some SGR sequences to override the background color for various cells to an explicitly selected background color.  It can only paint over addressable cells in the display.  This is why the color of padding is unaffected: `vis` is only sending sequences to change the background of specific cells.

wezterm supports a variety of dynamic color escape sequences; the easiest way to play with those is:

```
git clone https://github.com/mbadolato/iTerm2-Color-Schemes.git
cd dynamic-colors
./Borland.sh
```

This will turn the background, including the padding, to blue.  There's a script in that directory for each color scheme; running it will emit the escape sequences to change the active color palette.

Distilling it down:

```
# Override colors.background and set it to a blue color
printf "\033]11;#0000a4\007"
```

```
# Reset any overridden palette entries to the configured defaults
printf "\033]104\007"
```

What I think you want to do is teach `vis` to emit the first of those with the background color of its active color scheme when it starts, and then the second one when it exits.

**Comment by erf** [comment]
Sounds great. `vis` has a Lua [API](http://martanne.github.io/vis/doc/) and i'm able to do a `echo` command to the terminal, now i just need to figure out if it is possible to get the current theme background color.. There is no way for `Wezterm` to pick up this?

**Comment by wez** [comment]
> There is no way for Wezterm to get the background color, so we could enable an option to use that as the padding?

The issue is that `vis` isn't telling wezterm what to set as the overall background color, only for cells.  We can't reasonably deduce how to change the default color from that, as it would have weird effects; for instance, if you printed out a line of text with a different background color you wouldn't want to change the whole terminal.   Scanning the the terminal cells to figure out a predominantly used color is also fraught with false positives as well as being expensive.  Even if we had a heuristic for setting this, there isn't a good signal for when to clear it afterwards.

Having `vis` use `OSC 11` as above is the most definitive way to express what background color should be used!

**Comment by erf** [comment]
I see! Will try to figure out how to do that on `vis`
