### ISSUE TITLE
terminal sometimes hang for a split second when pressing tab to complete folder name

### ISSUE THREAD

**Issue by erf** [wez/wezterm#304]
## Describe the bug

I want to do a `cd projects` and i type `cd proj`and then press TAB to complete the folder name. The first time i do this after opening wezterm, it hangs for half a second. It's a bit annonying. Second time i do this it completes the name at once.

## Environment (please complete the following information):

 - OS: macOS
 - Version: 20200909-002054-4c9af461-210-gb0fdd15d

## To Reproduce

1. Open wezterm
2. Start typing some foldername then press TAB to complete it
3. Notice a slight delay

## Configuration

No config

## Expected behavior

I would expect the TAB key to complete the folder name at once.

**Comment by bew** [comment]
This seems like the shell is hanging on first completion, could you check if this happens in another terminal?

**Comment by erf** [comment]
@bew it does not happen in `iTerm2` or `Terminal`

**Comment by wez** [comment]
This may also be due to macOS checking whether an application is allowed to access the filesystem.
For example, I've noticed that right after I install a new version of wezterm and tab complete my Downloads folder, macOS pops up a prompt asking if wezterm should have access to that folder, even though it is the shell and not wezterm that is trying to access that location.

**Comment by erf** [comment]
I gave it "Full Disk Access" now, but there is still some delay.

**Comment by erf** [comment]
BTW this happens if i try to complete a regular file as well, but it only seem to happen the first time i press TAB, after i open Wezterm.

**Comment by erf** [comment]
This seem to work fine now on latest on my M1 macbook, so i'll close this now
