### ISSUE TITLE
Probably invalid emoji render

### ISSUE THREAD

**Issue by Tony-Sol** [wez/wezterm#3043]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I have two emoji  in my `PROMPT` env (zsh) - \U+2714 and \U+2718

\U+2714 is rendered incorrectly until \U+2718 appears and after that, it looks fine in every tmux pane/window

```bash
~ ✔ $ wezterm ls-fonts --codepoints=2714
LeftToRight
 0 ✔    \u{2714}     x_adv=9.754098360655737 cells=1  glyph=152  wezterm.font("Noto Color Emoji", {weight="Regular", stretch="Normal", style="Normal"})
                                      <built-in>, BuiltIn
~ ✔ $ wezterm ls-fonts --codepoints=2718
LeftToRight
 0 ✘    \u{2718}     x_adv=7  cells=1  glyph=uni2718,2661 wezterm.font("Menlo", {weight="Regular", stretch="Normal", style="Normal"})
                                      /System/Library/Fonts/Menlo.ttc, CoreText
~ ✔ $
```
Record: 

https://user-images.githubusercontent.com/33671815/216057630-d3879653-d5b5-4353-b95e-f9fd93d4950f.mp4

According to https://emojipedia.org/check-mark/, it looks like "Noto Color Emoji" version used instead of "Apple" one

### Configuration

My wezterm configs:
https://github.com/Tony-Sol/.config/blob/master/wezterm/wezterm.lua
My PROMPT:
https://github.com/Tony-Sol/.config/blob/master/zsh/.zshrc#L3

### Expected Behavior

\U+2714 renders correctly as \U+2718

**Comment by wez** [comment]
The Menlo font is added to the implicit fallback list in cases where a glyph is not found in the fallback list specified by your config but is found in the Menlo font on macOS. When that happens, Menlo ends up taking precedence over the implicit Noto emoji font from the fallback.

There's a longer discussion about this sort of thing in:
* https://github.com/wez/wezterm/issues/849

The resolution for this class of issue is to use `wezterm.font_with_fallback` to explicitly list the fonts you want to use, rather than leaving it up to the fallback processing. wezterm can run a little faster when you do that.

**Comment by Tony-Sol** [comment]
Yep, that's work with these changes https://github.com/Tony-Sol/.config/commit/693aceda405e0941b0668aba191982f6226a01a8
