### ISSUE TITLE
font kerning / rendering sometimes breaks

### ISSUE THREAD

**Issue by dead10ck** [wez/wezterm#3052]
Reopening #1931 since it is not resolved.

### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220408-101518-b908e2dd AppImage

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I've noticed recently that sometimes the font rendering will suddenly get messed up, misaligning characters inside their boxes. For example, this is with Pragmata Pro, and how the font should look:

![Wezterm-good](https://user-images.githubusercontent.com/846275/165795189-e4ed2f42-f6ad-4b68-96f6-4d02af842fed.png) 

And seemingly at random times, it will suddenly look like this:

![wezterm bad](https://user-images.githubusercontent.com/846275/165795264-0b4f6a1f-0d02-4936-9fba-1bf8bd9b9448.png)

It seems as if the glyphs lose their correct position somehow. I'm not a font expert, but I'm not sure if this might have something to do with kerning?

To add to the strangeness, it seems to be isolated to a specific window and/or tmux attachment. If I open a new window, the issue is not present. In the example above, when I have a window doing this with the fonts, if I detach from tmux, the font renders fine again. So I thought maybe somehow this was a tmux issue. But if I attach to the same session in a different window, it doesn't have the problem. Other terminals like Alacritty and Gnome Terminal don't have this problem.

### To Reproduce

Hard to say, since it seems to happen randomly.

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font("monospace"),
  font_size = 17.0,
  initial_cols = 120,
  initial_rows = 48,
  enable_tab_bar = false,
  enable_wayland = true,

  -- Solarized Dark Higher Contrast Modified
  colors = {
    foreground = "#9cc2c3",
    background = "#002b36",
    cursor_bg = "#9cc2c3",
    cursor_border = "#9cc2c3",
    cursor_fg = "#002831",
    selection_bg = "#003748",
    selection_fg = "#7a8f8e",
    
    ansi = {"#002831","#d11c24","#6cbe6c","#a57706","#2176c7","#c61c6f","#259286","#eae3cb"},
    brights = {"#006488","#f5163b","#51ef84","#b27e28","#178ec8","#e24d8e","#00b39e","#fcf4dc"},
  }
}
```

### Logs

```
10:20:18.541 ERROR wezterm_gui::termwindow > PaneOutput: wanted mux_window_id=1 from mux, but was not found, cancel mux subscription
11:22:32.164 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 2
11:22:32.164 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 2
11:22:32.164 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 2
11:22:32.164 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 2
11:49:42.892 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 2
11:49:42.892 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 2
11:49:42.892 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 2
11:49:42.892 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 2
11:57:43.023 WARN wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
11:57:43.023 WARN wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(7727))
11:58:06.370 WARN wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
11:58:06.382 WARN wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(7727))
11:58:06.383 WARN wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(7727))
12:01:51.558 ERROR window::os::wayland::copy_and_paste > Offer dnd_action None
12:01:51.559 ERROR window::os::wayland::copy_and_paste > Offer source_actions Copy | Move | Ask
12:02:11.716 ERROR window::os::wayland::copy_and_paste > Offer dnd_action None
12:02:11.716 ERROR window::os::wayland::copy_and_paste > Offer source_actions Copy | Move | Ask
```

**Comment by Neob91** [comment]
<img width="146" alt="Screenshot 2023-06-27 at 23 17 35" src="https://github.com/wez/wezterm/assets/6197476/3454394f-ba1f-4dfe-8440-bd951a1416e2">
<img width="144" alt="Screenshot 2023-06-27 at 23 18 21" src="https://github.com/wez/wezterm/assets/6197476/499812df-fabc-4e4f-a924-8d23b9f76ffa">

I'm seeing similar misalignment issues when highlighting brackets in vim

**Comment by dead10ck** [comment]
For what it's worth, I think I've noticed it happen more often with ligatures. I think it may be triggered by the transitions from two glyphs into one and back.

**Comment by wez** [comment]
@dead10ck asked for some pointers on how to dig into this, so here's the gist of it how the rasterization works.

Wezterm models the terminal display as a vector of [Line](https://docs.rs/termwiz/latest/termwiz/surface/struct.Line.html) objects.
A `Line` is comprised of a vector of [Cell](https://docs.rs/termwiz/latest/termwiz/cell/struct.Cell.html) that specify which unicode grapheme is present at that position on the screen.

When the display is rendered, the goal is transform that into glyphs and position them on screen.

The process for this is complex and has several stages:

1. The `Line` is transformed into a vector of [CellCluster](https://docs.rs/termwiz/latest/termwiz/cellcluster/struct.CellCluster.html) based on the applicable BIDI information and runs of cells with the same rendering attributes (eg: bold, italic, colors), so that we have a list of the set of graphemes with the same attributes and presentation in each cluster.
2. Each cluster then needs to be *shaped*.  Shaping is an iterative, multi-pass process that walks through the list of fonts configured for the text style (by the `font_rules` config and the `font` config option).  Starting with the first font in the list, we ask harfbuzz to shape the cluster, and it produces a list of sub-clusters. If harfbuzz cannot resolve a glyph in a cluster, we try the next font in the fallback list and repeat until we either arrive at a fully shaped CellCluster, or have to accept that there are missing glyphs in a sub-cluster.  Shaping produces a list of positioning offsets and corresponding font and glyph ids, so that rendering knows what to put where.
3. Since shaping can be rather expensive, the computed shaping information is cached by associating it as *appdata* in the `Line` (https://docs.rs/termwiz/latest/termwiz/surface/struct.Line.html#method.set_appdata).
4. To render this, we need to take the shaping data, rasterize the glyphs and place them on the screen. Rasterization is the process of taking the font data and producing a bitmap. When processing curves from scalable fonts, there is a process known as *hinting* which adjusts the positioning of vertical and horizontal strokes so that they fit "inside" pixels rather than fall "between" pixels. The default settings in wezterm have hinting enabled, but I'm increasingly of the belief that it should be disabled by default, especially for users that have some kind of system level display scaling for their hidpi screens.
5. Since rasterization can be expensive, the results are cached in a *texture atlas*, which is essentially a single bitmap that acts as a dynamically curated *sprite sheet*.  The texture atlas is a limited resource: we can only have a single texture to hold all of the glyphs in a given window, and the graphics card has a limit on the maximum size of a texture.  wezterm uses a fairly simple algorithm to manage the texture atlas: it allocates enough room for the glyph bitmap, plus a couple of pixels of spacing around the edges.  The padding is added because the GPU will interpolate and map the texture, and if you have glyphs too close to each other, you will start to see bits of those neighboring glyphs in some circumstances. https://github.com/wez/wezterm/blob/6a58a5ce94f186884ec70a60b5afbd728521b1c5/window/src/bitmaps/atlas.rs#L62-L67
6. Since rendering overall is expensive, we also have a cache for the generated texture *quads* that we would send to the GPU

So where to look to figure out this issue?

* Easiest thing to start with is to try turning off hinting: `config.freetype_load_flags = 'NO_HINTING'` and see if that fixes things.
* The strange glyph positioning reported in https://github.com/wez/wezterm/issues/3052#issuecomment-1610234145 seems like a cache invalidation issue, where some or all of the layers of cache are inconsistent. Could be the quad cache, or the texture atlas and the Line `appdata` are out of sync with each other.
* A place to look for cache invalidation around the texture atlas is around the handling of `OutOfTextureSpace`, which is an error result that is bubbled up whenever the atlas gets filled up, and also look at the `recreate_texture_atlas` method and places it is called from.

The glyphcache file has a lot of the relevant logic, and is most likely related to this issue:
https://github.com/wez/wezterm/blob/6a58a5ce94f186884ec70a60b5afbd728521b1c5/wezterm-gui/src/glyphcache.rs#L662-L664

shapcache is also relevant, but I think it is less likely to be related to this issue, aside from there being a cache invalidation issue:
https://github.com/wez/wezterm/blob/6a58a5ce94f186884ec70a60b5afbd728521b1c5/wezterm-gui/src/shapecache.rs

The logic that drives this stuff starts around here, where we try to resolve cache shaping info on a line:
https://github.com/wez/wezterm/blob/6a58a5ce94f186884ec70a60b5afbd728521b1c5/wezterm-gui/src/termwindow/render/pane.rs#L424

then here to see if we can use that to find cached quads
https://github.com/wez/wezterm/blob/6a58a5ce94f186884ec70a60b5afbd728521b1c5/wezterm-gui/src/termwindow/render/pane.rs#L446

this logic is where we start to figure out how to render a Line:
https://github.com/wez/wezterm/blob/6a58a5ce94f186884ec70a60b5afbd728521b1c5/wezterm-gui/src/termwindow/render/pane.rs#L491

which leads to this like to try to reuse cache shaping information:
https://github.com/wez/wezterm/blob/6a58a5ce94f186884ec70a60b5afbd728521b1c5/wezterm-gui/src/termwindow/render/screen_line.rs#L118

here where we perform shaping when there is no cache:
https://github.com/wez/wezterm/blob/6a58a5ce94f186884ec70a60b5afbd728521b1c5/wezterm-gui/src/termwindow/render/screen_line.rs#L154

If you can reliably reproduce this issue on demand, then the process I would suggest would be to force one of the cache lookups to act as a cache miss unconditionally and see if the problem stops.  If not, restore the logic and force one of the others to miss until you find which one is the most significant to the issue, then drill down from there.  Some of these things have config options, like `line_quad_cache_size` that you might be able to set really low or to 0 without having to recompile. Look for `cache_size` in `config/src/config.rs` to get a likely list of those.

**Comment by dead10ck** [comment]
Thanks for the very detailed hints! Really appreciate it. I'll use this comment to do my investigations when I get some time.

So far even after all this time, I've not been able to figure out something I can do from the terminal to reproduce the issue, so it sounds like maybe the first step I can try is to see what I can do at the terminal, or add some ability, to cause thrashing in these caches.

**Comment by dead10ck** [comment]
So actually, I tried using kitty for a few days for a sanity check, and it turns out that this problem actually happens in kitty too. So I'm no longer convinced this is a wezterm bug.
