### ISSUE TITLE
[Feature Request] Allow to add padding to tab_bar when not using fancy tab bar

### ISSUE THREAD

**Issue by protiumx** [wez/wezterm#3077]
**Is your feature request related to a problem? Please describe.**
When setting `use_fancy_tab_bar = false` the tab bar size gets reduced to its content.
I'd love to be able to add top/bottom padding.

**Describe the solution you'd like**
Expose a config `tab_bar_padding` similar to windows padding https://wezfurlong.org/wezterm/config/lua/config/window_padding.html

**Describe alternatives you've considered**
Window padding does add padding to the are bellow the tab bar and not within.

**Additional context**
I recently configured my term to use opacity and wanted to configure the padding since when `use_fancy_tab_bar` is enabled, the colors don't affect it. Alternatively it would be better if the fancy tab bar can use rgba colors

**Comment by wez** [comment]
The retro (non-fancy) tab bar is implemented as cells within the main terminal display and cannot have its padding adjusted.
The fancy tab bar is more configurable and you should use that for this sort of thing. If you have an issue with the fancy tab bar, please file a new issue describing in detail what that issue is.
