### ISSUE TITLE
Weird issue with Unicode combining characters

### ISSUE THREAD

**Issue by pragma-** [wez/wezterm#3093]
### What Operating System(s) are you seeing this problem on?

Windows, Linux X11

### WezTerm version

wezterm 20230210-152445-66ec3f6e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

There seems to be some weird issue with Unicode combining characters. When I issue the command `echo a$'\u301\u302'` in my shell, I expected to see `á̂` as the output, but instead see `aá̂`. Interestingly, when I cycle tmux windows back and forth, the output fixes itself to the expected `á̂`. Additionally, when I resize the tmux window the `á̂` splits apart again into `aá̂`.

Additional detail: `echo -n a && sleep 0.1 && echo -n $'\u301'` seems to reliably lose the combining character. Perhaps related to buffering?

### To Reproduce

Note, these steps aren't 100% guaranteed to reproduce the issue. I'm not sure what it depends on. Sometimes the characters combine correctly as `á̂`  but then split apart into `aá̂` when I resize the tmux window and then recombine back into `á̂` once again when I cycle tmux windows to force a redraw(?). The `^L` key chord that refreshes the display does not recombine the characters; cycling tmux windows does recombine the characters.

* Start `wezterm-gui` on Windows
* Ssh into Linux machine
* Start tmux
* Issue the command `echo a$'\u301\u302'`
* Output is rendered as `aá̂` but should be `á̂`
* Create new tmux window (`<prefix> c`)
* Switch back to original tmux window (`<prefix> p`)
* Output has correctly combined into `á̂`

Alternative way to reproduce:

* do the same steps as above
* now resize the terminal window
* the `á̂` splits apart into `aá̂`
* now cycle between tmux windows
* the `aá̂` combines back into `á̂`

Alternative way to reproduce:

* `echo -n a && sleep 0.1 && echo -n $'\u301'`

When the sleep is `0` or omitted, the characters combine properly. When the sleep is `0.1` or long enough, the combining character is lost completely.

### Configuration

no config

### Expected Behavior

Unicode combining characters are expected to render correctly as one cell.

**Comment by pragma-** [comment]
Resizing the terminal window does seem to 100% reliably split the characters apart. Then cycle tmux windows 100% reliably combines them back together.

**Comment by pragma-** [comment]
It's been brought to my attention that the combining characters issue occurs even on GitHub for some people.

I see:

![](https://0x0.st/HrNd.png)

But someone else sees:

![](https://0x0.st/HrNn.png)

Very strange.

**Comment by pragma-** [comment]
Apparently if they set their GitHub font to be sans-serf instead of monospace, the characters combine properly. Meanwhile, the issue unfortunately persists in wezterm.

**Comment by pragma-** [comment]
Possibly related to https://github.com/harfbuzz/harfbuzz/discussions/2790#discussioncomment-252552 ?

**Comment by pragma-** [comment]
I'm not entirely sure if it's a font bug as suggested by the above harfbuzz comment because I experience this bug with Microsoft's Consolas font as well.

**Comment by wez** [comment]
This sort of thing is influenced by a number of factors:

* The level of unicode conformance of each terminal emulation layer. Note that tmux and conpty (the windows pty infrastructure) are both additional layers that reinterpret and re-emit data, and I would recommend that you try to reproduce your issue without them to see if the issue is caused by a combination of software.
* When working in eg: a line editor, the level of unicode conformance of the line editor itself
* Depending on the sequence, whether BIDI processing is enabled
* The robustness of the selected font, which ultimately defines how codepoint sequences are mapped to glyphs, which is the source of the data used by the harfbuzz font shaper.

The sequence you shared appears to be in a non-canonical unicode form which can be problematic for combining sequences.

Wezterm has an option to force output to be normalized to Normalization Form C: https://wezfurlong.org/wezterm/config/lua/config/normalize_output_to_unicode_nfc.html and you might find that it helps, but you might find that it causes other problems.
