### ISSUE TITLE
Command-M doesn't minimize the window on macOS

### ISSUE THREAD

**Issue by chadaustin** [wez/wezterm#32]
Instead of minimizing the window, it types an m into the terminal.

**Comment by wez** [comment]
This is something that we'll get for free as part of https://github.com/wez/wezterm/pull/26 but that introduces a few problems as it stands today, because it masks a number of important key bindings.

I'm totally down with implementing this without using the apple menu stuff though, so we may resolve this more quickly in a different way.

**Comment by wez** [comment]
I've unblocked this in a slightly roundabout way; you can add this to your config file to get that behavior:

```
[[keys]]
key = "m"
mods = "CMD"
action = "Hide"
```

I personally disable this particular action in eg: iTerm because I'd mapped it to maximize-vertically in X11 a long time ago, so it does literally the opposite of what I want!

However, it makes sense for this to be a default behavior on macOS; I'll make a pass over the defaults.
