### ISSUE TITLE
Add a WezTerm REPL

### ISSUE THREAD

**Issue by alexherbo2** [wez/wezterm#324]
Similar to the [kitty] REPL.

``` sh
kitty @
```

[kitty]: https://sw.kovidgoyal.net/kitty/

**Comment by wez** [comment]
Can you expand on specifically what functions you think this should have?
Referencing just `kitty @` doesn't mean anything to me as I don't use kitty.

When you say REPL do you mean that the existing `wezterm cli` subcommand should have a REPL mode?

As a slight aside: the new issue templates ask for a lot of information up front because it saves everyone time later.  I've noticed that the issues that you've filed are all incredibly terse; they don't really help me understand what is on your mind and that makes it much more expensive to tease out the details with interactive asynchronous dialog in the issue.  I do appreciate all feedback, but if I have to work hard to get it, it subtracts both my available time and the amount of fun I have with this project.  So please: keep filing issues, but please take a few extra moments to answer the questions in the templates and expand on what you're seeing and provide as much context as you can.  It will save time and increase the quality of the end result!

**Comment by EpocSquadron** [comment]
@wez allow me to provide some context. @alexherbo2 is a prolific contributor and plugin writer for an editor called [kakoune](https://github.com/mawww/kakoune) , which is a bit like sam meets sublime text meets vim. Recently wezterm was [shared](https://discuss.kakoune.com/t/terminal-life-lust-for-life/778/47?u=epocsquadron) in it's community discourse and generated some excitement as many people wish to get away from tmux while retaining the session support, since kakoune does not implement it's own windowing but rather integrates with multiplexers and windowing systems externally.

One of kakoune's features is being able to spawn new windows (or panes or tabs) from it's prompt, which are in some way connected to the editor instance. More specifically, it [defines a repl-send-text command](https://github.com/mawww/kakoune/blob/master/rc/windowing/repl/kitty.kak#L24) which will paste editor selections in the window it created. Alex also created a plugin which expand on this capability by spawning terminal windows with added commands and environment variables to ease interaction between shells and editor instances. For instance, one might open the editor, spawn a connected terminal in a split pane, run some commands that pipe into the editor window without copying and pasting a lot.

Honestly I think the multiplexing domains implement all that's needed here, but I'm not 100% clear on that as I am not developing these integrations. Hopefully @alexherbo2 can pipe in with what's missing or misunderstood.

**Comment by wez** [comment]
I'm not clear on exactly what is being asked here.  I think this is asking for more `wezterm cli` subcommands to interact with the mux server rather than asking for a literal REPL.  I'm going to close this out as it isn't very actionable in its current state.  If you have specific examples of functionality that you'd like to see, please open issue(s) for those.
