### ISSUE TITLE
Allow regex groups in quick_select_patterns

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#3247]
**Is your feature request related to a problem? Please describe.**
I'd like to open file paths that appear in the terminal with a keybind, without a mouse. QuickSelect is a great option for identifying various patterns and allowing you to do custom actions with the selection (while the selection is also conveniently one extra button). However, it seems that [quick_select_patterns](https://wezfurlong.org/wezterm/config/lua/config/quick_select_patterns.html#quick_select_patterns) don't support any advanced regex things like groups, so if I wanted to have some negative lookahead/lookbehind that excludes that path displayed in my prompt (e.g., based on the prompt ending char), I'm out of luck

**Describe the solution you'd like**
Given the complexity of differentiating paths from regular text (there is not 100% clear solution since paths can have any char, but with sufficient number of filter we might get close enough) it would be great if I could have more advanced filters to be used in the `patterns` field, maybe something similar to `hyperlink_rules` where you have a `regex` with various rules and `format` that selects the groups you need to actually match

**Describe alternatives you've considered**
Manual selection is always the safe fallback :)

**Additional context**
None

**Comment by wez** [comment]
FWIW, the rust regex crate doesn't support look around assertions

**Comment by eugenesvk** [comment]
Oh, I see, and is https://github.com/fancy-regex/fancy-regex  that supports look arounds not ready yet to use in your great terminal?

By the way, another way to get around this specific example would be to exclude semantic zones from the text that is regex-searched (so prompt would never match), that would be a good combination of features to make dumb text a bit smarter?

**Comment by wez** [comment]
I hadn't seen fancy-regex. Seems worth a look.
Factoring semantic zone constraints into this may increase the CPU cost of matching, but I'll consider it when I next sit down to look at this.

**Comment by wez** [comment]
I switched to using fancy-regex and did a simple test with a negative look behind assertion to satisfy myself that it works.
Doing more than that here is problematic: for the sake of performance, wezterm builds a big alternation from all of the quick_select_patterns so that there is a single regex to be compiled and evaluated.

It's not trivial to reverse engineer from the resultant match which pattern term matched in order to apply something equivalent to the hyperlink_rules format option, which means that each pattern would need to be compiled and matched independently.
It feels both complex and slow to get that to work.

That said: I think the look around assertions are probably sufficient and we needn't go further than that.
Please give it a try and let me know how you get on!
