### ISSUE TITLE
[flatpak] launch_menu behaves different on wezterm cli command

### ISSUE THREAD

**Issue by jtourlamain** [wez/wezterm#3252]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Wayland/Gnome

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm using the flatpak version of wezterm. I'm using zsh as default shell. Opening a bash shell in a horizontal pane works when I execute 
`flatpak run org.wezfurlong.wezterm cli split-pane --horizontal -- /usr/bin/bash -l`

I suppose that adding the args in launch_menu should execute the action in the same way
```lua
 launch_menu = {
    {
      label = 'split bash',
      args = { 'flatpak', 'run', 'org.wezfurlong.wezterm', 'cli', 'split-pane', '--horizontal', '--', '/usr/bin/bash' },
    },
}
```
Instead it opens a bash shell in a new tab.

A key binding also works:
```lua
keys = {
 {key = "b", mods = "ALT", action = wezterm.action.SplitPane { direction = 'Right', command = { args = {'/usr/bin/bash' }}}},
},
```

### To Reproduce

Add the following launch_menu settting
```lua
launch_menu = {
    {
      label = 'split bash',
      args = { 'flatpak', 'run', 'org.wezfurlong.wezterm', 'cli', 'split-pane', '--horizontal', '--', '/usr/bin/bash' },
    },
}
```

### Configuration

```lua
launch_menu = {
    {
      label = 'split bash',
      args = { 'flatpak', 'run', 'org.wezfurlong.wezterm', 'cli', 'split-pane', '--horizontal', '--', '/usr/bin/bash' },
    },
}
```

**Comment by wez** [comment]
> Instead it opens a bash shell in a new tab.

In the same window, or is it a different window?

The flatpak is an unusual environment: flatpak runs the gui in a sandbox, and wezterm has to do a bunch of work to ask the system to run your launched programs outside the sandbox:

https://github.com/wez/wezterm/blob/b113cc909ea80552dac8ca7617a1154b3e58eea9/mux/src/domain.rs#L338-L391

I think the differences in the environment caused by the flatpak may be sufficient to screw with the mechanism used to locate the right instance; see:
* https://wezfurlong.org/wezterm/cli/cli/index.html

Another thing that may complicate this is that your shell is spawned with the environment populated with WEZTERM_UNIX_SOCKET and WEZTERM_PANE so that the cli will be able to locate things correctly

However, WEZTERM_PANE is *not* set for things launched by the launcher menu, because those programs are not spawned into any terminal managed by wezterm, and don't have a pane.

If you need the gui to perform splits directly then the best supported option is to use a key assignment.

If you like the convenience of the launcher menu, then you may want to look the [Command Palette](https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivateCommandPalette.html) which is pre-filled from a number of built-in actions, but will also pull in your key assignments and make those available there.  

For example, if you type `bash` in the command palette, the split action key assignment you shared above will be selected, with the caveat that the text that is displayed doesn't show that it is bash; that's a separate bug.

**Comment by wez** [comment]
I just pushed a commit that should fix the display of your key assignments in the palette.

```lua
    {
      key = "b",
      mods = "ALT",
      action = wezterm.action.SplitPane {
        direction = 'Right',
        command = {
          label = 'Bash Right', -- this label will be shown
          args = {'/usr/bin/bash' } -- falling back to the args if no label is set
        }
      }
    }
```

**Comment by jtourlamain** [comment]
This is great news and works! Thank you for the quick update.
