### ISSUE TITLE
pane name [iterm2 badge]

### ISSUE THREAD

**Issue by yanickxia** [wez/wezterm#3312]
**Describe the solution you'd like**
if tab contains multi pane, maybe want add name for there pane

<img width="400" alt="image" src="https://user-images.githubusercontent.com/6848593/226598351-9f2d8206-7d06-4001-aefa-a45d5ff5d8b5.png">

today, switch pane the tab name will change, it's cool

if impl iterm2 badge better
![image](https://user-images.githubusercontent.com/6848593/226597804-c1f84a50-5657-4b5e-b224-5e02f367270c.png)

**Comment by bew** [comment]
You don't want this anymore?

**Comment by wez** [comment]
Implementation wise, I think this would be done similarly to https://wezfurlong.org/wezterm/config/lua/window/set_right_status.html, but scoped to the pane instead of the window.
https://wezfurlong.org/wezterm/config/lua/window-events/update-status.html could be used to determine when to call/update the pane status.

The pane status would always render over the top right of the pane, and there would be some config to set padding and margins, as well as the font and font size.

However, there is some conceptual overlap with:
* https://github.com/wez/wezterm/issues/1970

so it's worth also thinking a bit about that before sitting down to code anything around this

**Comment by bew** [comment]
> The pane status would always render over the top right of the pane

I'd have though to have the pane status/name be kind of _behind_ the text, as some background info #user-specific-needs...

**Comment by wez** [comment]
> _behind_ the text,

Because the pane renderer produces opaque renderings (by default, unless the user has taken care to render with opacity), that would require interleaving the display logic for the pane renderer with the status renderer to insert the status over the top of the terminal background painting stage, which would make both of those things more complex than they already are.

It is much much simpler to render the status over the top of the pane after the pane is drawn.

**Comment by woodgear** [comment]
agree. standalone panel title would be great.
When there is more than one panel, a panel title is a must, I often have 5-6 panes in a tmux window, and if I don't have a name for them, it's easy to forget what each panel does when I cut back from another tmux session.
the current workload ”show pane name in tabbar“ has a  flaws，you must click one pane，then could know his name.

**Comment by xiangpeng2008** [comment]
I agree with @woodgear , it would be great if we could have a shortcut to show all pane id just on top of each panel, and press any key to make them disappear

**Comment by xiangpeng2008** [comment]
it would also work if we could just add an option of setting 

show_pane_titles=true

while we have already 
show_pane_ids=true
https://wezfurlong.org/wezterm/config/lua/keyassignment/PaneSelect.html
it should be straight forward to add this feature.

**Comment by xiangpeng2008** [comment]
also could we add PaneSelect to wezterm cli ? I want to call it from vim script.

**Comment by Jeansen** [comment]
Any update on this? I'd also very much like to see this feature implemented.
