### ISSUE TITLE
Tab navigation gets confused after move-pane-to-new-tab

### ISSUE THREAD

**Issue by junkblocker** [wez/wezterm#3373]
I am seeing weird navigation behavior if I randomly create splits and detach them using this - sometimes splits don't get created at all or tabs get created instead and tab navigation by number doesn't work correctly jumping to the wrong tab number.

_Originally posted by @junkblocker in https://github.com/wez/wezterm/issues/3219#issuecomment-1484110796_

**Comment by junkblocker** [comment]
wezterm 20230325-203323-59503034   on Fedora 37 / X11

**Comment by wez** [comment]
I'm going to close this because there's not enough information for me to use to recreate this issue. Please work out a minimal set of repro steps and then file a new issue using:
https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&template=bug.yml

and be sure to include all the information about your config, system and repro steps.

**Comment by junkblocker** [comment]
The 'Reference in new issue' option should be removed from the '...' menu on the right side of comments as it's always going to waste people's time as it doesn't lead to the bug template and will get closed like this.
