### ISSUE TITLE
Can't install wezterm nightly using brew instructions

### ISSUE THREAD

**Issue by craigmac** [wez/wezterm#3399]
Probably related to changes in https://github.com/wez/wezterm/pull/3131 ? I'm using brew version `4.0.10-62-g69b0243` which has introduced some [changes surrounding casks (among other things)](https://brew.sh/2023/02/16/homebrew-4.0.0/). 

The currently listed `brew install --cask wezterm-nightly` from the wezterm site returns:

```text
Warning: Cask 'wezterm-nightly' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
Error: No casks found for wezterm-nightly.
```

`brew install --cask wezterm` works, but that's not nightly. Any ideas?

**Comment by craigmac** [comment]
The old code pre #3131 changes works:

```text
~/.config % brew install --cask wez/wezterm/wezterm-nightly
==> Tapping wez/wezterm
Cloning into '/usr/local/Homebrew/Library/Taps/wez/homebrew-wezterm'...
remote: Enumerating objects: 184, done.
remote: Counting objects: 100% (184/184), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 184 (delta 47), reused 156 (delta 38), pack-reused 0
Receiving objects: 100% (184/184), 26.22 KiB | 3.28 MiB/s, done.
Resolving deltas: 100% (47/47), done.
Tapped 2 casks and 1 formula (16 files, 42.4KB).
==> Caveats
Cask wezterm-nightly related executables like 'wezterm', 'wezterm-gui',
'wezterm-mux-server', are linked into
  /usr/local/bin/    for x86 Mac,
  /opt/homebrew/bin/ for M1 Mac.

Removal of them is ensured by 'brew uninstall --cask wezterm-nightly'.

Since there's no version info included in the download URL of the nightly
build, NO update will be notified for 'wezterm-nightly' by Homebrew. (Not a
problem for non-nightly, regular released 'wezterm'.) To get the nightly
update, just run
'brew upgrade --cask wezterm-nightly --no-quarantine --greedy-latest'.
```

**Comment by plush-mesh** [comment]
Still works for me. However, I found the reason.
I missed the point that `wezterm-nightly` is in the `homebrew/cask-versions` tap when I introduced the changes in the PR (https://formulae.brew.sh/cask/wezterm#default / https://github.com/Homebrew/homebrew-cask/blob/66f80a142f4935d6b2b9f662aa1c79b02a031bfa/Casks/wezterm.rb points to `homebrew/cask-versions/wezterm-nightly` as a conflicting version, so https://github.com/Homebrew/homebrew-cask-versions/commits/master/Casks/wezterm-nightly.rb). I have `homebrew/cask-versions` added to my taps since long ago, sorry for that mistake.
It needs to be clarified in the README to use `homebrew/cask-versions`.
