### ISSUE TITLE
Scale down icons from icon fonts (& emojis?) when not followed by an empty space

### ISSUE THREAD

**Issue by bew** [wez/wezterm#342]
**Is your feature request related to a problem? Please describe.**
When using a icons from an icon font like Font Awesome, when you have an icon immediately followed by some text, the icon overlaps with the text.

Example:
![wez-stable](https://user-images.githubusercontent.com/9730330/100021509-e2bf2000-2de1-11eb-96f4-bba877870499.png)

Also, currently emojis take 2 spaces, is it sensible to do the same and scale down? (NOTE: I don't use emojis often)

**Describe the solution you'd like**
When the icon is not immediately followed by an empty space (a space or the end of the line), scale it to fit in a normal cell.

Here I'm using an example from alacritty, which does **not** do this, but using bold vs non bold text I can show you what I mean.
(the icon is not the same in the example, alacritty is probably using different fonts here)

![scaled-down-star](https://user-images.githubusercontent.com/9730330/100022220-13538980-2de3-11eb-8b9e-d831ccc879fb.png)

**Comment by wez** [comment]
There are two aspects to this issue:
* Font Awesome wasn't being scaled correctly
* presentation width of symbols

I've fixed the first of these in 98f289f

The second is fraught with PITA :-p
Different versions of unicode have ambiguous/varying definitions of the widths of certain characters.  For the most part, emoji are defined as being 2 cells wide (note that the star character in your post isn't actually an emoji: it's a private use codepoint defined by the Font Awesome font, and has a width of 1 cell), but there are some older unicode characters that are defined as a single cell in width.  This can result in unexpected rendering glitches if for example the program you are running uses a different version of the width definitions than those of the terminal emulator.

wezterm tries to conform to whatever version of unicode is supported by the various unicode crates in the rust ecosystem.  If we were to introduce an option to affect the presentation width then it would be in terms of the unicode version rather than in terms of contextual heuristics like the placement of spaces after a glyph, which is a bit too much complexity, especially when coupled with opaque contextual heuristics that the font shaper may apply from the font itself!

**Comment by mborejdo** [comment]
I am wondering, if emoji-scaling could be configured. since eee40f my emojis are very small (as I am using a pretty small pixelfont). Probably a solution might be https://github.com/wez/wezterm/issues/346. I like my emojis bigger then the "reading" font.

**Comment by bew** [comment]
Note: There are some discussion going on Gitter:
https://gitter.im/wezterm/Lobby?at=5fbc615c771c185e0ec257a8 (and below)

**Comment by wez** [comment]
I looked into this a bit last night and added `allow_square_glyphs_to_overflow_width = "WhenFollowedBySpace"` as an option.

![heart-overflow](https://user-images.githubusercontent.com/117777/100137744-c4890c80-2e41-11eb-91a4-df40d54e7627.png)

**Comment by bew** [comment]
@wez you rock you know that? 🙏😊

**Comment by bew** [comment]
Let's close this then.
I didn't test for emojis (I ~ never use them), but the way it is implemented it should work right away I think @mborejdo !

**Comment by mborejdo** [comment]
thanks @wez. I am not sure if I am doing anything wrong, but for my emojis (starship prompt symbols), no setting (I tried allow_square_glyphs_to_overflow_width = "WhenFollowedBySpace", "Always" and "Never".) worked. All settings had no effect on these symbols. So I guess my problem still persists @bew . Wondering if I should open another issue.

**Comment by mborejdo** [comment]
Interestingly the emoji scaling does work, if I explicitly set 

```
dpi = 90.0,
```

within my config

**Comment by wez** [comment]
There's something a bit off with the logic around this.
My test scenario is:

1. Make the window about 90-100 cells wide
2. `grep England test-data/emoji-test.txt` -> that should produce a line that shows the English (rather than the UK) flag as a double-width glyph, then a single space before it shows `E5.0`.
3. Use CTRL-- to scale the font size down a couple of times.  When the glyph gets small enough, it is suddenly scaled to be a single cell in width and there are two spaces after the flag before the `E5.0`.

**Comment by mborejdo** [comment]
The latest changes (bbb9536, 0fa2edb1f42f049524ce40de195d1cde10afbba8) seem to fix the problem for me.

**Comment by kiyoon** [comment]
Am I the only one that still sees small emojis? I'm using the latest stable.

The cloud, railway, film emojis are smaller than others.  
![image](https://user-images.githubusercontent.com/12980409/214350101-b1cac393-2ab4-40bb-b6aa-46cfa60e4e74.png)

**Comment by wez** [comment]
@kiyoon please file a new issue; I can't track comments made on closed issues
