### ISSUE TITLE
Support native Apple M1 build

### ISSUE THREAD

**Issue by erf** [wez/wezterm#343]
**Is your feature request related to a problem? Please describe.**

The macOS version run fine now on an M1 MacBook (via Rosetta), but would be interesting to see how a native M1 build would perform.

**Describe the solution you'd like**

Prebuilt M1 version for download.

**Describe alternatives you've considered**

I could build from source, but the rust-up tool doesn't yet support M1, even though the compiler does. rust-up should support it in a couple of weeks according to [this](https://github.com/rust-lang/rustup/issues/2413)

**Comment by wez** [comment]
I have an M1 on order, and that will make this a bit easier to wrangle.
Assuming that the tools remain the same as around the ppc -> intel transition, making a universal binary will require building both intel and arm and then gluing them together and placing that in the `.app` install dir.

**Comment by wez** [comment]
I have wezterm building from source on M1.  It'll be a little bit before this gets integrated into CI; I'm thinking of gating this on the platform making it into stable rust to keep things a bit simpler.

To build it, follow the instructions at http://wezfurlong.org/wezterm/install/source.html 
When prompted by rustup, don't accept the default (which is to use stable aarch64-apple-darwin; that will fail because it isn't available in stable yet), instead, select `nightly-aarch64-apple-darwin` toolchain and make it the default toolchain.

**Comment by wez** [comment]
After building, you can run `./ci/deploy.sh` to produce the equivalent zip file to what would be produced by CI, in case you want to manually install the .app for convenience of launching.

**Comment by erf** [comment]
Great! I was able to build and run ok. Feels more responsive now.

#304 and #308 is gone in this build now for me on the M1. could still be a problem on the old Mac, but feel free to close them

**Comment by wez** [comment]
Note that nightly downloads are Universal binaries as of 42b95cd4134af898f43624426d1b39b39fa7fc74 a few days ago!

**Comment by erf** [comment]
Yes i noticed. Great work!
