### ISSUE TITLE
Splitting from an ssh domain into a DefaultDomain fails

### ISSUE THREAD

**Issue by joshuarubin** [wez/wezterm#3442]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

e28b3cec4ef30940a3bc2cb8ac6073dd993a6ab9

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When connected to an ssh domain and try to make a split into the DefaultDomain, it fails.

Notably, spawning new tabs seems to work fine.

### To Reproduce

The trigger is `win:perform_action(wezterm.action.SplitHorizontal({ domain = "DefaultDomain" }), pane)`

This is on MacOS and my home dir is in /Users not /home

Remote side, running linux, is d36ad7ca7f9054a9d2b49ffe8696c3e617623194
Local side on MacOs is e28b3cec4ef30940a3bc2cb8ac6073dd993a6ab9

### Configuration

		{
			mods = "SUPER|SHIFT",
			key = "Enter",
			action = wezterm.action_callback(function(win, pane)
				win:perform_action(wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }), pane)
			end),
		},

### Expected Behavior

Create a new pane in the DefaultDomain (in my case it's just local)

### Logs

```
22:13:19.082 WARN mux::domain > Directory "/home/<USERNAME>" is not readable and will not be used for the command we are spawning: No such file or directory (os error 2)
```

**Comment by joshuarubin** [comment]
If I set the cwd of the new pane to `/` then I don't get the directory warning, but it still fails.

**Comment by wez** [comment]
The warning should be resolved as of 8ddd0d986d8cd609966bee1ddaa8d8351a0fb4e7

> If I set the cwd of the new pane to `/` then I don't get the directory warning, but it still fails.

Do you mean that setting the cwd doesn't take effect?
What's the config for the SshDomain that you're connecting into?

If it is set to `multiplexing='None'` (the default `SSH:hostname` entries in the command palette and launcher are configured that way), then setting an initial working directory won't work unless `assume_shell = 'Posix'` is also configured.  That isn't set by default because there isn't a way for a client to know this based purely on the SSH protocol.

If the SshDomain is set to `multiplexing='WezTerm'` (the default for `SSHMUX:hostname` entries in the command palette and launcher), then the working directory should work just fine.

Can you share a bit more about how you're connecting and what else you're seeing?

https://wezfurlong.org/wezterm/config/lua/SshDomain.html has more information about SshDomains, but it could probably do with another pass to clarify behavior in light of recent changes to the default `ssh_domains` config.

**Comment by joshuarubin** [comment]
I do have `assume_shell = "Posix"`.

```
	ssh_backend = "LibSsh",
	ssh_domains = {
		{
			name = "jrubin",
			remote_address = "jrubin",
			username = "jrubin",
			assume_shell = "Posix",
		},
	},
```

When I say "it fails", I see the pane open briefly, or at least the tab resizes things as if it were to add the pane, but no pane is actually created.

**Comment by wez** [comment]
I'd suggest adding `exit_behavior = "Hold"` to your config; that will hold the pane open and give you a chance to see why it closed

**Comment by joshuarubin** [comment]
Updated both sides to the 8ddd0d986d8cd609966bee1ddaa8d8351a0fb4e7 and the issue no longer appears.

**Comment by wez** [comment]
Great, let's close this!
