### ISSUE TITLE
Unix domain connection not respecting `wezterm.gui.get_appearance` value

### ISSUE THREAD

**Issue by omar25h** [wez/wezterm#3453]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Nightly didn't work for me when I tried it.
I am using a dynamic current scheme via `wezterm.gui.get_appearance()`. When connecting to a unix domain via `	default_gui_startup_args = { "connect", "unix" }`, the background is always black regardless of the `color_scheme` value. When using a hardcoded color_scheme value, this one is working as expected.

### Configuration

```lua
local function scheme_for_appearance(appearance)
    if appearance:find("Dark") then
        return "GruvboxDark"
    else
        return "Gruvbox (Gogh)"
    end
end

return {
    // ...
    color_scheme = scheme_for_appearance(wezterm.gui.get_appearance()),
    unix_domains = { { name = 'unix' } }
    default_gui_startup_args = { "connect", "unix" },
}
```

### Expected Behavior

Color scheme is set based on appearance settings

**Comment by wez** [comment]
`wezterm.gui` is not available to the mux server, because it has no GUI, so your config won't load there.
https://wezfurlong.org/wezterm/config/lua/wezterm.gui/index.html mentions this, but it's not driven home on every page that mentions the `wezterm.gui` module.

Also, because it has no GUI, it has no concept of appearance and the appearance selection is meaningless there.
I recommend using the nightly build because the color scheme choice is now managed by the GUI client rather than the server.

You need to make your config safe to use in the mux:

```lua
local function get_appearance()
   if wezterm.gui then
      return wezterm.gui.get_appearance()
   end
   return "Dark"
end

local function scheme_for_appearance(appearance)
    if appearance:find("Dark") then
        return "GruvboxDark"
    else
        return "Gruvbox (Gogh)"
    end
end

return {
    color_scheme = scheme_for_appearance(get_appearance()),
    unix_domains = { { name = 'unix' } }
    default_gui_startup_args = { "connect", "unix" },
}
```

**Comment by omar25h** [comment]
Oh I see, this actually also explains why I couldn't get the nightly version to work. Got it to work with nightly, thanks @wez !

**Comment by wez** [comment]
I updated the example in the docs to help others avoid this same issue!
