### ISSUE TITLE
Question about versioning

### ISSUE THREAD

**Issue by kekePower** [wez/wezterm#3462]
Hello.

I'm a packager for Mageia Linux and was wondering if you're planning to release a version 1.0 sometime in the future?

When I look at the build log, I see the version is set to 0.1.0 at the moment and the released tarballs use a different format.

20230326 > 1.0 and this means that I'd have to set en Epoch in the spec file if a version 1.0 is ever released and the date-time-hash format is dropped.

My solution is to use version 0.1.0 and the release date as a sub/dev release instead of using the release date as the version:
wezterm-0.1.0-0.r20230326.1.mga9.x86_64.rpm

I'm asking you before I introduce this package to Mageia and to create the best possible package.

Thanks in advance.

**Comment by wez** [comment]
Thanks for looking at this!

https://github.com/wez/wezterm/blob/main/README-DISTRO-MAINTAINER.md#versioning has information about versioning for distributions.

There will never be a 1.0 version of wezterm; the date based version is unambiguous and clearly indicates the underlying source version, and rolling out a 1.0 in the future will just make things confusing.

Please ensure that the build process for your distribution either runs from the git repo or includes the `.tag` file from the official source tarball so that `wezterm --version` reports the official version number, as that is the source of the version number that users are directed to report when filing issues.
