### ISSUE TITLE
Mac OS X key issues

### ISSUE THREAD

**Issue by ahcm** [wez/wezterm#357]
Pressing Option + n should give "~", instead it produces no output.
Option + 9 should give }, instead tab menu appears.
It's th same for left and right Option.
Toggle of use_ime does not seem to have any effect.

 - OS: Mac OS X 11.0.1 (Intel)
 - Version: wezterm 20201101-103216-403d002d
 - German MacBook Air Keyboard

**Comment by wez** [comment]
I just pushed a commit that improves how this works; that'll be available in a nightly build within an hour or two of this comment being posted.  You'll need to set `use_ime=true` for it to work.

**Comment by ahcm** [comment]
That indeed improves the behaviour. Thanks!

**Comment by wez** [comment]
Great, let's close this then!

**Comment by aorith** [comment]
> I just pushed a commit that improves how this works; that'll be available in a nightly build within an hour or two of this comment being posted. You'll need to set `use_ime=true` for it to work.

Hey!

Sorry to re-open a closed issue, [b2be296](https://github.com/wez/wezterm/commit/b2be2963a1c0bd11bc4abb102e2e78e6f11ef26b) allows the use of dead keys but disables most of key repeat functionality as stated in the docs.
That's a pity overall and specially for vim users.

Would it be possible to implement something in the lines to the behavior of alacritty with the option `alt_send_esc` set to `false`?

**Comment by wez** [comment]
> Sorry about replying on a closed issue, [b2be296](https://github.com/wez/wezterm/commit/b2be2963a1c0bd11bc4abb102e2e78e6f11ef26b) allows the use of dead keys but disables most of key repeat functionality as stated in the docs.
> That's a pity overall and specially for vim users.

Nod; I would like to find a solution to this, but haven't had the time thus far.
 
> Would it be possible to implement something in the lines to the behavior of alacritty with the option `alt_send_esc` set to `false`?

Sorry if this sounds a bit strong but: there's not enough context here for me to understand what you are asking.
Please open a new issue; the template there has some guiding questions that help you phrase this sort of request in a way that contains more context.

In general, referencing alacritty is not helpful both because I do no use it, and because I don't really want to be running around copying other's work if I can avoid it, even if that work is also open source.

Please instead open a new issue and describe the problem scenario and how it occurs as well as your proposed solution (if you have one!).

**Comment by aorith** [comment]
> Nod; I would like to find a solution to this, but haven't had the time thus far.

Good news that it's on the backlog :)

> Sorry if this sounds a bit strong but: there's not enough context ...

You're right I can't take it for granted that you know every random terminal emulator nor want to copy their implementation (that's nice). I wish I could help with this but I just found the project 2 days ago and know nothing about Rust. Anyway keep up good work and sorry about the noise!
