### ISSUE TITLE
automatically adjust color scheme config doesn't work after nvim closed.

### ISSUE THREAD

**Issue by ch4m1gn0n** [wez/wezterm#3685]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230501-084619-d0e9a034

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I want to automatically adjust color scheme to the current appearance, and config like document says.

but the tab color_scheme will never change after nvim closed in current tab.

Newly opened tabs work fine.

### Configuration

```lua
  function scheme_for_appearance(appearance)
    if appearance:find 'Dark' then
      return "Papercolor Dark (Gogh)"
    else
      -- return "Ashes (light) (terminal.sexy)"
      -- return "AtomOneLight"
      -- return "Belafonte Day"
      return "ayu_light"
    end
  end

  wezterm.on('window-config-reloaded', function(window, pane)
    local overrides = window:get_config_overrides() or {}
    local appearance = window:get_appearance()
    local scheme = scheme_for_appearance(appearance)
    print("appearance: " .. appearance)
    print("scheme: " .. scheme)

    if overrides.color_scheme then
      print("color_scheme: " .. overrides.color_scheme)
    end
    if overrides.color_scheme ~= scheme then
      overrides.color_scheme = scheme
      window:set_config_overrides(overrides)
    end
  end)


  return {
    font = wezterm.font("Hack Nerd Font"),
    tab_bar_at_bottom = true,
    use_fancy_tab_bar = false,
    launch_menu = launch_menu,
    keys = keys,
  }
```

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps; eg: open and close `nvim` or whatever those steps might be (you didn't include them in the original report!)
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by ch4m1gn0n** [comment]
My operation:
run `wezterm record`
change system to dark mode and the terminal theme also changed.
change system to light mode and terminal theme changed again.
type `lvim` to start nvim, and `space q` to quit it.
change system to dark mode and the terminal windows changed but theme didn't.
change system to light mode.

**Comment by wez** [comment]
when you change the color palette via escape sequences, you essentially fork it from the colors you set in the config file until you tell the terminal to reset the color palette back to the default.  This is so that an application's choice of colors remains intact even if you change the config at runtime.

Looking at your recording, you can see that the program you are running is changing the palette, and resetting just the thing it changed at the end:

```console
$ wezterm replay --explain-only wezterm-recording-ejA1H0.cast.txt | grep -i Dynamic
        Action(OperatingSystemCommand(ChangeDynamicColors(TextBackgroundColor, [Query])))
        Action(OperatingSystemCommand(ChangeDynamicColors(TextCursorColor, [Color(SrgbaTuple(0.15294118, 0.15294118, 0.15294118, 1.0))])))
        Action(OperatingSystemCommand(ChangeDynamicColors(TextCursorColor, [Color(SrgbaTuple(0.15294118, 0.15294118, 0.15294118, 1.0))])))
        Action(OperatingSystemCommand(ChangeDynamicColors(TextCursorColor, [Color(SrgbaTuple(0.15294118, 0.15294118, 0.15294118, 1.0))])))
        Action(OperatingSystemCommand(ResetDynamicColor(TextCursorColor)))
```

wezterm doesn't recognize this as the palette being reset completely, so it ends up freezing the palette.

I've pushed a fix for this, so this should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by ch4m1gn0n** [comment]
the nightly version works fine. Thanks for you job!!!  But there is still a small problem, changing the system color mode when opening nvim, also cause the same problem.  

[wezterm-recording-pFJeZ5.cast.txt](https://github.com/wez/wezterm/files/11673016/wezterm-recording-pFJeZ5.cast.txt)

**Comment by wez** [comment]
Is this still an issue in the latest release?
