### ISSUE TITLE
Issues with getting the '╱' character to tile nicely

### ISSUE THREAD

**Issue by fredrikaverpil** [wez/wezterm#3788]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

N/A

### WezTerm version

20230527-141007-05a2d633

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

As described [in this discussion thread](https://github.com/wez/wezterm/discussions/3780), I have noticed that the ╱ character seems to be tiling a bit strange in Wezterm, compared to Kitty:

![Screenshot 2023-05-26 at 15 18 03](https://github.com/wez/wezterm/assets/994357/40f09baf-bcfa-44f4-9cce-499c6a04fa26)

I've noticed this tiling looks the same in Alacritty as in Wezterm.

### To Reproduce

```lua
vim.opt.fillchars = "diff:╱"
```

I'm using the "JetBrains Mono" font, installed from https://www.jetbrains.com/lp/mono/

My screenshots are showing [sindrets/Diffview](https://github.com/sindrets/diffview.nvim).

### Configuration

```lua
local wezterm = require("wezterm")
local config = {}

-- font
-- https://www.jetbrains.com/lp/mono
-- https://github.com/ryanoasis/nerd-fonts/releases
-- https://fonts.google.com/noto/specimen/Noto+Color+Emoji
config.font = wezterm.font_with_fallback({
  { family = "JetBrains Mono", weight = "Regular", harfbuzz_features = { "calt=0", "clig=0", "liga=0" } },
  { family = "Symbols Nerd Font Mono" },
  { family = "Noto Color Emoji" },
})

config.color_scheme = "tokyonight_night"

return config
```

### Expected Behavior

I was hoping the ╱ character would tile seamlessly, like it does in Kitty.

**Comment by fredrikaverpil** [comment]
Another screenshot:

![image](https://github.com/wez/wezterm/assets/994357/914e27e2-9bd7-4b0f-a966-e9ed6053a2a1)

**Comment by wez** [comment]
Simpler script to reproduce that output:

```console
seq 24 | awk '{print "╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱"}'
```

If you zoom way in, with a single cell selected:

![image](https://github.com/wez/wezterm/assets/117777/00b3542e-6e67-4c78-9b98-92ad3608a7a3)

you can see that the line is fine within its cell, but to make it tile perfectly, anti-aliasing would need to put dots in the top-left and bottom-right corners, which would make the glyph have artifacts when used on its own.

I think the main issue here is that the bottom-left corner ends with a pretty chunky footer. If that were less pronounced then you wouldn't notice it as much.

Try setting:

```lua
config.anti_alias_custom_block_glyphs = false
```

to disable anti-aliasing in the custom block glyphs.

![image](https://github.com/wez/wezterm/assets/117777/4b83881a-7538-44a1-ac26-14d0e27c210b)


Another alternative option is:

```
config.custom_block_glyphs = false
```

to use the glyphs from your font. Note that this will likely trade this issue away for other alignment issues due to hinting issues in various fonts + freetype.

**Comment by fredrikaverpil** [comment]
@wez I really appreciate you looking into this!

It kind of looks weird either way. I'm not sure what is happening in Kitty that makes this look so much better. It's possible that chunkier weight causes more antialiasing there and is just hiding the problem?

Either way, I don't think it's worth spending time on this problem and I'll try to use a different character for my diffs which might work just as well:

```lua
vim.opt.fillchars = "diff:░"
```

So feel free to close this issue if you like, and again, thanks for looking into it - and huge thanks for all your awesome work on Wezterm!

**Comment by wez** [comment]
Don't open an issue with JetBrains Mono unless you have disabled custom block glyphs. The default configuration is that wezterm is rendering this particular glyph; it doesn't come from the font.
