### ISSUE TITLE
Tabs render "inside" the notch on macbooks with a notch when using non-native fullscreen

### ISSUE THREAD

**Issue by kamalmarhubi** [wez/wezterm#3807]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

N/A

### WezTerm version

wezterm 20230530-062729-95e44f21

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

(At least I think it's non-native fullscreen!)

When you are in non-native full-screen mode on a macbook that has a notch (m2 air in my case), the tabs will render inside the notch. I took a photo because I couldn't figure out how to capture a screenshot including the notch.

This seems related to #1737?

![wezterm-tabs-in-notch](https://github.com/wez/wezterm/assets/50936/8d89b208-9b4c-4eb0-b42c-c1d780950cd7)

### To Reproduce

Open wezterm, hit option+return to enter full screen, then command+t a bunch of times to create tabs until the tabs hit the middle of the screen.

### Configuration

no config

(this happens with `--skip-config`)

### Expected Behavior

The tabs should be fully visible. I'd slightly prefer to have tabs render either side of the notch over pushing down the tabs as the native fullscreen does, as then my terminals have a couple extra lines in them.

### Logs

```
Debug Overlay
wezterm version: 20230530-062729-95e44f21 aarch64-apple-darwin
Window Environment: macOS 13.3.1 (22E261)
WebGPU: name=Apple M2, device_type=IntegratedGpu, backend=Metal, vendor=0, device=0
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>
```

**Comment by wez** [comment]
FYI, I don't have a system with a notch so progress on this will be pretty slow.

**Comment by kamalmarhubi** [comment]
@wez if you have some rough guidance on how to split the tab bar in two for rendering, I might take a crack at it. my progress will also be pretty slow though :-)

**Comment by wez** [comment]
TBH, the first step would be to see why the content isn't being pushed below the notch as that other issue intended, leaving a black bar at the top.

Splitting around the notch would be a pretty huge change.

**Comment by kamalmarhubi** [comment]
@wez sorry for the super slow response here. I've never done any desktop UI programming so I haven't got a great idea how to start on investigating that.

**Comment by mbaird** [comment]
Just ran into this issue.

After checking out the source and playing around with the value [here](https://github.com/wez/wezterm/blob/main/window/src/os/macos/window.rs#L902C44-L902C51),  the magic number for me was to add 32.

I then noticed that the value returned for safeAreaInsets.top (MacBook Pro 14-inch, 2021) is also 32. Seems too coincidental that the fix is to multiply this number by 2? 

```
22:49:55.010  TRACE  window::os::macos::window              > NSEdgeInsets { top: 32.0, left: 0.0, bottom: 0.0, right: 0.0 }
```

**Comment by wez** [comment]
@mbaird perhaps the `NSEdgeInsets` values need to be multiplied by the scale factor, which is 2 on a retina display?
The scale factor can be computed using code like this:

https://github.com/wez/wezterm/blob/b8f94c474ce48ac195b51c1aeacf41ae049b774e/window/src/os/macos/window.rs#L1208-L1210

**Comment by mbaird** [comment]
@wez thanks, I've confirmed that computing the scale using the code you've highlighted and multiplying the value of `safeAreaInsets.top` gives me a perfect top border. 

There's a code-comment referencing https://github.com/wez/wezterm/issues/1737#issuecomment-1085923867, where an extra `2` was added to this number, but something must have changed since then because I cannot see a need for this now. 

In case they are useful for anyone in future, here are the values of `top` for [`safeAreaInsets`](https://developer.apple.com/documentation/appkit/nsscreen/3882821-safeareainsets) at the different built-in resolutions on a MacBook Pro 14-inch, 2021:

```
1024x665  = top: 22.0
1147x745  = top: 24.0
1352x878  = top: 29.0
1512x982  = top: 32.0
1800x1169 = top: 38.0
```

I'll clean up what I've got and submit a PR.
