### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by FelixKratz** [wez/wezterm#3815]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Hi there, I have just been trying out your terminal and it looks very cool. Thanks for the awesome project.

It seems there are some memory problems, as can be seen when running the binary through a profiler:
In the first 22 seconds after executing the app there are ~2000 memory leaks with varying severity:
![Screenshot 2023-06-01 at 15 30 57](https://github.com/wez/wezterm/assets/22680421/b6e9e903-9408-4f47-8f07-991c7937b3c2)

The most severe memory leaks seem to stem from hashbrown hashmap usage. Leaks seem to be generated at startup and will continue to happen when using the app.

Alacritty has similar problems, although they seem to be less severe.

### Configuration
```lua
local wezterm = require("wezterm")
local action = wezterm.action

local config = {}

if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.window_decorations = "RESIZE"
config.color_scheme = 'Catppuccin Mocha'
config.enable_tab_bar = true
config.hide_tab_bar_if_only_one_tab = true
config.font = wezterm.font('Liga SFMono Nerd Font', { weight = "Bold" })
config.harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' }
config.send_composed_key_when_left_alt_is_pressed = true
config.font_size = 14.0
config.cell_width = 0.8
return config
```

### Expected Behavior

No memory leakage. I plan to leave my terminal running for days or even weeks.

**Comment by vars1ty** [comment]
Expected this exact same issue as mentioned in the screenshot above, just on Linux.

**Comment by LeonHeidelbach** [comment]
This is also one of the two things I immediately noticed when trying out your terminal @wez after switching from Alacritty. I appreciate the extra features that Alacritty definitely lacks like support for ligatures, builting muxing, fallback fonts and having Lua to configure the experience with proper reporting when the config contains errors. However, there are two things that I find somewhat odd.

1. Excessive memory overhead right after launching the terminal which seems to only ever rise, even if no manual interaction with the application takes place. Compared to Alacritty after running both applications for approx. 45 minutes without doing anything other than having `btop` open on both terminals, Wezterm uses up 203mb of memory compared to Alacritty's 92mb, without any reason that is apparent to the user. As can be seen on @FelixKratz's screenshots most of the allocations can be attributed to Hashbrown HashMaps which does make sense. The general concept of HashMaps is to only really ever allocate memory if necessary and never automatically free it once the size of the map shrinks in order to improve performance. Hashbrown HashMaps howerver, do have the option to shrink back to the current size of the map after the allocated memory is no longer in use, using the `shrink_to_fit` method, which from a quick code search is only ever used once. I am obviously not very familiar with your code base and how ofthen you drop entire HashMaps or other allocations, but after having Wezterm open over night and finding it eat up over 1GB of memory without doing anything, this seems a bit concerning.
2. Incredibly poor redraw rate when using applications such as Neovim. This becomes noticable even when only moving the carret (compared to Alacritty), but it becomes jarring when using a plugin like neo-scroll to smoothly scroll through documents (#817) and is even further worsened when using tmux. As this seems to have been an issue for quite some time now, I am not sure if you are actively working on fixing this issue but for me it massively impacts the overall experience.

It would be nice to have your opinion on the above points @wez , since I really like what this project tries to achieve, but the responsiveness and robustness of the terminal I use on a daily basis is very important to me.

**Comment by wez** [comment]
My take on this is:

* This issue is really about memory usage, not memory leaks. I don't believe that there are any memory leaks in wezterm.
* wezterm uses memory and caching as a strategy to reduce CPU overhead for a number of hot tasks
* Modern color/emoji fonts have a lot of bitmap data which occupies more ram when mapped
* Some users set unrealistically large scrollback sizes without considering that it costs them RAM for each pane
* Modern operating systems page out memory when unused so simple tools like top can be misleading when it comes to understanding the actual physical memory used by an application
* I have not personally encountered a situation where wezterm's memory usage has caused any impact to my system. Other applications are always dominant.

As a result, it is not a priority for me to dive deeper into this.

If someone is motivated to carry out a more thorough investigation for themselves, I would encourage them to look into the caches and see about tuning them down. https://github.com/wez/wezterm/discussions/3664#discussioncomment-5784980 has some information about them in the context of a performance discussion.

Re: performance; wezterm is plenty responsive for me in my daily workflow, but there are some areas where I would like to see things get faster.  And honestly, I wouldn't mind seeing memory utilization get smaller either.

The reality is that I simply don't have the time to dedicate to it.  It's complex and deep work and while there are a small number of sponsors for wezterm there are not enough to fund my time on such a complex project.

Here's an excerpt from my sponsors page:

https://github.com/sponsors/wez
> WezTerm is big enough now that I cannot keep up with the backlog of issues; it's turned into real work. I was part of the mass of tech layoffs in November 2022, which, while it has taken away my income, has presented an opportunity to consider making wezterm an official part of my income stream. For that to work it needs to sustainably cover a significant portion of my outgoings; I have a mortgage and family of dependents to feed and cover their health insurance. 

What time I do have for wezterm is currently being siphoned off into triaging and responding to issues like this one, and this kind of work is draining rather than energizing.  On days like this where I wake up thinking that I'll sit down to do something fun, I quickly want to log off and do something else that is more rewarding.

As a means of safeguarding my own well-being, while I empathize that some users are unhappy with performance, memory usage, wayland support and so on, I can't afford the time or mental headspace for them right now: they are taking more than they are giving.

If folks want to see things improve, then there are two big things they can do:

* If capable, consider stepping up and contributing some engineering work. Running down concrete issues and capturing the details that precisely identify the root cause of individual issues would be great first steps. Submitting PRs to resolve them would be great follow up steps. I love to see and collaborate on those kinds of issues; actionable and helpful!
* If not capable of contributing directly, then contributing financially would be very welcome: I've put years into this project already and thousands of people are benefiting from it for their work. I believe that there are enough users out there that are in a position to sustainably (for them) sponsor me to make this more of a full-time job and keep making wezterm better and better for them.
