### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by erf** [wez/wezterm#382]
**Is your feature request related to a problem? Please describe.**

Ok, this is not really a problem, just a small thing i noticed which might could be improved.

When you scroll with the mouse pad i noticed when the speed of the of the scroll position slows down, it tries to find the line where to stop, so there is a lag in between lines until complete stop.

**Describe the solution you'd like**

I wonder if this could be improved so that there is no lag in movement until the speed is zero, and only then would you fit to the closest line.

Maybe you could make it an option like "smooth_scrolling = true" ( i know Android Studio has an option like this )

**Describe alternatives you've considered**

It really is fine as it is, this is just a small suggestion.

**Additional context**

I'm on version: 

wezterm 20201101-103216-403d002d-106-g35880cf4

**Comment by wez** [comment]
The behavior that you've described above sounds like the scrolling inertia that is built in to the macOS trackpad handling at a low level; I don't believe that wezterm has any influence over it.  However, you as the user can calm down or reverse it by moving your fingers in the opposite direction to arrest the motion.

Smooth scrolling typically refers to the idea of pixel-level viewport positioning, rather than character level positioning.  wezterm doesn't and won't support per-pixel scrolling.

**Comment by erf** [comment]
Ah, so wezterm doesn't control the scrolling speed / position? Then i guess it is difficult to do what i was thinking.

**Comment by wez** [comment]
The logic for this can be found here:

https://github.com/wez/wezterm/blob/master/window/src/os/macos/window.rs#L1166-L1227

If you scroll quickly and lift your hand off the trackpad, macos will continue to deliver events even after your hand has left the surface; those will be larger at first and then gradually decrease through some heuristic in macOS to synthesize inertia (eg: like spinning a physical mouse wheel).

The number of "pixels" (it's not really, because macOS doesn't like to talk about pixels) of distance is passed in, but that value needs to be turned into rows so it is scaled down to a fractional value and an accumulator is used to collect the fractional components to sum the intertial "residue" together to get it to add up to whole rows; this is important because what you may perceive to be a single movement can be delivered over time as a series of smaller events.  Without the accumulator, if we only took the truncated integer value the movement would feel very janky.

If you wanted to experiment with the logic there are a couple of easy to change things that may affect the experience:

* [Play with this factor](https://github.com/wez/wezterm/blob/master/window/src/os/macos/window.rs#L1169-L1175) especially if you have a very large or very small font size
* accumulated fractional movements that are older than [this interval](https://github.com/wez/wezterm/blob/master/window/src/os/macos/window.rs#L1189-L1193) will be discarded.

**Comment by erf** [comment]
OK, thanks for the explanation. I might take a look if i find the time. 

I've barely touch `rust` before though, but i find it a very interesting, although a bit verbose syntactically.

**Comment by erf** [comment]
I looked into it a little bit. So it looks like the scroll_wheel in window.rs creates VertWheel events with integer positions, which is handled in termwindow mouse_event and then calls set_viewport which invalidates and re-render.

Is it so that the scroll position events that are sent to the viewport are always integer and determine the line position vertically, e.g. you will always render as you described "character level positioning" and thus it will not be fully "smooth", but it only appear like that when you scroll fast.

**Comment by erf** [comment]
When i read what you wrote now, I guess my thinking was that if you could delay the creation of the whole rows, until the movement speed from the trackpad was closer to zero, you would have smoother scrolling. But i guess you can't do that since you have no control over the "speed" of events delivered by the trackpad.. I haven't gotten around to look into the code much yet, just some thoughts.
