### ISSUE TITLE
QuickSelect won't follow line wrap in tmux sessions

### ISSUE THREAD

**Issue by walkert** [wez/wezterm#4083]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230731-231025-ca9cf230

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm in a tmux session with a very long URL displayed on the screen. It is visually wrapped to the next line. If I pull up Quick Select with Ctrl-Shift-Space, only the first line is captured. If I exit tmux and attempt the same with a wrapped URL, the entire URL is selected. An example of what I mean below:

In a normal session it looks like this:
```
|[a]https://someverylong/url/is/listedh|
|[a]ere/index.html                     |
```

So with the above, in tmux once I copy the URL I get `https://someverylong/url/is/listedh` vs a regular session which gets `https://someverylong/url/is/listedhere/index.html`.

In tmux only the first line is selected (note the prefix only appears on the top line):
<img width="965" alt="Screenshot 2023-08-01 at 20 10 24" src="https://github.com/wez/wezterm/assets/2653795/b6219f79-c5d4-4410-b6e0-1b16ad4c5f06">
In a normal session it looks like this:
<img width="964" alt="Screenshot 2023-08-01 at 20 10 48" src="https://github.com/wez/wezterm/assets/2653795/1df2feb2-2bb6-4681-aff4-6957813b1771">

### To Reproduce

Open terminal. Echo long URL to the screen such as `https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&projects=&template=bug.yml`. Shrink the screen enough that the line is wrapped. Enter Quick Select mode. Do this within tmux and from a non-tmux shell.

### Configuration

no config

### Expected Behavior

I'd like the behaviour in a tmux session to be the same as outside.

### Logs

I wasn't able to find any relevant logs when using Quick Select.

**Comment by wez** [comment]
Matching works on logical lines. I'm not going to support matching this kind of output. You can use wezterm's native panes instead.

**Comment by walkert** [comment]
Just so I'm clear, this is an issue of not supporting tmux fully in the terminal since you're already matching these lines in a regular window?

**Comment by wez** [comment]
functions in wezterm that match text using regular expressions operate on logical lines, matching contiguous text.

Supporting matching arbitrary ranges delimited by arbitrary separator characters requires some engineering effort to guess at when a pane is a pane and is not some other kind of ascii art on the screen (and will thus be a source of bugs when it inevitably doesn't work how someone expects) and is also costly at runtime.  I won't be supporting that at that layer.

If/when:
* #336 

is done, then it will likely just happen work with no additional effort, because it will work "natively" in the Pane abstraction.

If you're using tmux and want to use quickselect style functionality, you should consider https://github.com/fcsonline/tmux-thumbs which was the inspiration for this feature in wezterm.

**Comment by walkert** [comment]
Thanks for the detailed reply!
