### ISSUE TITLE
Newlines removed when pasting multiple lines of text

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [wez/wezterm#411]
## Describe the bug

I copied multiple lines of text and paste in wezterm. All newlines were removed in the pasting.

## Environment (please complete the following information):

 - OS: Windows Server 2019
 - Version: wezterm 20201101-103216-403d002d

## To Reproduce

![single_line](https://user-images.githubusercontent.com/39968/103432547-868abf80-4c1b-11eb-88b3-5792bbcf8c60.gif)

## Configuration

I removed wezterm.lua and it still behaves the same.

**Comment by wez** [comment]
This is a bit of a tricky thing because we don't want CRLF in most unix apps.
I've pushed a commit with a reasonably compromize that should show in the nightly builds in the next hour or two.
More explanation on the behavior change is here:

https://github.com/wez/wezterm/blob/b7b72646e3343d54b4d269a3e646e2079fe073c4/term/src/terminalstate.rs#L715-L729

**Comment by vivekananthrp** [comment]
New lines inserted between pasted lines from terminal, after ssh into a remote linux system.

I used ctrl+shift+c for copy and ctrl+shift+v for pasting. Any way to fix this?



https://user-images.githubusercontent.com/11735154/126307581-d6947785-67e8-42c0-8f21-ea1464cc16fa.mp4
