### ISSUE TITLE
Calling `wezterm.gui.screens()` outsides event closure makes wezterm fail to start

### ISSUE THREAD

**Issue by neur1n** [wez/wezterm#4122]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230806-225328-bf172634

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I was trying to adjust the font size according to the screen width by doing this in *wezterm.lua*

```lua
SCREEN_WIDTH = 0  -- or `local screen_width = 0, I tried both`

Wezterm.on("gui-startup", function(_)
  local w = 0
  local scr = Wezterm.gui.screens()
  for _, s in pairs(scr.by_name) do
    if s.width > w then
      w = s.width
    end  
  end
end)

local font_size = 12 * SCREEN_WIDTH / 2560
```

However, it seems that `SCREEN_WIDTH` cannot be modified inside the `gui-startup` event closure. Therefore I tried to call `wezter.gui.screens()` in a function (or someplace in *wezterm.lua*, I tried both), but it makes wezterm unable to show up. By this I mean wezterm is shown in Windows's task manager, but there is no GUI windows shows up.

### To Reproduce

As mentioned in description.

### Configuration

```lua
local Wezterm = require("wezterm")

local w = 0
local scr = Wezterm.gui.screens()

for _, s in pairs(scr.by_name) do
  if s.width > w then
    w = s.width
  end
end

local config = {
  font_size = w
}

return config
```

**Comment by wez** [comment]
Look at the logs. I recommend running `wezterm.exe` from another different terminal on Windows, as that is the easiest way to see the logs.

regarding global variables, you cannot use them in wezterm, because there can be multiple threads and multiple different lua contexts in use.  There is no simple sharing of data between them. Look at https://wezfurlong.org/wezterm/config/lua/wezterm/GLOBAL.html for more information and a solution.

**Comment by Neur1n** [comment]
I tried to run `wezterm` and `wezterm start` in Windows Terminal, but no logs are shown. Then I tried `wezterm ls-fonts` and it gave:

```bash
ERROR  wezterm_gui > cannot get window Connection: not running on the gui thread?
```

**Comment by neur1n** [comment]
> Look at the logs. I recommend running `wezterm.exe` from another different terminal on Windows, as that is the easiest way to see the logs.
> 
> regarding global variables, you cannot use them in wezterm, because there can be multiple threads and multiple different lua contexts in use. There is no simple sharing of data between them. Look at https://wezfurlong.org/wezterm/config/lua/wezterm/GLOBAL.html for more information and a solution.

Sorry about the late response. I was intended to set the font size according to different screen resolutions, e.g. 12 on a 2560 (width) screen and 10 on a 1920 screen. However, it seems that the configurations are loaded before the `gui-startup` event and I couldn't figure how to set the dynamic font size via `wezterm.GLOBAL`.

**Comment by farzadmf** [comment]
I'm also curious about this. I recently bought a bigger monitor, and I'd like to have different font sizes for built-in or the new monitor.
- Tried `wezterm.GLOBAL`, didn't work.
- As mentioned, doing `wezterm.gui.screens()` generates an error

**Comment by wez** [comment]
I think there are two problems here:
* Some unknown error with the configuration you shared
* Solving the higher level goal of varying the font size based on available screens

For the first one, not enough information is present: there must be an error message somewhere that explains what wezterm didn't like, but neither of you have shared what that actual error message is; it is rather frustrating!

For the second one, firstly, I want to point out that wezterm uses *points* for the font size so that you can pick a size that will have a consistent mapping to a physical size, based on the dpi of your monitor.  So you should just need to set the point size to a readable size and be done with no additional headaches.

If the dpi is not set correctly for your monitor(s), in nightly builds of wezterm, it is now possible to override the dpi on a per-screen basis:
* https://github.com/wez/wezterm/issues/4096

Secondly: there may be multiple screens, and screens can be plugged and unplugged at any time.  At the time that the config file is loaded for the first time we don't have a complete picture of the screen situation and dpi, in particular, we haven't yet created any windows and we won't know where the OS will place the initial window, so we can't predict which will be used or otherwise reason about it.  If a window is moved to another screen, the configuration will need to be updated as well.  To make things more complicated, not every OS will reveal the position of the window an application (Wayland does this) which makes it even more difficult to reason about this stuff effectively.

What I would suggest is using the example from https://wezfurlong.org/wezterm/config/lua/window-events/window-resized.html as a basis and triggering your logic to compute a font size from both the `window-resized` and `window-config-reloaded` events so that you can re-evaluate it in both situations.

Something like this might do the job; I haven't tested this at all.

```lua
-- Maps the name of a screen to the desired font size
local FONT_SIZE_BY_SCREEN = {
   ["Display 1"] = 12,
   ["Display 2"] = 14,
}

-- Returns the name of the screen that window is on
-- This is imperfect and may return the wrong results
-- You are encouraged to adjust this to match whatever
-- heuristics make sense for your setup
function infer_current_screen(window)
  local dims = window:get_dimensions()
  local screens = wezterm.gui.screens()
  for screen_name, info in pairs(screens.by_name) do
     if math.floor(info.effective_dpi) == dims.dpi then
       -- guessing that this is the screen
       return screen_name
     end
   end
   -- Didn't find a match based on dpi, just assume that it is the main screen
   return screens.main.name
end

-- Figure out the desired font size for the window, and apply it as a config override
function recompute_font_size(window)
   local overrides = window:get_config_overrides() or {}
   overrides.font_size = FONT_SIZE_BY_SCREEN[infer_current_screen(window)]
   window:set_config_overrides(overrides)
end

wezterm.on('window-resized', function(window, pane)
  recompute_font_size(window)
end)

wezterm.on('window-config-reloaded', function(window)
  recompute_font_size(window)
end)
```

**Comment by farzadmf** [comment]
Thank you so much @wez for the super detailed explanation. Everything that you said makes total sense.

> but neither of you have shared what that actual error message is; it is rather frustrating!

Sorry about that from my side, but one of the comments mentioned the error I get, so I didn't put it again. This is the error:

`ERROR  wezterm_gui > cannot get window Connection: not running on the gui thread?`

(and, like the first comment in this issue, I tried calling `wezterm.gui.screens()` at the top level in my config file.

Last night, I read through some comments, docs, etc, and gave `window-resized` a shot, but it didn't seem to take my changes, but I'll definitely give your code a try
