### ISSUE TITLE
middle click paste onlinux not completely working

### ISSUE THREAD

**Issue by zeusintuivo** [wez/wezterm#417]
## Describe the bug

In Linux systems the mouse copies when selecting and pastes with the middle click. Wezterm does the select and copy from inside the terminal, but when selecting something from another program outside wezterm, the wezterm is not able to paste this inside of wezterm. 

## Environment (please complete the following information):

 - OS:  Linux Gnome Fedora 32
 - Version: wezterm 20201101-103216-403d002d 

## To Reproduce

Select something inside gnome-terminal go inside wezterm, mouse middle click and nothing happens. 
The expectation is that it should paste it. 

## Configuration

Default config. No file. 

## Expected behavior

Select something inside gnome-terminal go inside wezterm, mouse middle click and nothing happens. 
The expectation is that it should paste it. 

## Screenshots

NA

## Session Recording

NA

## Additional context

NA

**Comment by bew** [comment]
The default configuration does not paste from the primary buffer on middle click, it pasts from the normal clipboard (ctrl-c ctrl-v needed), it's working from inside wezterm because wezterm automatically copies to the normal clipboard when you select some text:
https://wezfurlong.org/wezterm/config/keys.html#default-mouse-assignments

To paste from the primary clipboard on middle click, you have to configure it yourself:
https://wezfurlong.org/wezterm/config/lua/keyassignment/PastePrimarySelection.html

**Comment by wez** [comment]
Copy and paste in X11 is annoying.  Wezterm will populate both the selection and the clipboard buffers when you select text for your convenience.  The other way around is more difficult, because the buffers can have different contents and it is almost impossible to programmatically automatically do what you expect in every situation.  If you explicitly use the copy function in gnome-terminal (ctrl-shift-c) then middle click will paste in wezterm without any additional configuration.

You can also configure an assignment to paste the primary selection as @bew mentions above.

A more holistic, system-wide, solution to the frustrating differences between clipboard and primary selection under X11 is to install `parcellite`, a clipboard manager.  It's likely available in a package of the same name from your linux distribution, but you can also find it [here](https://github.com/rickyrockrat/parcellite)) and turn on "Synchronize clipboards", pictured from a random screen shot I just found:

![image](https://user-images.githubusercontent.com/117777/104048061-851b4300-5197-11eb-8a78-83dec4bd5fea.png)

It will then listen for changes to both buffers, and populate the other one from the latest change, keeping them both in sync with the same contents.

**Comment by bew** [comment]
> Wezterm will populate both the selection and the clipboard buffers when you select text for your convenience

(_It's not exactly the topic of this issue, I can create another one if needed:_)
Can we have an option to not copy to both clipboard when doing mouse selection?
I'd like **avoid overwriting the clipboard** content every time I select something in the terminal.

**Comment by zeusintuivo** [comment]
> The default configuration does not paste from the primary buffer on middle click, it pasts from the normal clipboard (ctrl-c ctrl-v needed), it's working from inside wezterm because wezterm automatically copies to the normal clipboard when you select some text:
> https://wezfurlong.org/wezterm/config/keys.html#default-mouse-assignments
> 
> To paste from the primary clipboard on middle click, you have to configure it yourself:
> https://wezfurlong.org/wezterm/config/lua/keyassignment/PastePrimarySelection.html

Again, "why so hacky"  It is my understanding that having to "hack this" just get default Linux behaviour seems like the app is not even complying with minimum Linux standards. 

Avoid copy and paste, In Linux CONTROL C / CONTROL V holds a memory area, when MOUSE SELECT / MOUSE MIDDLE CLICK holds a different memory area.  Been that said, if you select "this text" then press CONTROL C, "control" memory, and "mouse" memory has the same, if later I select "that text" with the mouse. Now, "control" memory has "this text" and "mouse" memory has "that text."  . As users we should not have to "hack" any app that is expected to follow the default behavoir of the entire system.
