### ISSUE TITLE
Mouse bindings not working in terminal apps that capture mouse input

### ISSUE THREAD

**Issue by chtenb** [wez/wezterm#4235]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230828-220414-99c96139

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

[The docs suggest that wezterm bindings go first, before anything is passed to the terminal app.](https://wezfurlong.org/wezterm/config/mouse.html#gotcha-on-binding-an-up-event-only)
However, I find that my custom mouse bindings (ctrl-click to follow link) do not work in Vim and Helix.
- What's more, when I set `mouse = false` in the Helix config, the bindings **do** work in Helix.
- Shift-Click also just works in all situations, regardless whether `mouse = false` in Helix

### To Reproduce

Put the following config in wezterm config, open a file containing links in Vim or Helix with mouse support enabled, and ctrl-click the link. Nothing happens.
Shift-click the link. The browser opens.

### Configuration

```lua
  mouse_bindings = {
    -- Bind 'Up' event of CTRL-Click to open hyperlinks
    {
      event = { Up = { streak = 1, button = 'Left' } },
      mods = 'CTRL',
      action = act.OpenLinkAtMouseCursor,
    },
    -- Disable the 'Down' event of CTRL-Click to avoid weird program behaviors
    {
      event = { Down = { streak = 1, button = 'Left' } },
      mods = 'CTRL',
      action = act.Nop,
    },
  }
```

### Expected Behavior

I'd expect the wezterm mouse bindings to take precedence over terminal app bindings.

**Comment by wez** [comment]
That's how it works; see the top of https://wezfurlong.org/wezterm/config/mouse.html

If you really want certain mouse assignments to take precedence, look for the `mouse_reporting` option, also documented in that page.

**Comment by chtenb** [comment]
My apologies, it indeed says so in the docs. I should have read the page more carefully. However, I'm still confused. 

- If I read this correctly, mouse event tracking is something a terminal app can request, upon which it will receive all mouse events, and the wezterm assignments will do nothing. Unless any of the [`bypass_mouse_reporting_modifiers`](https://wezfurlong.org/wezterm/config/lua/config/bypass_mouse_reporting_modifiers.html) is held by the user, in which case it will NOT be passed onto the application.
- Then I don't understand the _Gotcha on binding an 'Up' event only_ section. If a terminal app has requested mouse event tracking it always will receive all mouse events, no? And if it doesn't it won't receive any mouse events at all, right? Then how would any of this create a situation of a terminal app receiving half of the events?
  - (Moreover, can't you always create the situation of an app only receiving the down event by dragging the mouse outside the terminal window?)
- I don't understand the explanation for the `mouse_reporting` and `alt_screen` properties.
  - What is the "mouse reporting state" of the current pane?
  - What is the "alt screen state" of the current pane?

Perhaps I can clarify the docs once I have a better grip.

**Comment by wez** [comment]
re: the *Gotcha* part of the docs, I think @bew wrote that and that perhaps there is something else from their config that is relevant for it to make the most sense?  They are a heavy user of mouse assignments!

> I don't understand the explanation for the `mouse_reporting` and `alt_screen` properties.
> 
>     * What is the "mouse reporting state" of the current pane?

There are certain escape sequences that can request one of a number of mouse reporting modes.
If a mouse reporting mode is active, then the "mouse reporting state" is considered to be `true`.

If you make a key assignment with `mouse_reporting=true`, then it will only match when mouse reporting mode is active.
 
>     * What is the "alt screen state" of the current pane?

There are certain escape sequences that enable the alternate screen buffer in a terminal.
When in alt screen mode, there is no scrollback.  "Full screen" terminal programs such as `vi` tend to use alt-screen mode in order to prevent thrashing and making the scrollback from your shell useless.  Those programs often also enable mouse reporting.

**Comment by bew** [comment]
> (Moreover, can't you always create the situation of an app only receiving the down event by dragging the mouse outside the terminal window?)

Actually no, because the mouse events will be clamp'ed as if the mouse didn't leave the terminal and is sitting at the top/bottom-most line and/or left/right-most column.

----
re: the Gotcha part of the docs, @chtenb you made me doubt..
My config for Ctrl-click [has nothing special](https://github.com/bew/dotfiles/blob/e2c2ba0289d93b2ca82a596dee64b5cfaec7e8ee/gui/wezterm/cfg_mouse.lua#L86-L96) (if you strip my helper functions)

### Let's reproduce the original issue:

With this wezterm config:
```lua
local act = require"wezterm".action
return {
  mouse_bindings = {
    -- Bind ONLY 'Up' event of CTRL-Click to open hyperlinks
    {
      event = { Up = { streak = 1, button = 'Left' } },
      mods = 'CTRL',
      action = act.OpenLinkAtMouseCursor,
    },
  }
}
```
Start wezterm with that config: `wezterm --config-file ./repro-wezterm.lua`

Let's make a _minimal_ neovim config, save this in `repro-nvim.vim`:
```vim
set mouse=n
nnoremap <C-LeftMouse> :echo "ctrl click"<cr>
nnoremap <C-S-LeftMouse> :echo "ctrl shift click"<cr>
```
And open a file having a link: `nvim -u ./repro-nvim.vim README.md` (e.g: wezterm's readme)
Now try to do Ctrl-click and Ctrl-Shift-click.

=> You will see that both clicks are seen by neovim, not only the first (non-shifted) key

### What's hapenning

:point_right: Adding the `SHIFT` key when doing mappings in wezterm will bypass mouse reporting ONLY if the key event is mapped on wezterm side, not in all cases.
There is a binding for Ctrl-click Up event, so shift key doesn't sent the event to the app, but the Down event is not bound in wezterm, so the shift key isn't used to bypass mouse reporting and the event is sent to the app.

@wez Maybe the 'gotha' could be avoided by having a special behavior, checking during a down event if the up event is bound? Personally I don't have any case in my config where I want to bind only up without down.
Other solution is to better explain that the bypass modifiers is only effective when the event is mapped ?

**Comment by chtenb** [comment]
> 👉 Adding the SHIFT key when doing mappings in wezterm will bypass mouse reporting ONLY if the key event is mapped on wezterm side, not in all cases.

I see, that was not clear to me.

> @wez Maybe the 'gotha' could be avoided by having a special behavior, checking during a down event if the up event is bound? Personally I don't have any case in my config where I want to bind only up without down.
Other solution is to better explain that the bypass modifiers is only effective when the event is mapped ?

Wouldn't it be easier and more consistent to simply not pass on any mouse events when a bypass key is held, regardless of any existing mappings?
