### ISSUE TITLE
Add Nix Flake

### ISSUE THREAD

**Issue by yoav-lavi** [wez/wezterm#4286]
Would be useful (IMO) to add a Nix flake (see for example https://github.com/helix-editor/helix/blob/master/flake.nix [the nixpkgs configuration for WezTerm is [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/terminal-emulators/wezterm/default.nix) and home-manager is [here](https://github.com/nix-community/home-manager/blob/master/modules/programs/wezterm.nix)) so Nix users (using flakes) can easily point to a "nightly" version of WezTerm. 

This would allow users to configure an input and overlay to use the GitHub `main` version of WezTerm.

This would also allow Nix users to contribute more easily.

(with `helix`:)

```nix
   # inputs ...
    helix = {
      url = "github:helix-editor/helix";
    };
    # ...
```
```nix
   # ...
    overlays = [
      (self: super: {
        inherit (helix.packages.aarch64-darwin) helix helix-unwrapped;
      })
    ];
    # ...
```

**Comment by wez** [comment]
I don't use nix and don't have time to learn it or maintain it. I'm only interested in having a flake in this repo if it is accompanied by a workflow that verifies that it continues to operate, and if someone steps up to own any issues that surface around it.

**Comment by jalil-salame** [comment]
> I don't use nix and don't have time to learn it or maintain it. I'm only interested in having a flake in this repo if it is accompanied by a workflow that verifies that it continues to operate, and if someone steps up to own any issues that surface around it.

I could do this, but I don't know how quickly I could address issues in the flake... How fast would issues need to be addressed? I think simple ones (30 minutes) I could fix every day, more complex ones I could fix only in the weekends.

**Comment by PaulGrandperrin** [comment]
I'm interested in working on this too!
I'm longing to move to wezterm but I can't right now because the cursor is extremely buggy on the version we have on NixOS (stable and unstable).
So I need to try the git version to see if it's fixed already, or then try to find a fix.

I could be interested in maintaining the `flake.nix` too if I definitively move to `wezterm`. I also know `rust` quite well so..

**Comment by jalil-salame** [comment]
> I'm interested in working on this too!
> I'm longing to move to wezterm but I can't right now because the cursor is extremely buggy on the version we have on NixOS (stable and unstable).
> So I need to try the git version to see if it's fixed already, or then try to find a fix.
> 
> I could be interested in maintaining the `flake.nix` too if I definitively move to `wezterm`. I also know `rust` quite well so..
> 

What are your problems? I'm on NixOS unstable using Sway (Wayland), and besides it disappearing at startup, I don't have any issues.

Do you mean the Mouse cursor or text cursor?

Wezterm hides the mouse cursor when typing, if it doesn't reappear after you move it then there is already a closed issue about that.

**Comment by PaulGrandperrin** [comment]
@jalil-salame yes the mouse cursor randomly disappearing and also often not having the correct icon.
I'm on gnome wayland.

**Comment by jalil-salame** [comment]
> @jalil-salame yes the mouse cursor randomly disappearing and also often not having the correct icon.
> I'm on gnome wayland.
> 

Might be related to #3334, you should check that. I don't have problems with the mouse cursor.

**Comment by MatrixManAtYrService** [comment]
I am also plagued by the cursor disappearance bug in wayland and gnome.  I find that it happens most often when wezterm is the only window on that desktop, so I usually make it go away by opening firefox.

I started working on an issue for that a while back and also became discouraged by the switch-to-nightly situation. The concern is that if I have to package it differently when in nightly mode (since nightly isn't in nixpkgs, and probably shouldn't be) then perhaps those differences will be meaningful in some way that interferes with the desired reasoning.  After all there's clearly a Gnome/Wayland interaction here that we need to recreate.

I maintain a flake.nix for my project at work.  The situation is the same: my team doesn't care because they use the same laptop everywhere.  I like to device-hop, so I maintain a flake.nix that pins the depended-upon tool versions such that they're project-deps and not system-deps.  They sort of just tolerate it, which I don't think is so bad for them.  Once you have it working in the first place, it's pretty hands off.  Projects that are this mature just don't have wildly different dependencies from week to week.

Besides, compared with python (which is what I'm dealing with at work), rust is well-behaved under nix.  Should be a cinch.

Wez's requirements were:

1. it is accompanied by a workflow that verifies that it continues to operate
2. someone steps up to own any issues that surface around it

Not being a rust dev, I'm reluctant to say "I've got this" for the whole story, but I'm willing to help where I can.

I see a cirrus.yml here, so I guess 1 would be met by an entry which does this in an environment where nix is installed:
```
nix run github:wez/wezterm/{the-branch-under-test} --version | grep {the-version-being-tested}
```

If the flake were broken in some way, that would likely fail.

As for 2, it looks like there's sufficient interest here that we can manage that.

Seems like the test can come later and the first goal should be a fork which launches wezterm when you run:
```
nix run github:{thefork}/wezterm
```

Once we like the flake in the fork, we can come up with a testing and maintenance strategy.  I'll take a crack at it.

**Comment by MatrixManAtYrService** [comment]
I just discovered this: https://github.com/wez/wezterm/pull/3547

Looks like @happenslol has already done this?

**Comment by alxpettit** [comment]
I'm super interested in a flake too. I'd be happy to report when anything breaks and suggest fixes! :) Also it'd be great to try out the newest versions of Wezterm.

> I'm interested in working on this too! I'm longing to move to wezterm but I can't right now because the cursor is extremely buggy on the version we have on NixOS (stable and unstable). So I need to try the git version to see if it's fixed already, or then try to find a fix.

@PaulGrandperrin 

I found a workaround for that awhile back, actually:

```lua
config.hide_mouse_cursor_when_typing = false
```

**Comment by MatrixManAtYrService** [comment]
Is there perhaps a better way to handle this sort of thing in general?  I find myself wishing for this all the time, wezterm stands out only because enough other people also want it here that there's a thread about it.

Ideally conversations like these wouldn't converge on bullying project maintainers to take on a maintenance burden.  Ideally the conversation would be:

> We are already maintaining a flake for this project over *here*. Can you link to it in your readme so that it's more discoverable?

Or maybe we need a convention: `.flake.nix.ref` points at where the flake lives so that it can be very explicit that it's somebody else's problem. One could imagine altering nix itself to follow these. Perhaps we can crowd source the maintenance of whatever ultimately coughs up a flake lock after the reference is followed.
