### ISSUE TITLE
"FULL BLOCK" renders dark lines when width or height is a fraction of a pixel

### ISSUE THREAD

**Issue by DONofDESTROY** [wez/wezterm#433]
## Describe the bug

There is a wired space between glyphs that is occuring in nightly build
launching wezterm with `wezterm -n` prodouces something like this in neofetch
![image](https://user-images.githubusercontent.com/47606472/105015705-d4028b80-5a67-11eb-8438-407fb6abf437.png)
making the font bigger at one time it looks like this
![image](https://user-images.githubusercontent.com/47606472/105015823-f3011d80-5a67-11eb-8975-647f824be2d7.png)

## Environment (please complete the following information):

 - OS:  manjaro gnome X11
 - Version: wezterm 20201101-103216-403d002d-263-gfc6f529e

## To Reproduce

Steps to reproduce the behavior.

install the nightly build and run neofetch

## Configuration

This is default but I have tried with other fonts and the results were same

## Expected behavior
the glyph should be rendered like the stable release
![image](https://user-images.githubusercontent.com/47606472/105016830-21332d00-5a69-11eb-98d3-595184fe124e.png)
version of the above screenshot `wezterm 20201101-103216-403d002d`

**Comment by wez** [comment]
I've spent a couple of hours poking at this over the past couple of days.  It's somehow related to antialiasing; if you disable it then freetype will render a completely solid block (and the rest of the text will be ugly).

Otherwise, what's happening is that either that first row or the last column of that particular glyph has a fractional width or height (depending on the font_size) just slightly less than the monospace cell metrics and gets emitted as a partial gray+alpha line.

An unhelpful observation: neofetch could render those blocks as reversed spaces like it does for the color palette, rather than using that glyph :-p

**Comment by DONofDESTROY** [comment]
previous version of alacritty had this issue but it seems like gone in the current release
 

> An unhelpful observation: neofetch could render those blocks as reversed spaces like it does for the color palette, rather than using that glyph :-p

is it the reason that it is not printing manjaro logo for JetBrainsMono Nerd Font in nightly version, forgive me if I got this wrong.

**Comment by wez** [comment]
I do think that something isn't right here, but I'm not yet sure precisely what.  If I compare how eg: Gnome Terminal renders the blocks, there are no gaps there.  (Gnome Terminal is a better comparison point because it uses pango to do proper shaping, whereas Alacritty doesn't do any shaping/ligatures AFAIR).

From what I can see so far, freetype is producing a glyph with a softer/gappier edge, but also AFAICT, it is at the correct size, so it looks "right" in terms of doing what it is asked to do.

It's possible that the shaper integration with harfbuzz has a rounding issue with glyph spacing that makes this more prominent.

**Comment by mborejdo** [comment]
fwiw, I am also observing this problem on windows. Playing a bit with the DPI solves this more or less (but then I seem to be having issues with emojis, which are not rendered correctly then)

**Comment by wez** [comment]
As far as I can tell, the root cause of this is that the configured point size results in either a fractional width or height; the default 10pt size gives a fractional height of `16.526813507080078`.  When rasterizing, freetype produces a glyph bitmap that is 17 pixels high and that has a half-bright (50%) line at either the top or bottom row, depending on whether the font's hinting or freetype's auto-hinting is in use.

This issue in freetype seems relevant: https://gitlab.freedesktop.org/freetype/freetype/-/issues/761
That issue discusses improving the autohinter so that it can handle the box drawing range of glyphs better.

I'm not yet sure quite what to do about this; my initial thought was just to truncate to an integer cell height and find a way to ignore eg: the bottom pixel, but the fact that the half-pixel could be top or bottom means that that simple heuristic could be wrong 50% of the time.

**Comment by wez** [comment]
I've opened https://gitlab.freedesktop.org/freetype/freetype/-/issues/1033 to see if the freetype folks have some suggestions on what to do about this.

Also, FWIW, I was poking around at this on my mac last night, and the macOS Terminal.app always renders a blank line under the "FULL BLOCK" glyph for every monospace font installed on that system!

**Comment by wez** [comment]
I decided to teach wezterm to produce its own block glyphs; the upstream freetype issue doesn't seem like it will be resolved soon, so it seemed most expedient to handle this for ourselves.

In this screen shot you can see that freetype (upper window) has produced glyphs with gaps, and for the vertical 1/8th block at this size, the vertical line is missing.  The lower window shows the computed block glyphs:

![Comparison of the changes; top is with freetype's hinted blocks, and the bottom is with wezterm's computed blocks](https://user-images.githubusercontent.com/117777/109428046-0b8b1e80-79aa-11eb-9215-ec05826e712e.png)

Whether this is enabled is controlled by a new option [custom_block_glyphs](https://wezfurlong.org/wezterm/config/lua/config/custom_block_glyphs.html) which defaults to `true`.

<image width="25%" alt="Bender meme: explaining how we're going to do our own block glyphs" src="https://user-images.githubusercontent.com/117777/109427952-9ddef280-79a9-11eb-9b95-54c3911914f2.png">

**Comment by bew** [comment]
Nice! This is great to have perfect glyphs (:

Little observation though, looking at your last screenshot:
For the last 10 columns in the example, it seems like the half blocks takes a little more than half of the block, no?

**Comment by wez** [comment]
> For the last 10 columns in the example, it seems like the half blocks takes a little more than half of the block, no?

Yeah; that's due to rounding up to solves the hinting issue.  I suppose the that we could round up on the exterior edges and round off for interior ones.

**Comment by DONofDESTROY** [comment]
That's actually great, thanks for considering to fix this
