### ISSUE TITLE
Suggestion: Clickable file links

### ISSUE THREAD

**Issue by erf** [wez/wezterm#434]
**Is your feature request related to a problem? Please describe.**

I've been following the project `serenityOS` and in their terminal emulator it is possible click any files or directories to open them by some program based on it's type.

**Describe the solution you'd like**

I'm not sure if this is even possible to implement, but it would be pretty awesome if you were able to configure this in the `.wezterm.lua` file or default to some programs dependent on the  OS.

 E.g. on `macOS` if you'd click a folder in the terminal it would call `open "folder"` to open the folder using `Finder`.

The file links would have a dotted line underneath.

**Describe alternatives you've considered**

I read about [hyperlinks](https://wezfurlong.org/wezterm/hyperlinks.html) but as i understand by this you can only search for patterns in the output, and for my file link suggestion i guess you would need knowledge of the file system..?

**Additional context**

**Comment by wez** [comment]
If you install a new enough version of GNU `ls`, you can run `ls --hyperlink` to have it emit clickable filename links.
It does this using OSC 8 hyperlinks.  Other applications are slowly developing support for this sort of thing; it is the preferred way to do this because the output is semantically annotated to show that it is clickable by an application that knows the correct context.  This also has the potential to work correctly when you're ssh'd into a remote system, as the `file://` URL has a way to encode the hostname (although it doesn't specify *how* to connect to a remote host).

For something more automatic, but less smart, take a look at this config snippet which matches things that look like grep-with-filename-and-line-number or compiler error diagnostics:

https://github.com/wez/wezterm/pull/412#issuecomment-753428584

You could tweak that a bit to match things that look like filenames and make them all clickable in a similar way.

**Comment by erf** [comment]
Ok, thanks. I will look into it.
