### ISSUE TITLE
Don't show window with error when there is a valid font fallback.

### ISSUE THREAD

**Issue by andradei** [wez/wezterm#4341]
**Is your feature request related to a problem? Please describe.**
It is frustrating to have this second window pop up when 1 of the fonts aren't valid the there are valid fallback ones.
I use the same config on Windows and Linux (Linux is fine but on Windows is window always pop up and it's unnecessary)

**Describe the solution you'd like**
Don't show a second window with a font error where there are valid fallbacks.

**Describe alternatives you've considered**
I tried renaming the fonts to have the same name on all platforms but that is hard to do and breaks the ability to update via package CLI tools.

**Additional context**
![image](https://github.com/wez/wezterm/assets/2653546/8e2e1a75-8520-4ca8-97e1-2d2871468730)

**Comment by wez** [comment]
I'm not going to change this behavior, because it is intended to surface issues.
What I'd recommend is that you use either or both of:

* https://wezfurlong.org/wezterm/config/lua/wezterm/hostname.html
* https://wezfurlong.org/wezterm/config/lua/wezterm/target_triple.html

to conditionally set your font fallback to the appropriate value for the different systems that you use.

**Comment by andradei** [comment]
Will take a look at those APIs. Thanks.

**Comment by andradei** [comment]
Update: ended up using `target_triple`. Thanks
