### ISSUE TITLE
Version of `termwiz` crate on crates.io appears to be outdated

### ISSUE THREAD

**Issue by silwol** [wez/wezterm#4352]
I found that the latest version of `termwiz` on crates.io is 0.20.0, whereas the version in the repository is already 0.22.0. Is there a chance that this version can get published to crates.io?

## Context

`termwiz` is a dependency of `zellij`. I'm looking into packaging `zellij` for Debian, and found that `termwiz` 0.20.0 on crates.io depends on some older versions of crates which are packaged in their latest release in Debian already. The standard tooling for packaging crates in Debian pulls them from crates.io. `termwiz` 0.22.0 in the repository looks a lot better in terms of its dependencies, so I'd appreciate an update published to crates.io so that `zellij` can pull in the newer version.

**Comment by chipsenkbeil** [comment]
Bumping this. @wez is there any chance of releasing a new version? Not sure if `0.22.0` is fully ready for a release and what remains to get it there. `distant` and the associated neovim plugin are also needing a newer version of this library, purely due to some limitations with the `terminfo` crate, which you bumped up to `0.8` after the `0.20.0` release.

**Comment by wez** [comment]
Yeah, it's overdue for publishing an update. There's some additional overhead though: I refactored some stuff and now there are a handful of other wezterm-xxx crates that need to be prepped for release to crates.io to support publishing the current version.

**Comment by wez** [comment]
Published termwiz v0.22.0 at registry `crates-io`
