### ISSUE TITLE
Quickselect mode selected option still highlighted after selection

### ISSUE THREAD

**Issue by mgpinf** [wez/wezterm#4359]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230922-143151-0f894d79

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Upon selecting the appropriate item in `QuickSelect` mode, the selection is still highlighted

e.g.:
* Before `QuickSelect`:
<img width="1151" alt="image" src="https://github.com/wez/wezterm/assets/56510798/31d39654-b8df-4684-9c70-6a4df185324f">

* During `QuickSelect`:
<img width="1152" alt="image" src="https://github.com/wez/wezterm/assets/56510798/c59178df-196f-424c-8244-607a1a220700">

* After `QuickSelect`:
<img width="1157" alt="image" src="https://github.com/wez/wezterm/assets/56510798/dbf93553-e87d-43ab-a030-69eaec8d646f">

### To Reproduce

Enter `QuickSelect` mode and select any of the options and notice the difference

### Configuration

```
config.colors = {
  quick_select_label_bg = { Color = palette.foam },
  quick_select_label_fg = { Color = palette.base },
  quick_select_match_bg = { Color = palette.overlay },
  quick_select_match_fg = { Color = palette.foam }
}
```

### Expected Behavior

There should be no highlight once `QuickSelect` mode exits

**Comment by Danielkonge** [comment]
I have a one line change in the source code that fixes this, but I think the behavior is on purpose? It looks like it highlights the selected entry to make it clear what you selected.

I guess a better behavior could be to highlight the selected text for a second or two, and then stop highlighting it. I am not sure what is the best way to do this though, so we should probably wait for wez's feedback.

**Comment by wez** [comment]
It's intentional; QuickSelect is about selecting text after all, and it selected the text and thus the selection is changed to what you selected.  That's helpful particularly in unix environments where it is easy to accidentally override a selection by clicking in the wrong place; you can then simply switch back to wezterm and ctrl-shift-c to re-copy your selection.

If you don't want it to be selected, you can use the `action` in https://wezfurlong.org/wezterm/config/lua/keyassignment/QuickSelectArgs.html to copy it to the clipboard and then ClearSelection.

Something like:

```lua
action = wezterm.action_callback(function(window, pane)
        local text = window:get_selection_text_for_pane(pane)
        window:copy_to_clipboard(text)
        window:perform_action(wezterm.action.ClearSelection, pane)
      end),
```

**Comment by mgpinf** [comment]
Thank you @wez for clarifying, closing the issue. Love wezterm
