### ISSUE TITLE
Add configuration option to avoid "Terminate WezTerm?" pop up on macOS when OS wants to terminate it

### ISSUE THREAD

**Issue by yerke** [wez/wezterm#4362]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that wezterm prevents macOS from restarting the machine automatically by showing me "Terminate WezTerm? Detach and close all panes and terminate wezterm?" popup. For example, when updating the macOS, OS will spend some time downloading the update and then automatically restart. But the restart will fail because of open wezterm.

**Describe the solution you'd like**
Please add a configuration option to not show this popup. This popup behavior is defined [here](https://github.com/wez/wezterm/blob/5e0fd1a06e10d23e2a61696d0b0ebdacffecb661/window/src/os/macos/app.rs#L17).
Thank you in advance!

**Describe alternatives you've considered**

**Additional context**
I do have `config.window_close_confirmation = 'NeverPrompt'` in my config. But that configuration option is doing something else.

P.S. If you are ok with adding this configuration option, but too busy with other things, I can try to submit a PR myself. But I would need to know the name you prefer for it.

![Screenshot 2023-09-29 at 18 09 05](https://github.com/wez/wezterm/assets/5137691/e7e49751-66ed-4133-b222-8bb5cdc61d9f)

**Comment by wez** [comment]
Ideally that popup should get re-routed to the QuitApplication key assignment, but the issue is that that event handler is synchronous and needs to make a response.

If you look at the `QuitApplication` logic, you can see that it checks the existing window_close_confirmation option for this:

https://github.com/wez/wezterm/blob/5e0fd1a06e10d23e2a61696d0b0ebdacffecb661/wezterm-gui/src/termwindow/mod.rs#L2601-L2625

What I suggest, if you want to take a crack at this in a PR is:

* check `config::configuration().window_close_confirmation == WindowCloseConfirmation::NeverPrompt`.  If so, then do the TerminateNow code path.
* Otherwise, instead of showing the popup, do something like:

```rust
conn.dispatch_app_event(ApplicationEvent::PerformKeyAssignment(
    KeyAssignment::QuitApplication,
));
// and return this to prevent immediate exit
NSApplicationTerminateReply::NSTerminateCancel as u64
```

**Comment by eproxus** [comment]
Note that this popup prevents every restart, not just updates. It also appears when right-clicking and selecting Quick on WezTerm in the Dock.

**Comment by quantonganh** [comment]
@wez If we do that, it will be re-routed to [frontend](https://github.com/wez/wezterm/blob/4b3660d166196025d45d97fa29af8e9405b830b5/wezterm-gui/src/frontend.rs?plain=1#L230), and WezTerm will quit immediately, even when `config.window_close_confirmation = 'AlwaysPrompt'`.

**Comment by yerke** [comment]
I tested @quantonganh 's https://github.com/wez/wezterm/pull/4420 and it fixes the problem completely for me.
