### ISSUE TITLE
Open WezTerm here erred.

### ISSUE THREAD

**Issue by Tarocch1** [wez/wezterm#451]
## Describe the bug

Can not open wezterm in root directory (C:\ or D:\) with "Open WezTerm here" in context menu. Normal in non-root directory (C:\Users).

## Environment (please complete the following information):

 - OS: windows 10
 - Version: wezterm 20201101-103216-403d002d

## To Reproduce

Install wezterm, click "Open WezTerm here" in root directory. Then report the following error:

![image](https://user-images.githubusercontent.com/15124068/106744607-ef21ed80-665a-11eb-8286-d3516ac04a3d.png)

Chinese error means "the directory name is invalid".

## Configuration

No configuration file.

## Expected behavior

Open wezterm in root directory correctly.

**Comment by wez** [comment]
Can you try these three cases and let me know which of them succeed/fail for you?

* Right click on the drive letter icon in the "file tree" in the left hand pane and choose "Open WezTerm here"
* Left click on the "This PC" icon in the file tree so that the right hand pane shows your Local Disk C: icon.  Then right click on that drive icon in the right hand pane and choose "Open WezTerm here"
* Left click on the drive letter icon in the file tree so that the right pane shows the contents of C:\.  Then right click on the background of the right hand pane and choose "Open WezTerm here"

Those are the three cases that are setup in the registry and one is subtly different from the others.  Knowing which of them is working or not will help me figure out what's going on.

For what it's worth, all three cases succeed for me, so I wonder if this might be somehow related to locale or similar; my system is a US English system.

**Comment by Tarocch1** [comment]
The first two succeed, the third fails.

**Comment by Tarocch1** [comment]
If I copy `HKEY_CLASSES_ROOT\Drive\shell\Open WezTerm here\command` to `HKEY_CLASSES_ROOT\Directory\Background\shell\Open WezTerm here\command`, the third case will succeed. But it will fail when right click on the background of the right hand pane of `C:\Users` and choose "Open WezTerm here".

If I remove all the quotes and backslashes in registry command, just like:

```
C:\Program Files\WezTerm\wezterm-gui.exe start --no-auto-connect --cwd %V
```

All cases will succeed.

**Comment by flyxyz123** [comment]
> 
> 
> If I copy `HKEY_CLASSES_ROOT\Drive\shell\Open WezTerm here\command` to `HKEY_CLASSES_ROOT\Directory\Background\shell\Open WezTerm here\command`, the third case will succeed. But it will fail when right click on the background of the right hand pane of `C:\Users` and choose "Open WezTerm here".
> 
> If I remove all the quotes and backslashes in registry command, just like:
> 
> ```
> C:\Program Files\WezTerm\wezterm-gui.exe start --no-auto-connect --cwd %V
> ```
> 
> All cases will succeed.

`%V` will not succeed if you right-click at the background of the file explorer at a directory that contains space, for example: `D:\Program Files` and `C:\Program Files`. `"%V` will succeed in all cases. Detail solution please see <https://github.com/wez/wezterm/issues/526> , <https://github.com/alacritty/alacritty/issues/4882#issue-825561096>, and <https://gist.github.com/flyxyz123/53ac952fe94a14482565f1d96e5704d5>
