### ISSUE TITLE
Portable Pty hangs on Windows

### ISSUE THREAD

**Issue by martonlanga** [wez/wezterm#463]
## Describe the bug

I'm using `portable_pty` in my project but having issues reaching EOF on Windows while reading `master.try_clone_reader()`. On Mac it works fine.

## Environment (please complete the following information):

 - OS: Windows 10 19042.746
 - Version: `0.3.1`

## To Reproduce

```rust
  let pty_system = native_pty_system();
  let mut pair = pty_system.openpty(PtySize {
    rows: 50,
    cols: 100,
    pixel_width: 0,
    pixel_height: 0,
  })?;

  let mut cmd = CommandBuilder::new(command);
  cmd.cwd(&cell.current_dir());
  cmd.args(args);

  let mut child = pair.slave.spawn_command(cmd)?;

  // Read an from the pty with reader
  let mut reader = pair.master.try_clone_reader()?;

  thread::spawn(move || {
    let mut chunk = [0u8; 1024];

    loop {
        let len = reader.read(&mut chunk).expect("No error here"); // hangs here at EOF on Windows

        if len == 0 {
          break; // on Mac it gets here and breaks out as expected
        }
        let chunk = &chunk[..len];

        info!("Sending chunk with length: {}", chunk.len());
      }
  });
```

## Expected behavior

The same behavior as on Mac. When reaching `reader`'s End of File, it shouldn't hang and return 0 for the length on Windows. 

## Additional

Maybe I'm just doing something wrong, please let me know if there's a better way to do this.

PS: Thanks for the crate - it's super helpful!

**Comment by wez** [comment]
Take a look at this section of the example:
https://github.com/wez/wezterm/blob/main/pty/examples/whoami.rs#L26-L32

What's happening is that the pty remains alive because there are 1 or more writable handles to it still, so even though you've consumed all of the data that was written, it hasn't reached "EOF" because more data might still be written.

You need to take care to close any pty handles (even the read side) when you no longer need them to avoid this sort of blocking behavior!

**Comment by martonlanga** [comment]
Dropping both the `master` and `slave` handle worked, thanks @wez.

The workaround I found was to check the child using `try_wait` in each iteration and get the remaining chunk by calling `read_to_end`.

```rust
  let mut child = pair.slave.spawn_command(cmd)?;
  let mut master = pair.master;
  let mut reader = master.try_clone_reader()?;
  drop(pair.slave); // dropping master

  thread::spawn(move || {
    let mut chunk = [0u8; 1024];

    loop {
        let len = reader.read(&mut chunk).expect("No error here"); // hangs here at EOF on Windows

        if len == 0 {
          break; // on Mac it gets here and breaks out as expected
        }
        let chunk = &chunk[..len];

        info!("Sending chunk with length: {}", chunk.len());

        // workaround
        if child.try_wait().unwrap().is_some() {
          drop(master);
          // child finished - try to get remaining chunk and break out
          let mut vec = vec![];
          let len = reader.read_to_end(&mut vec);
          info!("Sending last chunk");
          break;
        }
      }
  });

  // can't kill child from outside
  // can't write to master from here
```

The problem I'm having right now, is that I can't write to master from the main thread since the handle is moved inside the child thread and can't be accessed from outside.

How could I go around this problem? I'm using `std::thread` - would `async` be more suitable for what I'm trying to do?

**Comment by wez** [comment]
If you just need to write from another thread, you can [master.try_clone_writer](https://docs.rs/portable-pty/0.3.1/portable_pty/trait.MasterPty.html#tymethod.try_clone_writer) to get another writable handle.
Be careful about closing it when you're done to avoid a similar issue to what you mentioned in the OP.

Otherwise, if you need to kill from another thread, you'll need to wrap up the child in something like `Arc::new(Mutex::new(child))` and share it that way.  Take care to avoid locking the child and calling [child.wait](https://docs.rs/portable-pty/0.3.1/portable_pty/trait.Child.html#tymethod.wait); use only `try_wait` while the lock is held.
(You might need to use the version of portable-pty from master for that to work: https://github.com/wez/wezterm/pull/437 only recently landed and I haven't cut a new release for that crate yet).

regarding async: it might help by forcing you to think a bit differently about the program structure, but it is worth noting that on Windows you cannot use non-blocking IO with PTYs (it's a Windows limitation) so async itself won't automatically resolve anything.

**Comment by martonlanga** [comment]
Just wanted to close this!

Managed to make it work by keeping master in a single thread and sharing child using Mutex. Thanks a lot for your help @wez!
