### ISSUE TITLE
When an external program opens Wezterm

### ISSUE THREAD

**Issue by Songggggr** [wez/wezterm#4631]
When an external program opens Wezterm, disable opening of new window, want only opens the new tab.
How do I configure it

**Comment by wez** [comment]
This sounds like either a question or a bug report, but it has been incorrectly filed as enhancement. I'm going to close this, because it doesn't have enough information to respond to effectively. I'd recommend that you post in the discussions Q&A section, but please be sure to include more information about what you're trying and what you're seeing; please do take the time to fill out any template in posts that you make, because it will save everyone time in the long run.
