### ISSUE TITLE
Background source file optional image filetype parameter

### ISSUE THREAD

**Issue by methanius** [wez/wezterm#4654]
On my work Windows pc, I wanted to configure Wezterm to have the same background as my desktop. I enjoy background slideshows, changing backgrounds every hour or so and was stoked when I found wezterm.add_to_config_reload_watch_list, and by settting 

local wezterm = require("wezterm")
config.background = {
    { source = {
        File = "C:\\Users\\my_username\\AppData\\Roaming\\Microsoft\\Windows\\Themes\\TranscodedWallpaper",
    },
}
wezterm.add_to_config_reload_watch_list("C:\\Users\\my_username\\AppData\\Roaming\\Microsoft\\Windows\\Themes\\TranscodedWallpaper")

I almost got exactly what I wanted. But not quite!

As the filename suggests, Windows transcodes the wallpaper it sets as current background to a local file. However, it sets it without a file-extension, and I couldn't make Wezterm infer the underlying filetype!  I was unable to get around this challenge using only Wezterm functions. Of course, I might have missed something obvious.

I got around that small hiccup by soft symlinking TranscodedWallpaper to TranscodedWallpaper.jpeg and changing both filepaths above to the new symlink, but I would love to be able to keep such hijinks confined to my config!

My immediate thought was that a parameter to config.background[i].source along the lines of "filetype", defaulted to whatever the file-extension of the filepath is, but overwritable, would be a solution I'd love.

If this is something you envision could be a nice addition to Wezterm, I'm prepared to try and make a Pull Request on this and dive into the Rust source code. However, this would be my first pull-request on an open source project and indeed first actual change to a larger Rust code base.  So I'm a bit apprehensive of just diving in head first. Would you be able to guide me to where such a change could be done and the broad strokes of a solution?

**Comment by wez** [comment]
This sounds like a bug report in the guise of a feature request.
I think something else is causing your issues because wezterm doesn't care about the filename extension when handling images; it always decodes the image type from the data in the file that it loads.
I'm going to close this; if you want to follow up on what is going wrong for you, please open a new bug report issue and be sure to share detailed information about the version of wezterm, your configuration and the error logs, which may provide a strong clue about what isn't working.
