### ISSUE TITLE
Hardcoded fonts in wezterm is not the best option

### ISSUE THREAD

**Issue by munzirtaha** [wez/wezterm#4689]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Thanks wez for your great work and support!

I installed wezterm in archlinux to try it and found that it installed `ttf-roboto` and `ttf-jetbrains-mono`. It seems that you are hard coding those fonts, hence, they removed those assets and linked/depended on their packages instead. I don't like the idea that every application install its own font and prefer to choose my own. I cannot argue with them since you are hardcoding it, they would prefer to follow upstream. I know I can compile myself or customized the `PKGBUILD` to remove that dependency but this is not user friendly.

Is there a reason that justifies that `Roboto` font need to be hard coded or is it user preferences? Are you using it for the tab font? It doesn't even respect my default font configuration and take priority over them. Why not just depend on the default system fonts or libraries instead and keep the hard coding to a minimal?

### Configuration

no config

**Comment by rlees85** [comment]
Just started using wezterm instead of kitty and am extremely happy with it. This is also a little nitpick of mine though. The titlebar stands out badly with other windows (I know this is ultimately a Gnome 'feature') but by just allowing the configuration of titlebar font would allow me to at least sort that out (its far too big at the moment).

I also agree with the sentiment about using system defaults - if possible. For the actual terminal font I can see why you are not doing it since you need to use a font by default you KNOW will with with ligatures, etc, but can't see why not for titlebar?

**Comment by munzirtaha** [comment]
@rlees85
> its far too big at the moment ... allowing the configuration of titlebar font

Try `use_fancy_tab_bar = false`

**Comment by rlees85** [comment]
Thanks - I'm using the integrated buttons on the tab bar now which is a bit better. Also the titlebar font can be changed: https://wezfurlong.org/wezterm/config/appearance.html#tab-bar-appearance-colors - my bad.

I'll stop hijacking your thread now! I agree with your points about using system fonts 100%

**Comment by munzirtaha** [comment]
Let's see whether downstream Arch Linux would accept to fix this in the packaging even if it's hard-coded. I explained the issue [here](https://gitlab.archlinux.org/archlinux/packaging/packages/wezterm/-/issues/1)

**Comment by wez** [comment]
In wezterm's pure form, those fonts are not installed on your system, but are embedded into the binary.  If you don't use them you can ignore them.

Some downstream distros choose to unbundle the font, but since it is the default, if you don't have the font installed then wezterm will not work as intended.

wezterm has the same out of the box experience in all 4 of its different operating environments.  The unix based systems are, quite frankly, a huge headache to wrangle and resolve desktop defaults, especially under Wayland, which is not friendly for non-gnome applications.  I have no plans to make any changes to how this works in wezterm; I simply do not have the time, and do not want the additional complexity in this project.

While I understand the desire to minimize dependencies, these fonts are not that large, and I would suggest that you try ignore this issue.

**Comment by munzirtaha** [comment]
I understand and thanks for your response.

> if you don't have the font installed then wezterm will not work as intended.

Can you please give an example where not having the Roboto font make wezterm not work as intended in Linux? Just curious!
