### ISSUE TITLE
Add a keyassignment to toggle font ligatures

### ISSUE THREAD

**Issue by bew** [wez/wezterm#469]
_low priority_

**Is your feature request related to a problem? Please describe.**
Sometimes I want to see the text without any ligatures enabled, either because the ligature is out of place (when doing ascii art for example), the spacing is wrong, moves too much, or I want to really see the real chars, not a nice representation of them.

**Describe the solution you'd like**
A KeyAssignment I cound bind a key mapping to, to toggle between:
- disable all ligatures,
- re-enable what was enabled before

**Describe alternatives you've considered**
Not using ligatures at all, but they are nice to have :)

**Comment by wez** [comment]
See also https://github.com/wez/wezterm/issues/329

I think that the right way to make something like this work is:

* Introduce to the code the concept of a config override, which is effectively a sparse list of config options that you want to change (rather than a completely materialized `Config` that is filled out with defaults for the unspecified configs)
* The terminal window would maintain a window-instance-specific config override that is by default empty
* The actions to alter ligatures, opacity (perhaps there is just a general action to set or unset a config override in the current window instead?) would update that window-instance-specific config override
* config resolution for the window would merge the overrides with the global config in the `config_was_reloaded` method and then keep and use that merged config

For bonus points:

* Using the same override mechanism, there could also be a global config override for CLI arguments to override specific config settings.  Somewhat similar in concept to `ssh -o NAME=VALUE`, that could allow for `wezterm --config NAME=VALUE` overrides.  The difference with this is that the overrides would be applied to the `CONFIG` instance in the config crate after reloading the config file.

**Comment by MuhammedZakir** [comment]
I was thinking of opening an feature request for something similar for overriding local config -- `wezterm eval '<lua code>'`. But `wezterm --config NAME=VALUE` is enough for most use cases.

When I looked the reference doc now, I see that there is no getters for options. It would be great if we can get current values of options. This is pretty useful, for example, using different prompt depending on the font - nerd vs normal.

**Comment by wez** [comment]
https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html shows how you can configure an assignment to make whatever config changes you like; examples for ligatures and opacity are includes

**Comment by bew** [comment]
Very powerful, this is incredible ! :)

**Comment by MuhammedZakir** [comment]
Superb work @wez! 👏 Thanks a lot! 😄
