### ISSUE TITLE
Windows: All Ctrl-Alt-key incorrectly sends Alt-key

### ISSUE THREAD

**Issue by bew** [wez/wezterm#472]
## Describe the bug

TSIA

## Environment

 - OS: Windows (double checked, Linux is ok)
 - Version: 20210203-095643-70a364eb-26-g9bf419eb~

## Configuration

```lua
return {
  -- tested with and without
  use_dead_keys = false,
}
```

## To Reproduce

1. Open an ssh connection to a (linux) server
    _(local shells are also broken w.r.t keys, but I think it's another topic since other terminals have the same behavior)_
2. Open cat
3. Press Ctrl-Alt-z (or any alpha keys)

## Expected behavior

Observe the output `^[z` (Alt-z) instead of `^[^Z` (Alt-Ctrl-z)

**Comment by wez** [comment]
Are you using the left or right alt key?

On Windows, Ctrl-Alt is equivalent to AltGr when using a layout with dead keys because:
https://github.com/wez/wezterm/issues/392 and 
https://github.com/wez/wezterm/commit/79c945a8934d5a870434dd646b1460c487d222a8#diff-d2d2370b4b69c7220ea09cee8adcce177938ed10a0179c1d358591aa1b1a8c93R1512

There's not a lot of really great choices we can make here.

The easiest is to add a boolean config option named something like `treat_left_alt_ctrl_as_alt_gr` so that folks that are running under VNC can opt in to the behavior added in #392 and we can keep the default working as expected for others.

**Comment by wez** [comment]
FWIW, a workaround for the specific sequence you mentioned is typing `ESC CTRL-Z` instead, which emits the same output but is potentially more effort to type.

**Comment by bew** [comment]
> On Windows, Ctrl-Alt is equivalent to AltGr when using a layout with dead keys

😢

Also see #473 issue (when I have `use_dead_keys` enabled)

> The easiest is to add a boolean config option named something like `treat_left_alt_ctrl_as_alt_gr` so that folks that are running under VNC can opt in to the behavior added in #392 and we can keep the default working as expected for others.

That would be helpful yes, Ctrl-Alt => AltGr is counter intuitive as a default IMO.

**Comment by bew** [comment]
For the option naming if you want to go that route, I'd suggest `treat_left_ctrlalt_as_altgr` instead,
to better show that it's ctrl & alt together that are translated as altgr.
