### ISSUE TITLE
document that wezterm.lua may be evaluated multiple times and should be a "pure function" with no global side effects

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#477]
## Describe the bug

Config file is evaluated twice.

## Environment (please complete the following information):

 - OS: Manjaro (X11)
 - Version: 20210203-095643-70a364eb-26-g9bf419eb

## To Reproduce

1. Use below config
2. Run wezterm

Wezterm will log:

```
 2021-02-11T18:09:06.768Z ERROR config::lua > lua: 1. main
 2021-02-11T18:09:06.768Z ERROR config::lua > lua: 2. for loop
 2021-02-11T18:09:06.769Z ERROR config::lua > lua: 3. if, stdout: a

 2021-02-11T18:09:06.803Z ERROR config::lua > lua: 1. main
 2021-02-11T18:09:06.803Z ERROR config::lua > lua: 2. for loop
 2021-02-11T18:09:06.805Z ERROR config::lua > lua: 3. if, stdout: a

```

## Configuration

```
local wezterm = require 'wezterm'

wezterm.log_error('1. main')

for i = 2, 2 do
  wezterm.log_error(i .. '. for loop')
end

local success, stdout = wezterm.run_child_process {"echo", "a"}

if success then wezterm.log_error('3. if, stdout: ' .. stdout) end

return {}
```

## Expected behavior

Config must not be evaluated more than once.

**Comment by wez** [comment]
The config file can be (and is) intended to evaluatable an arbitrary number of times in quick succession due to the way that config loading and multi-threading works; the main body of the config script is supposed to be "functionally pure" in the respect that it shouldn't have global side effects.

What I think you really want is something like an event (using https://wezfurlong.org/wezterm/config/lua/wezterm/on.html) that fires once eg: when wezterm is first started.

We don't currently have such a thing, but could define one for setting up an initial session, which is something that was mentioned [in the matrix room](https://matrix.to/#/!PwBsagvymzymLNQXHO:matrix.org/$m_ZAwBo4TPaNBbg99XTirIMLfhQ4jVMeX-Bip5nElYE?via=matrix.org) today.

**Comment by MuhammedZakir** [comment]
> The config file can be (and is) intended to evaluatable an arbitrary number of times in quick succession due to the way that config loading and multi-threading works; the main body of the config script is supposed to be "functionally pure" in the respect that it shouldn't have global side effects.

Then, there should be a note or warning in doc about this?

> What I think you really want is something like an event (using https://wezfurlong.org/wezterm/config/lua/wezterm/on.html) that fires once eg: when wezterm is first started.
> 
> We don't currently have such a thing, but could define one for setting up an initial session, which is something that was mentioned [in the matrix room](https://matrix.to/#/!PwBsagvymzymLNQXHO:matrix.org/$m_ZAwBo4TPaNBbg99XTirIMLfhQ4jVMeX-Bip5nElYE?via=matrix.org) today.

:+1:

**Comment by wez** [comment]
Let's keep this open to remind me to update the docs
