### ISSUE TITLE
Whole ligature turns black when cursor is on one end, based on the current font

### ISSUE THREAD

**Issue by bew** [wez/wezterm#478]
## Describe the bug

When the cursor is on one end of a ligature, the whole ligature becomes black.
It does NOT happen with all ligatures & all fonts.

## Environment (please complete the following information):

 - OS: Linux X11 (and saw the same on Windows)
 - Version: 20210203-095643-70a364eb-8-gaa75dda1

## To Reproduce

Type `---`, put the cursor on the first dash or the right dash, see that the whole ligature turns black.

It turns out the font configuration changes on which end of the ligature this behavior happens.

Here is with my config, using the font CascadiaCode:

https://user-images.githubusercontent.com/9730330/107719900-8d582800-6cd9-11eb-8843-44cf20b7d162.mp4

Here is with my config, using the font Iosevka:

https://user-images.githubusercontent.com/9730330/107720725-36ebe900-6cdb-11eb-8712-1ae96c9a1e87.mp4

Here is with the default config, default font:

https://user-images.githubusercontent.com/9730330/107720232-3c94ff00-6cda-11eb-809c-be73cac8946c.mp4

## Expected behavior

No black, like with the font Iosevka!

**Comment by wez** [comment]
This issue depends on how a font designer has chosen to implement ligatures.  There are two cases for the `<--` sequence:

* The ligatured sequence maps to a single glyph that is 3x as wide
* cells within the ligatured sequence are individually mapped to alternate glyphs that fit together smoothly to form the overall long arrow glyph

In the former case, there is a single glyph to render and the render logic sets the glyph color to black because the cursor is at the starting position of the ligature.  The shaper doesn't know (or doesn't tell wezterm) about it being logically three distinct glyphs so the whole graphic is rendered with the inverse color.

In the latter case, each glyph is rendered independently and there is no issue with the color appearing to be wrong.

Resolving this is potentially tricky because that first case overlaps with eg: 2x wide emoji sequences that are "atomically" a double wide cell and that should be reversed together (and honestly, the cursor width in that case should probably also be double wide, which it isn't today).

There may be a reasonable heuristic to be employed based on comparing the number of cells that a shaped sequence spans and the number of graphemes in those cells, and then artificially slicing up the glyph sprite on cell boundaries.

**Comment by bew** [comment]
Doesn't looks completely fixed for me:
https://user-images.githubusercontent.com/9730330/108980507-079a8c00-768c-11eb-9f6d-072616b54493.mp4

Using the latest nightly (with all the commits referencing that issue)

**Comment by bew** [comment]
Also I get visual artifacts when typing chars that changes to a ligature, see this video:


https://user-images.githubusercontent.com/9730330/108996912-4a199400-769f-11eb-91e8-a9183b362de3.mp4



At the beginning I'm typing `cd .. .. .. ..`
And later I'm typing `- -- --- --- --` etc..

I'm using the font CascadiaCode if you want to try it out: https://github.com/microsoft/cascadia-code

**Comment by wez** [comment]
I believe that this is now resolved again in the nightly!

**Comment by bew** [comment]
It looks perfect, congrats on this!
Thank you :)

**Comment by wez** [comment]
@p00f reports: 

![image](https://user-images.githubusercontent.com/117777/109433136-a9d7ae00-79c3-11eb-935e-9b9188263136.png)

That's with Fira Code and the `...` ligature.
I need to nail down the precise cause of this; re-opening so that I don't forget!

**Comment by kaddkaka** [comment]
I'm not sure if this has been fixed or closed as non-fix due to the font issue mentioned. So, sorry if this information is irrelevant:

When hovering over the last char in this `&&&` ligatures, all chars become black. I think this is FiraCode font because I did not make any setting changes for font.
![wezterm_ligatures](https://user-images.githubusercontent.com/4508793/116663909-07728180-a998-11eb-8d6f-c5c3752c1e00.png)

**Comment by MuhammedZakir** [comment]
It's happening again. According to `wezterm ls-fonts`, wezterm is using default font, Jetbrains Mono.

Version: `20210613-090629-c80cb73c` (latest nightly)
OS: Manjaro (X11)

**Comment by follower** [comment]
Oh, yeah, I encountered this behaviour with a recent nightly (`wezterm 20210929-205847-2820b2c3`) and it was *super* confusing! :D

I'm using the color scheme "Builtin Solarized Dark" (with default steady block cursor & default ` BuiltIn "JetBrains Mono"`) and I first encountered this issue while editing the equivalent of `/tmp/foobar/` to be `/tmp/foo*/` where I was _mystified_ by why the asterisk suddenly disappeared when the cursor was on the trailing `/`! (In fact I just noticed/recalled that the asterisk doesn't appear _at all_ when the cursor is on top of it.)

I dismissed it as unknowable mystery until I noticed a similar issue with e.g. `--help` & suddenly thought it might be ligature related, searched & found this issue...

So, ummm, still happening, I guess? :)

**Comment by bew** [comment]
Thank you @wez 😃
Validated on Linux & Windows!
⚠️ Edit: it seems to only work when the cell has a non-default fg-color:
![image](https://user-images.githubusercontent.com/9730330/135988258-2acfa692-b08a-4e90-b56f-3e104a634664.png)
⚠️ And without fg color, the ligature completely disappears!!
![image](https://user-images.githubusercontent.com/9730330/135988391-9c4f6316-6db9-4710-8e20-655da755e420.png)
👉 I think it'll be auto-solved by using the configured cursor fg, see below.

---
However I think it should use cursor fg instead of the cell fg, no?
On text, uses configured cursor fg:
![image](https://user-images.githubusercontent.com/9730330/135987073-53c44de7-5ed0-4abc-bed4-e467303d2769.png)
On ligature, uses cell's fg:
![image](https://user-images.githubusercontent.com/9730330/135987003-8411070b-d872-48ef-9496-0892500b117d.png)
This is problematic when the ligature is white and the cursor bg is white --> I don't see the current char anymore:

**Comment by bew** [comment]
(sorry to say that, but) I think the 'fixed' UX is worse than before, and unless you plan to find a better solution before the next release, I think it would be safer to revert it, don't you think?

**Comment by wez** [comment]
This should now actually be truly resolved in `main`, and it does so without disabling ligatures

**Comment by bew** [comment]
YYYEEESSSS
![foo](https://user-images.githubusercontent.com/9730330/152668215-308a9e1e-03a5-49f6-a9bb-a71672bb4aeb.png)

\o/
