### ISSUE TITLE
`one_shot` not working when using `set_config_overrides` in action

### ISSUE THREAD

**Issue by sceneq** [wez/wezterm#4804]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240111-073635-6c36a4dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using set_config_overrides within a wezterm.action_callback, the one_shot attribute in the key binding seems to be ignored.

### Configuration

```lua
local wezterm = require "wezterm"
local act = wezterm.action

local function increase_opacity(delta)
  return wezterm.action_callback(function(win, _)
    local overrides = win:get_config_overrides() or {}
    overrides.window_background_opacity = (overrides.window_background_opacity or 1) + delta

    -- Replace this method with "print" and `one_shot = false` will work.
    win:set_config_overrides(overrides)
  end)
end

return {
  keys = { mods = "LEADER", key = "o", action = act.ActivateKeyTable { name = "opacity", one_shot = false } },
  key_tables = {
    opacity = {
      { key = "k", action = increase_opacity(0.1) },
      { key = "j", action = increase_opacity(-0.1) },
    },
  },
}
```

### Expected Behavior

The key table remains active and does not revert back to the default after an action involving set_config_overrides is executed  when one_shot is set to false.

**Comment by wez** [comment]
All key table state is intentionally cleared/cancelled out when the config is changed as a way to help you get unstuck if you move to a config where you might otherwise be left in a state that you cannot get out of.

This is documented https://wezfurlong.org/wezterm/config/key-tables.html#key-table-activation-stack

Config overrides are a form of config reloading, which is why this happens in this case.
