### ISSUE TITLE
Improve support hot-reloading the DPI value

### ISSUE THREAD

**Issue by rr-** [wez/wezterm#4806]
**Is your feature request related to a problem? Please describe.**
I'm viewing my screen at different physical distances throughout. the day. To ensure the characters stay readable when I'm at greater distances, I am switching my screen DPI at runtime to decrease or increase glyph size across the system and all of its apps. In wezterm's case, I'm updating the `config.dpi` value to either 96 or 144.

**Describe the solution you'd like**
I'd like for the `dpi` option to update my current terminal window with the new size, while respecting `config.adjust_window_size_when_changing_font_size = false`. Currently it's not happening – the option seems to be ignored.

**Describe alternatives you've considered**
I tried to spawn a new `wezterm` window to see the changes and surprisingly, not only the newly spawned window had the right DPI, but it also _retroactively updated the existing terminal window_ (but not changing the canvas size the right way).

**Additional context**
I use `config.adjust_window_size_when_changing_font_size: false` setting.
I also use bspwm, which is a X11-based tiling window manager, similar to the better-known i3.
I use wezterm 20230712-072601-f4abf8fd.

**Comment by wez** [comment]
DPI is associated with the physical display characteristics and, depending on the platform, is super awkward to deal with and may be sticky process-wide in some scenarios.

For your use case I would suggest changing the font size rather than the DPI, or using the built-in https://wezfurlong.org/wezterm/config/lua/keyassignment/IncreaseFontSize.html and https://wezfurlong.org/wezterm/config/lua/keyassignment/IncreaseFontSize.html assignments if you don't want to vary the font size.

**Comment by wez** [comment]
And for clarity and transparency: I have no plans to make DPI flexible, it is already fairly complex and it is possible to achieve your use case with the existing font_size option which can be changed very simply and dynamically.
