### ISSUE TITLE
Gradient grainy after window resize

### ISSUE THREAD

**Issue by mike-lloyd03** [wez/wezterm#4813]
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

N/A

### WezTerm version

20240119-085217-24115049

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I searched around because I was sure someone else would have had this problem already but I didn't find anything. Sorry if I missed it.

When using `window_background_gradient`, the gradient doesn't recalculate on window resize and ends up being grainy. Reloading the config file after resizing fixes it but the only way I can see to do that is to make a change to the config file and revert it.

![image](https://github.com/wez/wezterm/assets/49411532/c4c8243a-8193-42c1-9c8f-2da7baf9e8e1)

Is there something I can call on the `window-resized` event that would fix this? I tried `wezterm.on("window-resized", wezterm.reload_configuration)` but that didn't help.

### To Reproduce

1. Define a `window_background_gradient` in the config file.
2. Resize the current wezterm window
3. Gradient does not recalculate after resize

### Configuration

```lua
local wezterm = require("wezterm")
local act = wezterm.action
local config = {}

config.font = wezterm.font("JetBrainsMonoNL Nerd Font Mono")
config.hide_tab_bar_if_only_one_tab = true
config.enable_wayland = true
config.enable_scroll_bar = false
config.window_decorations = "RESIZE"
config.window_padding = {
    left = 0,
    right = 0,
    top = 0,
    bottom = 0,
}
config.window_background_gradient = {
    orientation = "Vertical",
    colors = {
        "#1a1c23",
        "#343434",
        "#1a1c23",
    },
}

config.color_scheme = "Catppuccin Mocha"

config.keys = {
    { key = "c", mods = "CMD|SHIFT", action = act.CopyTo("Clipboard") },
    { key = "v", mods = "CMD|SHIFT", action = act.PasteFrom("Clipboard") },
    { key = "w", mods = "CMD|SHIFT", action = act.CloseCurrentTab({ confirm = true }) },
}

return config

```

### Expected Behavior

The gradient should recalculate when the window is resized.

**Comment by wez** [comment]
Yeah, this is expected: gradients compute a bitmap image on startup, which is then treated similarly to attaching an image in the background.  That computed image will persist until the config is reloaded.

Note that you can force a config reload with `CTRL-SHIFT-R` in the default key assignments, or open the command palette with `CTRL-SHIFT-P` and choose "Reload Configuration".

**Comment by mike-lloyd03** [comment]
Works for me. Thanks man.

**Comment by peiart99** [comment]
>Is there something I can call on the window-resized event that would fix this? I tried wezterm.on("window-resized", wezterm.reload_configuration) but that didn't help.

Yes, in fact I came across this issue about 5 minutes ago (that's why I am here right now) and you had the right idea. So for anyone coming here in the future not satisfied with manual reloading, this is what worked for me:
```lua
wezterm.on('window-resized', function(window, pane)
    wezterm.reload_configuration()
end)
```
It seems to work as intended. Please let me know if there is a more efficient way to do this, I just quickly threw it together according to the docs. 

The only downside of this is the fact that reloading the configuration along with the gradient bitmap causes some graphical glitches during the act of resizing by dragging your mouse. It is because the ``window-resized`` event happening constantly during that process is invoking the reload multiple times. I imagine it isn't as taxing on systems that are a bit  more modern than what I have, but I can't confirm it right now.

The extent to which this is a problem really varies depending on how you operate with your windows. Personally I don't ever do live resizing with my mouse, I checked how it works just for the sake of testing. If all you need is to go from a small window to fullscreen and vice versa, it will work fine. But please keep in mind that if you use the resize feature a lot, reloading the whole configuration every time the window size changes is not the ideal approach, even if you don't notice it.
