### ISSUE TITLE
azerty: altgr and numpad are ignored

### ISSUE THREAD

**Issue by barmic** [wez/wezterm#4864]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3 on Debian 12 and Ubuntu 23.10

### WezTerm version

`20240125-231438-7f3a8355`

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Since yesterday AltGr and Numpad are both ignored in wezterm. It's work on others graphicals interfaces and others terminal emulator so it seem's not from my config.

### To Reproduce

On my european keyboard (pc105 fr/oss compose:rwin terminate ctrl_alt_bksp):

`AltGr + é` (or 2), the third key of line between F1 and azerty line should insert `~` but insert `é` (same if I put without AltGr).

### Configuration

reproduced without config

### Expected Behavior

`AltGr + é` (or 2), the third key of line between F1 and azerty line should insert `~` but insert `é` (same if I put without AltGr).

### Logs

```
09:55:39.959  ERROR  config::config > Your configuration specifies color_scheme="Bespin" but that scheme was not found
09:55:39.998  ERROR  config::config > Your configuration specifies color_scheme="Bespin" but that scheme was not found
09:55:40.065  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: get_appearance.read_setting: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```

### Anything else?

I rollback to `wezterm 20230712-072601-f4abf8fd` and it's work for me.

**Comment by wez** [comment]
I believe that this is resolved in the nightly build, which is currently being built out by CI.
I tested the ~ key, but since my keyboard doesn't have a numpad, I haven't directly tested whether this resolves the numpad issue you mentioned.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by barmic** [comment]
On version `wezterm 20240126-065150-d8228336` I can't reproduce the problem. All is ok for me :)

Thanks for your quick fix

**Comment by barmic** [comment]
Arf I speak too early, now it's seems to be Ctrl + r that don't work. I'm sorry to can't be more helpful with a patch but I'm very noob in rust.

**Comment by wez** [comment]
Please provide more information about the ctrl-r issue; what happens, what did you expect to happen and so on.

On my system, if I set the layout to azerty, pressing ctrl-r activates the backwards history search in my shell, which is consistent with how it behaves in my normal us layout.

Please launch wezterm like this: `wezterm -n --config debug_key_events=true` and share its output when you press ctrl-r.

**Comment by barmic** [comment]
Really sorry for my bad description and on my current computer I don't have the problem.
I close it. Have a nice day
