### ISSUE TITLE
MacOS: Weird font/unicode artifacts after update

### ISSUE THREAD

**Issue by cartesius68** [wez/wezterm#4882]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240127-113634-bbcac864

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

After an update to `wezterm 20240127-113634-bbcac864` I cannot use wezterm anymore.
Weird flickering artifacts for Ubuntu Mono or JetBrains Mono NL font. For example, I run vim, quit and some characters in the previous terminal state flicker for a second.

**Crossed squares randomly appear for a split second... even when window not focused.**

Even overall font rendering seems a bit changed.

Until resolved switching tu Kitty, sigh.....

MacOS Sonoma 14.3 (everything up to date), M2 Mac Mini

### To Reproduce

1. Run terminal
2. Start vim
3. Close vim
4. See how some chars flicker

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This table will hold the curation.
local c = {}

-- In newer versions of wezterm, use the c_builder which will
-- help provide clearer error messages
if wezterm.c_builder then
        c = wezterm.c_builder()
end

-- This is where you actually apply your c choices
c.default_prog = { "/opt/homebrew/bin/fish", "-l" }

--c.color_scheme = "Bamboo"
c.color_scheme = 'Cobalt 2 (Gogh)'

--c.font = wezterm.font("UbuntuMono Nerd Font Mono")

c.font = wezterm.font('JetBrains Mono NL')
--c.font = wezterm.font('Monaco')
--c.font = wezterm.font("Cascadia Code", {weight="DemiLight", stretch="Normal", italic=false})
--c.font = wezterm.font("Cascadia Code", {weight="Regular", stretch="Normal", italic=false})
--c.font = wezterm.font("Cascadia Code", {weight="DemiLight", stretch="Normal", italic=false})
c.font_size = 19
c.line_height = 1.08

c.initial_rows = 40
c.initial_cols = 140

c.harfbuzz_features = { "calt=0", "clig=0", "liga=0" }

c.keys = {
        {
                key = "a",
                mods = "CTRL|SHIFT",
                action = wezterm.action.ToggleFullScreen,
        },
}

-- and finally, return the curation to wezterm
return c
```

**Comment by wez** [comment]
Try setting `front_end = "OpenGL"`

**Comment by cartesius68** [comment]
Hi Sir,

Unfortunately, it's unrelated. No matter whatever `front_end` is used. But was lucky to capture a screen recording:

[wezterm-bug.webm](https://github.com/wez/wezterm/assets/107204517/c5ae0982-9837-4067-8043-49c28ca413d9)

**Comment by wez** [comment]
can you confirm that the front end setting was picked up? You have to restart wezterm for it to take effect

**Comment by wez** [comment]
You can see which is used by opening the debug overlay: CTRL-SHIFT-L and it will show information about your graphics setup, please share that here

**Comment by cartesius68** [comment]
Same behavior even with `front_end = 'Software'`. Can reproduce that each time. Feels deterministic to me.

For the `front_end = 'OpenGL' I get:

```
Debug Overlay
wezterm version: 20240127-113634-bbcac864 aarch64-apple-darwin
Window Environment: macOS 14.3 (23D56)
OpenGL: Apple M2 Pro 4.1 Metal - 88
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
```

**Comment by wez** [comment]
Ah, looking closely, that flash is the deferred/asynchronous loading of the glyphs when the glyphs are not covered by the fonts listed in your config.
You can resolve this by adding the relevant fonts to https://wezfurlong.org/wezterm/config/lua/wezterm/font_with_fallback.html and using that instead of `wezterm.font`.

Why is this more obvious in this release? Part of resolving [#4099](https://github.com/wez/wezterm/issues/4099) [#849](https://github.com/wez/wezterm/issues/849) means that the fallback font resolution is now slightly more expensive so your chances of observing the intermediate placeholder glyph are higher than in previous versions.

Why is it ok before running vim, and not after? Since you are editing your wezterm lua file there, saving it causes a reload and flushing of the various cached information about your font(s), so it has to be resolved again.

What I suggest is this:

* Run `wezterm ls-fonts --text "PASTE THOSE FLICKERING CHARACTERS HERE"`
* That will show you what font gets resolved for them
* Change your config to use `wezterm.font_with_fallback`, with your preferred font at the start of the list, and the supplemental fonts shown by `wezterm ls-fonts` listed after it

**Comment by cartesius68** [comment]
Closing the issue. Behavior explained. Great work anyway!
