### ISSUE TITLE
tab:get_current_working_dir() not returning URI string, and returns a different format.

### ISSUE THREAD

**Issue by BrendanRomanDev** [wez/wezterm#4911]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240129-220340-47f647ca

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

## OS: Mac OS Sonoma 14.3

I updated today from version `20230712-072601-f4abf8fd` to version  `20240128-202157-1e552d76`, and noticed one of my config functions was no longer working. 

I like my tab titles to update to the 'update-status' event, which I have firing every 10 seconds. I had trouble getting this implementation to work with the `format-tab-title` event, so on my previous version `20230712-072601-f4abf8fd`, I wrote this solution.

```lua
--  Update tab titles based on cwd of active pane
wezterm.on("update-status", function(window)
    local active_pane = window:active_tab():active_pane()

    if not active_pane then
        wezterm.log_info("no pane sorry")
        return
    end

    local cwd = active_pane:get_current_working_dir()
    local curr_tab_title = active_pane:tab():get_title()
    local new_tab_title = string.match(cwd, "/([^/\\]+)[/\\]?$")

    if curr_tab_title ~= new_tab_title then
        window:active_tab():set_title(new_tab_title)
    end
end)
``` 

This worked no problem, until today's update. After toying around with this, I realized that pane:get_active_working_dir() format has changed, but it also no longer returns a string [as mentioned in the docs](https://wezfurlong.org/wezterm/config/lua/pane/get_current_working_dir.html). 

In order for my implementation to work, I had to convert `cwd` to a string first. It also appears that the working dir file format output has _changed_, so I also needed to change my regex to a more generic one. 

These adjustments work in my latest update to version  `20240128-202157-1e552d76`.

```lua
-- Update tab titles based on cwd
wezterm.on("update-status", function(window)
    local active_pane = window:active_tab():active_pane()

    if not active_pane then
        wezterm.log_info("no pane sorry")
        return
    end

    local cwd = tostring(active_pane:get_current_working_dir())
    local curr_tab_title = active_pane:tab():get_title()
    local new_tab_title = cwd:match("/([^/]+)$")

    if curr_tab_title ~= new_tab_title then
        window:active_tab():set_title(new_tab_title)
    end
end)
```

If this intentional, then this is just reporting that the docs are stale. If not, it's an issue worth raising! It could be possible that I'm missing something, so I'm open to that possibility as well.

### To Reproduce

1. Using version 

### Configuration

See above for my configuration functions

### Expected Behavior

pane:get_current_working_dir() is expected to output a string.

**Comment by wez** [comment]
docs:
![image](https://github.com/wez/wezterm/assets/117777/c3097aef-ce85-4dab-abf2-40750ed5be45)
changelog:
![image](https://github.com/wez/wezterm/assets/117777/a10cd4c2-48e3-419b-a9fd-3dbc18f3db79)

See example on https://wezfurlong.org/wezterm/config/lua/window/set_right_status.html for forward/backward compatible usage

**Comment by ModProg** [comment]
Oh this also send me searching, being at the bottom of that page I didn't actually see it until I found this issue.

**Comment by BrendanRomanDev** [comment]
Whew. Apologies @wez.

Intuitively I figured more recent changes would be higher up on the docs page. Closing as it seems. You've got it covered. Thanks much!

**Comment by wez** [comment]
These sorts of living documents are tricky to balance: during development it's important to indicate the new behavior in the nightly builds, so putting that at the bottom seems reasonable.  When I cut a release I have automation to update the nightly tags to the current release.  At that point, yeah, perhaps the docs should get reviewed/revised to improve the order of the information, but the reality is that I'm generally very time constrained and such an effort is usually more complex than cut-and-paste to re-order the content, especially if it has been some time since a feature was merged, and we're looking at more than an hour of additional work around each release which is time that I just don't have.

Could this sort of thing be made more prominent somewhere? Maybe, but probably no: I'm at peace with the fact that some folks won't even read the changelog which is intended to serve exactly that purpose, or won't notice the changes in the changelog because the information density is so high, and for similar reasons, that they won't notice version dependent text in the main body of the docs either. I've learned over the years that you cannot cover everything that everyone missed in the docs; I've had someone complain that there is too much information on the same page where someone else complains that there is not enough information.

What that means to me is that spending more time than I do already on docs doesn't necessarily translate into more people actually succeeding in figuring things out, and may in fact hinder them, so I don't beat myself up over the state of it, and I'm totally fine with issues like this being filed to more succinctly phrase a question and provide its answer.

So, thanks for opening this!
