### ISSUE TITLE
win 11 wsl2 arch linux wezterm image preview on ranger wrongly positioned

### ISSUE THREAD

**Issue by glyh** [wez/wezterm#4913]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

The above doesn't apply.
I'm on Arch Linux on WSL2 on Windows 11.

`Linux mechrevo 5.15.133.1-microsoft-standard-WSL2 https://github.com/wez/wezterm/issues/1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux`

Windows 11 v22H2(22621.1265).

wezterm is installed on windows 11 while I'm invoking the command via something like wezterm.exe ....

### WezTerm version

wezterm 20240129-220340-47f647ca

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When previewing image in ranger with iterm2 protocol, wezterm doesn't display image in the correct position. 

### To Reproduce

1. Install ranger on arch linux WSL2, and wezterm on Win11. 
2. have `set preview_images_method iterm2` in local rc.conf
3. use ranger to preview image

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

config.default_prog = { 'D:\\Apps\\ArchWSL\\Arch.exe' }

config.font = wezterm.font 'FiraCode Nerd Font'

-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

Image positioned correctly

### Logs

14:21:08.543  WARN   wezterm_term::terminalstate::performer > ST never received for pending tmux title escape sequence: ""
14:21:08.544  WARN   wezterm_term::terminalstate::performer > ST never received for pending tmux title escape sequence: ""
14:21:10.451  WARN   wezterm_term::terminalstate::performer > ST never received for pending tmux title escape sequence: ""
14:21:10.451  WARN   wezterm_term::terminalstate::performer > ST never received for pending tmux title escape sequence: ""

**Comment by glyh** [comment]
Looks like here's a potential solution but I don't know how to get the size of the terminal's font:
https://github.com/ranger/ranger/issues/2758#issuecomment-1782551663

**Comment by wez** [comment]
On Windows, ConPTY can interfere with image protocol escape sequences.
https://wezfurlong.org/wezterm/what-is-a-terminal.html#windows-and-conpty has more information about conpty.
What I'd suggest as a way to test for this is to use `wezterm ssh` to connect into your WSL instance and see if things suddenly start working.

If that is the case, then you can use the integrated support for parsing your ssh config together with:
https://wezfurlong.org/wezterm/config/lua/config/default_domain.html and the name of the SSH domain you see if you run https://wezfurlong.org/wezterm/config/lua/wezterm/default_ssh_domains.html.

eg: if you add `Host wsl` to your .ssh config and configure it to get into your WSL instance, you can set `default_domain = 'SSH:wsl'` to make wezterm connect directly to it. I recommend pairing that with ssh key based authentication so that you don't have to type a password every time.

**Comment by glyh** [comment]
I tried to ssh on my local wsl instance, the issue doesn't seem to be solved. In ranger preview the image is still positioned incorrectly.

**Comment by wez** [comment]
Please capture a terminal recording:

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by glyh** [comment]
Does asciinema deal with image displayed in terminal?

**Comment by wez** [comment]
asciinema is not involved here. `wezterm record` records the output and saves it in the asciicast format, which lets me see what is being send by the program you are running.

**Comment by glyh** [comment]
I'm having more troubles. I can't type correctly when using wezterm record. Don't know if the issue is from fish shell or wsl or whatever. Also my system just break for no reason, I need to investigate this and will reach back for you later. This might be more issues coming lol.

**Comment by glyh** [comment]
Here's a screen record. I just file another issue as wezterm record is unusable for my case. 


https://github.com/wez/wezterm/assets/12870742/73acb668-f4ba-460c-bd90-9259efd5777f

**Comment by wez** [comment]
try using the AppImage linux version to perform the `wezterm record`

**Comment by glyh** [comment]
There's only appimage for ubuntu 20.04, I'm firstly not on 20.04 but also would like a solution for windows wezterm rather than passing through X.

**Comment by glyh** [comment]
The problem here is that there's 2 wezterm on my computer now. One is on win11 another is in WSL. The above recorded information is from the WSL wezterm and `wezterm record` also uses the WSL version. I wonder if that will cause inconsistency as the bug comes from the windows version.

**Comment by wez** [comment]
I need you to confirm how you are sshing into the WSL instance. What I said in https://github.com/wez/wezterm/issues/4913#issuecomment-1919211207 gave some specific instructions to bypass conpty, but it's not clear to me that you understood and followed those instructions.

A very test I would you to try now is to run this from the Windows side: `wezterm-gui.exe ssh HOSTNAME:PORT` where `HOSTNAME` and `PORT` are the appropriate things for your WSL instance.

Using that will bypass conpty.

Then run ranger and see if the image ends up in the right place.

I also want to note that if ranger is a native win32 program (eg: it is ranger.exe) then it will pull in conpty anyway.

If you are using `wezterm ssh` and the image is in the wrong place then I would like to see a screen shot of it.
Otherwise: what you are experiencing is a conpty issue and has the same resolution as https://github.com/wez/wezterm/issues/1236#issuecomment-1000371490

**Comment by glyh** [comment]
Yeah it does show up in the correct position when using `wezterm-gui.exe ssh`, But the image is too small:
![83{ G8@BEC85)ZC289A)P K](https://github.com/wez/wezterm/assets/12870742/2976c857-5348-407c-b939-f7ccf5b222d4)

**Comment by glyh** [comment]
I guess for now for a workaround I have to ssh into my wsl instead of invoking wsl instead? And should I leave this open or close this?

**Comment by wez** [comment]
Things are working about as well as they can be; once conpty supports passthru, things will work better.
That is outside of the control of wezterm.
This general class of conpty and image protocol issue is covered sufficiently in other open issues, so I'm going to close this one.
