### ISSUE TITLE
Animating the palette inconsistently rerenders

### ISSUE THREAD

**Issue by chadaustin** [wez/wezterm#4932]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240128-202157-1e552d76

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

xterm and others support palette animation with the `initc` and `oc` capabilities. WezTerm also supports these escape codes, but the window is not fully redrawn as expected.

### To Reproduce

Run palettetest.rs, available at `https://gist.github.com/chadaustin/7046bff2261b0f669d223a88ecad8282`

### Configuration

no config

### Expected Behavior

I would expect WezTerm to behave like xterm here: the background colors animate dynamically as the program outputs its `initc` escape sequences.

Actual behavior is no animation, unless you start typing over the program, in which case some lines animate and some don't.

**Comment by wez** [comment]
Thanks for the report!

It should have worked, but there were two bugs preventing it from taking effect:
* the `PaletteChanged` event wasn't propagating all the way to the right spot in the gui layer, so the logic that should have handled it and invalidated the window was never called
* Even with that plumbed, the palette was not part of the cache key used for the quads that comprise the line, so a cached version of the line was used.  I've fixed this by explicitly invalidating the shape cache, which is an overly strong effect, but I couldn't quickly come up with a suitably cheap way of factoring the palette into the cache key.

This is resolved for me now in `main`; that should start to filter down to nightly builds within about an hour.

I think this may also be the same root cause as https://github.com/wez/wezterm/issues/2635 so you are officially at least a 2x engineer :-p

**Comment by chadaustin** [comment]
That was fast, @wez! Thanks!
