### ISSUE TITLE
`divine_process_list().foreground` always gives the shell

### ISSUE THREAD

**Issue by crides** [wez/wezterm#4993]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

awesomewm

### WezTerm version

not a upstream version; based on `a7d9cfd25`

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`LocalPane::divine_process_list().foreground` always seems to return the shell. 

I'm doing this: 
```rust
        let proc_list = self.divine_process_list(CachePolicy::FetchImmediate);
        dbg!((self.pane_id(), proc_list.as_ref().map(|p| &p.foreground.argv), self.get_foreground_process_name(CachePolicy::FetchImmediate), self.get_foreground_process_info(CachePolicy::FetchImmediate).as_ref().map(|p| &p.argv)));
```

with neovim open, what I get is:
```
[mux/src/localpane.rs:821] (self.pane_id(), proc_list.as_ref().map(|p| &p.foreground.argv),
    self.get_foreground_process_name(CachePolicy::FetchImmediate),
    self.get_foreground_process_info(CachePolicy::FetchImmediate).as_ref().map(|p|
            &p.argv)) = (
    0,
    Some(
        [
            "/home/steven/.local/bin/nu",
        ],
    ),
    Some(
        "/usr/bin/nvim",
    ),
    Some(
        [
            "nvim",
        ],
    ),
)
```

I don't think nushell is the problem here, because bash and zsh both give this:
```
[mux/src/localpane.rs:821] (self.pane_id(), proc_list.as_ref().map(|p| &p.foreground.argv),
    self.get_foreground_process_name(CachePolicy::FetchImmediate),
    self.get_foreground_process_info(CachePolicy::FetchImmediate).as_ref().map(|p|
            &p.argv)) = (
    1,
    Some(
        [
            "/usr/bin/python3",
            "-c",
            "import sys; sys.path = [p for p in sys.path if p != \"\"]; import neovim; neovim.start_host()",
            "/home/steven/dotfiles/config/nvim/plugged/semshi/rplugin/python3/semshi",
        ],
    ),
    Some(
        "/usr/bin/nvim",
    ),
    Some(
        [
            "nvim",
        ],
    ),
)
```

Okay maybe `semshi` (a vim plugin for python stuff) is doing weird stuff, so I tried `ed`:
```
[mux/src/localpane.rs:821] (self.pane_id(), proc_list.as_ref().map(|p| &p.foreground.argv),
    self.get_foreground_process_name(CachePolicy::FetchImmediate),
    self.get_foreground_process_info(CachePolicy::FetchImmediate).as_ref().map(|p|
            &p.argv)) = (
    0,
    Some(
        [
            "/home/steven/.local/bin/nu",
        ],
    ),
    Some(
        "/usr/bin/ed",
    ),
    Some(
        [
            "ed",
        ],
    ),
)
[mux/src/localpane.rs:821] (self.pane_id(), proc_list.as_ref().map(|p| &p.foreground.argv),
    self.get_foreground_process_name(CachePolicy::FetchImmediate),
    self.get_foreground_process_info(CachePolicy::FetchImmediate).as_ref().map(|p|
            &p.argv)) = (
    1,
    Some(
        [
            "/usr/bin/bash",
        ],
    ),
    Some(
        "/usr/bin/ed",
    ),
    Some(
        [
            "ed",
        ],
    ),
)
```

### To Reproduce

1. add the above code somewhere and a keybinding to trigger it
2. run some persistent stuff and press the binding to trigger the debug

### Configuration

no config other than the keybind

**Comment by wez** [comment]
Can you share more about how this bubbled up and caught your attention?
The `foreground` concept in that particular function is really only there to approximate the actual posix foreground process concept when running on Windows.

I wouldn't expect this to matter to you on Linux, so I'm wondering if there is another issue at play here and that this (or rather, the bug in reading the proc information you fixed in #5001) is a second-order bug.

**Comment by wez** [comment]
Keeping this open for now, as I think there is also something else happening in this situation and I'd like to understand it!

**Comment by crides** [comment]
> Can you share more about how this bubbled up and caught your attention?

I.. am trying to add a resurrect feature to wezterm, and I used `divine_process_list` to get the root/shell and foreground processes so I know how to restore things. I realized later that I just need the root process though

**Comment by wez** [comment]
I see, so you're calling `divine_process_list` in new code.  It wasn't really intended to be used 100% in isolation on unix for code that cares about the foreground process.  If you look at `get_foreground_process_info` you'll see that it obtains the `process_group_leader` before falling back to `divine_process_list`.  If we do end up needing a reliable and correct foreground process field in `CachedProcInfo` on unix, then we should probably internalize that `process_group_leader` handling and use that instead of the logic that compute the youngest process.
