### ISSUE TITLE
MacOS cannot find config in different location

### ISSUE THREAD

**Issue by huantrinh1802** [wez/wezterm#4998]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22 aarch64-apple-darwin

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I want to use custom location for my configuration file (in a git repo without using symlink). I have configured both `$XDG_CONFIG_HOME` and `$WEZTERM_CONFIG_FILE` but Wezterm doesn't pick up the config file. The only place that works is `.config/wezterm/wezterm.lua`

### Configuration

```lua
local wezterm = require 'wezterm'

-- This will hold the configuration.
local config = wezterm.config_builder()
wezterm.log_info('Config file ' .. wezterm.config_file)
-- This is where you actually apply your config choices

-- For example, changing the color scheme:
config.color_scheme = 'Solarized Dark - Patched'
-- config.font = wezterm.font 'Fira Code Mono'

-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

Wezterm works with either `WEZTERM_CONFIG_FILE` or `XDG_CONFIG_HOME`

**Comment by wez** [comment]
If you are launching wezterm from Finder or other macOS launcher style software you should know that Finder doesn't load any of your shell startup or environment, so if you are setting things in your shell and hoping to influence the startup of other programs launched from Finder/the macOS GUI, you will be disappointed.

I think you may need to do something like this:
https://apple.stackexchange.com/a/17477/166425

to make a shortcut that will launch `wezterm --config-file /path/to/your/config/file`

**Comment by huantrinh1802** [comment]
Thank you for the reply. 

For clarification, I installed WezTerm via brew cask, thus inherently installed both cli and WezTerm.app in Finder/Application.

Your reply actually pointed me to find a better workaround (not sure if this is a good approach though) [HowTo: Set an Environment Variable in Mac OS X - launchd.plist](https://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-mac-os-x-launchd-plist/).

**Comment by Drew-Daniels** [comment]
Figured other people might find this useful, but since I use MacOS and I don't want to always have to use another terminal to launch WezTerm, I followed one of the answer's in the Stack Exchange link @wez provided (thanks a lot btw).

### Preface
I keep all my dotfiles in my `~/projects/dotfiles` folder, and have a `settings.lua` file adjacent to my `wezterm.lua` file that I use to store work-station specific info so I can launch work and home workspaces whenever I launch `wezterm`, depending  on what computer I'm using it with.

That's all to say, this is why I need to export `XDG_CONFIG_HOME`, because if I don't I'll get an error when I launch `wezterm` saying that it couldn't resolve the `require("settings")` line that I have at the beginning of my `wezterm.lua` file.

### 1. Create a Bash Script:

```bash
# launch_wezterm.sh
export XDG_CONFIG_HOME=~/projects/dotfiles
/opt/homebrew/bin/wezterm --config-file $XDG_CONFIG_HOME/wezterm/wezterm.lua
```

### 2. Create Apple Script:
Open `Script Editor` (`/Applications/Utilities/Script Editor.app`)

```applescript
-- Launch WezTerm.scpt
do shell script "~/projects/dotfiles/scripts/launch_wezterm.sh"
```
Save as an Application

### 3. Run the Application
You should see the WezTerm GUI get launched with all of your settings loaded.
