### ISSUE TITLE
Installing wezterm with brew did not install the app to /Applications

### ISSUE THREAD

**Issue by JoyceBabu** [wez/wezterm#501]
## Describe the bug

I installed wezterm with homebrew, following the official installation guide. Now I am able to open wezterm by running the command `wezterm` from bash. But homebrew did not move `WezTerm.app` to my `/Applications` or `~/Applications` directory

## Environment (please complete the following information):

 - OS: macOS
 - Version: wezterm 20210203-095643-70a364eb

## To Reproduce

Steps to reproduce the behavior.

- `brew tap wez/wezterm`
- ` brew install wezterm`

## Configuration

Be sure to include the relevant section(s) of your `wezterm.lua` configuration file.

## Expected behavior

`WezTerm.app` should be copied to `/Applications` or `~/Applications`

**Comment by wez** [comment]
To get brew to deploy to `/Applications`, the current `Formula` needs to be migrated to a `Cask`.  I looked at this a bit today and there are some issues:

* Cask installation defaults to setting quarantine flags on the extracted files, and since wezterm cannot be code signed in CI, macOS will always pop up a dialog that will scare users into moving the app to the trash whenever it runs any of the executables deployed with wezterm.  There is a `--no-quarantine` flag that can be passed to install, but I see this as a confusing source of support issues.
* Casks don't support `--HEAD` installation, which means that two separate casks would be needed; one for releases and another for the nightly builds
* It's unclear what the migration story is for users that had previously installed the Formula and then try to update when there is only a Cask

There's a lot of details to figure out there, and I don't plan on looking at it any time soon.
If someone is motivated to make this happen, I welcome that effort!

**Comment by caiges** [comment]
I wanted to point out that it's become a fairly standard habit for OSX folks, unfortunately, after installing a new app via homebrew or otherwise unsigned to first go to the applications folder, right click the app, select open and be on their way -- the popup dialog warning users will no longer appear after that. It's stilly but that's where we are.

**Comment by 4cm4k1** [comment]
FWIW, I agree with @caiges. As a developer, I execute `xattr -d com.apple.quarantine /Applications/${app}` on a regular basis because a number of tools are not code-signed, but I know the risk. I'll install it like a normie, but maybe in the future I can help with this story. :)

**Comment by teenjuna** [comment]
Probably we can do this as @caiges says and indicate this little hack in the installation section? That's a developer tool after all, so users can understand. Personally I find it very annoying that I need to launch a terminal from another terminal.

**Comment by jasikpark** [comment]
https://docs.brew.sh/Acceptable-Formulae#stuff-that-builds-an-app
Since wezterm builds a .app, brew.sh says it should be packaged as a Cask, maybe two: `wezterm` and `wezterm-nightly`

**Comment by laggardkernel** [comment]
@jasikpark I've made Casks here. https://github.com/laggardkernel/homebrew-tap/tree/master/Casks. Have a try,

```bash
brew tap laggardkernel/tap
brew install --cask wezterm
# or
brew install --cask wezterm-nightly
```

To expose the executables from Wezterm, I choose to add following path into `PATH`

```bash
# Add it to your shell init files
[[ -d /Applications/WezTerm.app/Contents/MacOS ]] && export PATH="/Applications/WezTerm.app/Contents/MacOS:$PATH"
```

**Comment by wez** [comment]
@laggardkernel great! Would you mind submitting those as a PR to https://github.com/wez/homebrew-wezterm ?

**Comment by wez** [comment]
Thanks to @laggardkernel's PR https://github.com/wez/homebrew-wezterm/pull/2, the wezterm tap is now a cask with migration information to help users transition from the formula to the cask!

I've updated the [wezterm installation docs](https://wezfurlong.org/wezterm/install/macos.html#homebrew) to use eg: `brew install --cask wezterm --no-quarantine` to avoid popping up the "move to trash" dialog.

Regarding PATH; the cask links the executables somewhere reasonable:

```
; brew install --cask wezterm-nightly --no-quarantine
==> Caveats
Cask wezterm-nightly related executables like 'wezterm', 'wezterm-gui',
'wezterm-mux-server', are linked into
  /usr/local/bin/    for x86 Mac,
  /opt/homebrew/bin/ for M1 Mac.

Removal of them is ensured by 'brew uninstall --cask wezterm-nightly'.

Since there's no version info included in the download URL of the nightly
build, NO update will be notified for 'wezterm-nightly' by Homebrew. (Not a
problem for non-nightly, regular released 'wezterm'.) To get the nightly
update, just run 'brew upgrade --cask wezterm-nightly'.

==> Downloading https://github.com/wez/wezterm/releases/download/nightly/WezAlready downloaded: /Users/wez/Library/Caches/Homebrew/downloads/02623fd97034dc23e772b65757081fe2c1de7e1ac2a5117e38cb4146d1ba4cc4--WezTerm-macos-nightly.zipWarning: No checksum defined for cask 'wezterm-nightly', skipping verification.
==> Installing Cask wezterm-nightly
Warning: macOS's Gatekeeper has been disabled for this Cask
==> Moving App 'WezTerm.app' to '/Applications/WezTerm.app'
==> Linking Binary 'wezterm' to '/usr/local/bin/wezterm'
==> Linking Binary 'wezterm-gui' to '/usr/local/bin/wezterm-gui'
==> Linking Binary 'wezterm-mux-server' to '/usr/local/bin/wezterm-mux-server'
==> Linking Binary 'strip-ansi-escapes' to '/usr/local/bin/strip-ansi-escapes`
🍺  wezterm-nightly was successfully installed!
```
