### ISSUE TITLE
URL highlighting breaks when URL wraps around multiple lines

### ISSUE THREAD

**Issue by pragma-** [wez/wezterm#5023]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

WezTerm-windows-20240212-074107-22f9f8d2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In the WeeChat IRC client, if a long URL traverses across multiple lines, only the first line gets highlighted for clicking. Note there are no sub-windows, splits or any fancy TUI rendering. It's a plain old simple raw terminal-like display.

![](https://i.imgur.com/1mPvMl1.png)

I've tried various WeeChat configuration options, all of which failed to fix the issue: `/set weechat.look.eat_newline_glitch on`, `/set weechat.look.align_multiline_words off`, `/set weechat.look.align_end_of_lines time` and `/window bare`.

However, it does not appear to be a WeeChat issue since the URLs highlight/click correctly in other terminals such as mintty and alacritty. 

### Configuration

no config

### Expected Behavior

The entire URL should be highlighted and clickable as seen here in mintty:

![](https://i.imgur.com/J6MsiiG.png)

**Comment by xxxserxxx** [comment]
It's not just weechat. It's any multi-line URL. The issue is also present in QuickSelect URLs.

To test, run the following and try to select the URL. This is zsh code; you may need to adjust the for loop if you use a different shell; and it also assumes you have `uuidgen` installed, which is included in the `util-linux` package on Arch.

```zsh
echo "https://" ${for x in $(seq 1 10); uuidgen) | tr -d ' '
```

With a QuickSelect pattern of `(?m)https?://[\t ]+` (properly escaping `\t` in the string), it also fails to span lines.

I would expect multi-line URLs to give problems in TUI applications with sub-windows, like `weechat`, `tut`, or `matrix` -- I don't expect wezterm to be able to figure those out. But this should work when it's a pure shell with no confusing rendering, right? Like, I can go into raw mode in gomuks and display pure URLs with no other markup, but if they span lines wezterm only ever sees the first line.

**Comment by pragma-** [comment]
Indeed. Updated title to remove "WeeChat", and edited my comment to clarify that I am not using any fancy TUI rendering concepts such as sub-windows or splits.

**Comment by pragma-** [comment]
Indeed. Updated title to remove "WeeChat", and edited my comment to clarify that I am not using any fancy TUI rendering concepts such as sub-windows or splits.

@wez It'd be great if you could take a look at this if you have time soon.

**Comment by wez** [comment]
There's a hard limit of a maximum of 1024 bytes to a logical line to prevent excessive resource utilization in highlighting, hovering and resizing, because it is relatively expensive to look backwards and ahead in those cases, and for pathological situations (like a 100MB json file that is on one line), it poses a huge memory burden in scenarios that need to have bounded compute and memory overheads.

**Comment by wez** [comment]
Separately: if you are running a TUI that does its own wrapping, wezterm may not be able to see through that. There was a recent PR that may improve this in nightly builds:
* https://github.com/wez/wezterm/pull/5396

**Comment by pragma-** [comment]
The URL in my screenshot is approximately 175 characters long and the TUI is not doing its own wrapping.

I'll give the latest nightly build a shot this week and report back.

**Comment by xxxserxxx** [comment]
The URL in my sample code should be 369 characters of only 7-bit ASCII characters, but even if it's represented as UTF-8 that's still below 1024 characters.

tmux is what's interfering, in my case. I get the right selection if I run it in a pure terminal. I don't even consciously notice I use tmux anymore, because I'm always in it.  I'll try #5396.

**Comment by pragma-** [comment]
@wez The nightly does indeed fix this issue. The full URL is now clickable even with wordwrapping. It works at the normal terminal, inside tmux, and within a tmux'd WeeChat, with the default wezterm config and with my custom config. 10/10.

**Comment by pragma-** [comment]
@wez I regret to say that I've reverted back to the WezTerm-windows-20230822-073555-67f4450d nightly I was using previously. While the new nightly does fix the URL highlighting/clicking, the text cursor now jumps around the screen when updating certain text elements like timestamps, channel indicators, etc. This distracting and annoying cursor-jumping behavior is not present in the older nightly. :-(

**Comment by pragma-** [comment]
I've opened #5560 regarding the abnormal cursor movement.

**Comment by xxxserxxx** [comment]
Confirmed that nightly fixes this in tmux. I'm on Linux (X11, Herbstluftwm) and there's no cursor hopping, either, so #5560 might be a Windows related issue. I'll put a comment there, too.
