### ISSUE TITLE
Font / Text rendering differences

### ISSUE THREAD

**Issue by Imzxhir** [wez/wezterm#5075]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240221-075452-95581d86

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I noticed that the font rendering, compared to other terminals, is worse and I am not sure why. For instance from the screenshot below, you can see that between iTerm2, Kitty and WezTerm, Wezterm looks the worst out of the three. I did notice a similiar issue [here](https://github.com/wez/wezterm/issues/681) but the suggestions to fix the issue did not work so I decided to create a new issue here.

### To Reproduce

Here is my font rendering settings for iTerm2:
![image](https://github.com/wez/wezterm/assets/98621617/65b83cea-dd95-44f2-8a24-46d78bd12f71)
![image](https://github.com/wez/wezterm/assets/98621617/eda577b1-28e3-4d75-8778-fd03da668d80)

Here is my config for Kitty:
```
# The basic colors
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5E0DC

# Cursor colors
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# URL underline color when hovering with mouse
url_color               #F5E0DC

# Kitty window border colors
active_border_color     #B4BEFE
inactive_border_color   #6C7086
bell_border_color       #F9E2AF

# OS Window titlebar colors
wayland_titlebar_color  #1E1E2E
macos_titlebar_color    #1E1E2E

# Tab bar colors
active_tab_foreground   #11111B
active_tab_background   #CBA6F7
inactive_tab_foreground #CDD6F4
inactive_tab_background #181825
tab_bar_background      #11111B

# Colors for marks (marked text in the terminal)
mark1_foreground #1E1E2E
mark1_background #B4BEFE
mark2_foreground #1E1E2E
mark2_background #CBA6F7
mark3_foreground #1E1E2E
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

# magenta
color5  #F5C2E7
color13 #F5C2E7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8

font_family MesloLGS NF
font_size   14.0
```

### Configuration

```
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This will hold the configuration.
local config = wezterm.config_builder()
local mux = wezterm.mux


wezterm.on('gui-startup', function(cmd) -- set startup Window position
    local tab, pane, window = mux.spawn_window(cmd or {
        width = 110,
        height = 30,
        position = {
            x = 845,
            y = 452,
        }
    })
end)

function scheme_for_appearance(appearance) -- set adaptive color scheme
  if appearance:find "Dark" then
    return "Catppuccin Mocha"
  else
    return "Catppuccin Latte"
  end
end

-- This is where you actually apply your config choices

config.color_scheme = scheme_for_appearance(wezterm.gui.get_appearance())
config.default_prog = { '/usr/local/bin/fish', '-l' }
config.enable_scroll_bar = true
config.exit_behavior = "Close"
config.font = wezterm.font 'MesloLGS NF'
config.font_size = 14
config.hide_tab_bar_if_only_one_tab = true
config.window_close_confirmation = "NeverPrompt"

-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

Font rendering should be the same or as close to the other terminals.

### Anything else?

iTerm2:
![image](https://github.com/wez/wezterm/assets/98621617/56a23692-4ff5-4846-a2e5-84556582259f)

Kitty:
![image](https://github.com/wez/wezterm/assets/98621617/7a5b7e8b-b5a4-4014-b032-b8674b8f0233)

WezTerm:
![image](https://github.com/wez/wezterm/assets/98621617/001e6cb7-d1d5-40a4-a659-9787a155f902)

**Comment by lcrownover** [comment]
I'm also experiencing this behavior:

Alacritty:
<img width="519" alt="image" src="https://github.com/wez/wezterm/assets/15133041/6dd32c87-3778-49c4-b4f4-855e5759cede">

Wezterm:
<img width="519" alt="image" src="https://github.com/wez/wezterm/assets/15133041/22343d8c-3917-46fb-83af-b49e230436aa">

**Comment by battlmonstr** [comment]
+1

The fonts are thinner in Wez (above) than in the standard Terminal (below).
Compare the dots over "i".
Because the font is thinner, the anti-aliased border is takes relatively area and the font looks blurrier (compare letter "g").

![Screenshot 2024-03-05 at 09 40 21](https://github.com/wez/wezterm/assets/11477595/6078d94c-984e-4105-9e21-5dd7730f5497)

Some thinner fonts become unusable (e.g. Courier New).

I've tried various [freetype_load_target](https://wezfurlong.org/wezterm/config/lua/config/freetype_load_target.html). Only `Mono` makes it more readable (a bit thicker), but it somewhat distorts the font.

It could look fine if it was possible to disable anti-aliasing, but how?

**Comment by doulighan** [comment]
+1, This is happening to me. Would absolutely love to get rid of iTerm, but I don't think I can currently.  I've messed with every font-rendering setting I could find, but nothing really fixes it. 

Interesting to note, on my native MacOS Retina screen, iTerm and WezTerm are nearly identical. Its just when you move to an external screen, iTerm (and Pycharm/VSCode) somehow adjust for the lowered resolution better. The aliased text is both literally thicker in terms of pixel count, and the opacity on the aliased pixels is brighter.

![font-compare](https://github.com/wez/wezterm/assets/16358780/e2f6ca5a-cc70-4d4a-ab7f-c37bdd63003d)

**Comment by lcrownover** [comment]
> Noticed this as well . I was using Jetbrains Mono nerd font. The regular version is thinner on wezterm so had to move to Medium . Turns out it was an issue afterall

Switching the font to Medium seems to help, but it's still slightly different. 

`config.font = wezterm.font("JetBrainsMono Nerd Font", { weight = 'Medium' })`

**Comment by TylerAtCodeOfLife** [comment]
It might be a good idea to ask the freetype developers or use the python bindings to experiment with the renderer to find a fix.

**Comment by truehumandesign** [comment]
> > Noticed this as well . I was using Jetbrains Mono nerd font. The regular version is thinner on wezterm so had to move to Medium . Turns out it was an issue afterall
> 
> Switching the font to Medium seems to help, but it's still slightly different.
> 
> `config.font = wezterm.font("JetBrainsMono Nerd Font", { weight = 'Medium' })`

I have tried this but still it looks quite different from font rendering in e.g. alacritty, vscode, zed...

wezterm
---
<img width="618" alt="Screenshot 2024-03-26 at 23 02 54" src="https://github.com/wez/wezterm/assets/591188/dcb58e65-dc3b-4d39-be9c-62211a57790e">

alacritty
---
<img width="618" alt="Screenshot 2024-03-26 at 22 59 35" src="https://github.com/wez/wezterm/assets/591188/7572b19e-bee6-45a6-94fe-5f323f03e8db">

vscode
---
<img width="618" alt="Screenshot 2024-03-26 at 23 06 35" src="https://github.com/wez/wezterm/assets/591188/28e6dc2d-de4b-4c1b-a4ab-28d177a5c5d3">

**Comment by oOosys** [comment]
Hmmm ... the wezterm version looks much better in my eyes than the same text in the other terminals ... Maybe the other terminals should change the way of rendering?

**Comment by truehumandesign** [comment]
> Hmmm ... the wezterm version looks much better in my eyes than the same text in the other terminals ... Maybe the other terminals should change the way of rendering?

I think it's not because it looks bad, i also think it looks better in wezterm. I'm just curious why...

**Comment by wez** [comment]
Fonts appearance is a highly subjective topic; there are thousands of users that are happy with how the fonts appear. That doesn't mean that you are wrong, just that you find different things more important in how you perceive text.

wezterm uses freetype on all operating systems for consistency and sanity in implementation and maintenance.
That makes its rasterization different from most other software that uses the macOS font renderer on macOS, or the Windows renderer on Windows, because it is a different renderer.

I am not going to make wezterm use the macOS renderer or the Windows renderer on those respective systems.

I've exposed just about every knob and option that is possible to expose from freetype to allow users to dial in their preference, but it is admittedly a complex topic.

I do not have time to troubleshoot and dial in all the configs of every user that has questions about this, so I'm sorry to say that I'm going to close this issue without spending more time on it. It's not that I don't care, or don't think that it is important to you, but rather that there isn't anything for me to fix and working through these sorts of issues is incredibly time consuming and frustrating, and I get nothing out of the experience.

If you feel that you have to use alacritty or some other terminal emulator as a result, that is fine by me: you've got to do what you've got to do.
