### ISSUE TITLE
add support for embedding webview pane

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#514]
Would it be possible to add support of embedding to native webview as one of the pane.

It will easy allow us to implement features such as these. https://github.com/dsanson/termpdf.py
![image](https://user-images.githubusercontent.com/287744/110252033-57a10a80-7f38-11eb-983e-bd05afa96210.png)

I'm primarily looking to interact create a vim plugin where on the left side I have vim editor and on the right side I have a webview which is rendering the markdown. Vim/Neovim allows talking with external programs through stdio/stdin, named pipes, tcp and sockets so I would use it to communicate with pane using it. It also natively supports json only so the messages would have to be transferred via json. It will be good if we can directly communicate with JSON RPC which is very popular for [LSP](https://microsoft.github.io/language-server-protocol/overviews/lsp/overview/) and almost all editors has features to support it.

**Comment by wez** [comment]
I'm not keen to embed a web view; it will never be as good as running a proper browser, and I feel that I'd be spending too much time trying to make the terminal be a browser.  On Linux, it will mean pulling in dependencies on very large non-rust libraries with their own event processing loops, which feels like a big headache.

Two alternatives to consider:

* wezterm supports both the iTerm2 and sixel image protocols.  I don't believe that there is a technical reason that prevents termpdf from targeting those image protocols rather than just the kitty protocol
* It wouldn't be all that much work to hook up image support in `termwiz` and then have a standalone markdown->image-enabled-terminal program to render markdown directly in the terminal.  There's already some code to do image-less markdown translation in wezterm that is used to render the changelog: https://github.com/wez/wezterm/blob/main/wezterm-gui/src/markdown.rs

**Comment by prabirshrestha** [comment]
Thanks. Getting images rendered would be great. Then we can have a custom tool outside of wezterm supporting rendering.
