### ISSUE TITLE
Use the XCursor mouse cursor theme

### ISSUE THREAD

**Issue by stevenxxiu** [wez/wezterm#524]
## Describe the bug
Mouse cursors don't use the same cursor theme as the rest of the OS.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210203-095643-70a364eb
 - The active keyboard layout name: ENG

## To Reproduce
- Choose a custom cursor theme in Linux.
- Move the cursor inside the *Wez Term* window.
- The mouse pointer changes style.

## Configuration
N/A

## Expected behavior
The mouse pointer should use the same cursor theme as the rest of the OS.

## Screenshots
The mouse pointer on the title bar, which is the correct cusor theme:

![Screenshot_2021-03-09_01-27-40](https://user-images.githubusercontent.com/2058940/110334462-e9af2d00-8076-11eb-9d82-366cb74ca77e.png)

The mouse pointer within *Wez Term*'s window, which uses an incorrect cusor theme:

![Screenshot_2021-03-09_01-28-17](https://user-images.githubusercontent.com/2058940/110334587-0d727300-8077-11eb-85ef-ce5fc7b9d790.png)

This is particularly bad for links in the terminal, where the cursor changes to a pixelated 90s hand pointer.

## Session Recording
N/A

## Additional context
N/A

**Comment by wez** [comment]
Under X11 there isn't the concept of a mouse pointer theme.  There is a concept of a GTK theme shared by GTK apps, but WezTerm is an X11 application, and it uses the X11 mouse cursors from the '90s.  This is working as designed!

That said, if there is a reasonable way for WezTerm to detect what the GTK theme is, without needing to link to GTK, and that theme is easy to load into a mouse cursor, I think this is a reasonable request for an enhancement.

**Comment by stevenxxiu** [comment]
I'm not sure if this is a GTK specific feature? [Cursor themes - ArchWiki](https://wiki.archlinux.org/index.php/Cursor_themes) suggests that it's an X11 or Wayland thing. I found the crates:

- [x11rb - crates.io: Rust Package Registry](https://crates.io/crates/x11rb)
- [wayland-cursor - crates.io: Rust Package Registry](https://crates.io/crates/wayland-cursor)

**Comment by stevenxxiu** [comment]
Just tested nightly with the commit https://github.com/wez/wezterm/commit/182a4d068bff25f78dfa246d5b749c5d419cab4c, and still buggy in Arch.

**Comment by stevenxxiu** [comment]
Ok I did some debugging, and looks like you read `Xcursor.theme`. This gave a strange value for me, so I wondered where it came from.

Turns out my XFCE had a value I configured previously, that was incorrect. Perhaps my cursors were cached by XFCE. I updated it by doing:

    $ xfconf-query --channel xsettings --property /Gtk/CursorThemeName --set aero

Upon reboot, now looks like I get the correct cursor. I hope this info is helpful to whoever stumbles upon this issue.

**Comment by dmfay** [comment]
I had the same issue and it turned out to be because I was using [XDG-style configuration](https://wiki.archlinux.org/index.php/Cursor_themes#Configuration) (`/usr/share/icons/default/index.theme`); adding my theme to `~/.Xresources` fixed it.

**Comment by nh2** [comment]
Coudl anybody explain (and per haps link the code) of how wezterm determines the name of the cursor theme?

In https://github.com/BachoSeven/dotfiles/commit/6063e85688ba08e9e6e30490e261ea2581f3783d#diff-5f0fdeab30eb3c89228368ae0a6f29224cfce40f5b72b6632ae5e10613b9a472R23 it is claimed that wezterm reads `~/.Xresources`, but that doesn't seem to work, I couldn't confirm it with `strace`, and I could find any reference to `Xresources` in the wezterm code.

I ask this because I noticed wezterm for me always reads the `default` curser scheme from `~/.icons/default/cursors`, even if I've set e.g. `Xcursor.theme: Simp1e-breeze` in `~/.Xresources`. Is that only read when my X session is started? If yes, how does wezterm pick it up then, if not reading this file explicitly?

**Comment by nh2** [comment]
Ah, I see, I think it's here:

https://github.com/wez/wezterm/blob/7b402678e46525f70c0d6756d4fc0d70bf6a9dc3/window/src/os/x11/cursor.rs#L92-L106

So wezterm queries the X runtime property `conn.xrm.borrow().get("Xcursor.theme")` via the X connection `conn`, instead of reading it from the `~/.Xresources` file.

So that runtime property is probably set from `~/.Xresources` at start of the session, or set dynamically using the desktop environment (for example, I use XFCE's settings manager on `i3`, and if I change it there and restart wezterm, then it reflects as expected.

(This is probably the same as was found in https://github.com/wez/wezterm/issues/524#issuecomment-801570387 above, just more explicit.)

**Comment by wez** [comment]
What wezterm does is equivalent to `xprop -root | grep RESOURCE_MANAGER | perl -pe 's/\\n/\n/g'  | grep -i cursor`; it asks the X server to resolve those properties.  It's up to you/your environment to arrange for those values to be set there.

Changing them after you've started the session is something you can usually do using something like `xrdb -merge`.

wezterm does re-read those properties in response to certain messages from the xserver:
https://github.com/wez/wezterm/blob/80e7f0bd93361336a9cdd64ea5119b49a762140a/window/src/os/x11/window.rs#L393-L405

**Comment by cbirchinger** [comment]
I'm trying to use every method i know to get the correct mouse pointer theme but i still get some X11 built-in one

Log from WEZTERM_LOG=trace:
~ $ grep xsettings wez.log
<...> Gtk/CursorThemeName": String("DMZ-White"), "Gtk/CursorThemeSize": Integer(16) <...>

# X Properties (command from above):
~ $ xprop -root | grep RESOURCE_MANAGER | perl -pe 's/\\n/\n/g' | grep -i Xcursor
Xcursor.theme:\tDMZ-White
Xcursor.size:\t16
Xcursor.theme_core:\t1

The Xresources config file itself:
~ $ grep Xcursor .Xresources 
Xcursor.theme:                  DMZ-White
Xcursor.size:			16

I've started ancient old Xlib only programs like xmessage or xvidtune to rule out Gtk or QT specific mouse theming
and even xvidtune and xmessage respect my X11 mouse theme (DMZ-White). Only wezterm is ignoring my mouse theme.

Is there a method that i'm missing?

**Comment by cbirchinger** [comment]
I've found the issue!

Gentoo installs Xorg icon themes in "/usr/share/cursors/xorg-x11" but Wezterm uses the following in
"wezterm/window/src/os/x11/cursor.rs":

OsString::from("~/.icons:/usr/share/icons:/usr/share/pixmaps:/usr/X11R6/lib/X11/icons")

As a workaround i've symlinked "~/.icons/DMZ-White" from "/usr/share/cursors/xorg-x11/DMZ-White"

I wonder how programs query the "/usr/share/cursors/xorg-x11" prefix path because no other program
ever failed because it did not know that path.

**Comment by wez** [comment]
Is the `XCURSOR_PATH` env var set to something reasonable on your system?  Is there some other env var or WM property visible via xprop that includes the correct location?

**Comment by wez** [comment]
another possibility: does some other path symlink to `/usr/share/cursors/xorg-x11` that wezterm could in theory find but is skipping over?

**Comment by cbirchinger** [comment]
I've seen the XCURSOR_PATH in the source, so that would be a solution, yes.

Since i'm on Gentoo and build from source anyway, i went for the following more radical method by adding the path to the source (cursor.rs):

-        OsString::from("~/.icons:/usr/share/icons:/usr/share/pixmaps:/usr/X11R6/lib/X11/icons")
+        OsString::from("~/.icons:/usr/share/icons:/usr/share/pixmaps:/usr/X11R6/lib/X11/icons:/usr/share/cursors/xorg-x11")

Since this will affect all Gentoo users and possibly other distros which went with this install location, changing this upstream
wouldn't be a bad idea.

**Comment by wez** [comment]
I wonder if the other software happens to work because they're using a C library that has those paths patched by their distro?
I'm open to adding more reasonable paths to wezterm's default xcursor path; please submit a PR!

**Comment by cbirchinger** [comment]
It appears to be some sort of standard. Some rust lib named xcursors has it for example.

https://docs.rs/xcursor/latest/src/xcursor/lib.rs.html#168

```
// The order is following other XCursor loading libs, like libwayland-cursor.
<...> 
xcursor_path.push(PathBuf::from("/usr/share/cursors/xorg-x11"));`
```

**Comment by wez** [comment]
I pushed a commit that adopts similar logic to the xcursor rust crate

**Comment by cbirchinger** [comment]
This fully breaks and panics on startup if env XCURSOR_PATH is unset:

```
~ $ wezterm
 2022-01-20T18:00:55.461Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-3084
thread 'main' panicked at 'failed to compose default xcursor path: JoinPathsError { inner: JoinPathsError }', window/src/os/x11/cursor.rs:63:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This works (value doesn't matter as long as it's not undefined):
~ $ XCURSOR_PATH=xyz wezterm

Here is the full backtrace:
```
~ $ RUST_BACKTRACE=full wezterm
 2022-01-20T18:09:56.849Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-19567
thread 'main' panicked at 'failed to compose default xcursor path: JoinPathsError { inner: JoinPathsError }', window/src/os/x11/cursor.rs:63:40
stack backtrace:
   0:     0x56186d90207c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7c5cbc950a6e98ca
   1:     0x56186d92ac7c - core::fmt::write::h6d4e36f71c229c7e
   2:     0x56186d8f8f25 - std::io::Write::write_fmt::h9a4d183c6d8e2e45
   3:     0x56186d904020 - std::panicking::default_hook::{{closure}}::h7077f7ca514617b6
   4:     0x56186d903bd7 - std::panicking::default_hook::h94f8fbeb7a4dbcff
   5:     0x56186d9046f9 - std::panicking::rust_panic_with_hook::h4f815477eb18bcfb
   6:     0x56186d9041b0 - std::panicking::begin_panic_handler::{{closure}}::h7a39573fedeb5d43
   7:     0x56186d902524 - std::sys_common::backtrace::__rust_end_short_backtrace::h6230e6996d5f866c
   8:     0x56186d904119 - rust_begin_unwind
   9:     0x56186c6ddbd1 - core::panicking::panic_fmt::h7e065fe499918015
  10:     0x56186c6ddcc3 - core::result::unwrap_failed::h934e10679b725d01
  11:     0x56186cd4c959 - window::os::x11::cursor::CursorInfo::new::h43a0b9a78b504de4
  12:     0x56186c880e50 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h62661f13768a0653
  13:     0x56186c7ed14f - <async_task::runnable::spawn_local::Checked<F> as core::future::future::Future>::poll::hea934e3433ebe38d
  14:     0x56186c6e7813 - async_task::raw::RawTask<F,T,S>::run::h7b0ee138ca06fdbb
  15:     0x56186cd5cb99 - window::spawn::SpawnQueue::run::hcba537f725572b64
  16:     0x56186cd21d90 - <window::os::x11::connection::XConnection as window::connection::ConnectionOps>::run_message_loop::h6135e4ec2c0bede4
  17:     0x56186c89b560 - wezterm_gui::run::hbbc5e56a2377bd6c
  18:     0x56186c896397 - wezterm_gui::main::h437619ad01a8fc06
  19:     0x56186c758c63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6bb4462fe8a7e775
  20:     0x56186c75a159 - std::rt::lang_start::{{closure}}::h111513aefe505d05
  21:     0x56186d904cda - std::rt::lang_start_internal::h57f29373da9cb8d0
  22:     0x56186c89d452 - main
  23:     0x7f244399e7fd - __libc_start_main
                               at /var/tmp/portage/sys-libs/glibc-2.33-r7/work/glibc-2.33/csu/../csu/libc-start.c:332:16
  24:     0x56186c6de3aa - _start
  25:                0x0 - <unknown>

```

**Comment by jgcodes2020** [comment]
This does not seem to be working with `enable_wayland = true`. Should I make a separate ticket for that?

**Comment by wez** [comment]
@jgcodes2020: please file a new issue

**Comment by jgcodes2020** [comment]
> @jgcodes2020: please file a new issue
See issue #1742
