### ISSUE TITLE
Wezterm intermittently successfully launches

### ISSUE THREAD

**Issue by entailz** [wez/wezterm#5245]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

In order to launch wezterm on Hyprland (a bleeding edge wlroots compositor) I have to first run `WEZTERM_LOG=trace wezterm` which successfully spawns a wezterm process at which time I can continue to spawn wezterm instances with start --always-new-process. Once running Wezterm runs flawlessly when compared to previous versions. If I attempt to first spawn it without this debug flag with my drun launcher of choice, or terminal, the process hangs indefinitely. It seems like the compatibility is one step away, which is slightly frustrating but also reassurring.

### Configuration

```
local w = require("wezterm")
return {
	enable_wayland = true,
	front_end = "WebGpu",
	window_close_confirmation = "NeverPrompt",
	hide_tab_bar_if_only_one_tab = true,
	color_schemes = {
		["Wal Colors"] = require("wezwal"),
		["Solarized Osaka"] = require("osaka"),
	},
	default_prog = { "zsh" },
	color_scheme = "Solarized Osaka",
	bypass_mouse_reporting_modifiers = "ALT",
	harfbuzz_features = { "calt=0" },
	font_locator = "ConfigDirsOnly", -- don't use font-config, only font_dirs
	font_dirs = { "/home/entailz/.local/share/TTF" },
	font = w.font("IosevkaTerm Nerd Font", { weight = "Book", stretch = "Expanded" }),
	font_size = 15,
	warn_about_missing_glyphs = false,
	font_rules = {
		{
			intensity = "Bold",
			font = w.font({ family = "IosevkaTerm Nerd Font", weight = "Regular" }),
		},
	},
	default_cursor_style = "BlinkingBar",
	window_padding = {
		top = "1cell",
		right = "1cell",
		bottom = "1cell",
		left = "1cell",
	},

	inactive_pane_hsb = {
		saturation = 0.9,
		brightness = 0.8,
	},
}
```

**Comment by Emmistea** [comment]
FYI " til death do us part" WIN DEATH   ..    I'm having a problem understanding why y'all have crossed protocol son  with this Internet..     you have crossed into the FYI "the old way" where the dead is crawling all over us ... I really like being an American 

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Mar 31, 2024 at 5:06 PM, ***@***.***> wrote:   


What Operating System(s) are you seeing this problem on?

Linux Wayland

Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

WezTerm version

wezterm 20240203-110809-5046fc22

Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

Describe the bug

In order to launch wezterm on Hyprland (a bleeding edge wlroots compositor) I have to first run WEZTERM_LOG=trace wezterm which successfully spawns a wezterm process at which time I can continue to spawn wezterm instances with start --always-new-process. Once running Wezterm runs flawlessly when compared to previous versions. If I attempt to first spawn it without this debug flag with my drun launcher of choice, or terminal, the process hangs indefinitely. It seems like the compatibility is one step away, which is slightly frustrating but also reassurring.

To Reproduce

No response

Configuration
local w = require("wezterm")
return {
	enable_wayland = true,
	front_end = "WebGpu",
	window_close_confirmation = "NeverPrompt",
	hide_tab_bar_if_only_one_tab = true,
	color_schemes = {
		["Wal Colors"] = require("wezwal"),
		["Solarized Osaka"] = require("osaka"),
	},
	default_prog = { "zsh" },
	color_scheme = "Solarized Osaka",
	bypass_mouse_reporting_modifiers = "ALT",
	harfbuzz_features = { "calt=0" },
	font_locator = "ConfigDirsOnly", -- don't use font-config, only font_dirs
	font_dirs = { "/home/entailz/.local/share/TTF" },
	font = w.font("IosevkaTerm Nerd Font", { weight = "Book", stretch = "Expanded" }),
	font_size = 15,
	warn_about_missing_glyphs = false,
	font_rules = {
		{
			intensity = "Bold",
			font = w.font({ family = "IosevkaTerm Nerd Font", weight = "Regular" }),
		},
	},
	default_cursor_style = "BlinkingBar",
	window_padding = {
		top = "1cell",
		right = "1cell",
		bottom = "1cell",
		left = "1cell",
	},

	inactive_pane_hsb = {
		saturation = 0.9,
		brightness = 0.8,
	},
}

Expected Behavior

No response

Logs

No response

Anything else?

No response

**Comment by Emmistea** [comment]
And how I know is because I'm in the tail pulling out all this hidden way because I turned on the light with truth ....  So while ur stealing from God I'm pressing print .....   Just to anyone who falls in this way and rotating.

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Mar 31, 2024 at 5:39 PM, Misty ***@***.***> wrote:   FYI " til death do us part" WIN DEATH   ..    I'm having a problem understanding why y'all have crossed protocol son  with this Internet..     you have crossed into the FYI "the old way" where the dead is crawling all over us ... I really like being an American 

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Mar 31, 2024 at 5:06 PM, ***@***.***> wrote:   


What Operating System(s) are you seeing this problem on?

Linux Wayland

Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

WezTerm version

wezterm 20240203-110809-5046fc22

Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

Describe the bug

In order to launch wezterm on Hyprland (a bleeding edge wlroots compositor) I have to first run WEZTERM_LOG=trace wezterm which successfully spawns a wezterm process at which time I can continue to spawn wezterm instances with start --always-new-process. Once running Wezterm runs flawlessly when compared to previous versions. If I attempt to first spawn it without this debug flag with my drun launcher of choice, or terminal, the process hangs indefinitely. It seems like the compatibility is one step away, which is slightly frustrating but also reassurring.

To Reproduce

No response

Configuration
local w = require("wezterm")
return {
	enable_wayland = true,
	front_end = "WebGpu",
	window_close_confirmation = "NeverPrompt",
	hide_tab_bar_if_only_one_tab = true,
	color_schemes = {
		["Wal Colors"] = require("wezwal"),
		["Solarized Osaka"] = require("osaka"),
	},
	default_prog = { "zsh" },
	color_scheme = "Solarized Osaka",
	bypass_mouse_reporting_modifiers = "ALT",
	harfbuzz_features = { "calt=0" },
	font_locator = "ConfigDirsOnly", -- don't use font-config, only font_dirs
	font_dirs = { "/home/entailz/.local/share/TTF" },
	font = w.font("IosevkaTerm Nerd Font", { weight = "Book", stretch = "Expanded" }),
	font_size = 15,
	warn_about_missing_glyphs = false,
	font_rules = {
		{
			intensity = "Bold",
			font = w.font({ family = "IosevkaTerm Nerd Font", weight = "Regular" }),
		},
	},
	default_cursor_style = "BlinkingBar",
	window_padding = {
		top = "1cell",
		right = "1cell",
		bottom = "1cell",
		left = "1cell",
	},

	inactive_pane_hsb = {
		saturation = 0.9,
		brightness = 0.8,
	},
}

Expected Behavior

No response

Logs

No response

Anything else?

No response

**Comment by oOosys** [comment]
Yeah ... follow the Tower of Babel idea of God and start to use new languages and approaches splitting the community into smaller groups to weaken their power of progress ... wasting their efforts keeping them busy with fixing all the issues the new language comes with ... so that they have no time to improve what they already came up  with ...

**Comment by entailz** [comment]
What the heck is going on here.

**Comment by wez** [comment]
Please try the latest nightly build

**Comment by entailz** [comment]
Sorry for late response on this! This build works. The most recent build with updated deps fixes the xcursor theme error log spam as well.
