### ISSUE TITLE
Ctrl + shift + p/f combination is not getting triggered, it only registers as ctrl + p/f

### ISSUE THREAD

**Issue by spa5k** [wez/wezterm#5334]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

Windows

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

```lua
config.keys = {
    -- disable ctrl + shift + f in wezterm
    { key = "f", mods = "CTRL|SHIFT", action = act.DisableDefaultAssignment },
    -- disable ctrl + shift + p
    { key = "p", mods = "CTRL|SHIFT", action = act.DisableDefaultAssignment },
}
```

here's my keymap in wezterm, the aim is that Wezterm ignores these 2 combinations, so that the neovim can handle it. But idk what's happening, it basically ignores the combination of ctrl + shift + f and only registers it as ctrl + f

### To Reproduce

use the config above

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'
local act = wezterm.action
-- This will hold the configuration.
local config = {}
if wezterm.config_builder then
    config = wezterm.config_builder()
end
config.default_prog = { 'ubuntu2204.exe' }
config.keys = {
    -- disable ctrl + shift + f in wezterm
    { key = "f", mods = "CTRL|SHIFT", action = act.DisableDefaultAssignment },
    -- disable ctrl + shift + p
    { key = "p", mods = "CTRL|SHIFT", action = act.DisableDefaultAssignment },
}

return config
```

### Expected Behavior

It should send forward the ctrl + shift + p/f combination to the neovim, as neovide does.

### Logs

Debug Overlay
wezterm version: 20240203-110809-5046fc22 x86_64-pc-windows-msvc
Window Environment: Windows
Lua Version: Lua 5.4
OpenGL: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 4.5.0 NVIDIA 552.12
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

### Anything else?

no

**Comment by bew** [comment]
Know that Ctrl+Shift+somekey does not work in any terminal by default because this keybind cannot be represented in the standard way keys are passed from the terminal to the running program.
To workaround this limitation (and a few others around keybinds) some terminals like kitty created their own keyboard protocol, that neovim supports and that wezterm also implements (and it mostly works).

Read more:
https://wezfurlong.org/wezterm/config/key-encoding.html#kitty-keyboard-protocol

Config option:
https://wezfurlong.org/wezterm/config/lua/config/enable_kitty_keyboard.html

**Comment by spa5k** [comment]
The kitty keyboard config didn't work, but this worked 

```
config.allow_win32_input_mode = false
```
