### ISSUE TITLE
Image protocol memory leaking ?

### ISSUE THREAD

**Issue by hzeller** [wez/wezterm#534]
### Context
The [timg terminal image and video viewer](https://github.com/hzeller/timg) now supports the iTerm image protocol and as such can be used in wezterm to show images, animations and videos.

Videos are played by emitting an image, cursor jumping back to the start position and emitting the next image.

Invocation e.g.
```bash
# filename can be any image file or movie. -pi switches on iterm pixelation
timg <somefile> -pi
```

### Observation
When playing a video, the wezterm process memory increases constantly.

## Environment

 - OS: Linux X11
 - Version: compiled from head `wezterm 20210203-095643-70a364eb-217-g9ddc2da6`

## To Reproduce

For simplicity and no need to compile `timg`, the attached [wezterm-memory-use.terminal.gz](https://github.com/wez/wezterm/files/6134176/wezterm-memory-use.terminal.gz) (about 7MiB) can be used - it contains a short video sequence that can be `zcat`-ed directly to the terminal.

After running this in a little loop, the wezterm-gui process uses about an additional ~3GiB (on my machine), and memory only ever increases with subsequent runs:

```bash
for i in $(seq 1 100); do zcat /tmp/wezterm-memory-use.terminal.gz ; done
```
 (Oh, and this is the Internet, so I had to use some Internet meme. I am sorry :) )

(Alternatively run [`timg`](https://github.com/hzeller/timg) with a video of your choice.
```
timg -pi somevideo.mp4
```
)

## Configuration
_(independent of configuration)_

## Expected behavior

A somewhat bounded memory use.

## Additional information

I _suspect_ that old images are never deleted from memory, after all they have to be around to display when scrolling. However, in this particular case, the images emitted in a video or animation are always placed _on top of the previous image_. So there is an opportunity to garbage collect the previous image.

**Comment by wez** [comment]
> (Oh, and this is the Internet, so I had to use some Internet meme. I am sorry :) )

Well played :)

**Comment by wez** [comment]
I pushed a commit that sets a bound on one aspect of image handling.

I ran this build under `heaptrack` to see if it could point out any hotspots, but nothing stands out.  However: the overall memory usage does climb for the duration of the playback of the stream you provided.

One thing I noted was that the cursor positioning wasn't stable when playing back the stream; the image was scrolling up, leading to this smearing effect:
![image](https://user-images.githubusercontent.com/117777/111025007-8256ed00-8396-11eb-8491-604eaae9c5a1.png)

that will cause the cells in each of those rows to hold a reference to their respective video frame.  Setting `scrollback_lines=0` was effective at limiting the peak memory usage.

Without the constrained scrollback, what was puzzling was that clearing the scrollback didn't cause the amount of memory to reduce.  It feels like Rust's allocator might be holding on to memory for longer than the application needs.

So I think there are two action items:

* Can you confirm that the cursor positioning is behaving correctly?  It doesn't seem right to me.  Not sure if that is a problem with the source data or if there is a conformance issue in wezterm wrt. where iTerm2 leaves the cursor
* I'll poke some more to see if I can shake out where the memory is being held on to; maybe it's some slack capacity somewhere, or maybe it is legit fragmentation and wezterm needs to do something special with the allocator.

**Comment by wez** [comment]
I've made wezterm a bit more memory efficient with the last couple of commits.  I think the big issue outstanding is cursor positioning, because if the cursor movement between the frames is incorrect then the video content is scrolled up into the scrollback.

Here's what heaptrack shows with 868a085; I'm running 10 iterations of the `zcat` for brevity.  You can see that memory usage climbs and then flattens; the flat portion is where I let it sit idle for a few moments.  The usage then drops off; that's when I ran `reset` to clear the scrollback:

![image](https://user-images.githubusercontent.com/117777/111037158-cb7b6100-83d7-11eb-81b9-f41022a12ccf.png)

(the numbers on the y-axis to the right are hard to read because heaptrack is a kde/qt app and it doesn't seem to like the dark gnome theme so much)

If I edit the stream you provided so that the cursor movement between the frames moves up by 18 instead of 17 cells, then I don't get the smearing effect and this is how the heap looks:

![image](https://user-images.githubusercontent.com/117777/111037267-3af15080-83d8-11eb-8f54-359e21c1a40f.png)

I also tried the stream in iTerm2 and it has the same smearing effect.

So, I think the thing to focus on now is cursor positioning, and I think there is a mismatch between `timg`'s expectations and the terminal.

**Comment by hzeller** [comment]
Thanks, I can confirm that the memory use is now much more bounded.

The 'smearing'  should not happen when you run timg directly. Problem in this case was of course that it is a canned output that matches my terminal font and size.

The jump size calculation is a function of the font size, which might be different for you and me. In fact my case it _also_ starts smearing when I resize the wezterm due to #535 .

Timg determines the character cell size on startup and uses that to determine how many character cells to jump up at the end of an image. In this particular case it was 17 characters. Since I just sent the terminal output that now has the hard-coded `\033[17A` in it, this might not line up of how large the pixels in your terminal are. This problem will not arise if you run timg directly, because then it can determine the pixel size on your particular terminal.

So if you compile and run [timg](https://github.com/hzeller/timg#build-and-install) directly, there should be no scrolling artifacts as it determines the size beforehand with `ioctl(...,TIOCGWINSZ)`

**Comment by wez** [comment]
Great; I did just confirm that this looks great when running `timg` directly!

Regarding the output stream, the iterm2 protocol supports specifying the dimensions in cells rather than pixels, so it may be viable for timg to specify those so that the cursor movement lines up with its calculations.  Assuming that the terminal emulator faithfully displays the image at the intended size!

**Comment by hzeller** [comment]
#TIL about heaptrack, neat.

I did not want to use the size depending on cell dimensions, as it would mean to slightly modify the aspect ratio of the image. And people do [notice...](https://github.com/hzeller/timg/issues/44)

I think this is resolved.
