### ISSUE TITLE
Crashes when maximized on Fedora X11

### ISSUE THREAD

**Issue by gaborbernat** [wez/wezterm#543]
## Environment (please complete the following information):

 - OS: Fedora Linux Wayland
 - Version: please run `wezterm -V` and include its output here: ``wezterm 20210314-114017-04b7cedd-3-g5681cd9b``

## To Reproduce

Just start wezterm and resize to full screen.

```
 2021-03-15T09:46:31.334Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-10874
 2021-03-15T09:46:31.753Z INFO  wezterm_gui::termwindow        > OpenGL initialized! llvmpipe (LLVM 11.1.0, 256 bits) OpenGL ES 3.2 Mesa 21.0.0 is_context_loss_possible=false wezterm version: 20210314-114017-04b7cedd-3-g5681cd9b
 2021-03-15T09:46:34.801Z ERROR wezterm_gui                    > X11 connection is broken: ClosedReqLenExceed Connection closed, exceeded request length that server accepts.; terminating
XIO:  fatal IO error 0 (Success) on X server ":0"
      after 228 requests (228 known processed) with 0 events remaining.
```

**Comment by wez** [comment]
What's the resolution of the screen?

**Comment by gaborbernat** [comment]
3840 x 1600, 👍🏻 100% scale.

**Comment by wez** [comment]
I've had something like this come up previously in https://github.com/wez/wezterm/issues/249
In that issue, the main problem was that we couldn't find a good opengl configuration and were falling back to a simplistic software renderer.  We don't have that renderer anymore, so it's probably not that.

From the output you shared, it looks like mesa is being used to talk to XWayland, which should be fine.
wezterm itself no longer has any code that might be directly making large requests, so I'm not 100% sure what to make of this.

What I'd suggest is capturing the X11 traffic so that I can take a peek and see if that provides any clues.

It's unfortunately a bit involved to do this.  You'll need:

```
sudo dnf install socat tcpdump
```

Now, run socat to allow a TCP connection to be routed to the X11 unix domain socket.  First you need to know which unix domain socket to attach to.  For regular X on Fedora (not via Wayland) a `DISPLAY=:1` environment maps to `/tmp/.X11-unix/X1`.  XWayland may be a little different.  You can likely figure it out using `lsof -p $(pgrep XWayland) | grep unix`.

Start socat in a terminal window of its own; we're using port 6002 here, which corresponds to `DISPLAY=:2` via TCP.
*NOTE*: this will listen on any address by default, and depending on your firewall may expose your xserver to other hosts on the network or beyond!  The unix-client portion should refer to the unix domain socket used by XWayland on your system.

```
socat TCP-LISTEN:6002 UNIX-CLIENT:/tmp/.X11-unix/X1
```

Now set up a packet capture for that port; in another terminal window:

```
sudo tcpdump -i any 'port 6002' -w /tmp/x.dump
```

and finally, start wezterm and point it at the tcp port:

```
DISPLAY=:2 wezterm
```

then try maximizing the window.

Once done, switch to the tcpdump window and hit CTRL-C.

Please attach `/tmp/x.dump` to this issue, or if you'd rather not share it in public, you could send it to me through some other means.  When I have it, I'll use `wireshark` to see if I can understand which request/response in the X11 protocol is erroring out.

**Comment by gaborbernat** [comment]
For reference, this only happens with Fedora with Wayland. Fedora on Xorg (x11) works fine. Also with Wayland there seems to be an extra empty pixel on the top of the screen. I have an Nvidia driver, so mind you Fedora with Wayland and Nvidia is not a really happy story at the moment.
