### ISSUE TITLE
More options from for DOMAINS in `ShowLauncherArgs`

### ISSUE THREAD

**Issue by simonmandlik** [wez/wezterm#5553]
I'm using this amazing keymap for attaching SSHMUX domains:

```{ mods = "LEADER", key = "a", action = act.ShowLauncherArgs { flags = "FUZZY|DOMAINS" } }```

This works amazingly as long as the specific hostname is specified in `~/.ssh_config`. There is one problem with this. Sometimes I modify settings only for the second-level (or the third-level) domain, as there are might be too many possible subdomains. 

This often happens in HPC clusters. I would have something like

```
cluster.com:
    User ...
    IdentityFile ...
```

in `~/.ssh_config`, and I would connect like `ssh node118.cluster.com` or `ssh node43.cluster.com`. In such cases, `wezterm.enumerate_ssh_hosts()` only shows `cluster.com`.

I can think of two ways two solve this without having to use wezterm cli for each connection:

- make it possible to explicitly write a full domain name in the menu
- parse hosts also from `~/.ssh/known_hosts`.

**Comment by wez** [comment]
I'm not sure exactly what you're angling for here, but I do want to note that:
You have full control over the list of ssh domains via https://wezfurlong.org/wezterm/config/lua/config/ssh_domains.html

You might consider adjusting your config to parse `~/.ssh/known_hosts` or otherwise obtain the relevant list of hosts using logic that makes sense to you and your specific use case.

**Comment by simonmandlik** [comment]
Thanks for the answer! I have solved it by manually modifying `config.ssh_domains`.
