### ISSUE TITLE
Missing Guidance on Howto set WezTerm as default terminal

### ISSUE THREAD

**Issue by jreuben11** [wez/wezterm#5861]
`sudo update-alternatives --config x-terminal-emulator` is not listing WezTerm as an option (installed from Snap)

**Comment by ViniciussSantos** [comment]
The guidance isn't shown because it changes depending on your system. If I'm not mistaken, gnome uses update-alternatives, kde uses its system config GUI, some window managers just ask you to modify a line in some random config file, etc. It would be a waste of time to document something that is so specific to the user's system and that is already documented in the window manager docs.

**Comment by holocronweaver** [comment]
As @jreuben11 mentioned, if installed via flatpak then wezterm does not show up in `update-alternatives`. However directly settings `gsettings` works for me:

```
gsettings set org.gnome.desktop.default-applications.terminal exec 'flatpak run org.wezfurlong.wezterm'
```

**Comment by majamin** [comment]
Also, this enables (flatpak) wezterm to start in a specific directory in Nautilus ("open terminal here"):

Following the directions from [Nautilus-open-any-terminal](https://github.com/Stunkymonkey/nautilus-open-any-terminal), in `dconf-editor` or `gsettings`, edit "com.github.stunkymonkey.nautilus-open-any-terminal" to have terminal 'custom' and 'custom-local-command' to `flatpak run org.wezfurlong.wezterm start --cwd %s`.
