### ISSUE TITLE
macOS PATH instructions: Should PATH be a string?

### ISSUE THREAD

**Issue by schlich** [wez/wezterm#5967]
**What page or section of the docs have an issue?**
[FAQ](https://wezfurlong.org/wezterm/faq.html#im-on-macos-and-wezterm-cannot-find-things-in-my-path)

**Describe the issue**
In the example towards the bottom, we have:

```
config.set_environment_variables = {
  PATH = {
    -- prepend the path to your utility
    wezterm.home_dir
      .. '/.local/bob/nvim-bin:'
      -- and include the rest of the PATH
      .. os.getenv 'PATH',
  },
}
```

however, PATH is expected to be a string, and at least on my system, would throw a Lua error when the configuration was saved until this was corrected.

**Comment by tjex** [comment]
Yes, PATH, and all environment variables for that matter are strings.

Are you saying the code example above from the documentation is incorrect / not a string?

**Comment by schlich** [comment]
@tjex

Yes, PATH was interpreted as an object by the Lua parser given the example, sorry for not being clear.

Taking away the brackets and trailing comma fixed the configuration error for me.

I don't know Lua but am happy to help further clarify the error if needed

**Comment by tjex** [comment]
@schlich Ahh yep. I guess because it was a singular string. 
The brackets _and_ a trailing comma on a singular string will suggest to lua that you're giving it a table, which is also valid, but you need to remove the last trailing comma (so brackets _without_ the trailing comma for a singular string should still be valid).

Eg, I fill `PATH` with multiple strings in my conf here: https://github.com/tjex/wezterm-conf/blob/main/util.lua
