### ISSUE TITLE
Wezterm Crash when copying text

### ISSUE THREAD

**Issue by ishaanparlikar** [wez/wezterm#6033]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

hyprland 0.42.0-1, EndeavorOS, Wezterm-git (AUR)

### WezTerm version

 wezterm 20240812-215703-30345b36

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

App crash when selecting text or copying.

### Configuration

https://github.com/ishaanparlikar/linux-dotfiles/tree/main/config/wezterm

### Logs

20:43:52.177  ERROR  wezterm_gui                            > running message loop: process_queued_xcb: ChangeProperty {
    mode: Replace,
    window: Window {
        res_id: 2097181,
    },
    property: Atom {
        res_id: 246,
    },
    type: Atom {
        res_id: 294,
    },
    data: [
        91,
        102,
        111,
        110,
        116,
        46,
        110,
        111,
        114,
        109,
        97,
        108,
        93,
        10,
        102,
        97,
        109,
        105,
        108,
        121,
    ],
}

**Comment by loops** [comment]
Hi ishaanparlikar,

Would you be able to apply this PR: https://github.com/wez/wezterm/pull/6004   and test again?

**Comment by ishaanparlikar** [comment]
Hey @loops 

Still same issue. 

`22:06:36.697  ERROR  wezterm_gui > running message loop: process_queued_xcb: ChangeProperty {
    mode: Replace,
    window: Window {
        res_id: 2097165,
    },
    property: Atom {
        res_id: 246,
    },
    type: Atom {
        res_id: 294,
    },
    data: [
        99,
        97,
        116,
        58,
        32,
        47,
        114,
        117,
        110,
        47,
        117,
        115,
        101,
        114,
        47,
        49,
        48,
        48,
        48,
        47,
        119,
        101,
        122,
        116,
        101,
        114,
        109,
        58,
        32,
        73,
        115,
        32,
        97,
        32,
        100,
        105,
        114,
        101,
        99,
        116,
        111,
        114,
        121,
    ],
}: X(Window(ValueError { response_type: 0, error_code: 3, sequence: 881, bad_value: 2097165, minor_opcode: 0, major_opcode: 18, pad: 1 }), Some("x::ChangeProperty")); terminating
`

**Comment by loops** [comment]
Okay, I installed Hyprland and gave it a try, but was still unable to reproduce your issue.  I'm assuming you are just using the mouse to select and copy text?   If you could capture a gdb backtrace of the panic, it might help narrow things down.

But it looks like you are actually running under emulated X11, rather than using Wezterms Wayland support.   (process_queued_xcb is for X11, not wayland).   So it's possible that your configuration is confusing Wezland, or maybe not passing all the necessary WAYLAND environment variables when starting Wezland.

For example:    

WAYLAND_DISPLAY=wayland-1
XDG_SESSION_TYPE=wayland

It would be interesting to know how each of those variables is set for you.

**Comment by ishaanparlikar** [comment]
@loops i was running wezterm without wayland support because AUR package wasn't working . 
I built it from source and removed  config which disables wayland support. It is working as expected.
