### ISSUE TITLE
True client server architucture

### ISSUE THREAD

**Issue by Zeioth** [wez/wezterm#6066]
**Is your feature request related to a problem? Please describe.**
There should be a way to start the wezterm server without the need to spawn the GUI.

**Describe the solution you'd like**
There should be 3 different executables:

* Wezterm server
* Wezterm client (the gui)
* Wezterm multiplexer

## Why a dedicated client/server architecture
* That way we only need one server for all clients.
* which greatly improves startup time.
* and reduce RAM consumption.

## Why a dedicated multiplexer?
* In the same way we have tmux, one could summon the multiplexer from any terminal, or instance.
* This has great flexibility, as the multiplexer is independant from the GUI

**Describe alternatives you've considered**
I imagine the reason for the current architecture is Windows support, as it is not trivial to create windows services and it might require user permissions.

**Additional context**
User feedback: I've tested wezterm for 48h, and while I really like the fact it's written in rust and its GPU acceleration is FAST. But

* I find the lack of a client/server architecture, not ideal from the point of view of resource management.
* Also the fact users are obligated to keep a GUI instance open in order to keep their session is quite limiting.

I get these two points are probably not a deal breaker for most people though.

**Comment by loops** [comment]
Hi Zeioth. 

Wezterm is already a client/server architecture.    For example, while not strictly necessary, one option is to run : 

   weterm-mux-server --daemonize

And the server will be running.  You can connect to it with the GUI from the local machine, or any other machine as long as you have network connectivity.  (This is accomplished by configuring wezterm local/ssh domains, to connect to the server).

So I don't think you've explained the problem properly.

It's not a lack of client-server that you're wishing for.  It sounds like what you want, is to have a text-based client, that you can use to connect to the server, without using the wezterm client.   But, pretty much the entire point of wezterm, is to free you from the need of using any other terminal emulator.

Or, maybe you just haven't figured out how to configure it yet?   Because, you can configure wezterm to run on any of your machines, and connect to it remotely from any client of your choosing.  Whereas tmux requires you to configure a terminal emulator to use it, wezterm provides the terminal emulator in a single, convenient program.
