### ISSUE TITLE
Initial Lag when trying load in maximised state

### ISSUE THREAD

**Issue by psadi** [wez/wezterm#6127]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When trying to open wezterm as a maximised state there is a animation lag (Comparing this to other terminals i was not able to produce the same).

Any idea why this happens ? Is there a  configuration i can change to make things better ?

Linking my config [wezterm.lua](https://raw.githubusercontent.com/psadi/.dotfiles/main/.config/wezterm/wezterm.lua) for reference. 

Attaching a screen-recording for the same.

https://github.com/user-attachments/assets/53017477-8ccb-4392-a89f-655c579f236b

### Configuration

```lua
wezterm.on("gui-startup", function()
  local tab, pane, window = mux.spawn_window(cmd or {})
  window:gui_window():maximize()
end)

```

### Logs

Debug Overlay
wezterm version: 20240203-110809-5046fc22 x86_64-apple-darwin
Window Environment: macOS 14.6.1 (23G93)
Lua Version: Lua 5.4
OpenGL: Intel(R) UHD Graphics 630 4.1 INTEL-22.5.11
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>

**Comment by loops** [comment]
Hey psadi,

Hopefully someone else who knows more about this will chime in.  But you could try
starting wezterm like so:

   WEZTERM_LOG=trace wezterm

And look through the resulting trace output detail, to see if it's obvious which
step is causing the delay.

**Comment by psadi** [comment]
Hi @loops 

As a global solution i tried removing & re-installing wezterm  (ensuring application cache files are removed)

The startup now seems better(imho its totally fine now & perfectly usable as it loads under 3ms, my config is pretty minimal)

I don't know why i faced such behaviour in the first place (I'll wait for someone to answer if this can be narrowed down).

**Comment by wez** [comment]
The approach being used to maximize on startup is really maximizing *while* starting up.
macOS animates trivial operations like window resizing, so the window is likely experiencing several "live" window resize events while it is trying to render.

Stutters like the one shown tend to correlate with something heavy in the configuration; you didn't share your full config so it is difficult to say whether you have a heavy configuration file or not.

In addition, opengl performance with intel graphics macs does tend to under perform.

You might consider trying one or more of:
* Setting the front end to webgpu: https://wezfurlong.org/wezterm/config/lua/config/front_end.html, which uses Metal instead of OpenGL.
* Disabling window animations in macOS
* Instead of maximizing the window, use https://wezfurlong.org/wezterm/config/lua/window/toggle_fullscreen.html which (by default) doesn't use the native animated full screen mode in macos, and resizes directly to the correct size. This is what I use when I want a full screen window; there's less chrome, more real estate for the terminal, and it is instantaneous.  Default key assignment to toggle this is alt-enter.

**Comment by psadi** [comment]
@wez  - Thanks for getting back,

Please do find my config - https://raw.githubusercontent.com/psadi/.dotfiles/main/.config/wezterm/wezterm.lua (Attached in OP under Description as a hyperlink hence could have been missed out)

I will try out your suggestions on WebGpu and `toggle_fulllscreen` and report back if there are any improvements.

**Comment by psadi** [comment]
@wez - Thank you for the proposed solution. While it's not exactly what I wanted, I agree that it works given the rendering constraints on Intel Macs. However, I’d like to note that ToggleFullscreen behaves differently from a maximized window at startup, as it moves the window to a separate workspace, which isn't ideal for my use case.

I would like to suggest the addition of a configuration option that allows users to toggle between Normal, Maximized, or Fullscreen modes at startup. At the moment, I don't see a straightforward way to configure this directly, and I had to implement a workaround based on my current setup.

Feel free to close the issue, or keep it open if you prefer to track this as a enhancement.
