### ISSUE TITLE
Lua Debug Terminal

### ISSUE THREAD

**Issue by gwww** [wez/wezterm#641]
**Is your feature request related to a problem? Please describe.**
In order to learn about the API having a playground to test things out would be helpful. It would allow tweaking the running in-memory configuration to try out ideas.

**Describe the solution you'd like**
The basic idea is that a new window (or tab??) pops up that allows you to type in Lua and see the results. The context would be with the running configuration, globals, etc. All `print` statements would display in the debug terminal. A bonus is that all `log` messages would show up there too.

Any Lua statements would affect the current running config if they are applicable.

I don't yet understand `domain`s but my guess is a `DebugDomain` concept might apply.

`Hammerspoon` (also Lua-based config) has a concept similar to what I'm proposed with the
 `toggleConsole` command. 

![Screen Shot 2021-04-04 at 14 39 24](https://user-images.githubusercontent.com/3060128/113518316-99cb6500-9553-11eb-813e-278571247298.png)

**Describe alternatives you've considered**
I thought about having a modifying `SendString` that might accomplish the purpose but that does not seem like a right solution as it would not be "powerful" enough.

**Comment by wez** [comment]
There's now a basic implementation of this in `main`; a debug overlay can be activated and shown over the tab of the current tab.
Pressing escape (when the prompt line is empty) will cancel the overlay.
Typing in lines of lua code will evaluate that code and print the return value of that expression.

I've bound `{key="l", mods="SHIFT|CTRL", action="ShowDebugOverlay"},` to trigger the debug overlay in my local config.

Any state changed in the lua context in that overlay is local to that overlay.  The lua context has `wezterm` pre-imported, but doesn't yet have access to the `window`, so it's not possible to effect any real changes from this context at this time.

One thing to note about this is that it won't be possible to directly define event handlers using `wezterm.on` in this repl, because those events need to be accessible via the main config on the main thread and this repl environment cannot access that context.

However, once `window` and some functions that expose info about the rest of the mux model are present, it should be useful as a way to inspect and prototype the more imperative things.  For example, this demonstrates playing around with the colors in format and quickly seeing the results:

![image](https://user-images.githubusercontent.com/117777/116904150-33893f00-abf2-11eb-8b13-d17d312273ed.png)

**Comment by gwww** [comment]
Thanks for this!!! You are rocking!!

A couple of things I noticed to start. SHIFT+CTRL+L cleared my screen rather than invoking the debug overlay. When I
added it to my key mappings it worked fine.

It was aggressive in parsing. I typed `a=` and got an syntax error before I could complete the `a=1`.

I haven't tried much else yet, and, I know this is early code. Pretty cool though! And it didn't seem to be much code when I browsed the commit.

**Comment by wez** [comment]
> When I added it to my key mappings it worked fine.

Yeah, I haven't added a default key assignment for this yet.

> It was aggressive in parsing

Yeah, the line under the line editor shows a "preview" of the parse status.  It parses but does not execute the code until you hit enter!
