### ISSUE TITLE
Windows font rendering isn't as sharp as cmd

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#79]
I've been playing around with the font settings, experimenting with the DPI sizes - taking it as low as 60 and as high as 144 and then adjusting the font size to compensate, and I even tried out the Allsorts shaper (briefly), but honestly, the text is nowhere near as sharp as the bog-standard command prompt or powershell terminal. (Also, don't use any DPI scaling, as I'm still on a 1920x1080 monitor.)

For all I know this might be a limitation of actually being able to support things like ligatures, emojis, and powerline, but just in case it's not intended or if I'm doing something wrong, I figured an issue is warranted.

**Comment by wez** [comment]
Would you mind sharing the font and font size you're using?
Please also share a screenshot demonstrating the difference between conhost and wezterm as that can help to understand the nature of the discrepancy!

**Comment by ImportTaste** [comment]
Here is Consolas, a default system font. Font size 16 on the left (conhost), font size 11 on the right (wezterm):

![image](https://user-images.githubusercontent.com/53661808/71136250-d130c980-21c9-11ea-8725-db28eda418f5.png)

Now here it is with 24 left (conhost), 15 right (wezterm)

![image](https://user-images.githubusercontent.com/53661808/71136333-210f9080-21ca-11ea-8c84-db67a66ffed9.png)

Of course this is without messing with dpi settings (neither in Windows or in wezterm toml, to clarify). I have messed with the wezterm toml dpi setting plenty but I tend to get similar results regardless, so I just omit it which I think puts it at the default of 96.

**Comment by wez** [comment]
I'll make some time to look at this in detail tomorrow on my windows machine, but in the meantime, in case you're still tinkering, here are a couple of pieces of data:

* The conhost terminal settings show font sizes in pixels.  The wezterm config is in points.  You can convert points to pixels using `pixels = points * dpi / 72`, and if you flip that, you can convert pixels to points using: `points = pixels * 72 / dpi`.
* For conhost pixel size 16, at 96 dpi you would use wezterm point size 12.  If it looks to your eye that 11 is the same size then I think that there is a discrepancy between our assumed default dpi of 96 and the actual dpi of your screen.
* Windows is the only platform for which we get precise dpi information from the OS, but for various cross platform annoyances reasons that value isn't directly available for some of the font calculations and the value from the config file is used instead.  If you set RUST_LOG=trace in the environment, [this line](https://github.com/wez/wezterm/blob/master/src/frontend/gui/termwindow.rs#L249) will log the window dimensions and dpi so you can tell exactly what dpi Windows has for your monitor.  I'd recommend setting you wezterm.toml to set dpi to that value so that we're not doing any fractional scaling.  (We should really make this "just work", but let's figure out how to get you sharpened up first!)
* It's possible that OpenGL driver weirdness is playing a part in scaling something in an unexpected way.  You may wish to try starting wezterm with the CPU (rather than GPU) based software renderer and see if that feels sharper: `wezterm start --front-end software`.  If that feels better for you, you can set `frontend = "Software"` at the top of your `wezterm.toml` to make it the default.
* We turn on maximum anti-aliasing options in freetype and don't expose options for experimenting with them yet.  We should add some because perceived clarity is definitely subjective, but in the meantime, if you're set up to build wezterm from source (you need the rust compiler and the community visual studio compiler: don't go out of your way for this, just try it if it is convenient), there are a couple of things you can change in the code to change those options:
  * Try commenting out [this line](https://github.com/wez/wezterm/blob/master/src/font/ftwrap.rs#L179) to disable a filtering pass for LCDs (subpixel rendering, which is roughly analgous to the Windows ClearType setting being enabled).  I'm not sure if this is properly enabled in our build on Windows so this may be a NOP anyway; this is something I'll look at tomorrow.  [this page](http://freetype.sourceforge.net/freetype2/docs/reference/ft2-lcd_filtering.html) describes how that works
   * [these lines](https://github.com/wez/wezterm/blob/master/src/font/rasterizer/freetype.rs#L26-L28) select the render mode, which is [described here](http://freetype.sourceforge.net/freetype2/docs/reference/ft2-base_interface.html#FT_Render_Mode) you could try setting it to the `DEFAULT` mode by uncommenting part of the first of those lines and commenting out the last of those lines.

As I said, I'll sit down and work though the above for myself tomorrow, and I'll expose some options to make it easier to dial in the settings that look best.

**Comment by ImportTaste** [comment]
```
 TRACE wezterm::frontend::gui::termwindow  > resize event, current cells: RowsAndCols { rows: 25, cols: 80 }, new dims: Dimensions { pixel_width: 720, pixel_height: 500, dpi: 96 }
```
Nope, that's not it...

> It's possible that OpenGL driver weirdness is playing a part in scaling something in an unexpected way. You may wish to try starting wezterm with the CPU (rather than GPU) based software renderer and see if that feels sharper: wezterm start --front-end software. If that feels better for you, you can set frontend = "Software" at the top of your wezterm.toml to make it the default.

THIS is the problem. Starting wezterm like this, it's way, way, WAY sharper.

**Comment by ImportTaste** [comment]
Well I got close, but unfortunately the `zstd-sys` package won't compile with the gcc provided by Strawberry Perl and I'm too tired to fuck with it any more tonight.

**Comment by wez** [comment]
I have finished looking into all of this yet, but just wanted to let you know that I pushed a commit that adds two new options:

```
font_antialias = "Subpixel" # None, Greyscale, Subpixel
font_hinting = "Full" # None, Vertical, VerticalSubpixel, Full
```

These take effect as you save the config file, so you can more easily see the effect of changing them.

**Comment by wez** [comment]
A couple of things I'm curious about if you wouldn't mind sharing:

 * What is the approx. physical diagonal size of your display in inches?  A larger 1080p display would be less forgiving of the rasterizer than a smaller panel, for example.
 * What is the driver/GPU that wezterm prints out if you set `RUST_LOG=info`? look for the `OpenGL initialized!` line

Aside from that, I've been playing with setting fractional sizes for fonts (eg: 10.3) and doing that with Consolas gets closer to the 16px line height.  I'm not sure if you tried using fractional sizes because it isn't obvious that that is possible.

**Comment by ImportTaste** [comment]
> What is the approx. physical diagonal size of your display in inches? A larger 1080p display would be less forgiving of the rasterizer than a smaller panel, for example.

24"

> What is the driver/GPU that wezterm prints out if you set `RUST_LOG=info`? look for the `OpenGL initialized`! line

INFO  wezterm::frontend::gui::termwindow  > OpenGL initialized! GeForce GTX 1070/PCIe/SSE2 4.6.0 NVIDIA 441.66

> Aside from that, I've been playing with setting fractional sizes for fonts (eg: 10.3) and doing that with Consolas gets closer to the 16px line height. I'm not sure if you tried using fractional sizes because it isn't obvious that that is possible.

I noticed that but I wasn't sure if it was intended, and I was concerned if I reported a fractional size, that would be blamed for the fuzzy text.

**Comment by ImportTaste** [comment]
Could you upload a pre-compiled Win10 x64 `zstd-sys` (not compiled with cygwin/msys2)? And perhaps, if the license allows, include it in the project?

**Comment by wez** [comment]
> Could you upload a pre-compiled Win10 x64 `zstd-sys` (not compiled with cygwin/msys2)? And perhaps, if the license allows, include it in the project?

Rust should be able to build this without resorting to binary uploads (also: it's effectively impossible to instruct the build system to use a pre-built binary for this due to the way that the `zstd` crates are configured).

I'd recommend that you use the `stable-msvc` rust toolchain: `rustup default stable-msvc`.  You'll need to install the (free!) community edition of visual studio from https://visualstudio.microsoft.com/downloads/ first.

**Comment by ImportTaste** [comment]
I have VS2019 Enterprise actually, I was just using the x64 Native Tools Command Prompt. I'll try it with that command.

**Comment by ImportTaste** [comment]
> rustup cannot be installed alongside Rust

wait what

**Comment by ImportTaste** [comment]
Alright, I got it compiled. It seems like the new options you added make the suggested edits obsolete though, but it will be useful for the future.

**Comment by ImportTaste** [comment]
font_hinting doesn't seem to do anything when font_antialias is set to Subpixel.

Setting font_antialias to Greyscale and font_hinting to None seems to look the best.

**Comment by ImportTaste** [comment]
@wez Will https://github.com/wez/wezterm/commit/291800b49a91ca6b64c584f029b0ec4580fa284a affect the appearance of non-glyphs? Just want to know if I should do another round of experiments.

**Comment by wez** [comment]
I did think of you when I pushed that commit.  I don't think it will change what you were experiencing here, but it may if for some reason on your system the rasterized font was overflowing the width of the cell.  I don't think that could happen for you and not me for the fonts and configs that we discussed.

That change does impact rendering of the Noto Color Emoji font in a semi-obscure case.
The example is the heart emoji, which has double width in some versions of the unicode spec and single character width in others.  We use single character width for compatibility with unix programs (eg: vim).  In that particular font it has double width.  Prior to that change we would scale it down to fit in a single character cell which made it look a bit small.  After that change we no longer scale it and it renders across two cells rather than the single cell it should occupy.  It looks better at its full size, provided that a space is rendered after it(!).   This is a bug and I'll be thinking about how to deal with that.

**Comment by ImportTaste** [comment]
I made an interesting discovery. Command Prompt actually uses ClearType. Open a command prompt and then 'Adjust ClearType Text' in the old school Control Panel and toggle this little checkbox here:

![image](https://user-images.githubusercontent.com/53661808/71332907-a1e9c780-24fd-11ea-93f6-479688c41a46.png)

I found some documentation on how ClearType does its subpixel rendering: https://docs.microsoft.com/en-us/typography/cleartype/

It looks like the Rust implementation would be DirectWrite, but looking into it, it seems it's a low priority: #40

**Comment by wez** [comment]
Did you end up with a satisfactory configuration?

It is possible to implement a DirectWrite rasterizer but I'm hoping to defer/avoid that if possible: there is a degree of simplicity to be had from just having a single rasterizer that makes it easier to know that a change made on one of the supported operating systems is going to look the same on one of the others.

**Comment by ImportTaste** [comment]
Yeah, Greyscale anti-aliasing just looks so much better than the Subpixel option. It's going to end up much bolder than what DirectWrite can do, but it's still clearly legible.

It wouldn't be a bad idea to try and [recreate the look](https://graphicdesign.stackexchange.com/questions/117027/how-to-recreate-subpixel-anti-aliasing-like-windows-command-prompt) if you ever get the drive or the time. Probably a low priority as well.

I'm anxious to get my hands on wzsh the moment it can handle scripts.

**Comment by wez** [comment]
FWIW, ClearType is patent encumbered, so I don't want to go near trying to copy how it works.  FreeType has a compilation option (which defaults to disabled with a strong notice about patents) to enable its equivalent (the LCD filtering option we discussed earlier).

The Subpixel rendering option is the patent-free implementation provided by FreeType that is generally quite good: it looks fine on my Windows system.  This aspect of font rendering is highly subjective which is why modern operating systems take you through a flow where you visually select the option that appears best to you.

The main thing is that you have some options that give you something that works for you, so with that in mind, I'd like to call this issue closed; does sound ok to you?

**Comment by ImportTaste** [comment]
Sounds good

**Comment by ImportTaste** [comment]
It's been a long time, but I've been playing with wezterm today and I discovered HorizontalLcd gives a very similar sharpness look to the traditional cmd window. Given this setting was around when I filed the issue, I'm sure I must've tried it, but it seemed that [#639](https://www.github.com/wez/wezterm/issues/639) was the culprit.
