### ISSUE TITLE
Slow framerate on MacOS 11.2.2

### ISSUE THREAD

**Issue by dabeeeenster** [wez/wezterm#790]
## Describe the bug

The larger the Wezterm window is, the slower the rendering framerate. Using it full height on a 4k monitor yields extremely low rendering performance

## Environment (please complete the following information):

 - OS: MacOS11.2.2
 - Version: wezterm 20210511-192024-a59e9b17
 - The active keyboard layout name ENG

## To Reproduce

Open new application with no configuration files defined. Maximise the window on a large monitor. Run something like `ls -R` and see low framerates.

## Configuration

No config file used. 

## Expected behavior
60fps rendering

## Other Info

Am running with a Radeon RX 570 8 GB. iTerm works fine with hardware acceleration enabled.

**Comment by wez** [comment]
Is the framerate better for you when using the latest stable release, rather than the nightly build?

**Comment by dabeeeenster** [comment]
No it's bad on both. Strangely its fine on my 13" MBP Intel laptop but not great on my desktop.

**Comment by wez** [comment]
FWIW, it is expected that the larger the terminal area (in cells), the more expensive the render becomes, because there is a lot of information to compute (shaping ligatures for the screen is `O(rows * cols)`).
Raw render performance is strongly influenced by the graphics card performance.

You mentioned that your mbp renders fine: is that when it is attached to the same monitor?
If so then it implies a lower level graphics issue on your desktop system.
If not, then I suspect that this is a higher level shaping issue.

You can run `WEZTERM_LOG=trace wezterm 2> /tmp/wezterm.txt` to capture logging with timing information.
Those logs will be really verbose, but if you `grep elapsed /tmp/wezterm.txt > /tmp/wezterm.timing.txt` it will focus on just the timing info and help to understand where time is being spent.

Please capture that timing info for both of those systems!

**Comment by dabeeeenster** [comment]
OK slow system is: https://gist.github.com/dabeeeenster/a33f4b6145c384a3c669f58bddb23af0
Fast system is: https://gist.github.com/dabeeeenster/ba9f452ad38c1026a1b34f2950f320d2

* Slow system is a hackintosh (which might have something to do with the cause?) with a Radeon RX 570 8 GB
* Fast system is a 2020 MBP 13"

**Comment by wez** [comment]
If you grep `lines elapsed`, do you consistently see ~100ms for the times on the hackintosh?

How does that compare with the mbp?  (the paste from the mbp seems shorter, and shows a fairly fast frame of ~3ms; I'm not sure we're seeing the whole picture there).

Are these both the same monitor/terminal size?

The work encapsulated in `lines elapsed` is all CPU bound; how does the CPU in the hackintosh compare to the mbp?

**Comment by dabeeeenster** [comment]
Hackintosh: https://gist.github.com/dabeeeenster/bbedb2b5c1ad241de7795016cbef1e93
MBP: https://gist.github.com/dabeeeenster/e38bab076973a7680a0a9f0fccab6b34

Both going through the same 4k monitor. Consistent window size/DPI etc. 

Hackintosh is a ryzen 5 5600x so quite a bit more powerful than the MBP.

**Comment by wez** [comment]
Would you mind trying the latest nightly and see if things are improved? The render logic has had a number of enhancements that should help

**Comment by dabeeeenster** [comment]
Perfect! All running at light speed now. Thanks so much.
