### ISSUE TITLE
`exit`ing shell with non-empty scrollback doesn't close the pane/tab

### ISSUE THREAD

**Issue by sclu1034** [wez/wezterm#795]
## Describe the bug

When trying to close a tab or pane where there is scrollback (output exceeded available height) by exiting the shell (e.g. `exit` or `Ctrl + D`), the pane doesn't close, but prints `[Process completed]` and becomes unusable.
If I close the X window through the WM, the process will linger and need to be `kill`ed. Closing the tab by middle mouse click does stop the `wezterm` process properly.

The `ClearScrollback` action (both versions) has no effect.

## Environment:

**OS:** Linux X11
**Version:** `wezterm 20210511-192024-a59e9b17`

## To Reproduce

- open WezTerm
- produce some output to fill the scrollback (e.g. `yes`)
- press `Ctrl + D` or run `exit` to end the shell

## Configuration

I did check `term`, `scrollback_lines` and `wezterm.sh` (sourced in `zsh`), but they don't affect behaviour.
I also tried a config of `return {}`.

## Expected behaviour

Closing the shell/process should always close the tab/pane.

**Comment by wez** [comment]
Take a look at https://wezfurlong.org/wezterm/config/lua/config/exit_behavior.html

Most likely what you are seeing is that you ctrl-c'd the last command in the shell; when you subsequently ctrl-d the shell, it returns with the unsuccessful exit status of the interrupted command.  Since `exit_behavior = "CloseOnCleanExit"` by default, wezterm keeps the pane alive so that you have a chance to see what went "wrong".

If you don't like that behavior, you can set `exit_behavior = "Close"`.

**Comment by sclu1034** [comment]
> Most likely what you are seeing is that you ctrl-c'd the last command in the shell

That was indeed the case and `exit_behavior = "Close"` does create the behaviour I had expected.

This might be worth mentioning in the guides or FAQ sections of the docs, given that WezTerm seems to be the only one with this particular default behaviour compared to other popular terminals.

**Comment by wez** [comment]
FWIW, I changed the messaging to be more explicit about this in https://github.com/wez/wezterm/commit/db4523876945f8ba95892e8b1233312c56e3ff0b
