### ISSUE TITLE
Add Error Log Window

### ISSUE THREAD

**Issue by ImportTaste** [wez/wezterm#80]
To make it easier to diagnose errors when spawned entirely from a GUI context, it would be desirable to add an error log window.

* Default to not showing the window on startup (but config to make it show anyway)
* Key assignment to show the window manually
* Allow certain conditions (such as error loading config, or connectivity errors with ssh/mux) to show the window
* The window would show a capture of the most recent log messages from the standard rust logging layer

**Comment by wez** [comment]
I think the current notifications are "OK" for their intended purpose, which is to let you know that something isn't working, rather than giving you a precise inventory of problems.

For the latter situation, I think that it is probably better overall if we had a separate window that we could show with an error log.   I'm going to edit this issue to capture how I think that should work.

**Comment by ImportTaste** [comment]
That's a good adaptation. Might I recommend configuration for tab flashing and/or user-selected sound file when an error does occur? (Startup being the exception.)

**Comment by wez** [comment]
Re: flashing/sounds: https://github.com/wez/wezterm/issues/3 is tracking the bell/alerting concept

**Comment by wez** [comment]
As of https://github.com/wez/wezterm/commit/bb9504d6262b54f52e5a534e5a2182591056aa95 I think this is "good enough".
