### ISSUE TITLE
Allow defining tab bar colors in color scheme files

### ISSUE THREAD

**Issue by Anomalocaridid** [wez/wezterm#807]
**Is your feature request related to a problem? Please describe.**
I was moving my wezterm configuration's color settings to a standalone color scheme file and I noticed that there was no way to define the tab bar's colors in the color scheme. In my opinion, this makes little sense, seeing as how in the wezterm.lua file, the tab bar colors are part of the colors settings.

**Describe the solution you'd like**
I would like a way to define the wezterm's tab bar's colors as part of a color scheme file.

**Describe alternatives you've considered**
Currently, my tab bar color settings are in the wezterm.lua file. This works fine, but is not ideal for sharing my color scheme with others.

**Additional context**
I have no additional context.

**Comment by wez** [comment]
I'm open to it; it needs a bit of thought: the color schemes that ship with wezterm come from https://github.com/mbadolato/iTerm2-Color-Schemes which doesn't have a concept of tab bar colors.

We'd need to make sure that there are no surprising side effects that result from allowing tab bar colors to live in the same color scheme file and that things work as users expect when sharing and activating color schemes.

Another thing to consider is that in recent wezterm releases, we've gained https://wezfurlong.org/wezterm/config/lua/window-events/format-tab-title.html which allows for more customization in code.  I was sort of anticipating that having an easier way to share that + the tab colors would be an upcoming feature request.

I don't know what the answer is to any of these, just sharing the questions that are top of mind right now!

**Comment by chtenb** [comment]
It would also be nice if the title bar foreground and background colors could be included in a colorscheme. I would like to make the look of wezterm more uniform and clean, similar to how e.g. VSCode looks.

> it needs a bit of thought: the color schemes that ship with wezterm come from [mbadolato/iTerm2-Color-Schemes](https://github.com/mbadolato/iTerm2-Color-Schemes) which doesn't have a concept of tab bar colors.

That is a valid concern. One hacky solution could be to reuse (optionally?) an existing colorscheme property, like selection_fg/selection_bg. 

But for a cleaner solution, what are the options of detaching the inner terminal colorscheme from the outer colorscheme? I.e. making the terminal colorscheme a part of a bigger colorscheme object (let's call this a UI theme). 
A user can then choose a UI theme (which defines the looks of UI components, but also has a default colorscheme).
The default colorscheme of the chosen UI theme can then be overridden similarly to how it's done now.

**Comment by wez** [comment]
Reusing selection colors feels a bit wonky; we already use those for the selection colors :)

One thing I'd considered was automatically computing tab bar colors from the palette; for example, taking the foreground and background colors and either deriving directly from those or perhaps lightening the background color to come up with the tab bar background color.

Another other thing to consider is that while it would be great to have a more in-tune with the pane scheme option for the tab colors, there can be multiple panes and tabs in a window, and each pane can have its own palette.

I can see it being desirable to control the tab color scheme independent of the active palette/scheme in a pane, so I don't want to couple these too tightly.  Perhaps there could be an option to control whether the tab colors are derived from the color scheme or set separately.

**Comment by chtenb** [comment]
> I can see it being desirable to control the tab color scheme independent of the active palette/scheme in a pane, so I don't want to couple these too tightly.

I didn't mean to imply that the UI theme and the colorscheme would be tightly coupled. Just that a UI theme could specify a *default* color scheme that is designed for use with the UI theme, such that selecting a UI theme immediately results in a good looking terminal. No need to mix and match. But the colorscheme would still be configurable separately.
 
> One thing I'd considered was automatically computing tab bar colors from the palette; for example, taking the foreground and background colors and either deriving directly from those or perhaps lightening the background color to come up with the tab bar background color.

Yeah that's also a valid solution I think. The transformation would have to be a little sophisticated to work with all possible colors. Although I guess it doesn't really matter if it only works for the majority of colorschemes, because the feature is opt-in.

Your suggestion sounds like the easiest to implement with the existing infrastructure, and I think that having this feature wouldn't hurt possible future implementations of some UI theme concept.

**Comment by chtenb** [comment]
> The transformation would have to be a little sophisticated to work with all possible colorschemes. Although I guess it doesn't really matter if it only works for the majority of colorschemes, because the feature is opt-in.

Maybe the transformation could consist of applying some "color mask", i.e. a user-definable color+alpha value which is applied on top of the background color of the active colorscheme.

**Comment by jason0x43** [comment]
Just out of curiosity, why couldn't color scheme definitions support a `tab_bar` property in the same way that `colors` does? It seems a bit inconsistent (to me, at least) that a color scheme and `colors` appear to be the same except for the lack of `tab_bar` support in schemes.

I'm only considering this from the Lua perspective. Possibly the situation is different when considering toml config files?

**Comment by digitallyserviced** [comment]
My two cents...

The fact that the tab bar color configuration is not statically loaded is actually something that I would see as a benefit to those who do not dive deep into advanced customization. If they were to set some scheme based off a static config then there can be issues where format-*-* hooks can conflict and make things look bad, and honestly become something not really polished due to the flexibility given to the user and because of the continued development of wezterm with the possibility of broken APIs or things not working as they did because of updates or changes to enhance or add features.

However, I do believe that maybe some features or functionality or config related settings that can allow for dynamic schemes that can be a bit more intelligent and are allowed to get more from the lua API then currently. I mean more in the way of getting information about the actual raw geometry, styling, widths, heights, x, y, layers, positioning, relations to pane,tab,wins... etc...  of things.

There's a lot that Wezterm is capable of doing and I am not in any way saying this is how it should be. But I believe that in fleshing out more of the lua based API to have more control, and be able to get more data/info about the window state and terminals and rendering, that the styling can then be something amazing with the ability to react to how panes are positioned in relation to others, or how tabs are laid out depending on projects, or adding animations or other effects with the rendering process of the window.

If there is time to be spent on making things more customizable, we should just go the whole way and make it so we can completely control the look and interface and bring more than just colors and styling. We could bring more features and uses to wezterm without having to rely on a dev implementing them in rust with the hopes the feature and how it was made will be awesome for everyone's use-case.

Wez has done an awesome job, and I am trying to get better with rust to be able to contribute more. He is just one dude and deserves our support and sponsorship if we can, but not make him feel like we need all this extra stuff or that he's not working hard enough to make X or Y for me or you.

**Comment by wez** [comment]
It turns out that this worked all along.

A couple of color schemes that are now bundled with wezterm (eg: https://github.com/EdenEast/nightfox.nvim/blob/main/extra/nightfox/nightfox_wezterm.toml and https://github.com/catppuccin/wezterm/blob/main/dist/catppuccin-mocha.toml) ship with tab bar colors defined.
