### ISSUE TITLE
Screen artifacts with large scrollback and blinking cursor

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#82]
Please include as much information as possible that can help to reproduce and understand the issue;
some pointers and suggestions are included here in this template.  You are empowered to include
more or less information than is asked for here!

## Did something not work the way you expected?

Using the config:
```
scrollback_lines = 10000
default_cursor_style = "BlinkingUnderline"
```
there's a speckled background to the window which changes when its resized.

I originally also had `enable_scroll_bar = true`, but that wasn't necessary to repro.

### What did you try?

1. Started wezterm with no (default) config.
2. Created config as above
3. Ctrl-Shift-R to reload config

### What did you expect to happen?

Blinking underline cursor (yes, got that), large scrollback (yep), no speckles (nope)

### What actually happened?

Speckles (a bit hard to see unless at 1:1 or magnified).

![Screenshot from 2019-12-26 22-30-56](https://user-images.githubusercontent.com/147966/71504937-3ee88f80-2873-11ea-8992-8ea2655ae1ce.png)
![Screenshot from 2019-12-26 22-39-36](https://user-images.githubusercontent.com/147966/71505054-a4fff300-2830-11ea-9842-d6fe79154278.png)

**Comment by jsgf** [comment]
This is Fedora 31 with X (not Wayland), using the Nvidia proprietary drivers.

**Comment by wez** [comment]
(as an aside: a42342ce0c8f1f701d06d2d85104fa6111fa0430 takes care of that preexec thing)

**Comment by wez** [comment]
I couldn't reproduce it; I'm running a similar configuration except that I'm using the nouveau drivers on it.

Some things to try:

* Try a build off todays master, as I think that c8cd6007068ae112c1be8aa8eca2fa61e5df396a may have an impact on rendering here too, especially since the speckles look like alpha channel artifacts from the `:` glyph.
* Not sure that this will help, but https://github.com/wez/wezterm/commit/bd0859bef6c558a5741d7eba89c319c13cbb8872 allows changing the padding around a texture.  In the past we had some issues where nearby glyphs in the atlas would interpolate into weird places.  I'm not convinced that that is happening here, but if you feel like ruling it out, you could try bumping up the `PADDING` value

**Comment by jsgf** [comment]
Yes, it looks fixed now.
