### ISSUE TITLE
Replacing colours beyond the first 16

### ISSUE THREAD

**Issue by kittywitch** [wez/wezterm#841]
**Is your feature request related to a problem? Please describe.**
Under weechat, when /redraw is executed (presumably using OSC 104), the colours from 16 to 21 are reset to their defaults. These are normally overrode by base16-shell for me, however when this is overwritten by weechat, those colours are lost. I use the built-in colour scheme to have a fallback for when this occurs.

**Describe the solution you'd like**
A way to replace colours past 15. Whether this is an additional config variable for another 8 or a way to redefine specific colours across the 256 mapping is irrelevant to me.

**Comment by wez** [comment]
This is a bit tricky to satisfy because OSC 104 is supposed to put the colors back to their defaults and there are people and apps that depend on those; I had issues filed against wezterm because the palette was slightly different to eg: xterm.

I think what you really want is https://github.com/weechat/weechat/issues/1364 so that you don't have to work in terms of color registers and instead can just use the rgb values that you want (that issue doesn't appear to be moving though), or to otherwise configure weechat to set up those color indices how you want (I have no idea about weechat and whether that's possible).

Do you know for sure that weechat is using OSC 104 for redraw?  Is there perhaps a way to tell it not to do that?

**Comment by kittywitch** [comment]
I'm actually unaware. I couldn't find the use of OSC 104 in weechat's source, I imagine it's actually called from within ncurses, but I could be wrong about that. I don't think there's a way to override the `/window refresh` or `/redraw` commands.

Regardless, being able to replace colours from the 256 palette in configuration would be nice.

**Comment by wez** [comment]
If you run `WEZTERM_LOG=wezterm_term=debug wezterm 2> /tmp/wezterm.txt` and trigger the redraw that will capture what wezterm does in response.  You probably don't want to share that complete log online, as it effectively captures all input/output in that terminal session.

You can `grep OperatingSystemCommand /tmp/wezterm.txt` to see what `OSC` escapes are being generated

**Comment by kittywitch** [comment]
```
 2021-06-02T02:16:52.209Z DEBUG wezterm_term::terminalstate > perform OperatingSystemCommand(ResetColors([]))
```

OSC 104 is definitely used on the redraw, unfortunately.
