### ISSUE TITLE
Synchronized Rendering (VT sequence extension)

### ISSUE THREAD

**Issue by christianparpart** [wez/wezterm#882]
Hey,

I am currently compiling a list of TEs / toolkits / apps that do support synchronized rendering. I hoped to also get you onto the list of that feature.

The tiny spec for that and the list of supporting software you can find [here](https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036).

Would you be interested in that?

Looking forward to hear from you,
Christian Parpart.

**Comment by wez** [comment]
I'm interested; last time I looked, I couldn't find any application that implemented it, which made it difficult to validate.

**Comment by klamonte** [comment]
Hi @christianparpart

(Sidebar: on your terminals list, you can remove jexer.  I'm not really active on it, plus I deliberately try to stay within xterm's envelope.  The one thing really outside xterm (the images thing) I hope to remove if xterm or ncurses ever adopt a 24/32-bit wire format.)

On synchronized updates, do you have a spot for a discussion on this?  That is NOT in terminal-wg?

Some surface questions I can imagine:
* Why all the distinctions regarding what will and will not update the screen vs icon title etc.?  Why not just have the sequence be "turn off all screen updates, but process everything", and then "OK now show the entire screen"?  That would let a (fast) terminal just turn BSU/ESU into a "continue appending to the input buffer until ESU, and now process everything within one frame update".
* Corollary to above: why isn't the alternate screen buffer good enough?  It already limits the total numbers of cells that can be updated at once.  The application could just set alternate buffer and blast data as fast as the network will carry it.
* Is it really necessary?  "Avoid showing a half-drawn screen" : we used to live with partially drawn screens at 2400bps and no one really complained.  ncurses, joe, and I believe tmux and screen all used custom optimizations to get good performance on serial line speeds.  If we are really seeing performance issues, let's fix the libraries, e.g. implement a proper diff algorithm for screen updates.
* If the terminal has its own choice on timeout, maximum bytes to buffer, when to just give up on the atomic update, etc.: this just begs for an application that needs "glass-smooth updates" to have to interrogate the terminal to know what those limits are so that it can reasonably try to avoid tearing.  It will make a curses-type application have to think like a game engine.
* Spec says: "If a Begin synchronized update sequence is received during a synchronized update, the timeout should be extended by its original duration." --> Does this open the door to a DoS?

Not trying to say never do it! An implementation might blow us all away and quickly justify itself. 😊

**Comment by christianparpart** [comment]
Hey @klamonte

On the list, I can remove jexer there, thx for the input.

> On synchronized updates, do you have a spot for a discussion on this? That is NOT in terminal-wg?

To be honest(!), I'm not a great fan of that place neither, but I also have to admit, that some central place would be really beneficial. This subject right now is the best example where I feel we have a couple of parties that are really interested in this subject, but we hop on and off in like 6+ different Github/Gitlab repos. 
I always was a little naive to believe the whole world can collaborate (heck, that's why all my code is open and free), so i was quite some time ago creating the Github orga *stdvte*. I might now point you to our already existing good-image-protocol repo, where I so far feel like we're all at least actively trying to communicate in a positive and constructive way, that repo I'd like to move out of my own personal namespace into that `stdvte` one, too. So it would make sense now to move this discussion into that orga (there is a discussions repo with the "Discussions" feature enabled that I'd like to openly suggest).

And if that idea is well accepted, i'd also move the good-image-protocol spec repo over to it, in the spirit of a better together (and less scattered, but definitely also less of the negative things in TWG). Not sure you like my attempt, tell me :-)

On the spec side:

I have tried to be as explicit as possible in https://github.com/xtermjs/xterm.js/issues/3375#issuecomment-868774766 where @jerch was asking me, too.

> Why all the distinctions regarding what will and will not update the screen vs icon title etc.? Why not just have the sequence be "turn off all screen updates, but process everything",

That is exactly how i have implemented it, and how I tried to explain it to @jerch in https://github.com/xtermjs/xterm.js/issues/3375#issuecomment-868774766 - maybe i should be more clear in the page at https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036 (actually I should! let me add that to my todo list, that is also another document that could be stored there).

i'm kinda in hurry right now, don't be mad if i'll respond to the rest later (mayabe here, or there, let's see) :-)

**Comment by klamonte** [comment]
Oh gosh, don't rush anything!  I was just putting some thoughts out there, don't feel obligated to respond unless you are totally bored later. :-)

**Comment by jerch** [comment]
> Spec says: "If a Begin synchronized update sequence is received during a synchronized update, the timeout should be extended by its original duration." --> Does this open the door to a DoS?

This indeed feels like a feature inviting ppl to do shady things. Imho it should not have that timeout stacking behavior.

> Is it really necessary? "Avoid showing a half-drawn screen" : we used to live with partially drawn screens at 2400bps and no one really complained. ncurses, joe, and I believe tmux and screen all used custom optimizations to get good performance on serial line speeds. If we are really seeing performance issues, let's fix the libraries, e.g. implement a proper diff algorithm for screen updates.

What you say is all true, but also kinda misses a crucial aspect - tearing is a matter of perception, that starts annoying ppl at higher speeds due to getting numbers in page updates close to raw FPS (artefacts from sampling theorem). At low speed the raw FPS numbers are too far away to cause a perceivable disturbance (FPS dominate here). Just like with the wagon-wheel-effect: the disturbance is always there, but not noticeable at lower speed.

**Comment by klamonte** [comment]
@christianparpart FYI I did just stick synchronized updates into the Jexer Xterm backend (the application side).  It's not yet in the terminal widget, but that will be soon when I get to seriously working on smoother handling of the notcurses demo.

I am glad you mentioned DECRQM/DECRPM in the spec.  I needed those to detect SGR-Pixels mode (1016) to support fine-grained mouse control for something else, and once those were in it was trivial to add detection for Synchronized Output and then wrap my screen updates with BSU/ESU.

(I know I mentioned not working on it anymore, and wanting to stay within xterm's scope, but I changed my mind. :-)  Though I'm not sure xterm _can_ do BSU/ESU without some potentially nontrivial rework.)

**Comment by christianparpart** [comment]
Welcome back, @klamonte ;)
I am glad you have time and energy to work on Jexer/TE stuff in general again.

With regards to xterm, if it can't implement it without some major internal rework, it would be nice to at least acknowledge the existence in the docs (ctlseqs) and maybe Thomas would be open to share his thoughts on wether he might be implementing it generally in the future.

**Comment by klamonte** [comment]
@christianparpart 

...and now it's in the terminal widget.  Jexer-within-Jexer with no (crossing fingers!) tearing.  OK, I'm swung, that was pretty cool. :-)
