### ISSUE TITLE
Support SVG for iTerm2 image support

### ISSUE THREAD

**Issue by ModProg** [wez/wezterm#896]
Support for rendering SVGs when running imgcat:
```sh
wezterm imgcat test.svg
```

I don't know if iTerm2 does support svgs, but I work a lot with them and imgcat is a lot faster than all the sixel tools I tried.

**Comment by ModProg** [comment]
Possible Libraries for that:
https://github.com/servo/pathfinder
https://github.com/RazrFalcon/resvg

**Comment by wez** [comment]
First: I tried iTerm2 and it doesn't render svgs.

Second: I sort of want to do this, but aside from not matching iTerm2's behavior, it's also a bit problematic because `imgcat` uses an image protocol to pass something that is logically a raster image with defined pixel dimensions through to the terminal.  An svg doesn't necessarily have those properties, and may access arbitrary fonts which means that there are a number of scenarios where the render behavior isn't super well defined or may not behave 100% as you might expect (eg: font resolution from a library wouldn't match the main wezterm font configuration).

This twitter thread suggests using `rsvg-convert` which is part of the `librsvg2-tools` rpm on Fedora:
https://twitter.com/thingskatedid/status/1316078716070445058

So something like:

`rsvg-convert test.svg | wezterm imgcat`

That's probably the easiest way to meet this need for now.

**Comment by ModProg** [comment]
> `rsvg-convert test.svg | wezterm imgcat` 

I'll be using somthing along that for now.

I think when svg is implemented it can only be done on a subset, but in the end that's what most SVG renderers do, some support more features some less. So I don't think it would be surprising if a Terminal can not display everything Firefox can.

**Comment by MuhammedZakir** [comment]
`rsvg-convert` is enough. I have been using mdcat[1] which uses `rsvg-convert` and it worked really well. Most of the time it was to read readme files. So haven't used it convert complex SVG.

[1] https://github.com/lunaryorn/mdcat/search?q=rsvg-convert

**Comment by wez** [comment]
I've decided not to do this in the interest of compatibility with iTerm2.
