### ISSUE TITLE
Selection with "Shift + mouse drag" is not the same as other terminal emulators.

### ISSUE THREAD

**Issue by zhou13** [wez/wezterm#911]
## Describe the bug

In most terminal emulators such as gnome-terminal, pressing the shift key will not make any difference if you try to select text. For example, Shift + triple-click will select a line. Therefore, I have the habit of pressing the shift key when I want to select text to make a copy (in case I am in an environment like vim where without the shift key mouse events will be fed into vim).

However, this is not the case in wezterm. In wezterm, shift behaviors like the shift in a text box. If I do a triple-click while pressing shift, it will select the text from the last selection to the current cursor. It is not clear to me if this is the intended behavior, but it let me always select too much text given my previous habit.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: `wezterm 20210628-091813-e05ddb17`
 - The active keyboard layout name ENG

## To Reproduce

Steps to reproduce the behavior.

1. In zsh/bash
2. Pressing the shift key and do a triple-click.

## Behavior now

Texts from the last selection to the current cursor are selected.

## Expected behavior

Only the current line should be selected.

**Comment by bew** [comment]
I'd say it's intentional, there is no ultimate solution for everyone..
If you want a specific moise behavior, you can always remove the default mouse bindings and make your own! 
(that's what I do)

**Comment by wez** [comment]
What's happening here is that `SHIFT + Triple Click` doesn't have a defined mouse binding, so that has no effect.  Depending on the timing of your clicks, you are most likely triggering `SHIFT + Click` which extends the selection.

The defined mouse bindings are here: https://wezfurlong.org/wezterm/config/mouse.html

So this isn't a bug.  As bew suggests, you could add an explicit binding for the triple-click case to satisfy your immediate need.

As an enhancement, I think it may be reasonable to want to allow SHIFT to match a binding that doesn't explicit include shift in its modifier mask, but it introduces additional complexity in the input mapper; right now the mapper is conceptually a simple hashmap lookup, but to allow this kind of soft match there would need to be an additional hashmap constructed with the synthesized modifier states to use as a fallback, but then there's additional complexities around whether a given mapping should allow the soft match or not.  Needs more thought.

**Comment by zhou13** [comment]
Thanks for the help. I add the following configuration and now it works as expected for me!

```    mouse_bindings = {
        {
            event={Down={streak=1, button="Left"}},
            mods="SHIFT",
            action=wezterm.action{SelectTextAtMouseCursor="Cell"},
        },
        {
            event={Down={streak=2, button="Left"}},
            mods="SHIFT",
            action=wezterm.action{SelectTextAtMouseCursor="Word"},
        },
        {
            event={Down={streak=3, button="Left"}},
            mods="SHIFT",
            action=wezterm.action{SelectTextAtMouseCursor="Line"},
        },
        {
            event={Up={streak=1, button="Left"}},
            mods="SHIFT",
            action=wezterm.action{CompleteSelectionOrOpenLinkAtMouseCursor="PrimarySelection"},
        },
        {
            event={Up={streak=2, button="Left"}},
            mods="SHIFT",
            action=wezterm.action{CompleteSelection="PrimarySelection"},
        },
        {
            event={Up={streak=3, button="Left"}},
            mods="SHIFT",
            action=wezterm.action{CompleteSelection="PrimarySelection"},
        },
        {
            event={Drag={streak=1, button="Left"}},
            mods="SHIFT",
            action=wezterm.action{ExtendSelectionToMouseCursor="Cell"},
        },
        {
            event={Drag={streak=2, button="Left"}},
            mods="SHIFT",
            action=wezterm.action{ExtendSelectionToMouseCursor="Word"},
        },
        {
            event={Drag={streak=3, button="Left"}},
            mods="SHIFT",
            action=wezterm.action{ExtendSelectionToMouseCursor="Line"},
        },
    },
```
It seems that there is no mention of how the mouse events are handled in environments such as vim. In vim, I always need to press `shift` to select. Is that also configurable?

**Comment by bew** [comment]
> It seems that there is no mention of how the mouse events are handled in environments such as vim. In vim, I always need to press `shift` to select. Is that also configurable?

You might be interested in #581

**Comment by wez** [comment]
> In vim, I always need to press shift to select. Is that also configurable?

I just pushed ac5199c21663e39dcce887308a92b5e36b338866 which makes this configurable, as well as documents the mouse reporting capture behavior.
