### ISSUE TITLE
Is the "term" crate here on cargo?

### ISSUE THREAD

**Issue by bitc** [wez/wezterm#934]
Hello, this github repository has a crate titled "term" here: https://github.com/wez/wezterm/tree/main/term

I can't seem to find it on Cargo though :cry: 

The [Cargo.toml](https://github.com/wez/wezterm/blob/main/term/Cargo.toml) file says:

    documentation = "https://docs.rs/wezterm-term"

but this link is broken.

Thank you

**Comment by wez** [comment]
I haven't published it to crates.io yet.  There was a user that was embedding the term crate into some other application, and I was waiting to hear back from them about that before publishing it.  It's been a while since I've heard from them though!

Publishing means thinking about API stability more deeply and that can make it more difficult to iterate rapidly, so in the absence of users asking about this, I've not felt the need to aggressively push it so far!
