### ISSUE TITLE
Wezterm always terminates replies to OSC commands with ST even if the BEL was used

### ISSUE THREAD

**Issue by lunaryorn** [wez/wezterm#935]
## Describe the bug

Wezterm allows both ST and BEL as terminator for OSC command sequences, but it always terminates its own replies with ST even if BEL was used.  For example wezterm answers a `\x1b]11;?\x07` sequence with `\033]11;rgb:ffff/ffff/ffff\x1b\\`.

However xterm (and compatible terminals, notably all VTE based ones) always uses the same terminator as in the input, i.e. xterm would answer `\033]11;rgb:ffff/ffff/ffff\007`, see e.g. <https://invisible-island.net/xterm/ctlseqs/ctlseqs.html>:

> XTerm accepts either BEL  or ST  for terminating OSC sequences, and when returning information, uses the same           terminator used in a query.  While the latter is preferred, the former is supported for legacy applications […]

Not the most pressing thing, for sure; I just noticed this because I always use BEL in my scripts (being a single character it's easier to handle than ST).  I've patched my scripts to use ST, so I doesn't affect me anymore, but I figured ought to report it nonetheless, for it may affect compatibility with older tools.

Feel free to close as wontfix :slightly_smiling_face: Thanks for this great terminal emulator :pray: 

## Expected behavior
For compatibility with xterm I'd expect wezterm to answer OSC commands with the same terminator as used for the command, namely ASCII BEL if that was used to terminate the OSC command.

**Comment by wez** [comment]
Ah interesting.  I'm leaning towards won't fix for this, until we find an example of where this choice breaks something.
The reason is that wezterm's parsed version of the escapes doesn't preserve that context and instead serializes to the canonical ST form, and there's a decent amount of churn in the rest of the code. I don't mind doing the work if it's actively needed, but if not, I'd like to save that time for something else!

If someone wanted to take a stab at a PR for this, the steps would be roughly:

* Adjust the vtparse crate to include the terminator in `VTActor::osc_dispatch` and `Action::OscDispatch` 
* Adjust the termwiz crate to introduce something like a `TerminatedOperatingSystemCommand` struct that has both the existing `OperatingSystemCommand` and the terminator as fields
* in the Display impl for `TerminatedOperatingSystemCommand`, emit the appropriate terminator after displaying the underlying `OperatingSystemCommand`.
* Deal with the fanout through the rest of the code

**Comment by lunaryorn** [comment]
> The reason is that wezterm's parsed version of the escapes doesn't preserve that context and instead serializes to the canonical ST form

I figured as much, so I'm fine with closing🙂

Just wanted to make you aware, in case there's a similar issue later on 🙂

**Comment by wez** [comment]
Alright, let's close this and we can reopen if needed in the future!
