### ISSUE TITLE
Hovering over a link highlights every place where the link appears

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#94]
## Describe the bug

When hovering the pointer over a hyperlink, it highlights every instance of that link on the screen, rather than just the one being highlighted.

## Environment (please complete the following information):

 - OS: Linux X11
 - Frontend:  OpenGL
 - Version: wezterm 20191218-101156-bf35707-54-g10cb48f

## To Reproduce

1. Run ` for i in $(seq 10); do echo https://github.com; done`
2. Hover pointer over one of the github.com links

## Expected behavior
It should just highlight the link that's actually being pointed to. It also seems to be inconsistently only highlight some of the other URLs.

## Screenshots

![Screenshot from 2019-12-28 18-35-04](https://user-images.githubusercontent.com/147966/71551664-65a4e400-29a1-11ea-9d94-99ed15f1688c.png)

**Comment by wez** [comment]
That's semi-intentional behavior... [this part of the hyperlinks spec](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#hover-underlining-and-the-id-parameter) (which I believe has changed since I implemented the feature) suggested that they should all highlight because they have the same implicit id value.

We can't simply use a hovered range because we need to allow for this application defined window wrapping scenario:
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#viewers-editors

So the bug is that they don't all highlight, rather than just the hovered range highlighting.

Then there's a legitimate feature request for generating a new unique id at parse time rather than deriving it from the url itself; that would effectively make each instance unique and resolve the problem.

**Comment by jsgf** [comment]
Looks fixed to me.
