### ISSUE TITLE
Mouse events not working

### ISSUE THREAD

**Issue by rashil2000** [wez/wezterm#943]
## Describe the bug

I have tried many TUIs to verify this - [broot](https://github.com/Canop/broot), [ncspot](https://github.com/hrkfdn/ncspot), [bottom](https://github.com/ClementTsang/bottom), [fzf's bat preview](https://github.com/junegunn/fzf#preview-window), [yedit](http://www.malsmith.net/edit), [Far Manager](https://farmanager.com/).
Mouse events don't work in Wezterm, while they work in old conhost (cmd's default terminal).

## Environment (please complete the following information):

 - OS: Windows
 - Version: wezterm 20210502-154244-3f7122cb
 - The active keyboard layout name: ENG

## To Reproduce

Just try to use any of the above apps with the mouse.

## Configuration

```lua
local wezterm = require 'wezterm';

return {
  --window_decorations = "RESIZE",
  window_padding = {
    left = 25,
    right = 25,
    top = 25,
    bottom = 25,
  },
  hide_tab_bar_if_only_one_tab = true,
  font = wezterm.font("RecMonoSemicasual NF"),
  color_scheme = "BlulocoLight",
  font_size = 11.0
}
```

## Expected behavior
The mouse should respond as it does in conhost.

## Additional context

None

**Comment by wez** [comment]
The issue was that Window's PTY layer didn't allow the win32 console API mouse reporting to be passed through.
https://github.com/microsoft/terminal/issues/376 was the issue I filed with MS about this, and it was only recently fixed.

From wezterm's changelog https://wezfurlong.org/wezterm/changelog.html?highlight=conpty.dll#continuousnightly 

> Updated: conpty.dll to v1.9.1445.0; fixes color bar artifacts when resizing window and allows win32 console applications to use mouse events

So please use the nightly and things should be OK!

**Comment by rashil2000** [comment]
Hi! Just tried the nightly version, and yes the clicks work fine. 
Thanks!
