### ISSUE TITLE
Screen tear/flicker when scrolling in NVim

### ISSUE THREAD

**Issue by JeanMertz** [wez/wezterm#965]
I'm seeing screen tearing / flickering when rapidly scrolling up/down a NVim window. I can't reproduce this in Kitty, so it appears to be Wezterm related.

I added screen recordings of both Wezterm and Kitty below.

**Wezterm**

https://user-images.githubusercontent.com/383250/126386018-24d78c31-c8aa-457a-b55e-a38a17114a14.mov

**Kitty**

https://user-images.githubusercontent.com/383250/126386090-ab6d44e6-55bf-4ee9-b177-899bab58a172.mov

 - OS: macOS
 - Version: wezterm 20210704-095357-4f7b21d5

**Comment by wez** [comment]
Is this an M1 mac or an Intel based mac?

**Comment by JeanMertz** [comment]
@wez this is an Intel-based mac.

MacBook Pro (16-inch, 2019)
2,3 GHz 8-Core Intel Core i9
32 GB 2667 MHz DDR4
AMD Radeon Pro 5500M 4 GB

**Comment by wez** [comment]
Can you try copying the dylibs from https://github.com/wez/wezterm/tree/main/assets/macos/WezTerm.app into the same directory as the wezterm-gui executable and then re-launching wezterm and see if the behavior is any better?
That should allow wezterm to run in EGL mode using Angle -> Metal instead of the default CGL mode.
