### ISSUE TITLE
add function ActivatePaneClockwiseNext

### ISSUE THREAD

**Issue by Aaron-Vungle** [wez/wezterm#976]
Hi all

it would be good if it support `ActivatePaneClockwiseNext`, where wezterm keep activate the next pane clockwised

Regards

**Comment by lithammer** [comment]
...and counterclockwise.

**Comment by wez** [comment]
Clockwise is a difficult concept to encode, as it requires stateful iteration to know when to go right or go down.  It also cannot visit interior panes: once you reach an edge, you'll continue to iterate the border panes only.

Rather than implement literally that, I added support for `Next` and `Prev` which iterate the panes by their index in the pane tree.  This gives an unambiguous order of traversal that is easy to reason about.

This will be present in the nightly downloads within the next hour.
