### ISSUE TITLE
adding wezterm into MPR (should i maintain it or not)

### ISSUE THREAD

**Issue by onlyvip** [wez/wezterm#983]
[MPR](https://mpr.hunterwittenborn.com/) is an user repository similar to aur but for debian(partially with debian for now, mainly for ubuntu lts but should work with debian fully once bullseye gets released). it uses makedeb and makepkg using the PKGBUILD.

I checked the aur packages of wezterm and saw the [PKGBUILD.template](https://github.com/wez/wezterm/blob/main/ci/PKGBUILD.template) 
and i had decided to  maintain it on MPR. however if you want to be the maintainer then you can. if not i would refer the `PKGBUILD.template` and maintain in MPR. 
whatever you decide with i will go forward with either way.

**Comment by wez** [comment]
if the MPR is distributing binaries then I'd prefer to be in control of that and use a similar model to AUR.
If the MPR always builds eg: nightly from source then it doesn't feel as important.
Note that there are pre-built .debs available for wezterm, both for release and nightly builds.
How does MPR compare to those? When would someone use MPR vs. one of those debs?

**Comment by onlyvip** [comment]
It's exactly similar to aur. Whatever reason you have to make it available
on aur applies in here. Yes we have .deb but it won't update for a newer
version on its own mpr can update. About building and binaries mpr works
exactly like aur so it has templates like pkgbuild so it's upto the
maintainer what he wants to provide with.

**Comment by hwittenborn** [comment]
Hi! Just adding my own little blurb (pre-warning, I'm the one maintaining makedeb and the MPR).

The whole gist of why you might use it is because, like @onlyvip said, it can allow users to automatically update packages, either through pulling any changes from the Git repo, or through the use of an MRP helper (quite literally the same concept as an AUR helper).

If you just want to distribute prebuilt Debs, you can also just use makedeb by itself to make Debian packages from PKGBUILDs, and then just distribute that Deb.

Getting back to the original point - the main purpose of using something like the MPR is to allow third parties to easily distribute their packages (by use of a PKGBUILD), while also making things easier for end users through features like automatic updates and everything being centralized.

**Comment by onlyvip** [comment]
Considering you haven't replied for a week. I would try making wezterm available on mpr you take the maintainer ship when you want to. Until then it shall become available on mpr by me.

**Comment by wez** [comment]
Hey, sorry, there was a short discussion of this over in https://matrix.to/#/!PirwUBcuIlTXwNveYz:matrix.org/$4H5Ft1vaG0fnqJ71gtGLr2e5idnByKdPpBmwNpeLlg4?via=matrix.org&via=butterfly.zone&via=greyface.org and I assumed that you were part of it because it referenced exactly this issue.

The summary: https://matrix.to/#/!PirwUBcuIlTXwNveYz:matrix.org/$YVq-em6A_5EoK04mYAQX7gMfRVfpjGtvIJudGQPKxjo?via=matrix.org&via=butterfly.zone&via=greyface.org

**Comment by onlyvip** [comment]
I can't access the exact conversation on Matrix. Can you give a tl;dr?

**Comment by wez** [comment]
Why can't you access it? It should be publicly accessible?

What I said over there was:

> For binaries, if it is an individual maintaining their own binaries, it feels harder for users to trust. I'm actually fine with a distro or project maintaining binaries

> with respect to the PKGBUILD.template stuff in wezterm: that was primarily to automate generating the PKGBUILD when wezterm cuts a release.  I view it as a convenience.  If someone is actively maintaining a build/pkg spec in a downstream project, then automation from the wezterm repo isn't required

> So the TLDR is really: if you want to actively maintain a spec for some kind of distro then I welcome it!  If that is distributing binaries I think it is more trustworthy if that distro is a sufficiently open project with more than just one person behind it.  If that distro is compatible with eg: wezterm's CI automation pushing an update to the package spec then I think that could save some manual effort, and help wezterm's users always have access to the latest version, but I don't require it.

**Comment by wez** [comment]
Closing this out as there isn't an immediate action for me!
