### ISSUE TITLE
Is there a way to create a copy-mode specific keybinding?

### ISSUE THREAD

**Issue by kuator** [wez/wezterm#993]
I use vim, and the way I usually copy text is: select text region with `v` and then copy it with `y`. Wezterm instead uses `ctrl-shift-c` to copy text, which is okay, but I would like to know if it's possible to create copy-mode specific mapping for `y` to copy text?

**Comment by wez** [comment]
Copy mode doesn't have configurable bindings today. https://github.com/wez/wezterm/blob/7f9d96328cdadefb8f12c67b42165fcc7382cca0/wezterm-gui/src/overlay/copy.rs#L401 is the place in the code that handles key presses in copy mode if you wanted to tack a crack at expanding it.

Are you thinking that you'd want `y` to copy the selection and exit copy mode?

**Comment by kuator** [comment]
I think yes, the behaviour would be more similar to the vim's one

**Comment by kuator** [comment]
I really like the way [dvtm](https://github.com/martanne/dvtm) handles copy mode: 
![image](https://user-images.githubusercontent.com/25168308/128133351-5752672b-15da-4f08-ba64-a469c428deaa.png)

**Comment by aca** [comment]
tmux vi-copy mode + search integration is something I really miss.
But I just couldn't figure how to make it work. It seems to require some changes in the internal.
This is the trick I am using right now. 
```
wezterm.on("open_in_vim", function(window, pane)
	 local file = io.open( "/tmp/wezterm_buf", "w" )
	 file:write(pane:get_lines_as_text())
	 file:close()
   window:perform_action(wezterm.action({ SpawnCommandInNewTab = { args = { "nvim", "/tmp/wezterm_buf" } } }), pane)
end)
```
```
{ key = "[", mods = "LEADER", action = wezterm.action({ EmitEvent = "open_in_vim" }) },
```

**Comment by wez** [comment]
> tmux vi-copy mode + search integration is something I really miss.

Would you mind opening a Feature Request issue to capture/track the specific feature that you're missing?  What's most useful is describing the specific thing you want to do and how you'd like it to work in wezterm.

**Comment by Lenbok** [comment]
I am really missing this feature, as I would like the copy bindings to be more emacs-compatible, e.g:

- Ctrl-b/f for left/right character
- Ctrl-n/p for down/up character
- Ctrl-a/e for start/end of line
- Ctrl-v and Alt-v to page down/up respectively
- Alt-</> for start/end of scrollback
- Ctrl-space for toggle selection,

How are you thinking copy mode bindings should look in the config? As a separate config property, like `keys` and `mouse_bindings`? Or a separate "mods" property, like how `LEADER` is treated now?

**Comment by wez** [comment]
In terms of configuration, I'm thinking that there could be a [Key Table](https://wezfurlong.org/wezterm/config/key-tables.html) for copy mode, and that it would effectively get pushed on to the activation stack when copy mode is activated, and removed from the stack when exited.

In terms of implementation: what's tricky is that the overlays are implemented as embedded TUI applications that runs in a somewhat isolated context.  They receive encoded input the same way that an actual application running inside the terminal would do.  That happens after regular key mapping handling occurs, and they aren't directly connected to it.

I think the path through that would be to introduce a method in `mux::Pane`: `fn perform_assignment(&self, assignment: &KeyAssignment) -> bool { false }` that would give an overlay a chance to handle an assignment if it wishes.

So the work for this would be something like:

* Define that new `Pane::perform_assignment` method in the `mux` crate.
* At the top of the `perform_key_assignment` method in the `wezterm-gui` crate, first try calling `pane::perform_assignment`.  If that returns true, skip further processing, otherwise allow the normal processing to run.
* Define new `KeyAssignments` for each of the copy mode keyboard actions.  Some actions are pretty generic and do things like move the viewport around, while some change the scope of the selection: those seem generally useful and could be good as general actions that could be used outside of copy mode.  The actions that are copy mode specific should probably have a `CopyModeXXX` style name to make it clear that they only apply to copy mode.  The copy mode specific assignments would need to be listed and made to do nothing in the `perform_key_assignment` method.
* Implement `perform_assignment` for `CopyOverlay` and have it implement the copy mode specific assignments
* Define a default key table for copy mode, based on the current defaults.  Naming wise, it is a good idea to establish a convention that avoids conflicting with user-defined key tables.  eg: `copy_mode_overlay` (with `_overlay` as a suffix) or `wezterm_copy_mode` (with `wezterm_` as a prefix) to avoid collision.
* Ensure that there is a reasonable way for users to override or completely replace that key table.  I'm leaning towards adding a function to the `wezterm` module that can return the default key tables.
* Ensure that the copy mode key table is pushed on the key table activation stack when the overlay is activated and either that the original state of the activation stack is restored when it is cancelled, or that the stack is cleared (the latter feels a bit too aggressive)

**Comment by wez** [comment]
Thinking about it a bit, with key tables, copy mode doesn't strictly even need to be an overlay any more.

The overlay aspect is useful to show that the mode is active, but if you don't need to see that (perhaps you are using the right status to see the key table per https://wezfurlong.org/wezterm/config/key-tables.html) then an alternative way to implement this request is to add a set of key assignments that provide the movement you're looking for in the viewport and operate on the selection directly.

**Comment by Lenbok** [comment]
Offtopic: Heck, I didn't even know wezterm had a right-status, that'll get me one step closer to replicating my current tmux status line (shown below)
![image](https://user-images.githubusercontent.com/282098/166864740-0c875d78-9949-4ecb-8046-2bfc2cf479bc.png)
(disclaimer: I don't know rust, but will try having a poke around)

**Comment by wez** [comment]
I've started to code up some of the things I outlined above!

**Comment by wez** [comment]
The current state of `main` is that copy mode now activates a `copy_mode` key table when it is enabled.  That key table has the same set of key assignments/actions from the previous release.

You can replace it with your own key table by doing something like this:

```lua
local wezterm = require 'wezterm';

-- Show which key table is active in the status area
wezterm.on("update-right-status", function(window, pane)
  local name = window:active_key_table()
  if name then
    name = "TABLE: " .. name
  end
  window:set_right_status(name or "")
end);

return {
  key_tables = {
    copy_mode = {
      {key="Escape", mods="NONE", action=wezterm.action{CopyMode="Close"}},
      {key="h", mods="NONE", action=wezterm.action{CopyMode="MoveLeft"}},
      {key="j", mods="NONE", action=wezterm.action{CopyMode="MoveDown"}},
      {key="k", mods="NONE", action=wezterm.action{CopyMode="MoveUp"}},
      {key="l", mods="NONE", action=wezterm.action{CopyMode="MoveRight"}},
      {key=" ", mods="NONE", action=wezterm.action{CopyMode="ToggleSelectionByCell"}},
    },
  },
}
```

Here's the list of copy mode specific actions:
https://github.com/wez/wezterm/blob/main/wezterm-gui/src/overlay/copy.rs#L415-L433

There aren't any docs for this yet.
There isn't yet a way to copy and extend the default assignments: when you define the `copy_mode` table it will replace the defaults.  I'll add something for this later!

This state makes it easier to add new actions and separately to add new default or custom assignments for them.

**Comment by Lenbok** [comment]
This looks awesome!! So far it works well. I could see myself adding an action that combines copy to clipboard plus close copy mode.

One thing I noticed while testing this (but not keymap related) is that the copy mode selection is inclusive of both start and end position, so if I: jump to the start of a line, enable selection, move down a few lines and copy the selection, I don't get whole lines -- there's one extra character corresponding to the cursor position. Similarly if I put the cursor on the first character of a word, enable selection, MoveForwardWord, and copy, you end up accidentally copying the first character of the next word.  Is there a way to make the selection end-exclusive so behaves more like text editors (at least that's how emacs, nano, and tmux selection all do it, I don't know about others)? In that mode I would expect MoveToEndOfLineContent to put the cursor just *after* the last character on the line.

FYI, here are my current binds:
```
   key_tables = {
      copy_mode = {
         {key="Escape", mods="NONE", action=wezterm.action{CopyMode="Close"}},
         {key="g", mods="CTRL", action=wezterm.action{CopyMode="Close"}},
         {key="b", mods="CTRL", action=wezterm.action{CopyMode="MoveLeft"}},
         {key="f", mods="CTRL", action=wezterm.action{CopyMode="MoveRight"}},
         {key="p", mods="CTRL", action=wezterm.action{CopyMode="MoveUp"}},
         {key="n", mods="CTRL", action=wezterm.action{CopyMode="MoveDown"}},
         {key="b", mods="ALT", action=wezterm.action{CopyMode="MoveBackwardWord"}},
         {key="f", mods="ALT", action=wezterm.action{CopyMode="MoveForwardWord"}},
         {key="a", mods="CTRL", action=wezterm.action{CopyMode="MoveToStartOfLine"}},
         {key="e", mods="CTRL", action=wezterm.action{CopyMode="MoveToEndOfLineContent"}},
         {key="m", mods="ALT", action=wezterm.action{CopyMode="MoveToStartOfLineContent"}},
         {key="v", mods="CTRL", action=wezterm.action{CopyMode="PageDown"}},
         {key="v", mods="ALT", action=wezterm.action{CopyMode="PageUp"}},
         {key="<", mods="ALT|SHIFT", action=wezterm.action{CopyMode="MoveToScrollbackTop"}},
         {key=">", mods="ALT|SHIFT", action=wezterm.action{CopyMode="MoveToScrollbackBottom"}},
         {key=" ", mods="CTRL", action=wezterm.action{CopyMode="ToggleSelectionByCell"}},
         {key="w", mods="ALT", action=wezterm.action{CopyTo="ClipboardAndPrimarySelection"}},
      },
   },

```

**Comment by gegoune** [comment]
Is that suppose to be added next to `keys` table or do you plan of nesting 'regular' assignments within `key_tables`?

**Comment by wez** [comment]
> if I put the cursor on the first character of a word, enable selection, MoveForwardWord, and copy, you end up accidentally copying the first character of the next word

This is consistent with the behavior in vim, which was the model for this mode; enter visual mode, press w then press y to yank.
I just tried this in tmux and it behaves this way also.

I'm not opposed to having a way to control this behavior.

**Comment by wez** [comment]
> I could see myself adding an action that combines copy to clipboard plus close copy mode.

You can use [Multiple](https://wezfurlong.org/wezterm/config/lua/keyassignment/Multiple.html) to express that; this defines `y` as a yank operation, similar to what was requested by @kuator in the OP:

```lua
   {key="y", mods="NONE", action=wezterm.action{Multiple={
             wezterm.action{CopyTo="ClipboardAndPrimarySelection"},
             wezterm.action{CopyMode="Close"}
   }}}
```

**Comment by wez** [comment]
> Is that suppose to be added next to `keys` table or do you plan of nesting 'regular' assignments within `key_tables`?

Take a look at the [Key Tables](https://wezfurlong.org/wezterm/config/key-tables.html) docs for more info about that!

**Comment by kuator** [comment]
Awesome!

**Comment by wez** [comment]
Keeping this open until things are wrapped up and documented!

**Comment by Lenbok** [comment]
> > if I put the cursor on the first character of a word, enable selection, MoveForwardWord, and copy, you end up accidentally copying the first character of the next word
> 
> This is consistent with the behavior in vim, which was the model for this mode; enter visual mode, press w then press y to yank. I just tried this in tmux and it behaves this way also.

Ahh, for me tmux doesn't, but I see it allows `setw -g mode-keys vi` to turn on vi-style selection. 

I will open a separate issue to track this.

**Comment by wez** [comment]
Docs are at:
https://wezfurlong.org/wezterm/copymode.html#configurable-key-assignments
https://wezfurlong.org/wezterm/scrollback.html#configurable-search-mode-key-assignments

**Comment by wez** [comment]
FWIW, I just added the vim-style yank `y` assignment as a default in `main`
